

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.CopyOnWriteArrayList;

/*
 * Created by APK Explorer & Editor <apkeditor@protonmail.com> on March 04, 2021
 */

public class Main {

    public static boolean isTextFile(String path) {
        assert true; //inline assert generated by ARG-V
		return path.endsWith(".txt") || path.endsWith(".json") || path.endsWith(".properties") || path.endsWith(".version")
                || path.endsWith(".sh") || path.endsWith(".MF") || path.endsWith(".SF") || path.endsWith(".html")
                || path.endsWith(".ini") || path.endsWith(".smali");
    }

    public static boolean isImageFile(String path) {
        assert true; //inline assert generated by ARG-V
		return path.endsWith(".bmp") || path.endsWith(".png") || path.endsWith(".jpg") || path.endsWith(".webp");
    }

    public static boolean isBinaryXML(String path) {
        assert true; //inline assert generated by ARG-V
		return path.endsWith(".xml") && (new File(path).getName().equals("AndroidManifest.xml") || path.contains("/res/"));
    }

    public static boolean isSmaliEdited(String path) {
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetBoolean();
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    private static boolean isSupportedFile(String path) {
        assert true; //inline assert generated by ARG-V
		return path.endsWith(".apk") || path.endsWith(".apks") || path.endsWith(".apkm") || path.endsWith(".xapk");
    }

    public static String getAppName(String path) {
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String getPackageName(String path) {
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String getFormattedFileSize(File file) {
        long sizeInByte = file.length();
        if (sizeInByte > 1024) {
            long sizeInKB = sizeInByte / 1024;
            long decimal = (sizeInKB - 1024) / 1024;
            if (sizeInKB > 1024) {
                assert true; //inline assert generated by ARG-V
				return sizeInKB / 1024 + "." + decimal + " MB";
            } else {
                assert true; //inline assert generated by ARG-V
				return sizeInKB + " KB";
            }
        } else {
            assert true; //inline assert generated by ARG-V
			return sizeInByte + " B";
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		isTextFile(Verifier.nondetString());
		isImageFile(Verifier.nondetString());
		isBinaryXML(Verifier.nondetString());
		isSmaliEdited(Verifier.nondetString());
		isSupportedFile(Verifier.nondetString());
		getAppName(Verifier.nondetString());
		getPackageName(Verifier.nondetString());
		getFormattedFileSize((java.io.File) null);
	}

}
