

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Parses a Object relational query statement into a OrmQueryDetail and OrmQueryAttributes.
 * <p>
 * The reason they are split into detail and attributes is that the AutoTune feature is used to
 * replace the OrmQueryDetail leaving the attributes unchanged.
 * </p>
 */
public final class Main {

  public Main(String oql) {
  }

  private void processInitial() {
    if (Verifier.nondetBoolean()) {
      readSelect();
    }
  }

  private boolean isFetch() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetBoolean();
  }

  /** ARG-V: suitable */
 private void readSelect() {
    String props = Verifier.nondetString();
    if (props.startsWith("(")) {
      props = props.substring(1, props.length() - 1);
    }
  }

  private boolean isFindFetchEnd() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetBoolean();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main(Verifier.nondetString());
	instance.processInitial();
	instance.isFetch();
	instance.readSelect();
	instance.isFindFetchEnd();
}
}
