

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.UUID;

public class Main {
    private static String VERSION = "1.8.2302070202.46";

    /** ARG-V: suitable */
	 public static String enterFarm(String userId) {
        String args = "[{\"queryLastRecordNum\":true,\"recall\":false,\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"userId\":\"" + userId + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String enterFarm(String farmId, String userId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }
    // 一起拿小鸡饲料
    /** ARG-V: suitable */
	 public static String letsGetChickenFeedTogether() {
        String args1 = "[{\"needHasInviteUserByCycle\":\"true\",\"requestType\":\"RPC\",\"sceneCode\":\"ANTFARM_P2P\",\"source\":\"ANTFARM\",\"startIndex\":0," +
                "\"version\":\""+VERSION+"\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }
    // 赠送饲料
    /** ARG-V: suitable */
	 public static String giftOfFeed(String bizTraceId,String userId) {
        String args1 = "[{\"beInvitedUserId\":\"" + userId +
                "\",\"bizTraceId\":\"" + bizTraceId +
                "\",\"requestType\":\"RPC\",\"sceneCode\":\"ANTFARM_P2P\"," +
                "\"source\":\"ANTFARM\",\"version\":\"" + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }
    /** ARG-V: suitable */
	 public static String syncAnimalStatus(String farmId) {
        String args1 = "[{\"farmId\":\"" + farmId +
                "\",\"operType\":\"FEEDSYNC\",\"queryFoodStockInfo\":false,\"recall\":false,\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"userId\":\""
                + farmId2UserId(farmId) + "\",\"version\":\"" + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String sleep() {
        String args1 = "[{\"requestType\":\"RPC\",\"sceneCode\":\"ANTFARM\",\"source\":\"LOVECABIN\",\"version\":\"unknown\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String wakeUp() {
        String args1 = "[{\"requestType\":\"RPC\",\"sceneCode\":\"ANTFARM\",\"source\":\"LOVECABIN\",\"version\":\"unknown\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String queryLoveCabin(String userId) {
        String args = "[{\"requestType\":\"RPC\",\"sceneCode\":\"ANTFARM\",\"source\":\"LOVECABIN\",\"userId\":\"" + userId + "\"}]";
assert true; //inline assert generated by ARG-V
		//        String args1 = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"ENTERFARM\",\"userId\":\"" + userId + "\"}]";
        return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String rewardFriend(String consistencyKey, String friendId, String productNum, String time) {
        String args1 = "[{\"canMock\":true,\"consistencyKey\":\"" + consistencyKey
                + "\",\"friendId\":\"" + friendId + "\",\"operType\":\"1\",\"productNum\":" + productNum +
                ",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"time\":"
                + time + ",\"version\":\"" + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String recallAnimal(String animalId, String currentFarmId, String masterFarmId) {
        String args1 = "[{\"animalId\":\"" + animalId + "\",\"currentFarmId\":\""
                + currentFarmId + "\",\"masterFarmId\":\"" + masterFarmId +
                "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String orchardRecallAnimal(String animalId, String userId) {
        String args1 = "[{\"animalId\":\"" + animalId + "\",\"orchardUserId\":\"" + userId +
                "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ORCHARD\",\"source\":\"zhuangyuan_zhaohuixiaoji\",\"version\":\"0.1.2403061630.6\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String sendBackAnimal(String sendType, String animalId, String currentFarmId, String masterFarmId) {
        String args1 = "[{\"animalId\":\"" + animalId + "\",\"currentFarmId\":\""
                + currentFarmId + "\",\"masterFarmId\":\"" + masterFarmId +
                "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"sendType\":\""
                + sendType + "\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String harvestProduce(String farmId) {
        String args1 = "[{\"canMock\":true,\"farmId\":\"" + farmId +
                "\",\"giftType\":\"\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String getCharityAccount(String userId) {
        String args = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"userId\":\"" + userId + "\",\"version\":\"unknown\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String listActivityInfo() {
        String args1 = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String getProjectInfo(String projectId) {
        String args = "[{\"activityId\":\"\",\"projectId\":\"" + projectId + "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"ANTFARM\",\"version\":\"" + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String donation(String activityId, int donationAmount) {
        String args1 = "[{\"activityId\":\"" + activityId + "\",\"donationAmount\":" + donationAmount +
                ",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String listFarmTask() {
        String args1 = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String getAnswerInfo() {
        String args1 = "[{\"answerSource\":\"foodTask\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String answerQuestion(String quesId, int answer) {
        String args1 = "[{\"answers\":\"[{\\\"questionId\\\":\\\"" + quesId + "\\\",\\\"answers\\\":[" + answer +
                "]}]\",\"bizkey\":\"ANSWER\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String receiveFarmTaskAward(String taskId) {
        String args1 = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"taskId\":\""
                + taskId + "\",\"version\":\"" + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String listToolTaskDetails() {
        String args1 = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String receiveToolTaskReward(String rewardType, int rewardCount, String taskType) {
        String args1 = "[{\"ignoreLimit\":false,\"requestType\":\"NORMAL\",\"rewardCount\":" + rewardCount
                + ",\"rewardType\":\"" + rewardType + "\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"taskType\":\""
                + taskType + "\",\"version\":\"" + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String feedAnimal(String farmId) {
        String args1 = "[{\"animalType\":\"CHICK\",\"canMock\":true,\"farmId\":\"" + farmId +
                "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String listFarmTool() {
        String args1 = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String useFarmTool(String targetFarmId, String toolId, String toolType) {
        String args1 = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"targetFarmId\":\""
                + targetFarmId + "\",\"toolId\":\"" + toolId + "\",\"toolType\":\"" + toolType + "\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String rankingList(int pageStartSum) {
        String args1 = "[{\"pageSize\":20,\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"startNum\":"
                + pageStartSum + ",\"version\":\"" + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String notifyFriend(String animalId, String notifiedFarmId) {
        String args1 = "[{\"animalId\":\"" + animalId +
                "\",\"animalType\":\"CHICK\",\"canBeGuest\":true,\"notifiedFarmId\":\"" + notifiedFarmId +
                "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"version\":\""
                + VERSION + "\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String feedFriendAnimal(String friendFarmId) {
        String args = "[{\"friendFarmId\":\"" + friendFarmId + "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String feedFriendAnimal(String friendFarmId, String groupId) {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return feedFriendAnimal(friendFarmId);
        }
        String args = "[{\"friendFarmId\":\"" + friendFarmId + "\",\"groupId\":\"" + groupId + "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ChickFamily\",\"source\":\"H5\",\"spaceType\":\"ChickFamily\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String farmId2UserId(String farmId) {
        int l = farmId.length() / 2;
        assert true; //inline assert generated by ARG-V
		return farmId.substring(l);
    }

    public static String collectManurePot(String manurePotNO) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String sign() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String initFarmGame(String gameType) {
        if ("flyGame".equals(gameType)) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static int RandomScore(String str) {
        if ("starGame".equals(str)) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } else if ("jumpGame".equals(str)) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } else if ("flyGame".equals(str)) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } else if ("hitGame".equals(str)) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } else {
            assert true; //inline assert generated by ARG-V
			return 210;
        }
    }

    public static String recordFarmGame(String gameType) {
        String uuid = getUuid();
        String md5String = getMD5(uuid);
        int score = RandomScore(gameType);
        if ("flyGame".equals(gameType)) {
            int foodCount = score / 50;
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private static String getUuid() {
        StringBuilder sb = new StringBuilder();
        assert true; //inline assert generated by ARG-V
		return sb.toString();
    }

    public static String getMD5(String password) {
        try {
            // 得到一个信息摘要器
            MessageDigest digest = MessageDigest.getInstance("md5");
            byte[] result = digest.digest(password.getBytes());
            StringBuilder buffer = new StringBuilder();
            assert true; //inline assert generated by ARG-V
			// 标准的md5加密后的结果
            return buffer.toString();
        } catch (Exception e) {
            e.printStackTrace();
            assert true; //inline assert generated by ARG-V
			return "";
        }
    }

    /* 小鸡厨房 */

    public static String enterKitchen(String userId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String collectDailyFoodMaterial(int dailyFoodMaterialAmount) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String queryFoodMaterialPack() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String collectDailyLimitedFoodMaterial(int dailyLimitedFoodMaterialAmount) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String farmFoodMaterialCollect() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String cook(String userId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String useFarmFood(String cookbookId, String cuisineId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String collectKitchenGarbage() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /* 日常任务 */

    public static String queryTabVideoUrl() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String videoDeliverModule(String bizId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String videoTrigger(String bizId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /* 惊喜礼包 */
    public static String drawLotteryPlus() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /* 小麦 */

    public static String acceptGift() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String visitFriend(String friendFarmId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /* 小鸡日记 */
    public static String queryChickenDiaryList() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String queryChickenDiary(String queryDayStr) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String diaryTietie(String diaryDate, String roleId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String visitAnimal() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String feedFriendAnimalVisit(String friendFarmId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String visitAnimalSendPrize(String token) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /* 抽抽乐 */
    public static String enterDrawMachine() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String drawPrize() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String listFarmDrawTimesTask() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String receiveFarmDrawTimesTaskAward(String taskId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String hireAnimal(String farmId, String animalId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String drawGameCenterAward() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String queryGameList() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    // 小鸡换装
    public static String listOrnaments() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String saveOrnaments(String animalId, String farmId, String ornaments) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    // 亲密家庭
    public static String enterFamily() {
        String args = "[{\"fromAnn\":false,\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /**
     * 同步家庭状态
     * @param groupId 家庭ID
     * @param operType 要同步的信息类型
     *                 INTIMACY_VALUE : 亲密度
     *                 FAMILY_INTERACT_ACTION : 进行的活动
     *                 ANIMAL_STATUS : 小鸡状态
     *                 SLEEP_INFO|ANIMAL_STATUS : 小鸡状态与睡眠信息
     * @param syncUserIds 要同步的用户ID
     * @return String
     */
    /** ARG-V: suitable */
	 public static String syncFamilyStatus(String groupId, String operType, String syncUserIds) {
        // INTIMACY_VALUE
        // FAMILY_INTERACT_ACTION
        // SLEEP_INFO|ANIMAL_STATUS
        // ANIMAL_STATUS|SLEEP_INFO
        // ANIMAL_STATUS
        String args = "[{\"groupId\":\"" + groupId + "\",\"operType\":\"" + operType + "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"syncUserIds\":[\"" + syncUserIds + "\"]}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

//    public static String familyListFarmTask() {
//        String args = "[{\"bizKey\":\"FAMILY_SIGN_TASK\",\"requestType\":\"NORMAL\",\"sceneCode\":\"familySign\",\"signSceneCode\":\"\",\"source\":\"H5\",\"taskSceneCode\":\"ANTFARM_FAMILY_TASK\"}]";
//        return ApplicationHook.requestString("com.alipay.antfarm.listFarmTask", args);
//    }

    /** ARG-V: suitable */
	 public static String familyReceiveFarmTaskAward(String taskId) {
        String args = "[{\"awardType\":\"FAMILY_INTIMACY\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"taskId\":\"" + taskId + "\",\"taskSceneCode\":\"ANTFARM_FAMILY_TASK\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String familyAwardList() {
        String args = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String receiveFamilyAward(String rightId) {
        String args = "[{\"requestType\":\"NORMAL\",\"rightId\":\"" + rightId + "\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String familySleep(String groupId) {
        String args = "[{\"groupId\":\"" + groupId + "\",\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"H5\",\"spaceType\":\"ChickFamily\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String familyWakeUp() {
        String args = "[{\"requestType\":\"NORMAL\",\"sceneCode\":\"ANTFARM\",\"source\":\"aixinxiaowutojiating\"}]";
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		enterFarm(Verifier.nondetString());
		enterFarm(Verifier.nondetString(), Verifier.nondetString());
		letsGetChickenFeedTogether();
		giftOfFeed(Verifier.nondetString(), Verifier.nondetString());
		syncAnimalStatus(Verifier.nondetString());
		sleep();
		wakeUp();
		queryLoveCabin(Verifier.nondetString());
		rewardFriend(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString(),
				Verifier.nondetString());
		recallAnimal(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		orchardRecallAnimal(Verifier.nondetString(), Verifier.nondetString());
		sendBackAnimal(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString(),
				Verifier.nondetString());
		harvestProduce(Verifier.nondetString());
		getCharityAccount(Verifier.nondetString());
		listActivityInfo();
		getProjectInfo(Verifier.nondetString());
		donation(Verifier.nondetString(), Verifier.nondetInt());
		listFarmTask();
		getAnswerInfo();
		answerQuestion(Verifier.nondetString(), Verifier.nondetInt());
		receiveFarmTaskAward(Verifier.nondetString());
		listToolTaskDetails();
		receiveToolTaskReward(Verifier.nondetString(), Verifier.nondetInt(), Verifier.nondetString());
		feedAnimal(Verifier.nondetString());
		listFarmTool();
		useFarmTool(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		rankingList(Verifier.nondetInt());
		notifyFriend(Verifier.nondetString(), Verifier.nondetString());
		feedFriendAnimal(Verifier.nondetString());
		feedFriendAnimal(Verifier.nondetString(), Verifier.nondetString());
		farmId2UserId(Verifier.nondetString());
		collectManurePot(Verifier.nondetString());
		sign();
		initFarmGame(Verifier.nondetString());
		RandomScore(Verifier.nondetString());
		recordFarmGame(Verifier.nondetString());
		getUuid();
		getMD5(Verifier.nondetString());
		enterKitchen(Verifier.nondetString());
		collectDailyFoodMaterial(Verifier.nondetInt());
		queryFoodMaterialPack();
		collectDailyLimitedFoodMaterial(Verifier.nondetInt());
		farmFoodMaterialCollect();
		cook(Verifier.nondetString());
		useFarmFood(Verifier.nondetString(), Verifier.nondetString());
		collectKitchenGarbage();
		queryTabVideoUrl();
		videoDeliverModule(Verifier.nondetString());
		videoTrigger(Verifier.nondetString());
		drawLotteryPlus();
		acceptGift();
		visitFriend(Verifier.nondetString());
		queryChickenDiaryList();
		queryChickenDiary(Verifier.nondetString());
		diaryTietie(Verifier.nondetString(), Verifier.nondetString());
		visitAnimal();
		feedFriendAnimalVisit(Verifier.nondetString());
		visitAnimalSendPrize(Verifier.nondetString());
		enterDrawMachine();
		drawPrize();
		listFarmDrawTimesTask();
		receiveFarmDrawTimesTaskAward(Verifier.nondetString());
		hireAnimal(Verifier.nondetString(), Verifier.nondetString());
		drawGameCenterAward();
		queryGameList();
		listOrnaments();
		saveOrnaments(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		enterFamily();
		syncFamilyStatus(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		familyReceiveFarmTaskAward(Verifier.nondetString());
		familyAwardList();
		receiveFamilyAward(Verifier.nondetString());
		familySleep(Verifier.nondetString());
		familyWakeUp();
	}
}
