

/** filtered and transformed by ARG-V */

/**
 * OpenKM, Open Document Management System (http://www.openkm.com)
 * Copyright (c) 2006-2017 Paco Avila & Josep Llort
 * <p>
 * No bytes were intentionally harmed during the development of this application.
 * <p>
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
	/**
	 * Create internal cron tasks
	 */
	public static void createOrUpdate(String name, String expression, String content) throws RuntimeException {
		if (Verifier.nondetBoolean()) {
			String mail = Verifier.nondetString();
		}
	}

	/**
	 * Change "Text Extractor Worker" or "Text extractor worker" to "TextExtractorWorker".
	 */
	/** ARG-V: suitable */
	 private static String toFileName(String str) {
		StringBuilder sb = new StringBuilder();
		boolean toUpper = true;

		for (int i = 0; i < str.length(); i++) {
			char c = str.charAt(i);

			if (c == ' ') {
				toUpper = true;
				continue;
			} else if (toUpper) {
				sb.append(Character.toUpperCase(c));
				toUpper = false;
			} else {
				sb.append(c);
			}
		}

		assert true; //inline assert generated by ARG-V
		return sb.toString();
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		createOrUpdate(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		toFileName(Verifier.nondetString());
	}
}
