

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
    public String inkStoryFile = Verifier.nondetString();

    protected String currentLine = Verifier.nondetString();

    /** ARG-V: suitable */
	 public void makeMessage() {
        String message = currentLine;

        if(message.startsWith("[image:") && message.endsWith("]")) {
            String imageFile = message.substring(7);
            imageFile = imageFile.substring(0, imageFile.length() - 1);

            if(Verifier.nondetBoolean()) {
                float scale = Verifier.nondetFloat();
            }

            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    public void onShow() {
        try {
            String fileJson = Verifier.nondetString();

            // Fixup some characters for Ink, will explode otherwise (https://github.com/bladecoder/blade-ink/issues/8)
            String BOM = new String("\uFEFF".getBytes("UTF-8"));
            fileJson = fileJson.replace(BOM, "");

            processStory();
        } catch(Exception e) {
        }
    }

    public void next() {
        if(Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        processStory();

        // Update the window
        makeMessage();
    }

    public void processStory() {
        try {
        } catch(Exception e) {
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.makeMessage();
		instance.onShow();
		instance.next();
		instance.processStory();
	}
}
