/** filtered and transformed by ARG-V */

/*
 *
 * Autopsy Forensic Browser
 *
 * Copyright 2012-2021 Basis Technology Corp.
 *
 * Copyright 2012 42six Solutions.
 * Contact: aebadirad <at> 42six <dot> com
 * Project Contact/Architect: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Paths;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.Collection;
import java.util.Scanner;
import java.util.stream.Collectors;

/**
 * Extracts activity from Internet Explorer browser, as well as recent documents
 * in windows.
 */
class Main {

    private String PASCO_LIB_PATH = Verifier.nondetString();
    private String JAVA_PATH = Verifier.nondetString();
    private static String RESOURCE_URL_PREFIX = "res://";
    private static SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
    /**
     * Finds the files storing bookmarks and creates artifacts
     */
    private void getBookmark() {
        try {
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    /**
     * Finds files that store cookies and adds artifacts for them.
     */
    private void getCookie() {
        try {
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    /**
     * Locates index.dat files, runs Pasco on them, and creates artifacts.
     *
     * @param moduleTempDir        The path to the module temp directory.
     * @param moduleTempResultsDir The path to the module temp results
     *                             directory.
     */
    private void getHistory(String moduleTempDir, String moduleTempResultsDir) {
        boolean foundHistory = false;

        final File pascoRoot = null; //NON-NLS
        if (pascoRoot == null) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        final String pascoHome = pascoRoot.getAbsolutePath();
        File resultsDir = new File(moduleTempResultsDir);
        resultsDir.mkdirs();

        try {
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        String temps = Verifier.nondetString();
        String indexFileName = Verifier.nondetString();
    }

    /**
     * Execute pasco on a single file that has been saved to disk.
     *
     * @param indexFilePath        Path to local index.dat file to analyze
     * @param outputFileName       Name of file to save output to
     * @param moduleTempResultsDir the path to the module temp directory.
     *
     * @return false on error
     */
    /** ARG-V: suitable */
	 private boolean executePasco(String indexFilePath, String outputFileName, String moduleTempResultsDir) {
        boolean success = true;
        try {
            final String outputFileFullPath = moduleTempResultsDir + File.separator + outputFileName;
            final String errFileFullPath = moduleTempResultsDir + File.separator + outputFileName + ".err"; //NON-NLS
            List<String> commandLine = new ArrayList<>();
            commandLine.add(JAVA_PATH);
            commandLine.add("--add-exports=java.xml/com.sun.org.apache.xalan.internal.xsltc.dom=ALL-UNNAMED");
            commandLine.add("-cp"); //NON-NLS
            commandLine.add(PASCO_LIB_PATH);
            commandLine.add("isi.pasco2.Main"); //NON-NLS
            commandLine.add("-T"); //NON-NLS
            commandLine.add("history");  //NON-NLS
            commandLine.add(indexFilePath);
            ProcessBuilder processBuilder = new ProcessBuilder(commandLine);
            processBuilder.redirectOutput(new File(outputFileFullPath));
            processBuilder.redirectError(new File(errFileFullPath));
        } catch (Exception e) {
            success = false;
        }
        assert true; //inline assert generated by ARG-V
		return success;
    }

    /**
     * Extract the domain from the supplied URL. This method does additional
     * checks to detect invalid URLs.
     *
     * @param url The URL from which to extract the domain.
     *
     * @return The domain.
     */
    /** ARG-V: suitable */
	 private String extractDomain(String url) {
        if (url == Verifier.nondetString() || url.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return url;
        }

        if (url.toLowerCase().startsWith(RESOURCE_URL_PREFIX)) {
            assert true; //inline assert generated by ARG-V
			/*
             * Ignore URLs that begin with the matched text.
             */
            return Verifier.nondetString();
        }

        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getBookmark();
		instance.getCookie();
		instance.getHistory(Verifier.nondetString(), Verifier.nondetString());
		instance.executePasco(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		instance.extractDomain(Verifier.nondetString());
	}
}
