

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Collection;

/**
 * Parses the BindParams if they are using named parameters.
 * <p>
 * This is a thread safe implementation.
 * </p>
 */
public final class Main {

  private static String ENCRYPTKEY_PREFIX = "encryptkey_";
  private static String ENCRYPTKEY_GAP = "___";
  private static int ENCRYPTKEY_PREFIX_LEN = ENCRYPTKEY_PREFIX.length();
  private static int ENCRYPTKEY_GAP_LEN = ENCRYPTKEY_GAP.length();
  /**
   * Used to parse sql looking for named parameters.
   */
  private static String quote = "'";
  /**
   * Used to parse sql looking for named parameters.
   */
  private static String colon = ":";

  private String sql = Verifier.nondetString();
  /**
   * Parse the sql changed named parameters to positioned parameters if required.
   * <p>
   * The sql is used when named parameters are used.
   * </p>
   * <p>
   * This is used in most cases of named parameters. The case it is NOT used for is
   * named parameters in a having clause. In this case some of the named parameters
   * could be for a where clause and some for the having clause.
   * </p>
   */
  private String parseSql() {
    if (Verifier.nondetBoolean()) {
      String preparedSql = Verifier.nondetString();
      if (preparedSql != Verifier.nondetString() && !preparedSql.isEmpty()) {
        assert true; //inline assert generated by ARG-V
		// the sql has already been parsed and positionedParameters are set in order
        return preparedSql;
      }
    }
    String preparedSql = Verifier.nondetString();
    assert true; //inline assert generated by ARG-V
	return preparedSql;
  }

  /** ARG-V: suitable */
 private int findEndOfParam(int nameParamStart) {
    int endOfParam = nameParamStart + 1;
    do {
      char c = sql.charAt(endOfParam);
      if (c != '_' && !Character.isLetterOrDigit(c)) {
        break;
      }
      endOfParam++;
    } while (endOfParam < sql.length());
    assert true; //inline assert generated by ARG-V
	return endOfParam;
  }

  /**
   * Find the next named parameter start position (based on colon).
   */
  /** ARG-V: suitable */
 static int findNameStart(String sql, int startPos) {
    while (true) {
      int colonPos = sql.indexOf(colon, startPos);
      if (colonPos > -1) {
        // validate the next character after the colon (ignore postgres cast)
        char c = sql.charAt(colonPos + 1);
        if (c == '_' || Character.isLetterOrDigit(c)) {
          assert true; //inline assert generated by ARG-V
		return colonPos;
        } else {
          startPos = colonPos + 2;
          continue;
        }
      }
      assert true; //inline assert generated by ARG-V
	return -1;
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.parseSql();
	instance.findEndOfParam(Verifier.nondetInt());
	findNameStart(Verifier.nondetString(), Verifier.nondetInt());
}

}
