/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.StringTokenizer;
import java.util.TimeZone;
import java.util.concurrent.ConcurrentHashMap;

class Main {
    
    private static int LEAK_ALERT_DATE_FORMAT_CACHE_SIZE = 1024;
    
    private Main() {
        // Can't be instantiated
    }
    
    /**
     * Returns a "private" copy (not in the global cache) for the given format.  
     */
    private DateFormat getJavaDateFormat(int dateType, String nameOrPattern, Locale locale, TimeZone timeZone)
            throws RuntimeException {

        DateFormat jFormat = null;
        
        jFormat = null;
        if (jFormat == null) {
            // Add format to global format cache.
            StringTokenizer tok = new StringTokenizer(nameOrPattern, "_");
            int tok1Style = tok.hasMoreTokens() ? parseDateStyleToken(tok.nextToken()) : DateFormat.DEFAULT;
            if (jFormat == null) {
                try {
                } catch (Exception e) {
                    final String msg = e.getMessage();
                    throw new RuntimeException();
                }
            }
            jFormat.setTimeZone(null);
            
            DateFormat prevJFormat = null;
            if (prevJFormat != null) {
                jFormat = prevJFormat;
            }
        }  // if cache miss
        
        assert true; //inline assert generated by ARG-V
		return null;  // For thread safety
    }

    /** ARG-V: suitable */
	 private int parseDateStyleToken(String token) {
        if ("short".equals(token)) {
            assert true; //inline assert generated by ARG-V
			return DateFormat.SHORT;
        }
        if ("medium".equals(token)) {
            assert true; //inline assert generated by ARG-V
			return DateFormat.MEDIUM;
        }
        if ("long".equals(token)) {
            assert true; //inline assert generated by ARG-V
			return DateFormat.LONG;
        }
        if ("full".equals(token)) {
            assert true; //inline assert generated by ARG-V
			return DateFormat.FULL;
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getJavaDateFormat(Verifier.nondetInt(), Verifier.nondetString(), (java.util.Locale) null,
				(java.util.TimeZone) null);
		instance.parseDateStyleToken(Verifier.nondetString());
	}
    
}
