

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * url 相关工具类
 *
 * @author zhaojun
 */
public class Main {

	/**
	 * 判断 URL 是否包含协议部分
	 *
	 * @param 	url
	 * 			URL 地址
	 *
	 * @return	是否包含协议部分
	 */
	public static boolean hasScheme(String url) {
		assert true; //inline assert generated by ARG-V
		return url.startsWith("http://") || url.startsWith("https://");
	}

	/**
	 * 为 URL 拼接参数
	 *
	 * @param 	url
	 * 			原始 URL
	 *
	 * @param 	name
	 * 			参数名称
	 *
	 * @param 	value
	 * 			参数值
	 *
	 * @return	拼接后的 URL
	 */
	/** ARG-V: suitable */
	 public static String concatQueryParam(String url, String name, String value) {
		if (Verifier.nondetBoolean()) {
			assert true; //inline assert generated by ARG-V
			return url + "&" + name + "=" + value;
		} else {
			assert true; //inline assert generated by ARG-V
			return url + "?" + name + "=" + value;
		}
	}

	/**
	 * 获取 URL 中的协议部分
	 *
	 * @param 	url
	 * 			URL 地址
	 *
	 * @return	协议部分
	 */
	public static String getSchema(String url) {
		if (Verifier.nondetBoolean()) {
			assert true; //inline assert generated by ARG-V
			return "http";
		} else if (Verifier.nondetBoolean()) {
			assert true; //inline assert generated by ARG-V
			return "https";
		} else {
			assert true; //inline assert generated by ARG-V
			return "http";
		}
	}

	/**
	 * 移除 URL 中的协议部分
	 *
	 * @param 	url
	 * 			URL 地址
	 *
	 * @return	移除协议部分后的 URL
	 */
	/** ARG-V: suitable */
	 public static String removeScheme(String url) {
		if (Verifier.nondetBoolean()) {
			url = url.substring(7);
		} else if (Verifier.nondetBoolean()) {
			url = url.substring(8);
		}

		assert true; //inline assert generated by ARG-V
		return url;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		hasScheme(Verifier.nondetString());
		concatQueryParam(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		getSchema(Verifier.nondetString());
		removeScheme(Verifier.nondetString());
	}

}
