/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    public boolean canHandle(String url) {
        assert true; //inline assert generated by ARG-V
		return url.startsWith("jdbc:hive2");
    }

    /** ARG-V: suitable */
	 public String quoteIdentifier(String colName) {
        if(colName.contains(".")){
            String colName1 = colName.substring(colName.indexOf(".") + 1);
            assert true; //inline assert generated by ARG-V
			return "`"+colName1+"`";
        }
        assert true; //inline assert generated by ARG-V
		return  "`"+colName+"`";
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.canHandle(Verifier.nondetString());
		instance.quoteIdentifier(Verifier.nondetString());
	}
}
