# This is a Docker image for running the tests.
# It should be pushed to registry.gitlab.com/sosy-lab/software/test-format/test
# and will be used by CI as declared in .gitlab-ci.yml.
#
# Commands for updating the image:
# docker build --pull -t registry.gitlab.com/sosy-lab/sv-comp/bench-defs/test:latest - < test/Dockerfile.test
# docker push registry.gitlab.com/sosy-lab/sv-comp/bench-defs/test:latest

FROM python:3.8

RUN pip install -U pip \
    && pip install lxml pyyaml
