/** filtered and transformed by ARG-V */

/*
 * This is the source code of Telegram for Android v. 5.x.x.
 * It is licensed under GNU GPL v. 2 or later.
 * You should have received a copy of the license in this archive (see LICENSE).
 *
 * Copyright Nikolai Kudashov, 2013-2018.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.lang.ref.WeakReference;
import java.net.URLEncoder;
import java.util.List;
import java.util.regex.Matcher;

public class Main {

    private static String customTabsPackageToBind = Verifier.nondetString();
    public static boolean isTelegraphUrl(String url, boolean equals) {
        assert true; //inline assert generated by ARG-V
		return isTelegraphUrl(url, equals, false);
    }
    /** ARG-V: suitable */
	 public static boolean isTelegraphUrl(String url, boolean equals, boolean forceHttps) {
        if (equals) {
            assert true; //inline assert generated by ARG-V
			return url.equals("telegra.ph") || url.equals("te.legra.ph") || url.equals("graph.org");
        }
        assert true; //inline assert generated by ARG-V
		return url.matches("^(https" + (forceHttps ? "" : "?") + "://)?(te\\.?legra\\.ph|graph\\.org)(/.*|$)"); // telegra.ph, te.legra.ph, graph.org
    }

    /** ARG-V: suitable */
	 public static String extractUsername(String link) {
        if (link.startsWith("@")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(1);
        }
        if (link.startsWith("t.me/")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(5);
        }
        if (link.startsWith("http://t.me/")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(12);
        }
        if (link.startsWith("https://t.me/")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(13);
        }
        Matcher prefixMatcher = null;
        if (prefixMatcher.find()) {
            assert true; //inline assert generated by ARG-V
			return prefixMatcher.group(1);
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static boolean urlMustNotHaveConfirmation(String url) {
        assert true; //inline assert generated by ARG-V
		return (
            isTelegraphUrl(url, false, true) ||
            url.matches("^(https://)?t\\.me/iv\\??(/.*|$)") || // t.me/iv?
            url.matches("^(https://)?telegram\\.org/(blog|tour)(/.*|$)") || // telegram.org/blog, telegram.org/tour
            url.matches("^(https://)?fragment\\.com(/.*|$)") // fragment.com
        );
    }

    public static boolean isInternalUrl(String url, boolean[] forceBrowser) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public static boolean isInternalUrl(String url, boolean all, boolean[] forceBrowser) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public static boolean isPassportUrl(String url) {
        if (url == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        try {
            url = url.toLowerCase();
            if (url.startsWith("tg:passport") || url.startsWith("tg://passport") || url.startsWith("tg:secureid") || url.contains("resolve") && url.contains("domain=telegrampassport")) {
                assert true; //inline assert generated by ARG-V
				return true;
            }
        } catch (Exception e) {

        }
        assert true; //inline assert generated by ARG-V
		return false;
    }
	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		isTelegraphUrl(Verifier.nondetString(), Verifier.nondetBoolean());
		isTelegraphUrl(Verifier.nondetString(), Verifier.nondetBoolean(), Verifier.nondetBoolean());
		extractUsername(Verifier.nondetString());
		urlMustNotHaveConfirmation(Verifier.nondetString());
		isInternalUrl(Verifier.nondetString(), new boolean[] { Verifier.nondetBoolean() });
		isInternalUrl(Verifier.nondetString(), Verifier.nondetBoolean(), new boolean[] { Verifier.nondetBoolean() });
		isPassportUrl(Verifier.nondetString());
	}
}
