/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.LinkedList;
import java.util.List;

public final class Main {
    public static int OTHER = -1;
    public static int PREPARE = 1;
    public static int EXECUTE = 2;
    public static int DROP = 3;

    private Main() {
    }

    /** ARG-V: suitable */
	 private static boolean needSpaceAndComment(String stmt, int offset) {
        if (stmt.length() > offset + 1) {
            char c = stmt.charAt(offset + 1);
            if (c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '/' || c == '#') {
                assert true; //inline assert generated by ARG-V
				return true;
            }
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    /** ARG-V: suitable */
	 private static int skipSpaceAndComment(String stmt, int offset) {
        int i = ++offset;
        for (; i < stmt.length(); ++i) {
            switch (stmt.charAt(i)) {
                case ' ':
                case '\t':
                case '\r':
                case '\n':
                    break;
                case '/':
                case '#':
                    i = Verifier.nondetInt();
                    break;
                default:
                    return i - 1;
            }
        }
        assert true; //inline assert generated by ARG-V
		return i - 1;
    }

    /** ARG-V: suitable */
	 public static void parseStmt(String stmt, List<String> parts) {
        int start = 0;
        for (int i = 0; i < stmt.length(); ++i) {
            switch (stmt.charAt(i)) {
                case '/':
                case '#':
                    i = Verifier.nondetInt();
                    break;
                case '?':
                    parts.add(stmt.substring(start, i));
                    start = i + 1;
                    break;
                default:
                    break;
            }
        }
        parts.add(stmt.substring(start, stmt.length()));
    }

    /** ARG-V: suitable */
	 private static void argsParse(String stmt, int offset, List<String> arguments) {
        int i = offset;
        while (i < stmt.length()) {
            char c1 = stmt.charAt(++i);
            if (c1 == '@') {
                i = argName(stmt, i, arguments);
            }
        }
    }

    /** ARG-V: suitable */
	 private static int argName(String stmt, int offset, List<String> arguments) {
        int i = ++offset;
        for (; i < stmt.length(); i++) {
            char c1 = stmt.charAt(i);
            switch (c1) {
                case ',':
                case ' ':
                case '\t':
                case '\r':
                case '\n':
                case '/':
                case '#':
                    arguments.add(stmt.substring(offset, i).toUpperCase());
                    i = skipSpaceAndComment(stmt, i);
                    return i;
                default:
                    break;
            }
        }
        arguments.add(stmt.substring(offset, i).toUpperCase());
        assert true; //inline assert generated by ARG-V
		return i;
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{needSpaceAndComment(Verifier.nondetString(),Verifier.nondetInt());skipSpaceAndComment(Verifier.nondetString(),Verifier.nondetInt());parseStmt(Verifier.nondetString(),(java.util.List<java.lang.String>)null);argsParse(Verifier.nondetString(),Verifier.nondetInt(),(java.util.List<java.lang.String>)null);argName(Verifier.nondetString(),Verifier.nondetInt(),(java.util.List<java.lang.String>)null);}
}
