

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    private String commentStart = Verifier.nondetString();
    private int commentStartLength = Verifier.nondetInt();

    private String commentEnd = Verifier.nondetString();
    private int commendEndLength = Verifier.nondetInt();

    /** ARG-V: suitable */
	 public void commentSelected() {
        int start = Verifier.nondetInt();
        int end = Verifier.nondetInt();
        if (start != end) {
            String[] lines = new java.lang.String[] { Verifier.nondetString() };
            StringBuilder builder = new StringBuilder();
            int len = lines.length;
            for (int i = 0; i < len; i++) {
                String line = lines[i];
                if (!line.startsWith(commentStart)) {
					builder.append(commentStart);
				}
                builder.append(line);
                if (!line.endsWith(commentEnd)) {
					builder.append(commentEnd);
				}
                if (i != len - 1) {
					builder.append("\n");
				}
            }
        }
    }

    /** ARG-V: suitable */
	 public void unCommentSelected() {
        int start = Verifier.nondetInt();
        int end = Verifier.nondetInt();
        if (start != end) {
            String[] lines = new java.lang.String[] { Verifier.nondetString() };
            StringBuilder builder = new StringBuilder();
            int len = lines.length;
            for (int i = 0; i < len; i++) {
                String line = lines[i];
                if (line.startsWith(commentStart) && line.endsWith(commentEnd)) {
					builder.append(line.substring(commentStartLength, line.length() - commendEndLength));
				} else builder.append(line);
                if (i != len - 1) {
					builder.append("\n");
				}
            }
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.commentSelected();
		instance.unCommentSelected();
	}
}
