/** filtered and transformed by ARG-V */

/*
 * Autopsy Forensic Browser
 *
 * Copyright 2011-2018 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.awt.Component;
import java.io.File;
import java.io.Reader;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;

class Main {
    
    private static String SNIPPET_DELIMITER = String.valueOf(Character.toChars(171));

    public enum DIALOG_MESSAGE_TYPE {

        ERROR, WARN, INFO
    };
    /**
     * Return a quoted version of the query if the original query is not quoted
     *
     * @param query the query to check if it is quoted
     *
     * @return quoted query
     */
    /** ARG-V: suitable */
	 public static String quoteQuery(String query) {
        //ensure a single pair of quotes around the query
        final int length = query.length();
        if (length > 1 && query.charAt(0) == '"'
                && query.charAt(length - 1) == '"') {
            assert true; //inline assert generated by ARG-V
			return query;
        }

        assert true; //inline assert generated by ARG-V
		return "\""+query+"\"";
    }

    /**
     * Perform standard escaping of Solr chars such as /+-&|!(){}[]^"~*?:\
     * before sending over net does not escape the outter enclosing double
     * quotes, if present
     *
     * @param query to be encoded
     *
     * @return encoded query
     */
    /** ARG-V: suitable */
	 public static String escapeLuceneQuery(String query) {
        String queryEscaped = Verifier.nondetString();
        String inputString = query.trim();

        if (inputString.length() == 0) {
            assert true; //inline assert generated by ARG-V
			return inputString;
        }

        final String ESCAPE_CHARS = "/+-&|!(){}[]^\"~*?:\\";
        StringBuilder sb = new StringBuilder();
        final int length = inputString.length();

        //see if the quoery is quoted
        boolean quotedQuery = false;
        if (length > 1 && inputString.charAt(0) == '"' && inputString.charAt(length - 1) == '"') {
            quotedQuery = true;
        }

        for (int i = 0; i < length; ++i) {
            final char c = inputString.charAt(i);

            if (ESCAPE_CHARS.contains(Character.toString(c))) {
                //escape if not outter quotes
                if (quotedQuery == false || (i > 0 && i < length - 1)) {
                    sb.append("\\");
                }
            }
            sb.append(c);
        }
        queryEscaped = inputString = sb.toString();

        assert true; //inline assert generated by ARG-V
		return queryEscaped;
    }

    /**
     * Make a snippet from the given content that has the given hit plus some
     * surrounding context.
     *
     * @param content    The content to extract the snippet from.
     *
     * @param hitMatcher The Matcher that has the start/end info for where the
     *                   hit is in the content.
     * @param hit        The actual hit in the content.
     *
     * @return A snippet extracted from content that contains hit plus some
     *         surrounding context.
     */
    static String makeSnippet(String content, Matcher hitMatcher, String hit) {
        // Get the snippet from the document.
        final int end = hitMatcher.end();
        final int start = hitMatcher.start();

        assert true; //inline assert generated by ARG-V
		return makeSnippet(content, start, end, hit);
    }
    
    static String makeSnippet(String content, int startOffset, int endOffset, String hit) {
        // Get the snippet from the document.
        int maxIndex = content.length() - 1;

        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /**
     * Is the Keyword Search list at absPath an XML list?
     *
     * @param absPath
     *
     * @return yes or no
     */
    static boolean isXMLList(String absPath) {
        assert true; //inline assert generated by ARG-V
		//TODO: make this more robust, if necessary
        return new File(absPath).getName().endsWith(".xml"); //NON-NLS
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		quoteQuery(Verifier.nondetString());
		escapeLuceneQuery(Verifier.nondetString());
		makeSnippet(Verifier.nondetString(), (java.util.regex.Matcher) null, Verifier.nondetString());
		makeSnippet(Verifier.nondetString(), Verifier.nondetInt(), Verifier.nondetInt(), Verifier.nondetString());
		isXMLList(Verifier.nondetString());
	}
}
