/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author mycat
 */
public final class Main {
    private Main() {
    }

    public static int OTHER = -1;
    public static int DATABASES = 1;
    public static int TRACE = 2;
    public static int TABLES = 5;
    public static int TABLE_STATUS = 6;
    public static int CHARSET = 7;
    public static int COLUMNS = 8;
    public static int INDEX = 9;
    public static int CREATE_TABLE = 10;
    public static int VARIABLES = 11;
    public static int CREATE_VIEW = 12;
    public static int CREATE_DATABASE = 13;
    public static int DBLE_PROCESS_LIST = 14;

    /** ARG-V: suitable */
	 public static int parse(String stmt, int offset) {
        int i = offset;
        for (; i < stmt.length(); i++) {
            switch (stmt.charAt(i)) {
                case ' ':
                case '\r':
                case '\n':
                case '\t':
                    continue;
                case 'F':
                case 'f':
                    return showFCheck(stmt, i);
                case 'A':
                case 'a':
                    return showACheck(stmt, i);
                case '/':
                case '#':
                    i = Verifier.nondetInt();
                    continue;
                case 'D':
                case 'd':
                    return showDCheck(stmt, i);
                case 'G':
                case 'g':
                    return showGCheck(stmt, i);
                case 'T':
                case 't':
                    return showTCheck(stmt, i);
                case 'S':
                case 's':
                    return showSCheck(stmt, i);
                case 'C':
                case 'c':
                    return showCCheck(stmt, i);
                case 'I':
                case 'i':
                    return showIndex(stmt);
                case 'K':
                case 'k':
                    return showIndex(stmt);
                case 'V':
                case 'v':
                    return showVariables(stmt, i);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    private static int showCCheck(String stmt, int offset) {
        if (stmt.length() > offset++) {
            if (stmt.charAt(offset) == 'h' || stmt.charAt(offset) == 'H') {
                assert true; //inline assert generated by ARG-V
				return charsetCheck(stmt, offset);
            } else if (stmt.charAt(offset) == 'o' || stmt.charAt(offset) == 'O') {
                assert true; //inline assert generated by ARG-V
				return showColumns(stmt);
            } else if (stmt.charAt(offset) == 'r' || stmt.charAt(offset) == 'R') {
                assert true; //inline assert generated by ARG-V
				return showCreateCheck(stmt, offset);
            } else {
                assert true; //inline assert generated by ARG-V
				return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showDCheck(String stmt, int offset) {
        if (stmt.length() > offset++) {
            switch (stmt.charAt(offset)) {
                case 'a':
                case 'A':
                    return dataCheck(stmt, offset);
                case 'b':
                case 'B':
                    return showDbleProcessListCheck(stmt, offset);
                default:
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    private static int showFCheck(String stmt, int offset) {
        if (stmt.length() > offset++) {
            if (stmt.charAt(offset) == 'u' || stmt.charAt(offset) == 'U') {
                assert true; //inline assert generated by ARG-V
				return showFullCheck(stmt, offset);
            } else if (stmt.charAt(offset) == 'i' || stmt.charAt(offset) == 'I') { //show fields
                assert true; //inline assert generated by ARG-V
				return showColumns(stmt);
            } else {
                assert true; //inline assert generated by ARG-V
				return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showFullCheck(String stmt, int offset) {
        if (stmt.length() > offset + "ll ?".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            if ((c1 == 'L' || c1 == 'l') &&
                    (c2 == 'L' || c2 == 'l')) {
                while (stmt.length() > ++offset) {
                    if (Verifier.nondetBoolean()) {
                        continue;
                    }
                    switch (stmt.charAt(offset)) {
                        case 'T':
                        case 't':
                            return showTableType(stmt);
                        case 'C':
                        case 'c':
                        case 'F':
                        case 'f':
                            return showColumns(stmt);
                        default:
                            return OTHER;
                    }
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showACheck(String stmt, int offset) {
        if (stmt.length() > offset + "ll ?".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            if ((c1 == 'L' || c1 == 'l') &&
                    (c2 == 'L' || c2 == 'l')) {
                while (stmt.length() > ++offset) {
                    if (Verifier.nondetBoolean()) {
                        continue;
                    }
                    switch (stmt.charAt(offset)) {
                        case 'T':
                        case 't':
                            return showTableType(stmt);
                        default:
                            return OTHER;
                    }
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // SHOW DATA
    /** ARG-V: suitable */
	 private static int dataCheck(String stmt, int offset) {
        if (stmt.length() > offset + "ta?".length()) {
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            if ((c2 == 'T' || c2 == 't') && (c3 == 'A' || c3 == 'a')) {
                switch (stmt.charAt(++offset)) {
                    case 'B':
                    case 'b':
                        return showDatabases(stmt, offset);
                    default:
                        return OTHER;
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showGCheck(String stmt, int offset) {
        if (stmt.length() > offset + "lobal".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            if ((c1 == 'L' || c1 == 'l') && (c2 == 'O' || c2 == 'o') && (c3 == 'B' || c3 == 'b') && (c4 == 'A' || c4 == 'a') &&
                    (c5 == 'L' || c5 == 'l')) {
                while (stmt.length() > ++offset) {
                    if (Verifier.nondetBoolean()) {
                        continue;
                    }
                    assert true; //inline assert generated by ARG-V
					return showVariables(stmt, offset);
                }
            }
        }

        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    //show create table
    /** ARG-V: suitable */
	 private static int showCreateCheck(String stmt, int offset) {
        if (stmt.length() > offset + "eate".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            if ((c1 == 'E' || c1 == 'e') &&
                    (c2 == 'A' || c2 == 'a') &&
                    (c3 == 'T' || c3 == 't') &&
                    (c4 == 'E' || c4 == 'e')) {
                while (stmt.length() > ++offset) {
                    if (Verifier.nondetBoolean()) {
                        continue;
                    }
                    switch (stmt.charAt(offset)) {
                        case 'T':
                        case 't':
                            return showCreateTable(stmt, offset);
                        case 'V':
                        case 'v':
                            return showCreateView(stmt, offset);
                        case 'D':
                        case 'd':
                            return showCreateDatabase(stmt, offset);
                        default:
                            return OTHER;
                    }
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // show create table
    /** ARG-V: suitable */
	 private static int showCreateTable(String stmt, int offset) {
        if (stmt.length() > offset + 5) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
        }

        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // show create database
    /** ARG-V: suitable */
	 private static int showCreateDatabase(String stmt, int offset) {
        if (stmt.length() > offset + 8) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // show create view
    /** ARG-V: suitable */
	 private static int showCreateView(String stmt, int offset) {
        if (stmt.length() > offset + 4) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // SHOW DATABASES
    /** ARG-V: suitable */
	 private static int showDatabases(String stmt, int offset) {
        if (stmt.length() > offset + "ases".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            //"show database " statement need stricter inspection #1961
            int j = offset;
            for (; j < stmt.length(); j++) {
                switch (stmt.charAt(j)) {
                    case ' ':
                    case '\r':
                    case '\n':
                    case '\t':
                        continue;
                    case 'L':
                    case 'l':
                        return showDatabasesLike(stmt, offset);
                    case 'W':
                    case 'w':
                        return showDatabasesWhere(stmt, offset);
                    default:
                        return OTHER;
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showDatabasesLike(String stmt, int offset) {
        if (stmt.length() > offset + "like".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            if ((c1 == 'L' || c1 == 'l') &&
                    (c2 == 'I' || c2 == 'i') &&
                    (c3 == 'K' || c3 == 'k') &&
                    (c4 == 'E' || c4 == 'e')) {
                if (c5 != ' ' && c5 != '\r' && c5 != '\n' && c5 != '\t') {
                    assert true; //inline assert generated by ARG-V
					return OTHER;
                }
                assert true; //inline assert generated by ARG-V
				return DATABASES;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showDatabasesWhere(String stmt, int offset) {
        if (stmt.length() > offset + "where".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            if ((c1 == 'W' || c1 == 'w') &&
                    (c2 == 'H' || c2 == 'h') &&
                    (c3 == 'E' || c3 == 'e') &&
                    (c4 == 'R' || c4 == 'r') &&
                    (c5 == 'E' || c5 == 'e')) {
                if (c6 != ' ' && c6 != '\r' && c6 != '\n' && c6 != '\t') {
                    assert true; //inline assert generated by ARG-V
					return OTHER;
                }
                assert true; //inline assert generated by ARG-V
				return DATABASES;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showSCheck(String stmt, int offset) {
        // the length of "ession" or "chemas" is 6.
        if (stmt.length() > offset + 6) {
            switch (stmt.charAt(++offset)) {
                case 'C':
                case 'c':
                    return schemasCheck(stmt, offset);
                case 'E':
                case 'e':
                    return sessionCheck(stmt, offset);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    //show schemas
    /** ARG-V: suitable */
	 private static int schemasCheck(String stmt, int offset) {
        char c1 = stmt.charAt(++offset);
        char c2 = stmt.charAt(++offset);
        char c3 = stmt.charAt(++offset);
        char c4 = stmt.charAt(++offset);
        char c5 = stmt.charAt(++offset);
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    //show session
    /** ARG-V: suitable */
	 private static int sessionCheck(String stmt, int offset) {
        char c1 = stmt.charAt(++offset);
        char c2 = stmt.charAt(++offset);
        char c3 = stmt.charAt(++offset);
        char c4 = stmt.charAt(++offset);
        char c5 = stmt.charAt(++offset);
        if ((c1 == 'S' || c1 == 's') && (c2 == 'S' || c2 == 's') && (c3 == 'I' || c3 == 'i') && (c4 == 'O' || c4 == 'o') && (c5 == 'N' || c5 == 'n')) {
            while (stmt.length() > ++offset) {
                if (Verifier.nondetBoolean()) {
                    continue;
                }
                assert true; //inline assert generated by ARG-V
				return showVariables(stmt, offset);
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    //show charset
    /** ARG-V: suitable */
	 private static int charsetCheck(String stmt, int offset) {
        if (stmt.length() > offset + "arset".length()) {
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showTCheck(String stmt, int offset) {
        if (stmt.length() > offset++) {
            char c1 = stmt.charAt(offset);
            if (c1 == 'A' || c1 == 'a') {
                assert true; //inline assert generated by ARG-V
				return showTableType(stmt);
            } else if (c1 == 'R' || c1 == 'r') {
                assert true; //inline assert generated by ARG-V
				return showTrace(stmt, offset);
            } else {
                assert true; //inline assert generated by ARG-V
				return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int showTrace(String stmt, int offset) {
        if (stmt.length() > offset + "ace".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    public static int showTableType(String sql) {
        Pattern pattern = null;
        Matcher ma = pattern.matcher(sql);
        Pattern pattern1 = null;
        Matcher tableStatus = pattern1.matcher(sql);
        if (ma.matches()) {
            assert true; //inline assert generated by ARG-V
			return TABLES;
        } else if (tableStatus.matches()) {
            assert true; //inline assert generated by ARG-V
			return TABLE_STATUS;
        } else {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
    }

    private static int showColumns(String sql) {
        Pattern pattern = null;
        Matcher ma = pattern.matcher(sql);
        if (ma.matches()) {
            assert true; //inline assert generated by ARG-V
			return COLUMNS;
        } else {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
    }

    private static int showIndex(String sql) {
        Pattern pattern = null;
        Matcher ma = pattern.matcher(sql);
        if (ma.matches()) {
            assert true; //inline assert generated by ARG-V
			return INDEX;
        } else {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
    }

    /** ARG-V: suitable */
	 private static int showVariables(String stmt, int offset) {
        if (stmt.length() > offset + "ariables".length()) {
            char c1 = stmt.charAt(offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
            char c8 = stmt.charAt(++offset);
            char c9 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // SHOW dble_PROCESSLIST
    private static int showDbleProcessListCheck(String stmt, int offset) {
        final String keyword = "BLE_PROCESSLIST";
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		parse(Verifier.nondetString(), Verifier.nondetInt());
		showCCheck(Verifier.nondetString(), Verifier.nondetInt());
		showDCheck(Verifier.nondetString(), Verifier.nondetInt());
		showFCheck(Verifier.nondetString(), Verifier.nondetInt());
		showFullCheck(Verifier.nondetString(), Verifier.nondetInt());
		showACheck(Verifier.nondetString(), Verifier.nondetInt());
		dataCheck(Verifier.nondetString(), Verifier.nondetInt());
		showGCheck(Verifier.nondetString(), Verifier.nondetInt());
		showCreateCheck(Verifier.nondetString(), Verifier.nondetInt());
		showCreateTable(Verifier.nondetString(), Verifier.nondetInt());
		showCreateDatabase(Verifier.nondetString(), Verifier.nondetInt());
		showCreateView(Verifier.nondetString(), Verifier.nondetInt());
		showDatabases(Verifier.nondetString(), Verifier.nondetInt());
		showDatabasesLike(Verifier.nondetString(), Verifier.nondetInt());
		showDatabasesWhere(Verifier.nondetString(), Verifier.nondetInt());
		showSCheck(Verifier.nondetString(), Verifier.nondetInt());
		schemasCheck(Verifier.nondetString(), Verifier.nondetInt());
		sessionCheck(Verifier.nondetString(), Verifier.nondetInt());
		charsetCheck(Verifier.nondetString(), Verifier.nondetInt());
		showTCheck(Verifier.nondetString(), Verifier.nondetInt());
		showTrace(Verifier.nondetString(), Verifier.nondetInt());
		showTableType(Verifier.nondetString());
		showColumns(Verifier.nondetString());
		showIndex(Verifier.nondetString());
		showVariables(Verifier.nondetString(), Verifier.nondetInt());
		showDbleProcessListCheck(Verifier.nondetString(), Verifier.nondetInt());
	}
}
