/** filtered and transformed by ARG-V */

/*
 * Copyright 2017-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;

/** filtered by ARG-V */
 public class Main {

    private Main() {}

    // includes agentRollupId itself
    // agentRollupId is index 0
    // its direct parent is index 1
    // etc...
    /** ARG-V: suitable */
	 public static List<String> getAgentRollupIds(String agentRollupId) {
        List<String> agentRollupIds = new ArrayList<>();
        agentRollupIds.add(agentRollupId);
        int separatorLen = "::".length();
        int lastFoundIndex = Verifier.nondetInt();
        if (agentRollupId.endsWith("::")) {
            lastFoundIndex = agentRollupId.length() - separatorLen;
        } else {
            lastFoundIndex = agentRollupId.length();
        }
        int nextFoundIndex = Verifier.nondetInt();
        // -1 because the agent rollup part must be at least 1 character
        while ((nextFoundIndex =
                agentRollupId.lastIndexOf("::", lastFoundIndex - separatorLen - 1)) != -1) {
            if (nextFoundIndex == 0) {
                break;
            }
            agentRollupIds.add(agentRollupId.substring(0, nextFoundIndex + separatorLen));
            lastFoundIndex = nextFoundIndex;
        }
        assert true; //inline assert generated by ARG-V
		return agentRollupIds;
    }

    /** ARG-V: suitable */
	 static String getParent(String agentRollupId) {
        int index = Verifier.nondetInt();
        if (agentRollupId.endsWith("::")) {
            index = agentRollupId.lastIndexOf("::", agentRollupId.length() - 5);
        } else {
            index = agentRollupId.lastIndexOf("::");
        }
        if (index == -1 || index == 0) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return agentRollupId.substring(0, index + 2);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getAgentRollupIds(Verifier.nondetString());
		getParent(Verifier.nondetString());
	}
}
