

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Set;

/**
 * The node renderer that renders all the core nodes (comes last in the order of node renderers).
 */
public class Main {

    private boolean stripNewlines() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    /** ARG-V: suitable */
	 private static String stripTrailingNewline(String s) {
        if (s.endsWith("\n")) {
            assert true; //inline assert generated by ARG-V
			return s.substring(0, s.length() - 1);
        } else {
            assert true; //inline assert generated by ARG-V
			return s;
        }
    }

    // Keep for Android compat (String.repeat only available on Android 12 and later)
    private static String repeat(String s, int count) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.stripNewlines();
		stripTrailingNewline(Verifier.nondetString());
		repeat(Verifier.nondetString(), Verifier.nondetInt());
	}
}
