/** filtered and transformed by ARG-V */

/*
 * Copyright © 2022 jsonwebtoken.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public final class Main {

    private static char FORWARD_SLASH = '/';

    private static String APP_MEDIA_TYPE_PREFIX = "application" + FORWARD_SLASH;

    /** ARG-V: suitable */
	 static String compactIfPossible(String cty) {
        if (Verifier.nondetBoolean()) {
            // per https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.10
            // we can only use the compact form if no other '/' exists in the string
            for (int i = cty.length() - 1; i >= APP_MEDIA_TYPE_PREFIX.length(); i--) {
                char c = cty.charAt(i);
                if (c == FORWARD_SLASH) {
                    assert true; //inline assert generated by ARG-V
					return cty; // found another '/', can't compact, so just return unmodified
                }
            }
            assert true; //inline assert generated by ARG-V
			// no additional '/' found, we can strip the prefix:
            return cty.substring(APP_MEDIA_TYPE_PREFIX.length());
        }
        assert true; //inline assert generated by ARG-V
		return cty; // didn't start with 'application/', so we can't trim it - just return unmodified
    }

    public Object applyTo(String s) {
        assert true; //inline assert generated by ARG-V
		return compactIfPossible(s);
    }

    /** ARG-V: suitable */
	 public String applyFrom(Object o) {
        String s = Verifier.nondetString();

        // https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.10:
        //
        //     A recipient using the media type value MUST treat it as if
        //     "application/" were prepended to any "cty" value not containing a
        //     '/'.
        //
        if (s.indexOf(FORWARD_SLASH) < 0) {
            s = APP_MEDIA_TYPE_PREFIX + s;
        }

        assert true; //inline assert generated by ARG-V
		return s;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		compactIfPossible(Verifier.nondetString());
		instance.applyTo(Verifier.nondetString());
		instance.applyFrom((java.lang.Object) null);
	}
}
