/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * @author mycat
 */
public class Main {
    public Main() {
    }

    /** ARG-V: suitable */
	 public int parse(String stmt, int offset) {
        int i = offset;
        for (; i < stmt.length(); i++) {
            switch (stmt.charAt(i)) {
                case ' ':
                    continue;
                case '/':
                case '#':
                    i = Verifier.nondetInt();
                    continue;
                case 'T':
                case 't':
                    return transactionCheck(stmt, i);
                default:
                    return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    /** ARG-V: suitable */
	 protected int transactionCheck(String stmt, int offset) {
        if (stmt.length() > offset + 10) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
            char c8 = stmt.charAt(++offset);
            char c9 = stmt.charAt(++offset);
            char c10 = stmt.charAt(++offset);
            if ((c1 == 'R' || c1 == 'r') && (c2 == 'A' || c2 == 'a') && (c3 == 'N' || c3 == 'n') &&
                    (c4 == 'S' || c4 == 's') && (c5 == 'A' || c5 == 'a') && (c6 == 'C' || c6 == 'c') &&
                    (c7 == 'T' || c7 == 't') && (c8 == 'I' || c8 == 'i') && (c9 == 'O' || c9 == 'o') &&
                    (c10 == 'N' || c10 == 'n')) {
                if (stmt.length() == ++offset)
                    return Verifier.nondetInt();
                int currentOffset = Verifier.nondetInt();
                if (stmt.length() == currentOffset) {
                    assert true; //inline assert generated by ARG-V
					return Verifier.nondetInt();
                } else {
                    int currentOffset2 = Verifier.nondetInt();
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    /** ARG-V: suitable */
	 protected int transactionReadCheck0(String stmt, int offset) {
        if (stmt.length() >= offset + "read ".length()) {
            char c0 = stmt.charAt(offset);
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            if ((c0 == 'R' || c0 == 'r') && (c1 == 'E' || c1 == 'e') && (c2 == 'A' || c2 == 'a') &&
                    (c3 == 'D' || c3 == 'd')) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.parse(Verifier.nondetString(), Verifier.nondetInt());
		instance.transactionCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.transactionReadCheck0(Verifier.nondetString(), Verifier.nondetInt());
	}
}
