/** filtered and transformed by ARG-V */

/*
 * Copyright 2016-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.List;
import java.util.ListIterator;

/** filtered by ARG-V */
 public class Main {

    private String permission = Verifier.nondetString();
    private int index = Verifier.nondetInt();
    private boolean inAgentRollupId = Verifier.nondetBoolean();
    private boolean inQuotedAgentRollupId = Verifier.nondetBoolean();
    private StringBuilder currAgentRollupId = new StringBuilder();
    private List<String> agentRollupIds = null;

    public Main(String permission) {
    }

    /** ARG-V: suitable */
	 public void parse() {
        if (permission.equals("agent")) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        if (permission.equals("agent:")) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        if (!permission.startsWith("agent:")) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        index = "agent:".length();
        while (index < permission.length()) {
            readNextChar();
            if (!inAgentRollupId && permission.charAt(index - 1) == ':') {
                break;
            }
        }
        if (inAgentRollupId) {
            // add the last value
            agentRollupIds.add(currAgentRollupId.toString());
        }
    }

    public List<String> getAgentRollupIds() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public String getPermission() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 private void readNextChar() {
        char c = permission.charAt(index++);
        if (isStartOfValue(c)) {
            startValue(c);
        } else if (isEndOfValue(c)) {
            endValue();
        } else if (inQuotedAgentRollupId && c == '\\') {
            currAgentRollupId.append(permission.charAt(index++));
        } else if (inAgentRollupId) {
            currAgentRollupId.append(c);
        }
    }

    private boolean isStartOfValue(char c) {
        assert true; //inline assert generated by ARG-V
		return !inAgentRollupId && c != ',' && c != ':';
    }

    /** ARG-V: suitable */
	 private void startValue(char c) {
        inAgentRollupId = true;
        if (c == '"') {
            inQuotedAgentRollupId = true;
        } else {
            currAgentRollupId.append(c);
        }
    }

    private boolean isEndOfValue(char c) {
        assert true; //inline assert generated by ARG-V
		return isEndOfQuotedValue(c) || isEndOfNonQuotedValue(c);
    }

    private void endValue() {
        agentRollupIds.add(currAgentRollupId.toString());
        inAgentRollupId = false;
        inQuotedAgentRollupId = false;
        currAgentRollupId.setLength(0);
    }

    private boolean isEndOfQuotedValue(char c) {
        assert true; //inline assert generated by ARG-V
		return inQuotedAgentRollupId && c == '"';
    }

    private boolean isEndOfNonQuotedValue(char c) {
        assert true; //inline assert generated by ARG-V
		return inAgentRollupId && !inQuotedAgentRollupId && (c == ',' || c == ':');
    }

    public static String quoteIfNeededAndJoin(List<String> agentRollupIds) {
        List<String> quotedIfNeededAgentRollupIds = null;
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static boolean upgradeAgentPermissionsFrom_0_9_1_to_0_9_2(List<String> perms) {
        boolean hasAgentJvmAll = perms.contains("agent:tool");
        boolean upgrade = false;
        ListIterator<String> i = perms.listIterator();
        while (i.hasNext()) {
            String perm = i.next();
            if (perm.equals("agent:view")) {
                i.set("agent:transaction");
                i.add("agent:error");
                if (!hasAgentJvmAll) {
                    // in 0.9.1, agent:view gave access to JVM gauges and environment
                    i.add("agent:jvm:gauges");
                    i.add("agent:jvm:environment");
                }
                upgrade = true;
            } else if (perm.equals("agent:tool")) {
                i.set("agent:jvm");
                upgrade = true;
            } else if (perm.startsWith("agent:tool:")) {
                i.set("agent:jvm:" + perm.substring("agent:tool:".length()));
                upgrade = true;
            }
        }
        if (!upgrade) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        // only apply below updates if upgrading from 0.9.1 to 0.9.2
        int configViewIndex = perms.indexOf("agent:config:view");
        int configEditIndex = perms.indexOf("agent:config:edit");
        if (configViewIndex != -1 && configEditIndex != -1) {
            perms.set(configViewIndex, "agent:config");
            perms.remove(configEditIndex);
        }
        assert true; //inline assert generated by ARG-V
		return true;
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main(Verifier.nondetString());instance.parse();instance.getAgentRollupIds();instance.getPermission();instance.readNextChar();instance.isStartOfValue(Verifier.nondetChar());instance.startValue(Verifier.nondetChar());instance.isEndOfValue(Verifier.nondetChar());instance.endValue();instance.isEndOfQuotedValue(Verifier.nondetChar());instance.isEndOfNonQuotedValue(Verifier.nondetChar());quoteIfNeededAndJoin((java.util.List<java.lang.String>)null);upgradeAgentPermissionsFrom_0_9_1_to_0_9_2((java.util.List<java.lang.String>)null);}
}
