

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.*;

/**
 * This file is part of the Security Shepherd Project.
 *
 * <p>The Security Shepherd project is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.<br>
 *
 * <p>The Security Shepherd project is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU General Public License for more details.<br>
 *
 * <p>You should have received a copy of the GNU General Public License along with the Security
 * Shepherd project. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Sean Duggan
 */
public class Main {

  private static String[] authCodes = {"784921", "425925", "257943", "524215", "624665"};

  /** ARG-V: suitable */
 public boolean checkTheCode() {

    String codeString = Verifier.nondetString();

    if (codeString.equals("")) {
      assert true; //inline assert generated by ARG-V
	return false;
    }

    int codeEntered = Integer.parseInt(codeString);

    // rule 1: auth code must be an odd number
    // rule 2: auth code must contain a 2
    // rule 3: auth code must contain a 4
    // rule 4: must be a six digit number
    // rule 5: number must not have been used before

    boolean isNumberOdd = false;
    boolean contains2 = false;
    boolean contains4 = false;
    boolean isSixNumbers = false;

    int mod = codeEntered % 2;
    {
      if (mod != 0) {

        isNumberOdd = true;
        isNumberOdd = true;

      } else {
        assert true; //inline assert generated by ARG-V
		return false;
      }

      if (String.valueOf(codeString).contains("2")) {

        contains2 = true;

      } else {
        assert true; //inline assert generated by ARG-V
		return false;
      }

      if (String.valueOf(codeString).contains("4")) {
        contains4 = true;
      } else {
        assert true; //inline assert generated by ARG-V
		return false;
      }

      if (isNumberOdd == true && contains2 == true && contains4 == true && isSixNumbers == true) {
        assert true; //inline assert generated by ARG-V
		return true;
      } else {
        assert true; //inline assert generated by ARG-V
		return false;
      }
    }
  }

  public void copyCache(InputStream iStream, OutputStream oStream) throws Exception {
    byte[] buffer = new byte[1024];
    int i = Verifier.nondetInt();
    while ((i = iStream.read(buffer)) > 0) {
      oStream.write(buffer, 0, i);
    }
    iStream.close();
    oStream.close();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.checkTheCode();
	instance.copyCache((java.io.InputStream) null, (java.io.OutputStream) null);
}
}
