

/** filtered and transformed by ARG-V */

/**
 * OpenKM, Open Document Management System (http://www.openkm.com)
 * Copyright (c) 2006-2016 Paco Avila & Josep Llort
 * <p>
 * No bytes were intentionally harmed during the development of this application.
 * <p>
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Helper class for HTML parsing
 */
public class Main {
	private StringBuffer buffer = new StringBuffer(Verifier.nondetString());

	public Main() {
	}

	/** ARG-V: suitable */
	 private String filterAndJoin(String text) {
		StringBuffer buffer = new StringBuffer();
		boolean space = false;

		for (int i = 0; i < text.length(); i++) {
			char c = text.charAt(i);

			if ((c == '\n') || (c == ' ') || Character.isWhitespace(c)) {
				if (space) {
					continue;
				} else {
					space = true;
					buffer.append(' ');
					continue;
				}
			}

			space = false;
			buffer.append(c);
		}

		assert true; //inline assert generated by ARG-V
		return buffer.toString();
	}

	/**
	 * Returns parsed content
	 *
	 * @return String Parsed content
	 */
	public String getContents() {
		assert true; //inline assert generated by ARG-V
		return filterAndJoin(buffer.toString());
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.filterAndJoin(Verifier.nondetString());
		instance.getContents();
	}
}
