/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.regex.Pattern;

/**
 * @author mycat
 */
public final class Main {
    private Main() {
    }

    public static int OTHER = -1;
    public static int LOCK_READ = 2;
    public static int SELECT_VAR_ALL = 9;


    private static Pattern LOCK_READ_PATTERN = Pattern.compile("^.*((\\s+for\\s+update)|(\\s+for\\s+share)|(\\s+lock\\s+in\\s+share\\s+mode))\\s*$", Pattern.CASE_INSENSITIVE);


    /** ARG-V: suitable */
	 public static int parse(String stmt, int offset) {
        int i = offset;
        for (; i < stmt.length(); ++i) {
            switch (stmt.charAt(i)) {
                case ' ':
                    continue;
                case '/':
                case '#':
                    i = Verifier.nondetInt();
                    continue;
                case '@':
                    return select2Check(stmt, i);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }


    public static int parseSpecial(String stmt) {

        if (LOCK_READ_PATTERN.matcher(stmt).matches()) {
            assert true; //inline assert generated by ARG-V
			return LOCK_READ;
        }

        assert true; //inline assert generated by ARG-V
		return OTHER;
    }


    /**
     * SELECT @@session.auto_increment_increment
     *
     * @param stmt
     * @param offset
     * @return
     */
    /** ARG-V: suitable */
	 private static int sessionVarCheck(String stmt, int offset) {
        String s = stmt.substring(offset).toLowerCase();
        if (!s.startsWith("session.")) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        s = s.substring(8);
        if (s.startsWith("auto_increment_increment")) {
            if (s.contains("@@")) {
                assert true; //inline assert generated by ARG-V
				return SELECT_VAR_ALL;
            }

        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }


    static int select2Check(String stmt, int offset) {
        if (stmt.length() > ++offset && stmt.charAt(offset) == '@' && stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {

                case 's':
                case 'S':
                    return sessionVarCheck(stmt, offset);

                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }


	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		parse(Verifier.nondetString(), Verifier.nondetInt());
		parseSpecial(Verifier.nondetString());
		sessionVarCheck(Verifier.nondetString(), Verifier.nondetInt());
		select2Check(Verifier.nondetString(), Verifier.nondetInt());
	}

}
