

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashMap;
import java.util.Map;

/**
 * @author jllort
 */
public class Main {
	private String hash = Verifier.nondetString();
	private String host = Verifier.nondetString();
	private String hostName = Verifier.nondetString();
	private String href = Verifier.nondetString();
	private String path = Verifier.nondetString();
	private String port = Verifier.nondetString();
	private String protocol = Verifier.nondetString();
	private String queryString = Verifier.nondetString();

	private HashMap<String, String> paramMap = null;

	public String getHash() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public String getHost() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public String getHostName() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public String getHref() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public String getPath() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	/** ARG-V: suitable */
	 public String getContext() {
		if (path.equals("/frontend/index.html")) {
			assert true; //inline assert generated by ARG-V
			return "";
		} else {
			String context = path.substring(path.indexOf("/") + 1);
			context = context.substring(0, context.indexOf("/"));
			assert true; //inline assert generated by ARG-V
			return "/" + context;
		}
	}

	public String getPort() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public String getProtocol() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public String getQueryString() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	/** ARG-V: suitable */
	 protected void setQueryString(String queryString) {
		if (queryString != Verifier.nondetString() && queryString.length() > 1) {
			String qs = queryString.substring(1);
			String[] kvPairs = qs.split("&");
		}
	}

	public String getParameter(String name) {
		assert true; //inline assert generated by ARG-V
		return paramMap.get(name);
	}

	public Map<String, String> getParameterMap() {
		assert true; //inline assert generated by ARG-V
		return null;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getHash();
		instance.getHost();
		instance.getHostName();
		instance.getHref();
		instance.getPath();
		instance.getContext();
		instance.getPort();
		instance.getProtocol();
		instance.getQueryString();
		instance.setQueryString(Verifier.nondetString());
		instance.getParameter(Verifier.nondetString());
		instance.getParameterMap();
	}
}
