

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.FileDescriptor;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.Map;

public class Main {
    private static int TIMEOUT_USEC = 0000;

    private int trackIndex = Verifier.nondetInt();

    private long startTimeUs = Verifier.nondetLong();
    private long endTimeUs = Verifier.nondetLong();
    private boolean loopingEnabled = Verifier.nondetBoolean();

    private boolean allInputExtracted = Verifier.nondetBoolean();
    private boolean decodingDone = Verifier.nondetBoolean();
    private int audioIndex = -1;

    public Main(String sourcePath) throws Exception {
        init();
    }

    public Main(String sourcePath, int audioIndex) throws Exception {
        init();
    }

    private void init() throws Exception {
        selectTrack();

        startTimeUs = 0;
        try {
            endTimeUs = Verifier.nondetLong();
        } catch (Exception e) {
            endTimeUs = -1;
        }
    }

    private void selectTrack() {
        trackIndex = audioIndex;
        if (trackIndex == -1) {
            int numTracks = Verifier.nondetInt();
            for (int i = 0; i < numTracks; i++) {
                String mime = Verifier.nondetString();
                if (mime != Verifier.nondetString() && mime.startsWith("audio/")) {
                    trackIndex = i;
                    break;
                }
            }
        }
        if (trackIndex < 0) {
            throw new RuntimeException("No audio track found in source");
        }
    }

    public long getDurationUs() {
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetLong();
        } catch (Exception e) {
        }
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetLong();
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    public int getSampleRate() {
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } catch (Exception e) {
        }
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    public int getBitrateRate() {
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } catch (Exception e) {}
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } catch (Exception e) {}
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    public int getChannelCount() {
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } catch (Exception e) {
        }
        try {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    public long getStartTimeUs() {
        assert true; //inline assert generated by ARG-V
		return startTimeUs;
    }

    public long getEndTimeUs() {
        assert true; //inline assert generated by ARG-V
		return endTimeUs;
    }

    public boolean isLoopingEnabled() {
        assert true; //inline assert generated by ARG-V
		return loopingEnabled;
    }

    public boolean isDecodingDone() {
        assert true; //inline assert generated by ARG-V
		return decodingDone;
    }

    public void setStartTimeUs(long startTimeUs) {
        long durationUs = getDurationUs();
    }

    public void setEndTimeUs(long endTimeUs) {
        long durationUs = getDurationUs();
    }

    /** ARG-V: suitable */
	 public void start() {
        if (startTimeUs > endTimeUs) {
            throw new RuntimeException("StartTimeUs(" + startTimeUs + ") must be less than or equal to EndTimeUs(" + endTimeUs + ")");
        }

        allInputExtracted = false;
        decodingDone = false;
    }

    public void stop() {
        decodingDone = true;
    }

    public void release() {
        stop();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString(), Verifier.nondetInt());
		instance.init();
		instance.selectTrack();
		instance.getDurationUs();
		instance.getSampleRate();
		instance.getBitrateRate();
		instance.getChannelCount();
		instance.getStartTimeUs();
		instance.getEndTimeUs();
		instance.isLoopingEnabled();
		instance.isDecodingDone();
		instance.setStartTimeUs(Verifier.nondetLong());
		instance.setEndTimeUs(Verifier.nondetLong());
		instance.start();
		instance.stop();
		instance.release();
	}
}
