/** filtered and transformed by ARG-V */

/*
 * Copyright 2017-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

class Main {

    // includes agentId itself
    // agentId is index 0
    // its direct parent is index 1
    // etc...
    /** ARG-V: suitable */
	 static List<String> getAgentRollupIdsV09(String agentId) {
        List<String> agentRollupIds = new ArrayList<>();
        int nextFoundIndex = agentId.lastIndexOf("::", agentId.length() - 3);
        if (nextFoundIndex == -1) {
            agentRollupIds.add(agentId);
        } else {
            agentRollupIds.add(agentId.substring(agentId.lastIndexOf("::", agentId.length()) + 2));
            while (nextFoundIndex != -1) {
                agentRollupIds.add(agentId.substring(0, nextFoundIndex).replace("::", "/"));
                nextFoundIndex = agentId.lastIndexOf("::", nextFoundIndex - 1);
            }
        }
        assert true; //inline assert generated by ARG-V
		return agentRollupIds;
    }

    /** ARG-V: suitable */
	 static String getParentV09(String agentRollupId) {
        int index = agentRollupId.lastIndexOf("::", agentRollupId.length() - 3);
        if (index == -1) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } else {
            assert true; //inline assert generated by ARG-V
			return agentRollupId.substring(0, index).replace("::", "/");
        }
    }

    /** ARG-V: suitable */
	 static String convertToV09(String agentRollupId) {
        if (agentRollupId.endsWith("::")) {
            assert true; //inline assert generated by ARG-V
			return agentRollupId.substring(0, agentRollupId.length() - 2).replace("::", "/");
        }
        int index = agentRollupId.lastIndexOf("::");
        if (index == -1) {
            assert true; //inline assert generated by ARG-V
			return agentRollupId;
        } else {
            assert true; //inline assert generated by ARG-V
			return agentRollupId.substring(index + 2);
        }
    }

    static boolean isLeaf(String agentRollupId) {
        assert true; //inline assert generated by ARG-V
		return !agentRollupId.endsWith("::");
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getAgentRollupIdsV09(Verifier.nondetString());
		getParentV09(Verifier.nondetString());
		convertToV09(Verifier.nondetString());
		isLeaf(Verifier.nondetString());
	}
}
