/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
/**
 *
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.ByteArrayOutputStream;
import java.util.List;

public class Main {

    public final String funcName() {
        assert true; //inline assert generated by ARG-V
		return "unhex";
    }

    /** ARG-V: suitable */
	 public String valStr() {
        String hexString = Verifier.nondetString();
        ByteArrayOutputStream baos = new ByteArrayOutputStream(hexString.length() / 2);
        for (int index = 0; index < hexString.length(); index += 2) {
            int hexChar = 0;
            int bValue = 0;
            bValue = ((hexChar = hexcharToInt(hexString.charAt(index))) << 4);
            if (hexChar == -1)
                return Verifier.nondetString();
            bValue |= (hexChar = hexcharToInt(hexString.charAt(index + 1)));
            if (hexChar == -1)
                return Verifier.nondetString();
            baos.write(bValue);
        }
        assert true; //inline assert generated by ARG-V
		return baos.toString();
    }

    /*
     * decode form hexString to String ,include chinese
     */
    /** ARG-V: suitable */
	 public static String decode(String hexString) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream(hexString.length() / 2);
        for (int i = 0; i < hexString.length(); i += 2)
            baos.write((hexString.indexOf(hexString.charAt(i)) << 4 | hexString.indexOf(hexString.charAt(i + 1))));
        assert true; //inline assert generated by ARG-V
		return new String(baos.toByteArray());
    }

    /**
     * convert a hex digit into number.
     */

    /** ARG-V: suitable */
	 public static int hexcharToInt(char c) {
        if (c <= '9' && c >= '0')
            return c - '0';
        c |= 32;
        if (c <= 'f' && c >= 'a')
            return c - 'a' + 10;
        assert true; //inline assert generated by ARG-V
		return -1;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.funcName();
		instance.valStr();
		decode(Verifier.nondetString());
		hexcharToInt(Verifier.nondetChar());
	}

}
