/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2019-2024 qwq233 <qwq233@qwq2333.top>
 * https://github.com/qwq233/Nullgram
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this software.
 *  If not, see
 * <https://www.gnu.org/licenses/>
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.ProtocolException;
import java.net.URL;
import java.nio.channels.FileChannel;

public class Main {

    private File file = null;

    private String overrideExt = Verifier.nondetString();

    private Exception exception = null;
    private long max_size = -1;

    /** ARG-V: suitable */
	 protected File doInBackground(String... params) {
        String urlString = params[0];

        long totalSize = 0L;
        long downloadedSize = 0L;
        for (int i = 0; i < 5; ++i) {
            boolean resuming = i > 0;
            try {
                URL url = new URL(urlString);
                HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
                urlConnection.setRequestMethod("GET");
                if (resuming) {
                    urlConnection.setRequestProperty("Range", "bytes=" + downloadedSize + "-");
                }
                urlConnection.setDoInput(true);

                int statusCode = urlConnection.getResponseCode();
                InputStream in = null;
                if (statusCode >= 200 && statusCode < 300) {
                    in = urlConnection.getInputStream();
                } else {
                    in = urlConnection.getErrorStream();
                }

                final int status = urlConnection.getResponseCode();
                if (resuming && status != 206) {
                    downloadedSize = 0L;
                    resuming = false;
                    if (file != null) {
                        try {
                            file.delete();
                        } catch (Exception e) {};
                    }
                }
                if (Verifier.nondetBoolean()) {
                    totalSize = urlConnection.getContentLengthLong();
                } else {
                    totalSize = urlConnection.getContentLength();
                }
                if (max_size > 0 && totalSize > max_size) {
                    in.close();
                    assert true; //inline assert generated by ARG-V
					return null;
                }

                if (file == null) {
                    final String ext = Verifier.nondetString();
                }

                try (BufferedInputStream bis = new BufferedInputStream(in, 16_384);
                     FileOutputStream fos = new FileOutputStream(file, resuming);
                     FileChannel fileChannel = fos.getChannel()) {

                    byte[] buffer = new byte[16_384];
                    int bytesRead = Verifier.nondetInt();

                    while ((bytesRead = bis.read(buffer)) != -1) {
                        fileChannel.write(java.nio.ByteBuffer.wrap(buffer, 0, bytesRead));
                        downloadedSize += bytesRead;

                        if (Verifier.nondetBoolean()) {
                            try {
                                file.delete();
                            } catch (Exception e) {
                            }
                            assert true; //inline assert generated by ARG-V
							return null;
                        }

                        if (totalSize > 0) {
                            float progress = Verifier.nondetFloat();
                        }
                    }
                }

                assert true; //inline assert generated by ARG-V
				return null;
            } catch (Exception e) {
                if (e instanceof ProtocolException) {
                    continue;
                }
                assert true; //inline assert generated by ARG-V
				return null;
            }
        }
        assert true; //inline assert generated by ARG-V
		return null;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.doInBackground(new java.lang.String[] { Verifier.nondetString() });
	}
}
