# To execute a job locally, install gitlab-runner (https://docs.gitlab.com/runner/install/)
# and run the following command:
# gitlab-runner exec docker --docker-privileged --docker-volumes /sys/fs/cgroup:/sys/fs/cgroup:rw <<JOB_NAME>>

image: registry.gitlab.com/sosy-lab/benchmarking/competition-scripts/python:latest

include:
  # Run CI for default branch, tags, and merge requests (not for other branches)
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

# Do not checkout any submodules for now; sv-benchmarks and archives-20xx are just too big.
# Set depth to 10, such that new commits in one of the submodules makes do not break the CI immediately.
variables:
  GIT_SUBMODULE_STRATEGY: none
  GIT_STRATEGY: fetch
  GIT_DEPTH: 50
  REQUIRED_SUBMODULES: "scripts benchexec sv-benchmarks"

before_script:
  - git submodule sync
  - git submodule update --depth 50 --init $REQUIRED_SUBMODULES

check-definitions:
  script:
    - ./scripts/test/check-benchdef.py benchmark-defs/*xml

check-category-structure:
  script:
    - ./scripts/test/check-categories.py --tasks-directory sv-benchmarks --category-structure benchmark-defs/category-structure.yml

check-installed-required-packages:
  # This large image is not actually necessary, but it is currently the easiest way
  # to get an image with the correct Ubuntu version and some required utilities.
  image: registry.gitlab.com/sosy-lab/benchmarking/competition-scripts/user:latest
  # no submodules required
  before_script:
    - pip install yq
  script:
    - echo "Checking if all required packages are valid and available for the Ubuntu version used for the competition ..."
    - apt-get update
    - apt-get install -y chronic
    - yq -r '[ (.verifiers + .validators)[]."required-ubuntu-packages"[] ] | unique [] ' benchmark-defs/category-structure.yml | xargs -n 1 chronic apt-cache show -q=0
    - echo "Checking if all required packages are installed in the competition installation ..."
    # The first check prints missing required packages, then second check makes the CI fail
    - yq -r '[ (.verifiers + .validators)[]."required-ubuntu-packages"[] ] | unique [] ' benchmark-defs/category-structure.yml | xargs -n 1 dpkg --get-selections 2>&1 >/dev/null
    - yq -r '[ (.verifiers + .validators)[]."required-ubuntu-packages"[] ] | unique [] ' benchmark-defs/category-structure.yml | while read PKG; do dpkg --get-selections $PKG | grep install || exit 1; done

