/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.sql.SQLSyntaxErrorException;

/**
 * @author collapsar
 */
public final class Main {

    public static int OTHER = -1;

    public static int SQL = 1;
    public static int SHARDING_NODE = 2;
    public static int DB_TYPE = 3;
    public static int DB_INSTANCE_URL = 4;
    public static int PLAN = 5;

    public static int UPROXY_DEST = 11;
    public static int UPROXY_MASTER = 12;

    private Main() {
    }

    /** ARG-V: suitable */
	 private static int dbleHint(String sql, int offset) throws Exception {
        if (sql.length() > ++offset) {
            switch (sql.charAt(offset)) {
                case 'S':
                case 's':
                    return sCheck(sql, offset);
                case 'D':
                case 'd':
                    return dCheck(sql, offset);
                case 'P':
                case 'p':
                    return planCheck(sql, offset);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int sCheck(String stmt, int offset) throws Exception {
        if (stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'H':
                case 'h':
                    return shardingNodeCheck(stmt, offset);
                case 'q':
                case 'Q':
                    return sqlCheck(stmt, offset);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int dCheck(String stmt, int offset) throws Exception {
        if (stmt.length() > offset + 3) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            if ((c1 == 'B' || c1 == 'b') && c2 == '_') {
                switch (c3) {
                    case 'T':
                    case 't':
                        return dbTypeCheck(stmt, offset);
                    case 'I':
                    case 'i':
                        return dbInstanceUrlCheck(stmt, offset);
                    default:
                        return OTHER;
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int shardingNodeCheck(String stmt, int offset) throws Exception {
        if (stmt.length() > offset + 10) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
            char c8 = stmt.charAt(++offset);
            char c9 = stmt.charAt(++offset);
            char c10 = stmt.charAt(++offset);
            if ((c1 == 'A' || c1 == 'a') && (c2 == 'R' || c2 == 'r') &&
                    (c3 == 'D' || c3 == 'd') && (c4 == 'I' || c4 == 'i') &&
                    (c5 == 'N' || c5 == 'n') && (c6 == 'G' || c6 == 'g') &&
                    (c7 == 'N' || c7 == 'n') && (c8 == 'O' || c8 == 'o') &&
                    (c9 == 'D' || c9 == 'd') && (c10 == 'E' || c10 == 'e')) {
                offset = Verifier.nondetInt();
                if (offset == -1) {
                    throw new Exception();
                } else {
                    assert true; //inline assert generated by ARG-V
					return (offset << 8) | SHARDING_NODE;
                }
            }
        }
        throw new Exception();
    }

    /** ARG-V: suitable */
	 private static int sqlCheck(String stmt, int offset) throws Exception {
        if (stmt.length() > offset + 1) {
            char c1 = stmt.charAt(++offset);
            if (c1 == 'L' || c1 == 'l') {
                offset = Verifier.nondetInt();
                if (offset == -1) {
                    throw new Exception();
                } else {
                    assert true; //inline assert generated by ARG-V
					return (offset << 8) | SQL;
                }
            }
        }
        throw new Exception();
    }

    /** ARG-V: suitable */
	 private static int dbTypeCheck(String stmt, int offset) throws Exception {
        if (stmt.length() > offset + 3) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            if ((c1 == 'Y' || c1 == 'y') && (c2 == 'P' || c2 == 'p') &&
                    (c3 == 'E' || c3 == 'e')) {
                offset = Verifier.nondetInt();
                if (offset == -1) {
                    throw new Exception();
                } else {
                    assert true; //inline assert generated by ARG-V
					return (offset << 8) | DB_TYPE;
                }
            }
        }
        throw new Exception();
    }

    /** ARG-V: suitable */
	 private static int dbInstanceUrlCheck(String stmt, int offset) throws Exception {
        if (stmt.length() > offset + 11) {
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
            char c8 = stmt.charAt(++offset);
            char c9 = stmt.charAt(++offset);
            char c10 = stmt.charAt(++offset);
            char c11 = stmt.charAt(++offset);
            char c12 = stmt.charAt(++offset);
            if ((c2 == 'N' || c2 == 'n') && (c3 == 'S' || c3 == 's') &&
                    (c4 == 'T' || c4 == 't') && (c5 == 'A' || c5 == 'a') &&
                    (c6 == 'N' || c6 == 'n') && (c7 == 'C' || c7 == 'c') &&
                    (c8 == 'E' || c8 == 'e') && (c9 == '_') &&
                    (c10 == 'U' || c10 == 'u') && (c11 == 'R' || c11 == 'r') &&
                    (c12 == 'L' || c12 == 'l')) {
                offset = Verifier.nondetInt();
                if (offset == -1) {
                    throw new Exception();
                } else {
                    assert true; //inline assert generated by ARG-V
					return (offset << 8) | DB_INSTANCE_URL;
                }
            }
        }
        throw new Exception();
    }

    /** ARG-V: suitable */
	 private static int planCheck(String stmt, int offset) throws Exception {
        if (stmt.length() > offset + 3) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            if ((c1 == 'l' || c1 == 'L') && (c2 == 'A' || c2 == 'a') &&
                    (c3 == 'N' || c3 == 'n')) {
                offset = Verifier.nondetInt();
                if (offset == -1) {
                    throw new Exception();
                } else {
                    assert true; //inline assert generated by ARG-V
					return (offset << 8) | PLAN;
                }
            }
        }
        throw new Exception();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		dbleHint(Verifier.nondetString(), Verifier.nondetInt());
		sCheck(Verifier.nondetString(), Verifier.nondetInt());
		dCheck(Verifier.nondetString(), Verifier.nondetInt());
		shardingNodeCheck(Verifier.nondetString(), Verifier.nondetInt());
		sqlCheck(Verifier.nondetString(), Verifier.nondetInt());
		dbTypeCheck(Verifier.nondetString(), Verifier.nondetInt());
		dbInstanceUrlCheck(Verifier.nondetString(), Verifier.nondetInt());
		planCheck(Verifier.nondetString(), Verifier.nondetInt());
	}

}
