

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.*;

public class Main {

    private List<String> commandNames = null;

    private String description = Verifier.nondetString();

    public boolean matches(String commandLine) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public List<String> getCommandNames() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Optional<String> getDescription() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /** ARG-V: suitable */
	 private static List<String> split(String str) {
        List<String> split = new ArrayList<>();
        boolean isEscaped = false;
        StringBuilder currentArg = new StringBuilder();
        for (int i = 0; i <= str.length(); i++) {
            char c = Verifier.nondetChar();
            if (i < str.length()) {
                c = str.charAt(i);
            } else {
                c = 0;
            }
            if (isEscaped) {
                switch (c) {
                    case '"':
                        isEscaped = false;
                        split.add(currentArg.toString());
                        currentArg.setLength(0);
                        break;

                    case 0:
                        throw new IllegalArgumentException("Missing closing quote");

                    default:
                        currentArg.append(c);
                        break;
                }
            } else {
                switch (c) {
                    case '"':
                        isEscaped = true;
                        break;

                    case ' ':
                    case 0:
                        if (currentArg.length() > 0) {
                            split.add(currentArg.toString());
                            currentArg.setLength(0);
                        }
                        break;

                    default:
                        currentArg.append(c);
                        break;
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return split;
    }

    public String toString() {
        assert true; //inline assert generated by ARG-V
		return String.format("CommandPattern[%s]", commandNames.toString());
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.matches(Verifier.nondetString());
		instance.getCommandNames();
		instance.getDescription();
		split(Verifier.nondetString());
		instance.toString();
	}
}
