

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

class Main<T> {

  private static String DISTINCT = "distinct";

  private static String NULLS = "nulls";

  private static String ASC = "asc";

  Object namedParam(String parameterName) {
    assert true; //inline assert generated by ARG-V
	return null;
  }

  Object positionParam(String paramPosition) {
    assert true; //inline assert generated by ARG-V
	return null;
  }

  /**
   * Trim leading '(' and trailing ')'
   */
  /** ARG-V: suitable */
 private String trimParenthesis(String text) {
    if (text.charAt(0) == '(') {
      assert true; //inline assert generated by ARG-V
	return text.substring(1, text.length() - 1);
    }
    assert true; //inline assert generated by ARG-V
	return text;
  }

  /** ARG-V: suitable */
 private String trimQuotes(String path) {
    if (path.charAt(0) == '\'' || path.charAt(0) == '`') {
      assert true; //inline assert generated by ARG-V
	return path.substring(1, path.length() - 1);
    }
    assert true; //inline assert generated by ARG-V
	return path;
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.namedParam(Verifier.nondetString());
	instance.positionParam(Verifier.nondetString());
	instance.trimParenthesis(Verifier.nondetString());
	instance.trimQuotes(Verifier.nondetString());
}

}
