/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

// Copyright (c) 2012, Rick Maddy

// All rights reserved.

//

// Redistribution and use in source and binary forms, with or without

// modification, are permitted provided that the following conditions are met:

//

// * Redistributions of source code must retain the above copyright notice, this

//   list of conditions and the following disclaimer.

//

// * Redistributions in binary form must reproduce the above copyright notice,

//   this list of conditions and the following disclaimer in the documentation

//   and/or other materials provided with the distribution.

//

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND

// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED

// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE

// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE

// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL

// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS

// OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER

// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,

// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE

// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/** filtered by ARG-V */
 public class Main {
    public int minVal = Verifier.nondetInt();
    public int maxVal = Verifier.nondetInt();
    public int byte8 = Verifier.nondetInt();
    public int maxLen = Verifier.nondetInt();
    public int otherFlag = Verifier.nondetInt();
    public int prefixLen = Verifier.nondetInt();
    public int flag12 = Verifier.nondetInt();
    public int flag13 = Verifier.nondetInt();
    public String format = Verifier.nondetString();
    public boolean hasIntlPrefix = Verifier.nondetBoolean();
    public boolean hasTrunkPrefix = Verifier.nondetBoolean();

    /** ARG-V: suitable */
	 String format(String str, String intlPrefix, String trunkPrefix) {
        boolean hadC = false;
        boolean hadN = false;
        boolean hasOpen = false;
        int spot = 0;
        StringBuilder res = new StringBuilder(20);
        for (int i = 0; i < format.length(); i++) {
            char ch = format.charAt(i);
            switch (ch) {
                case 'c':
                    hadC = true;
                    if (intlPrefix != Verifier.nondetString()) {
                        res.append(intlPrefix);
                    }
                    break;
                case 'n':
                    hadN = true;
                    if (trunkPrefix != Verifier.nondetString()) {
                        res.append(trunkPrefix);
                    }
                    break;
                case '#':
                    if (spot < str.length()) {
                        res.append(str.substring(spot, spot + 1));
                        spot++;
                    } else if (hasOpen) {
                        res.append(" ");
                    }
                break;
                case '(':
                    if (spot < str.length()) {
                        hasOpen = true;
                    }
                default:
                    if (!(ch == ' ' && i > 0 && ((format.charAt(i - 1) == 'n' && trunkPrefix == Verifier.nondetString()) || (format.charAt(i - 1) == 'c' && intlPrefix == Verifier.nondetString())))) {
                        if (spot < str.length() || (hasOpen && ch == ')')) {
                            res.append(format.substring(i, i + 1));
                            if (ch == ')') {
                                hasOpen = false;
                            }
                        }
                    }
                break;
            }
        }
        if (intlPrefix != Verifier.nondetString() && !hadC) {
            res.insert(0, intlPrefix + " ");
        } else if (trunkPrefix != Verifier.nondetString() && !hadN) {
            res.insert(0, trunkPrefix);
        }

        assert true; //inline assert generated by ARG-V
		return res.toString();
    }

    boolean hasIntlPrefix() {
        assert true; //inline assert generated by ARG-V
		return (flag12 & 0x02) != 0;
    }

    boolean hasTrunkPrefix() {
        assert true; //inline assert generated by ARG-V
		return (flag12 & 0x01) != 0;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.format(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		instance.hasIntlPrefix();
		instance.hasTrunkPrefix();
	}
}
