/** filtered and transformed by ARG-V */

/*
 * Copyright 2019 WeBank
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    static String INDEX_FILE_PREFIX = "index_";
    static String INDEX_FILE_SUFFIX = ".index";

    static String REQUEST_URI = "reqUri";

    /** ARG-V: suitable */
	 public static String getHomepageUrl(String baseUrl, String homepageUri,
                                        Long workspaceId, String workspaceName) {
        if(Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return baseUrl;
        }
        if(workspaceId != null && homepageUri.contains("${workspaceId}")) {
            homepageUri = homepageUri.replace("${workspaceId}", workspaceId.toString());
        }
        if(baseUrl.endsWith("/")) {
            assert true; //inline assert generated by ARG-V
			return baseUrl + homepageUri;
        } else {
            assert true; //inline assert generated by ARG-V
			return baseUrl + "/" + homepageUri;
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getHomepageUrl(Verifier.nondetString(), Verifier.nondetString(), (java.lang.Long) null,
				Verifier.nondetString());
	}

}
