/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class Main {
    private volatile boolean connectionDetached = false;

    /**
     * only first init Lazy load
     *
     * @throws Exception
     */
    public void initCluster() throws Exception {
        try {
        } catch (Exception e) {
            throw e;
        }
    }

    /** ARG-V: suitable */
	 public void cleanPath(String path) {
        try {
            if (path.endsWith(Verifier.nondetString())) {
                path = path.substring(0, path.length() - 1);
            }
        } catch (Exception e) {
        }
    }

    public void cleanKV(String path) {
        try {
        } catch (Exception e) {
            throw new RuntimeException("cleanKV failure for" + path);
        }
    }

    public boolean isDetach() {
        assert true; //inline assert generated by ARG-V
		return connectionDetached;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.initCluster();
		instance.cleanPath(Verifier.nondetString());
		instance.cleanKV(Verifier.nondetString());
		instance.isDetach();
	}
}
