/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Created by szf on 2017/10/9.
 */
public class Main {

    public static int TYPE_CREATE_VIEW = 1;
    public static int TYPE_REPLACE_VIEW = 2;
    public static int TYPE_ALTER_VIEW = 3;

    private int offset = -1;
    private String originalSql = Verifier.nondetString();
    private int type = TYPE_CREATE_VIEW;

    public Main(String originalSql) {
    }

    public String getViewName() {
        //parse the sql
        while (true) {
            switch (originalSql.charAt(++offset)) {
                case ' ':
                case '\t':
                case '\r':
                case '\n':
                    continue;
                case '/':
                    offset = Verifier.nondetInt();
                    break;
                case 'a':
                    offset = offset + 5;
                    type = TYPE_ALTER_VIEW;
                    return parseCreateOrReplace();
                default:
                    //skip the create because in ServerParse is already know
                    offset = offset + 6;
                    return parseCreateOrReplace();
            }
        }
    }

    /** ARG-V: suitable */
	 public String parseCreateOrReplace() {

        while (true) {
            char next = originalSql.charAt(++offset);
            if (next != ' ' && next != '\t' && next != '\r' && next != '\n') {
                if (next == 'o' || next == 'O') {
                    offset += 2;
                    while (true) {
                        next = originalSql.charAt(++offset);
                        if (next == 'r' || next == 'R') {
                            offset += 7;
                            assert true; //inline assert generated by ARG-V
							return parseCreateOrReplace();
                        }
                    }
                } else if (next == 'v' || next == 'V') {
                    //skip the word view because in ServerParse is already know
                    offset += 4;
                    int viewNameStat = 0;
                    while (true) {
                        next = originalSql.charAt(++offset);
                        if (next != ' ' && next != '\t' &&
                                next != '\r' &&
                                next != '\n' &&
                                viewNameStat == 0) {
                            viewNameStat = offset;
                        } else if ((next == ' ' || next == '\t' ||
                                next == '\r' ||
                                next == '\n' ||
                                next == '(') && viewNameStat != 0) {
                            assert true; //inline assert generated by ARG-V
							return originalSql.substring(viewNameStat, offset);
                        }
                    }
                } else {
                    assert true; //inline assert generated by ARG-V
					return "";
                }
            }
        }
    }


    /** ARG-V: suitable */
	 public String parseSelectSQL() {
        while (true) {
            char next = originalSql.charAt(offset++);
            if ((next == 'a' || next == 'A') &&
                    (originalSql.charAt(offset) == 's' ||
                            originalSql.charAt(offset) == 'S')) {
                offset++;
                break;
            } else if (offset == originalSql.length() - 1) {
                throw new RuntimeException("You have an error in your SQL syntax;");
            }
        }
        assert true; //inline assert generated by ARG-V
		return originalSql.substring(offset);
    }


    /** ARG-V: suitable */
	 public List<String> getViewColumn() {
        int start = 0;
        String columnList = "";
        while (true) {
            char next = originalSql.charAt(offset++);
            if (next != ' ' && next != '\t' && next != '\n' && next != '\r' && next != '(' && start == 0) {
                offset--;
                assert true; //inline assert generated by ARG-V
				return null;
            } else if (next == '(' && start == 0) {
                start = offset;
            } else if (next == ')') {
                columnList = originalSql.substring(start, offset - 1);
                break;
            }
        }
        assert true; //inline assert generated by ARG-V
		return new ArrayList<>(Arrays.asList(columnList.split(",")));
    }


    public int getType() {
        assert true; //inline assert generated by ARG-V
		return type;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString());
		instance.getViewName();
		instance.parseCreateOrReplace();
		instance.parseSelectSQL();
		instance.getViewColumn();
		instance.getType();
	}
}
