/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2019-2024 qwq233 <qwq233@qwq2333.top>
 * https://github.com/qwq233/Nullgram
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this software.
 *  If not, see
 * <https://www.gnu.org/licenses/>
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    private int currentAccount = Verifier.nondetInt();
    public int maxWidth = Verifier.nondetInt();
    private boolean relayout = true;
    private boolean animated = Verifier.nondetBoolean();

    public float density = Verifier.nondetFloat();
    public int padx = Verifier.nondetInt(), pady = Verifier.nondetInt();

    private float textScale = 1;
    private float layoutWidth = Verifier.nondetFloat(), layoutLeft = Verifier.nondetFloat();

    private float iconPadding = 3.25f;
    private float flagIconPadding = 2.25f;
    private float iconSize = 30f;

    private boolean messageAbove = Verifier.nondetBoolean();
    private boolean hasTitle = Verifier.nondetBoolean();
    private boolean hasSiteName = Verifier.nondetBoolean();
    private boolean hasDescription = Verifier.nondetBoolean();
    private float descriptionLayoutWidth = Verifier.nondetFloat(), descriptionLayoutLeft = Verifier.nondetFloat();

    public boolean hasPhoto = Verifier.nondetBoolean();
    private boolean smallPhoto = Verifier.nondetBoolean();
    private boolean video = Verifier.nondetBoolean();
    public int previewType = Verifier.nondetInt();
    public int type = Verifier.nondetInt(), color = Verifier.nondetInt();
    public float w = Verifier.nondetFloat(), h = Verifier.nondetFloat();
    private float previewHeight = Verifier.nondetFloat();
    private float photoHeight = Verifier.nondetFloat();

    public void setupLayout() {
        if (!relayout || Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (withPreview()) {
            final String text = Verifier.nondetString();
            float maxWidth = this.maxWidth - padx - padx;

            h = 0;
            w = 0;
            previewHeight = 0;

            final int colorId = Verifier.nondetInt();
            h += 7.33f * density;
            messageAbove = Verifier.nondetBoolean();
            w = Verifier.nondetFloat();
            h += Verifier.nondetFloat();
            h += 7 * density;

            hasPhoto = Verifier.nondetBoolean();
            smallPhoto = Verifier.nondetBoolean();
            final int photoSide = Verifier.nondetInt();
            int pw = 0, ph = 0;
            if (Verifier.nondetBoolean()) {
                if (Verifier.nondetBoolean()) {
                    pw = Verifier.nondetInt();
                    ph = Verifier.nondetInt();
                }
            } else if (Verifier.nondetBoolean()) {
                if (Verifier.nondetBoolean()) {
                    pw = Verifier.nondetInt();
                    ph = Verifier.nondetInt();
                }
            }

            int lines = 0;
            previewHeight += 5.66f * density;
            hasSiteName = Verifier.nondetBoolean();
            if (hasSiteName) {
                w = Verifier.nondetFloat();
                previewHeight += Verifier.nondetFloat();
                previewHeight += 2.66f * density;
                lines += Verifier.nondetInt();
            }

            hasTitle = Verifier.nondetBoolean();
            if (hasTitle) {
                w = Verifier.nondetFloat();
                previewHeight += Verifier.nondetFloat();
                previewHeight += 2.66f * density;
                lines += Verifier.nondetInt();
            }

            hasDescription = Verifier.nondetBoolean();
            if (hasDescription) {
                descriptionLayoutWidth = 0;
                descriptionLayoutLeft = Float.MAX_VALUE;
                w = Math.max(w, Math.min(descriptionLayoutWidth + 40 * density, maxWidth));

                previewHeight += Verifier.nondetFloat();
                previewHeight += 2.66f * density;
            }

            if (hasPhoto && !smallPhoto) {
                if (pw <= 0 || ph <= 0) {
                    photoHeight = 120 * density;
                } else {
                    final float photoWidth = Math.max(0, w - 40 * density);
                    photoHeight = Math.min(photoWidth / pw * ph, 200 * density);
                }
                previewHeight += photoHeight;
                previewHeight += 2.66f * density;
            }

            previewHeight += 7 * density;
            h += previewHeight;

            h += 11 * density;

        } else {
            final String text = Verifier.nondetString();
            float maxWidth = Verifier.nondetFloat();
            textScale = 1f;
            layoutWidth = 0;
            layoutLeft = Float.MAX_VALUE;
            w = Verifier.nondetFloat();
            h = Verifier.nondetFloat();
        }

        relayout = false;
    }

    public void pushPhotoToCache() {
        if (!hasPhoto) return;
    }

    public int getPhotoSide() {
        assert true; //inline assert generated by ARG-V
		return (int) (smallPhoto ? 48 : (maxWidth - padx - padx) / density - 40) * 2;
    }

    public boolean withPreview() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public int backgroundColor = Verifier.nondetInt();

    public void setType(int type, int color) {
        if (this.type == 1) return;
        if (type == 0) {
            backgroundColor = color;
            final int textColor = Verifier.nondetInt();
        } else if (type == 1) {
            backgroundColor = 0xFF000000;
        } else if (type == 2) {
            backgroundColor = 0x4C000000;
        } else {
            backgroundColor = 0xFFFFFFFF;
        }
    }

    public void setPreviewType(int type) {
        previewType = type;
    }

    public int getPreviewType() {
        assert true; //inline assert generated by ARG-V
		return previewType;
    }

    public static String fromUrl(String url) {
        assert true; //inline assert generated by ARG-V
		return url;
    }

    /** ARG-V: suitable */
	 public static String fromUrlWithoutSchema(String url) {
        if (url.startsWith("https://")) {
            assert true; //inline assert generated by ARG-V
			return url.substring(8);
        }
        assert true; //inline assert generated by ARG-V
		return url;
    }


    public float getRadius() {
        assert true; //inline assert generated by ARG-V
		return withPreview() ? 16.66f * density : .2f * h;
    }

    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        setupLayout();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.setupLayout();
		instance.pushPhotoToCache();
		instance.getPhotoSide();
		instance.withPreview();
		instance.setType(Verifier.nondetInt(), Verifier.nondetInt());
		instance.setPreviewType(Verifier.nondetInt());
		instance.getPreviewType();
		fromUrl(Verifier.nondetString());
		fromUrlWithoutSchema(Verifier.nondetString());
		instance.getRadius();
		instance.onMeasure(Verifier.nondetInt(), Verifier.nondetInt());
	}
}
