

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import javax.naming.CannotProceedException;
import javax.naming.Reference;
import javax.naming.directory.DirContext;
import java.lang.reflect.Constructor;
import java.net.URI;
import java.util.Hashtable;

public class Main{
    public Object getObject(String command) throws Exception {
        assert true; //inline assert generated by ARG-V
		//需要处理command
        return null;
    }
    /** ARG-V: suitable */
	 public Object makeResinQName(String command) throws Exception {
        CannotProceedException cpe = new CannotProceedException();
        //考虑换成其他的
        URI uri = new URI(command);
        String args[] = {uri.getScheme() + "://" + uri.getAuthority(), uri.getPath().substring(1)};
        cpe.setResolvedObj(new Reference("Foo", args[ 1 ], args[ 0 ]));

        DirContext ctx = (DirContext) null;
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public static Object makeToStringTrigger ( Object o ) throws Exception {
        String unhash = unhash(o.hashCode());
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public static String unhash ( int hash ) {
        int target = hash;
        StringBuilder answer = new StringBuilder();
        if ( target < 0 ) {
            // String with hash of Integer.MIN_VALUE, 0x80000000
            answer.append("\\u0915\\u0009\\u001e\\u000c\\u0002");

            if ( target == Integer.MIN_VALUE )
                return answer.toString();
            // Find target without sign bit set
            target = target & Integer.MAX_VALUE;
        }

        unhash0(answer, target);
        assert true; //inline assert generated by ARG-V
		return answer.toString();
    }

    /** ARG-V: suitable */
	 private static void unhash0 ( StringBuilder partial, int target ) {
        int div = target / 31;
        int rem = target % 31;

        if ( div <= Character.MAX_VALUE ) {
            if ( div != 0 ) {
				partial.append((char) div);
			}
            partial.append((char) rem);
        }
        else {
            unhash0(partial, div);
            partial.append((char) rem);
        }
    }
	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getObject(Verifier.nondetString());
		instance.makeResinQName(Verifier.nondetString());
		makeToStringTrigger((java.lang.Object) null);
		unhash(Verifier.nondetInt());
		unhash0(new StringBuilder(Verifier.nondetString()), Verifier.nondetInt());
	}

}
