/** filtered and transformed by ARG-V */

/*
 * Copyright 2015 Synced Synapse. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Fragment that presents the welcome message
 */
public class Main {
    private static String TAG = Verifier.nondetString();

    /**
     * Fragment arguments
     */
    private static String PREFIX = "org.xbmc.kore";
    public static String HOST_ID = PREFIX + ".host_id",
            HOST_NAME = PREFIX + ".host_name",
            HOST_ADDRESS = PREFIX + ".host_address",
            HOST_HTTP_PORT = PREFIX + ".host_http_port",
            HOST_TCP_PORT = PREFIX + ".host_tcp_post",
            HOST_USERNAME = PREFIX + ".host_username",
            HOST_PASSWORD = PREFIX + ".host_password",
            HOST_MAC_ADDRESS = PREFIX + ".host_mac_address",
            HOST_WOL_PORT = PREFIX + ".host_wol_port",
            HOST_DIRECT_SHARE = PREFIX + ".host_direct_share",
            HOST_PROTOCOL = PREFIX + ".host_protocol",
            HOST_USE_EVENT_SERVER = PREFIX + ".host_use_event_server",
            HOST_EVENT_SERVER_PORT = PREFIX + ".host_event_server_port",
            HOST_IS_HTTPS = PREFIX + ".host_is_https";
    public static String GO_STRAIGHT_TO_TEST = PREFIX + ".go_straight_to_test";

    public static String CANCEL_BUTTON_LABEL_ARG = PREFIX + ".cancel_button_label";
    private static boolean isValidPort(int port) {
        assert true; //inline assert generated by ARG-V
		return port > 0 && port <= 65535;
    }

    /**
     * Tests a connection with the values set in the UI.
     * Checks whether the values are correctly set, and then tries to make
     * a ping call. First through HTTP, and if it succeeds, through TCP to
     * check availability. Finally adds the host and advances the wizard
     */
    /** ARG-V: suitable */
	 private void testConnection() {
        String kodiName = Verifier.nondetString();

        boolean isHttps = false;
        String kodiAddress = Verifier.nondetString();
        if (kodiAddress.startsWith("https://")) {
            kodiAddress = kodiAddress.substring("https://".length());
            isHttps = true;
        } else if (kodiAddress.startsWith("http://")) {
            kodiAddress = kodiAddress.substring("http://".length());
        }
        int kodiHttpPort = Verifier.nondetInt();

        Integer implicitPort = null;
        Matcher m = Pattern.compile("^.*:(\\d{1,5})\\z").matcher(kodiAddress);
        if (m.matches()) {
            // Minus one character for the colon
            kodiAddress = kodiAddress.substring(0, m.start(1) - 1);
            try {
                implicitPort = Integer.parseInt(m.group(1));
            } catch (Exception e) {
                implicitPort = -1;
            }
        }

        Integer explicitPort = null;
        String aux = Verifier.nondetString();
        if (implicitPort != null) {
            if (!isValidPort(implicitPort)) {
                assert true; //inline assert generated by ARG-V
				return;
            }
            kodiHttpPort = implicitPort;
        } else if (explicitPort != null) {
            if (!isValidPort(explicitPort)) {
                assert true; //inline assert generated by ARG-V
				return;
            }
            kodiHttpPort = explicitPort;
        }

        String kodiUsername = Verifier.nondetString();
        String kodiPassword = Verifier.nondetString();
        aux = Verifier.nondetString();
        int kodiTcpPort = Verifier.nondetInt();
        try {
            kodiTcpPort = Verifier.nondetInt();
        } catch (Exception e) {
            kodiTcpPort = -1;
        }

        int kodiProtocol = Verifier.nondetInt();

        String macAddress = Verifier.nondetString();
        aux = Verifier.nondetString();

        int kodiWolPort = Verifier.nondetInt();
        try {
            kodiWolPort = Verifier.nondetInt();
        } catch (Exception e) {
            // Ignoring this exception and keeping WoL port at the default value
        }

        boolean kodiUseEventServer = Verifier.nondetBoolean();
        aux = Verifier.nondetString();
        int kodiEventServerPort = Verifier.nondetInt();
        try {
            kodiEventServerPort = Verifier.nondetInt();
        } catch (Exception e) {
            kodiEventServerPort = -1;
        }

        // Check Kodi name and address
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        } else if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        } else if (kodiTcpPort <= 0) {
            assert true; //inline assert generated by ARG-V
			return;
        } else if (kodiEventServerPort <= 0) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        // If username or password empty, set it to null
        if (Verifier.nondetBoolean()) {
			kodiUsername = Verifier.nondetString();
		}
        if (Verifier.nondetBoolean()) {
			kodiPassword = Verifier.nondetString();
		}
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		isValidPort(Verifier.nondetInt());
		instance.testConnection();
	}
}
