

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** filtered by ARG-V */
 public class Main {

  private static String DEVICE_PATH = "device_path";
  private static String VID = "vid";
  private static String PID = "pid";
  private static String SERIAL_NUMBER = "serial_number";
  private static String DEV_TTY_USBSERIAL = "/dev/tty.usbserial-";
  private static String DEV_CU_USBSERIAL = "/dev/cu.usbserial-";
  private static String DEV_TTY_USBMODEM = "/dev/tty.usbmodem";
  private static String DEV_CU_USBMODEM = "/dev/cu.usbmodem";

  private Pattern vidRegex = null;
  private Pattern serialNumberRegex = null;
  private Pattern locationRegex = null;
  private Pattern pidRegex = null;

  public Main() {
  }

  /** ARG-V: suitable */
 public String extractVIDAndPID(String output, String serial) throws Exception {
    BufferedReader reader = new BufferedReader(new StringReader(output));

    String devicePrefix = Verifier.nondetString();
    if (serial.startsWith(DEV_TTY_USBSERIAL)) {
      devicePrefix = DEV_TTY_USBSERIAL;
    } else if (serial.startsWith(DEV_CU_USBSERIAL)) {
      devicePrefix = DEV_CU_USBSERIAL;
    } else if (serial.startsWith(DEV_TTY_USBMODEM)) {
      devicePrefix = DEV_TTY_USBMODEM;
    } else {
      devicePrefix = DEV_CU_USBMODEM;
    }

    Map<String, String> device = new HashMap<>();

    String line = Verifier.nondetString();
    Matcher matcher = null;
    while ((line = reader.readLine()) != Verifier.nondetString()) {
      line = line.trim();
      line = line.replaceAll("\\s+", " ");

      if ((matcher = serialNumberRegex.matcher(line)).matches()) {
        device.put(SERIAL_NUMBER, matcher.group(1));
        if (serial.startsWith(DEV_TTY_USBSERIAL) || serial.startsWith(DEV_CU_USBSERIAL)) {
          String devicePath = devicePrefix + matcher.group(1);
          device.put(DEVICE_PATH, devicePath);
        }
      } else if ((serial.startsWith(DEV_TTY_USBMODEM) || serial.startsWith(DEV_CU_USBMODEM)) && (matcher = locationRegex.matcher(line)).matches()) {
        String suffix = matcher.group(1).substring(2, 6).replaceAll("0", "");
        String devicePath = devicePrefix + suffix + "1";
        device.put(DEVICE_PATH, devicePath);
      } else if ((matcher = pidRegex.matcher(line)).matches()) {
        String pid = matcher.group(1);
        if (pid.indexOf(" ") > 0) {
          pid = pid.substring(0, pid.indexOf(" ")); // Remove any text after the hex number
        }
        device.put(PID, pid);
      } else if ((matcher = vidRegex.matcher(line)).matches()) {
        String vid = matcher.group(1);
        if (vid.indexOf(" ") > 0) {
          vid = vid.substring(0, vid.indexOf(" ")); // Remove any text after the hex number
        }
        device.put(VID, vid);
      } else if (line.equals("")) {
        if (device.containsKey(DEVICE_PATH)) {
          String computedDevicePath = device.get(DEVICE_PATH);
          String computedDevicePathMinusChar = computedDevicePath.substring(0, computedDevicePath.length() - 1);
          String serialMinusChar = serial.substring(0, serial.length() - 1);
          if (computedDevicePath.equalsIgnoreCase(serial) || computedDevicePathMinusChar.equalsIgnoreCase(serialMinusChar)) {
            assert true; //inline assert generated by ARG-V
			return (device.get(VID) + "_" + device.get(PID)).toUpperCase();
          }
        }
        device = new HashMap<>();
      }
    }

    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.extractVIDAndPID(Verifier.nondetString(), Verifier.nondetString());
}

}
