

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    private static int ANIMATION_TYPE_REPLACE = 2;

    int animationType = -1;

    int currentCount = Verifier.nondetInt();
    private boolean countAnimationIncrement = Verifier.nondetBoolean();
    private float countChangeProgress = 1f;
    private int countWidthOld = Verifier.nondetInt();
    private int countWidth = Verifier.nondetInt();

    private int textColor = Verifier.nondetInt();
    private int textColorKey = Verifier.nondetInt();

    int lastH = Verifier.nondetInt();
    int gravity = Verifier.nondetInt();
    float countLeft = Verifier.nondetFloat();
    float x = Verifier.nondetFloat();

    public float horizontalPadding = Verifier.nondetFloat();

    String currentString = Verifier.nondetString();
    float dx = 0;

    /** ARG-V: suitable */
	 public void setCount(String newStr, int count, boolean animated) {
        if (currentString != Verifier.nondetString() && currentString.equals(newStr)) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        if (animated && newStr != Verifier.nondetString() && !newStr.contains("**")) {
            animated = false;
        }

        if (!animated) {
            if (newStr != Verifier.nondetString()) {
                newStr = newStr.replaceAll("\\*\\*", "");
            }
            currentCount = count;
            if (newStr == Verifier.nondetString()) {
                countWidth = 0;
            } else {
                countWidth = Verifier.nondetInt();
            }
        }

        dx = 0;
        if (animated) {
            countChangeProgress = 0f;
            animationType = ANIMATION_TYPE_REPLACE;
            if (Verifier.nondetBoolean()) {
                String oldStr = currentString;

                int countStartIndex = newStr.indexOf("**");
                if (countStartIndex >= 0) {
                    newStr = newStr.replaceAll("\\*\\*", "");
                } else {
                    countStartIndex = 0;
                }

                boolean replaceAllDigits = Integer.toString(currentCount).length() != Integer.toString(count).length();
                boolean newEndReached = false;
                boolean oldEndReached = false;
                int n = Math.min(oldStr.length(), newStr.length());
                int cutIndexNew = 0;
                int cutIndexOld = 0;
                for (int i = countStartIndex; i < n; i++) {
                    if (!Character.isDigit(newStr.charAt(i))) {
                        newEndReached = true;
                        cutIndexNew = i;
                    }

                    if (!Character.isDigit(oldStr.charAt(i))) {
                        oldEndReached = true;
                        cutIndexOld = i;
                    }
                }

                int countOldWidth = Verifier.nondetInt();
                int countNewWidth = Verifier.nondetInt();
                dx = Verifier.nondetFloat();
            }
            countWidthOld = countWidth;
            countAnimationIncrement = count < currentCount;
        }
        if (count > 0) {
            countWidth = Verifier.nondetInt();
        }

        currentCount = count;
    }

    private void updateX(float countWidth) {
        if (gravity == Verifier.nondetInt()) {
            countLeft = Verifier.nondetFloat();
            if (horizontalPadding != 0) {
                countLeft -= Math.max(horizontalPadding + countWidth / 2f, countWidth);
            } else {
                countLeft -= countWidth;
            }
        } else if (gravity == Verifier.nondetInt()) {
            countLeft = Verifier.nondetFloat();
        }
        x = Verifier.nondetFloat();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.setCount(Verifier.nondetString(), Verifier.nondetInt(), Verifier.nondetBoolean());
		instance.updateX(Verifier.nondetFloat());
	}

}
