/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */

/** filtered by ARG-V */
 public final class Main {
    private Main() {
    }

    /**
     * remove the ' at the beginning and the end
     *
     * @param number
     * @return
     */
    /** ARG-V: suitable */
	 public static String eliminateQuote(String number) {
        number = number.trim();
        if (number.contains("\"")) {
            if (number.charAt(0) == '\"') {
                number = number.substring(1);
                if (number.charAt(number.length() - 1) == '\"') {
                    number = number.substring(0, number.length() - 1);
                }
            }
        } else if (number.contains("\'")) {
            if (number.charAt(0) == '\'') {
                number = number.substring(1);
                if (number.charAt(number.length() - 1) == '\'') {
                    number = number.substring(0, number.length() - 1);
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return number;
    }

    /**
     * can parse values like 200M ,200K,200M1(2000001)
     *
     * @param val
     * @return
     */
    /** ARG-V: suitable */
	 public static long parseLong(String val) {
        val = val.toUpperCase();
        int index = val.indexOf("M");

        int plus = 10000;
        if (index < 0) {
            index = val.indexOf("K");
            plus = 1000;
        }
        if (index > 0) {
            String longVal = val.substring(0, index);

            long theVale = Long.parseLong(longVal) * plus;
            String remain = val.substring(index + 1);
            if (remain.length() > 0) {
                theVale += Integer.parseInt(remain);
            }
            assert true; //inline assert generated by ARG-V
			return theVale;
        } else {
            assert true; //inline assert generated by ARG-V
			return Long.parseLong(val);
        }

    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		eliminateQuote(Verifier.nondetString());
		parseLong(Verifier.nondetString());
	}
}
