

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.UUID;

public class Main {
    boolean exitTempIdAfterInit = false;
    boolean cleanupTempIdAfterInit = false;

    /** ARG-V: suitable */
	 void replaceTempIDWithRealIDinRQ(String targetDeviceId) {
        String[] storedRequests = new java.lang.String[] { Verifier.nondetString() };
        String temporaryIdTag = Verifier.nondetString();
        String newIdTag = "&device_id=" + targetDeviceId;

        boolean foundOne = false;
        for (int a = 0; a < storedRequests.length; a++) {
            if (storedRequests[a].contains(temporaryIdTag)) {
                storedRequests[a] = storedRequests[a].replace(temporaryIdTag, newIdTag);
                foundOne = true;
            }
        }
    }

    void exitTemporaryIdMode(String deviceId) {
        //update stored request for ID change to use this new ID
        replaceTempIDWithRealIDinRQ(deviceId);
    }

    /**
     * Changes current device id type to the one specified in parameter. Closes current session and
     * reopens new one with new id. Doesn't merge user profiles on the server
     *
     * @param deviceId Optional device ID for a case when type = DEVELOPER_SPECIFIED
     */
    void changeDeviceIdWithoutMergeInternal(String deviceId) {
        if (isTemporaryIdEnabled() && Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			// we already are in temporary mode and we want to set temporary mode
            // in this case we just ignore the request since nothing has to be done
            return;
        }

        

        // we are either making a simple ID change or entering temporary mode
        // in both cases we act the same as the temporary ID requests will be updated with the final ID later

    }

    /**
     * Changes current device id to the one specified in parameter. Merges user profile with new id
     * (if any) with old profile.
     *
     * @param deviceId new device id
     */
    void changeDeviceIdWithMergeInternal(String deviceId) {
        if (deviceId.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    private void setIDInternal(String newDeviceID) {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            // an ID was provided by the host app previously
            // we can assume that a device ID change with merge was executed previously
            // now we change it without merging
            changeDeviceIdWithoutMergeInternal(newDeviceID);
        } else {
            // SDK generated ID
            // we change device ID with merge so that data is combined
            changeDeviceIdWithMergeInternal(newDeviceID);
        }
    }

    public static String PREF_KEY = "openudid"; // key of old impl, keeping because needs migration
    public static String PREFS_NAME = "openudid_prefs";

    public String getUUID() {
        String retrievedID = Verifier.nondetString();

        //Try to get the stored UUID from local preferences
        retrievedID = Verifier.nondetString();
        if (retrievedID == Verifier.nondetString()) //Not found if temp storage
        {
            retrievedID = UUID.randomUUID().toString();
        }

        assert true; //inline assert generated by ARG-V
		return retrievedID;
    }

    public String getDeviceId() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public boolean isTemporaryIdEnabled() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.replaceTempIDWithRealIDinRQ(Verifier.nondetString());
		instance.exitTemporaryIdMode(Verifier.nondetString());
		instance.changeDeviceIdWithoutMergeInternal(Verifier.nondetString());
		instance.changeDeviceIdWithMergeInternal(Verifier.nondetString());
		instance.setIDInternal(Verifier.nondetString());
		instance.getUUID();
		instance.getDeviceId();
		instance.isTemporaryIdEnabled();
	}
}
