

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import java.util.stream.Collectors;

public final class Main {

    private String apiVersion = Verifier.nondetString();

    // Base Docker URL
    private String baseUrl = Verifier.nondetString();

    public Main(String baseUrl, String apiVersion) {
    }

    public String copyArchive(String containerId, String targetPath) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String inspectImage(String name) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String listImages(boolean all) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String containerLogs(String containerId, boolean follow) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String createContainer(String name, String platform) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String version() {
        assert true; //inline assert generated by ARG-V
		return String.format("%s/version", baseUrl);
    }

    public String deleteImage(String name, boolean force) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String inspectContainer(String containerId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String inspectExecContainer(String containerId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String listContainers(boolean all, String ... filter) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String loadImage() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String removeContainer(String containerId, boolean removeVolumes) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String startContainer(String containerId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String createExecContainer(String containerId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String startExecContainer(String containerId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String stopContainer(String containerId, int killWait) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String killContainer(String containerId) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String listNetworks() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String createNetwork() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String removeNetwork(String id) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String createVolume() {
       assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
    }

    public String removeVolume(String name) {
       assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
    }

    public String getBaseUrl() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    // ============================================================================

    private static String encode(String param) {
        try {
            assert true; //inline assert generated by ARG-V
			return URLEncoder.encode(param, "UTF-8");
        }
        catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			// wont happen
            return URLEncoder.encode(param);
        }
    }

    /** ARG-V: suitable */
	 private String stripSlash(String url) {
        String ret = url;
        while (ret.endsWith("/")) {
            ret = ret.substring(0, ret.length() - 1);
        }
        assert true; //inline assert generated by ARG-V
		return ret;
    }

    private String[] encodeArgs(String[] args) {
        String ret[] = new String[args.length];
        int i=0;
        assert true; //inline assert generated by ARG-V
		return ret;
    }

    private String createUrl(String path) {
        assert true; //inline assert generated by ARG-V
		return String.format("%s/%s/%s", baseUrl, apiVersion, path);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString(), Verifier.nondetString());
		instance.copyArchive(Verifier.nondetString(), Verifier.nondetString());
		instance.inspectImage(Verifier.nondetString());
		instance.listImages(Verifier.nondetBoolean());
		instance.containerLogs(Verifier.nondetString(), Verifier.nondetBoolean());
		instance.createContainer(Verifier.nondetString(), Verifier.nondetString());
		instance.version();
		instance.deleteImage(Verifier.nondetString(), Verifier.nondetBoolean());
		instance.inspectContainer(Verifier.nondetString());
		instance.inspectExecContainer(Verifier.nondetString());
		instance.listContainers(Verifier.nondetBoolean(), new java.lang.String[] { Verifier.nondetString() });
		instance.loadImage();
		instance.removeContainer(Verifier.nondetString(), Verifier.nondetBoolean());
		instance.startContainer(Verifier.nondetString());
		instance.createExecContainer(Verifier.nondetString());
		instance.startExecContainer(Verifier.nondetString());
		instance.stopContainer(Verifier.nondetString(), Verifier.nondetInt());
		instance.killContainer(Verifier.nondetString());
		instance.listNetworks();
		instance.createNetwork();
		instance.removeNetwork(Verifier.nondetString());
		instance.createVolume();
		instance.removeVolume(Verifier.nondetString());
		instance.getBaseUrl();
		encode(Verifier.nondetString());
		instance.stripSlash(Verifier.nondetString());
		instance.encodeArgs(new java.lang.String[] { Verifier.nondetString() });
		instance.createUrl(Verifier.nondetString());
	}
}
