/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Properties;
import java.util.TimeZone;

/**
 * One-stop shop for Secor configuration options.
 *
 * @author Pawel Garbacki (pawel@pinterest.com)
 */
public class Main {
    public String getKafkaSeedBrokerHost() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.seed.broker.host");
    }

    public int getKafkaSeedBrokerPort() {
        assert true; //inline assert generated by ARG-V
		return getInt("kafka.seed.broker.port");
    }

    public String getKafkaZookeeperPath() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.zookeeper.path");
    }

    public String getZookeeperQuorum() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public int getConsumerTimeoutMs() {
        assert true; //inline assert generated by ARG-V
		return getInt("kafka.consumer.timeout.ms");
    }

    public String getConsumerAutoOffsetReset() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.consumer.auto.offset.reset");
    }

    public String[] getKafkaTopicList() {
        assert true; //inline assert generated by ARG-V
		return getStringArray("kafka.new.consumer.topic.list");
    }

    public String getNewConsumerAutoOffsetReset() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.auto.offset.reset");
    }

    public int getNewConsumerPollTimeoutSeconds() {
        assert true; //inline assert generated by ARG-V
		return getInt("kafka.new.consumer.poll.timeout.seconds");
    }

    public String getNewConsumerRequestTimeoutMs() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.request.timeout.ms");
    }

    public String getSslKeyPassword() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.key.password");
    }

    public String getSslKeystoreLocation() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.keystore.location");
    }

    public String getSslKeystorePassword() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.keystore.password");
    }

    public String getSslTruststoreLocation() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.truststore.location");
    }

    public String getSslTruststorePassword() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.truststore.password");
    }

    public String getIsolationLevel() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.isolation.level");
    }

    public String getMaxPollIntervalMs() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.max.poll.interval.ms");
    }

    public String getMaxPollRecords() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.max.poll.records");
    }

    public String getSaslClientCallbackHandlerClass() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.sasl.client.callback.handler.class");
    }

    public String getSaslJaasConfig() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.sasl.jaas.config");
    }

    public String getSaslKerberosServiceName() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.sasl.kerberos.service.name");
    }

    public String getSaslLoginCallbackHandlerClass() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.sasl.login.callback.handler.class");
    }

    public String getSaslLoginClass() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.sasl.login.class");
    }

    public String getSaslMechanism() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.sasl.mechanism");
    }

    public String getSecurityProtocol() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.security.protocol");
    }

    public String getSslEnabledProtocol() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.enabled.protocols");
    }

    public String getSslKeystoreType() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.keystore.type");
    }

    public String getSslProtocol() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.protocol");
    }

    public String getSslProvider() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.provider");
    }

    public String getSslTruststoreType() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.ssl.truststore.type");
    }

    public String getNewConsumerPartitionAssignmentStrategyClass() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.new.consumer.partition.assignment.strategy.class");
    }

    public String getPartitionAssignmentStrategy() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.partition.assignment.strategy");
    }

    public String getRebalanceMaxRetries() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.rebalance.max.retries");
    }

    public String getRebalanceBackoffMs() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.rebalance.backoff.ms");
    }

    public String getFetchMessageMaxBytes() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.fetch.message.max.bytes");
    }

    public String getSocketReceiveBufferBytes() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.socket.receive.buffer.bytes");
    }

    public String getFetchMinBytes() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.fetch.min.bytes");
    }

    public String getFetchMaxBytes() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.fetch.max.bytes");
    }

    public String getFetchWaitMaxMs() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.fetch.wait.max.ms");
    }

    public String getDualCommitEnabled() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.dual.commit.enabled");
    }

    public String getOffsetsStorage() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.offsets.storage");
    }

    public boolean useKafkaTimestamp() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("kafka.useTimestamp", false);
    }

    public String getKafkaMessageTimestampClass() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.message.timestamp.className");
    }

    public String getKafkaMessageIteratorClass() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.message.iterator.className");
    }

    public String getKafkaClientClass() {
        assert true; //inline assert generated by ARG-V
		return getString("kafka.client.className");
    }

    public int getGeneration() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.generation");
    }

    public int getConsumerThreads() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.consumer.threads");
    }

    public int getMaxBadMessages() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.consumer.max_bad_messages", 1000);
    }

    public long getMaxFileSizeBytes() {
        assert true; //inline assert generated by ARG-V
		return getLong("secor.max.file.size.bytes");
    }

    public long getMaxFileAgeSeconds() {
        assert true; //inline assert generated by ARG-V
		return getLong("secor.max.file.age.seconds");
    }

    public int getMaxActiveFiles() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.max.file.count", -1);
    }

    public boolean getUploadOnShutdown() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.upload.on.shutdown");
    }

    public boolean getUploadLastSeenOffset() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.upload.last.seen.offset", false);
    }

    public boolean getDeterministicUpload() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.upload.deterministic");
    }

    public long getMaxFileTimestampRangeMillis() {
        assert true; //inline assert generated by ARG-V
		return getLong("secor.max.file.timestamp.range.millis");
    }

    public long getMaxInputPayloadSizeBytes() {
        assert true; //inline assert generated by ARG-V
		return getLong("secor.max.input.payload.size.bytes");
    }

    public boolean getFileAgeYoungest() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.file.age.youngest");
    }

    public long getOffsetsPerPartition() {
        assert true; //inline assert generated by ARG-V
		return getLong("secor.offsets.per.partition");
    }

    public int getMessagesPerSecond() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.messages.per.second");
    }

    public String getS3FileSystem() { assert true; //inline assert generated by ARG-V
	return getString("secor.s3.filesystem"); }

    /** ARG-V: suitable */
	 public boolean getSeparateContainersForTopics() {
    	assert true; //inline assert generated by ARG-V
		return getString("secor.swift.containers.for.each.topic").toLowerCase().equals("true");
    }

    public String getSwiftContainer() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.swift.container");
    }

    public String getSwiftPath() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.swift.path");
    }

    public String getS3Bucket() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.s3.bucket");
    }

    public String getS3Path() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.s3.path");
    }

    public String getS3AlternativePath() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.s3.alternative.path");
    }

    public String getS3AlterPathDate() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.s3.alter.path.date");
    }

    /** ARG-V: suitable */
	 public String getS3Prefix() {
        assert true; //inline assert generated by ARG-V
		return getS3FileSystem() + "://" + getS3Bucket() + "/" + getS3Path();
    }

    public String getLocalPath() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.local.path");
    }

    public String getKafkaTopicFilter() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.kafka.topic_filter");
    }

    public String getKafkaTopicBlacklist() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.kafka.topic_blacklist");
    }

    public String getKafkaTopicUploadAtMinuteMarkFilter() { assert true; //inline assert generated by ARG-V
	return getString("secor.kafka.upload_at_minute_mark.topic_filter");}

    public int getUploadMinuteMark(){ assert true; //inline assert generated by ARG-V
	return getInt("secor.upload.minute_mark");}

    public String getKafkaGroup() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.kafka.group");
    }

    public int getZookeeperSessionTimeoutMs() {
        assert true; //inline assert generated by ARG-V
		return getInt("zookeeper.session.timeout.ms");
    }

    public int getZookeeperSyncTimeMs() {
        assert true; //inline assert generated by ARG-V
		return getInt("zookeeper.sync.time.ms");
    }

    public String getSchemaRegistryUrl(){ assert true; //inline assert generated by ARG-V
	return getString("schema.registry.url"); }

    public String getMessageParserClass() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.message.parser.class");
    }

    public String getUploaderClass() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.upload.class", "com.pinterest.secor.uploader.Uploader");
    }

    public String getUploadManagerClass() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.upload.manager.class");
    }

    public String getMessageTransformerClass(){
    	assert true; //inline assert generated by ARG-V
		return getString("secor.message.transformer.class");
    }

    public int getTopicPartitionForgetSeconds() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.topic_partition.forget.seconds");
    }

    public int getLocalLogDeleteAgeHours() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.local.log.delete.age.hours");
    }

    public String getFileExtension() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.file.extension");
    }

    public int getOstrichPort() {
        assert true; //inline assert generated by ARG-V
		return getInt("ostrich.port");
    }

    public String getCloudService() {
        assert true; //inline assert generated by ARG-V
		return getString("cloud.service");
    }

    public String getAwsAccessKey() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.access.key");
    }

    public String getAwsSecretKey() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.secret.key");
    }

    public String getAwsSessionToken() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.session.token", "");
    }

    public String getAwsEndpoint() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.endpoint");
    }

    public String getAwsRole() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.role");
    }

    public boolean getAwsClientPathStyleAccess() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("aws.client.pathstyleaccess", false);
    }

    public boolean getAwsProxyEnabled(){
    	assert true; //inline assert generated by ARG-V
		return getBoolean("aws.proxy.isEnabled");
    }

    public String getAwsProxyHttpHost() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.proxy.http.host");
    }

    public int getAwsProxyHttpPort() {
        assert true; //inline assert generated by ARG-V
		return getInt("aws.proxy.http.port");
    }

    public String getAwsRegion() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.region");
    }

    public String getAwsSseType() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.sse.type");
    }

    public String getAwsSseKmsKey() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.sse.kms.key");
    }

    public String getAwsSseCustomerKey() {
        assert true; //inline assert generated by ARG-V
		return getString("aws.sse.customer.key");
    }

    public String getSwiftTenant() {
        assert true; //inline assert generated by ARG-V
		return getString("swift.tenant");
    }

    public String getSwiftRegion() {
        assert true; //inline assert generated by ARG-V
		return getString("swift.region");
    }

    public String getSwiftUsername() {
        assert true; //inline assert generated by ARG-V
		return getString("swift.username");
    }

    public String getSwiftPassword() {
        assert true; //inline assert generated by ARG-V
		return getString("swift.password");
    }

    public String getSwiftAuthUrl() {
        assert true; //inline assert generated by ARG-V
		return getString("swift.auth.url");
    }

    public String getSwiftPublic() {
    	assert true; //inline assert generated by ARG-V
		return getString("swift.public");
    }

    public String getSwiftPort() {
    	assert true; //inline assert generated by ARG-V
		return getString("swift.port");
    }

    public String getSwiftGetAuth() {
    	assert true; //inline assert generated by ARG-V
		return getString("swift.use.get.auth");
    }

    public String getSwiftApiKey() {
    	assert true; //inline assert generated by ARG-V
		return getString("swift.api.key");
    }

    public String getQuboleApiToken() {
        assert true; //inline assert generated by ARG-V
		return getString("qubole.api.token");
    }

    public String getTsdbHostport() {
        assert true; //inline assert generated by ARG-V
		return getString("tsdb.hostport");
    }

    public String getStatsDHostPort() {
        assert true; //inline assert generated by ARG-V
		return getString("statsd.hostport");
    }

    public boolean getStatsDPrefixWithConsumerGroup(){
    	assert true; //inline assert generated by ARG-V
		return getBoolean("statsd.prefixWithConsumerGroup");
    }

    public boolean getStatsdDogstatdsTagsEnabled() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("statsd.dogstatsd.tags.enabled");
    }

    public String[] getStatsDDogstatsdConstantTags() {
        assert true; //inline assert generated by ARG-V
		return getStringArray("statsd.dogstatsd.constant.tags");
    }

    public String getMonitoringBlacklistTopics() {
        assert true; //inline assert generated by ARG-V
		return getString("monitoring.blacklist.topics");
    }

    public String getMonitoringPrefix() {
        assert true; //inline assert generated by ARG-V
		return getString("monitoring.prefix");
    }

    public long getMonitoringIntervalSeconds() {
        assert true; //inline assert generated by ARG-V
		return getLong("monitoring.interval.seconds");
    }

    public String getMessageTimestampName() {
        assert true; //inline assert generated by ARG-V
		return getString("message.timestamp.name");
    }

    public String getMessageTimestampNameSeparator() {
        assert true; //inline assert generated by ARG-V
		return getString("message.timestamp.name.separator");
    }

    public int getMessageTimestampId() {
        assert true; //inline assert generated by ARG-V
		return getInt("message.timestamp.id");
    }

    public String getMessageTimestampType() {
        assert true; //inline assert generated by ARG-V
		return getString("message.timestamp.type");
    }

    public String getMessageTimestampInputPattern() {
        assert true; //inline assert generated by ARG-V
		return getString("message.timestamp.input.pattern");
    }

    public boolean isMessageTimestampRequired() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public long getMessageTimestampSkewMaxMs() { assert true; //inline assert generated by ARG-V
	return getLong("message.timestamp.skew.max.ms"); }

    public String getMessageSplitFieldName() {
        assert true; //inline assert generated by ARG-V
		return getString("message.split.field.name");
    }

    public int getFinalizerLookbackPeriods() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.finalizer.lookback.periods", 10);
    }

    public String getHivePrefix() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.hive.prefix");
    }

    public String getHiveTableName(String topic) {
        String key = "secor.hive.table.name." + topic;
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public boolean getQuboleEnabled() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.enable.qubole");
    }

    public long getQuboleTimeoutMs() {
        assert true; //inline assert generated by ARG-V
		return getLong("secor.qubole.timeout.ms");
    }

    public String getCompressionCodec() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.compression.codec");
    }

    public int getMaxMessageSizeBytes() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.max.message.size.bytes");
    }

    public String getFileReaderWriterFactory() {
    	assert true; //inline assert generated by ARG-V
		return getString("secor.file.reader.writer.factory");
    }

    public String getFileReaderDelimiter(){
      String readerDelimiter = getString("secor.file.reader.Delimiter");
      if (readerDelimiter.length() > 1) {
        throw new RuntimeException("secor.file.reader.Delimiter length can not be greater than 1 character");
      }
      assert true; //inline assert generated by ARG-V
	return readerDelimiter;
    }

    public String getFileWriterDelimiter(){
      String writerDelimiter = getString("secor.file.writer.Delimiter");
      if (writerDelimiter.length() > 1) {
        throw new RuntimeException("secor.file.writer.Delimiter length can not be greater than 1 character");
      }
      assert true; //inline assert generated by ARG-V
	return writerDelimiter;
    }

    public String getZookeeperPath() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.zookeeper.path");
    }

    public String getGsCredentialsPath() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.gs.credentials.path");
    }

    public String getGsBucket() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.gs.bucket");
    }

    public String getGsPath() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.gs.path");
    }

    public double getGsRateLimit() {
        assert true; //inline assert generated by ARG-V
		return getDouble("secor.gs.tasks.ratelimit.pr.second", 10.0);
    }

    public int getGsThreadPoolSize() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.gs.threadpool.fixed.size", 256);

    }

    public int getGsConnectTimeoutInMs() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.gs.connect.timeout.ms", 3 * 60000);
    }

    public int getGsReadTimeoutInMs() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.gs.read.timeout.ms", 3 * 60000);
    }

    public boolean getGsDirectUpload() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.gs.upload.direct");
    }

    public int getFinalizerDelaySeconds() {
        assert true; //inline assert generated by ARG-V
		return getInt("partitioner.finalizer.delay.seconds");
    }

    public boolean getS3MD5HashPrefix() {
      assert true; //inline assert generated by ARG-V
	return getBoolean("secor.s3.prefix.md5hash");
    }

    public String getAzureEndpointsProtocol() { assert true; //inline assert generated by ARG-V
	return getString("secor.azure.endpoints.protocol"); }

    public String getAzureAccountName() { assert true; //inline assert generated by ARG-V
	return getString("secor.azure.account.name"); }

    public String getAzureAccountKey() { assert true; //inline assert generated by ARG-V
	return getString("secor.azure.account.key"); }

    public String getAzureContainer() { assert true; //inline assert generated by ARG-V
	return getString("secor.azure.container.name"); }

    public String getAzurePath() { assert true; //inline assert generated by ARG-V
	return getString("secor.azure.path"); }

    /** ARG-V: suitable */
	 public Map<String, String> getProtobufMessageClassPerTopic() {
        String prefix = "secor.protobuf.message.class";
        Iterator<String> keys = null;
        Map<String, String> protobufClasses = new HashMap<String, String>();
        while (keys.hasNext()) {
            String key = keys.next();
            String className = Verifier.nondetString();
            protobufClasses.put(key.substring(prefix.length() + 1), className);
        }
        assert true; //inline assert generated by ARG-V
		return protobufClasses;
    }

    /** ARG-V: suitable */
	 public Map<String, String> getMessageFormatPerTopic() {
        String prefix = "secor.topic.message.format";
        Iterator<String> keys = null;
        Map<String, String> topicMessageFormats = new HashMap<String, String>();
        while (keys.hasNext()) {
            String key = keys.next();
            String topic = Verifier.nondetString();
            topicMessageFormats.put(key.substring(prefix.length() + 1), topic);
        }
        assert true; //inline assert generated by ARG-V
		return topicMessageFormats;
    }

    /** ARG-V: suitable */
	 public Map<String, String> getThriftMessageClassPerTopic() {
        String prefix = "secor.thrift.message.class";
        Iterator<String> keys = null;
        Map<String, String> thriftClasses = new HashMap<String, String>();
        while (keys.hasNext()) {
            String key = keys.next();
            String className = Verifier.nondetString();
            thriftClasses.put(key.substring(prefix.length() + 1), className);
        }
        assert true; //inline assert generated by ARG-V
		return thriftClasses;
    }

    public TimeZone getTimeZone() {
        String timezone = getString("secor.parser.timezone");
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public boolean getBoolean(String name, boolean defaultValue) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public boolean getBoolean(String name) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public String getString(String name) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getString(String name, String defaultValue) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public int getInt(String name) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    public int getInt(String name, int defaultValue) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    public double getDouble(String name, double defaultValue) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetDouble();
    }

    public long getLong(String name) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetLong();
    }

    public String[] getStringArray(String name) {
        assert true; //inline assert generated by ARG-V
		return new java.lang.String[] { Verifier.nondetString() };
    }

    public String getThriftProtocolClass() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getMetricsCollectorClass() {
        assert true; //inline assert generated by ARG-V
		return getString("secor.monitoring.metrics.collector.class");
    }

    public boolean getMicroMeterCollectorJmxEnabled() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.monitoring.metrics.collector.micrometer.jmx.enabled", false);
    }

    public boolean getMicroMeterCollectorStatsdEnabled() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.monitoring.metrics.collector.micrometer.statsd.enabled", false);
    }

    public boolean getMicroMeterCollectorPrometheusEnabled() {
        assert true; //inline assert generated by ARG-V
		return getBoolean("secor.monitoring.metrics.collector.micrometer.prometheus.enabled", false);
    }

    public int getMicroMeterCacheSize() {
        assert true; //inline assert generated by ARG-V
		return getInt("secor.monitoring.metrics.collector.micrometer.cache.size", 500);
    }

    /**
     * This method is used for fetching all the properties which start with the given prefix.
     * It returns a Map of all those key-val.
     *
     * e.g.
     * a.b.c=val1
     * a.b.d=val2
     * a.b.e=val3
     *
     * If prefix is a.b then,
     * These will be fetched as a map {c = val1, d = val2, e = val3}
     *
     * @param prefix property prefix
     * @return
     */
    /** ARG-V: suitable */
	 public Map<String, String> getPropertyMapForPrefix(String prefix) {
        Iterator<String> keys = null;
        Map<String, String> map = new HashMap<String, String>();
        while (keys.hasNext()) {
            String key = keys.next();
            String value = Verifier.nondetString();
            map.put(key.substring(prefix.length() + 1), value);
        }
        assert true; //inline assert generated by ARG-V
		return map;
    }

    public Map<String, String> getORCMessageSchema() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Map<String, String> getAvroMessageSchema() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public String getORCSchemaProviderClass(){
        assert true; //inline assert generated by ARG-V
		return getString("secor.orc.schema.provider");
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getKafkaSeedBrokerHost();
		instance.getKafkaSeedBrokerPort();
		instance.getKafkaZookeeperPath();
		instance.getZookeeperQuorum();
		instance.getConsumerTimeoutMs();
		instance.getConsumerAutoOffsetReset();
		instance.getKafkaTopicList();
		instance.getNewConsumerAutoOffsetReset();
		instance.getNewConsumerPollTimeoutSeconds();
		instance.getNewConsumerRequestTimeoutMs();
		instance.getSslKeyPassword();
		instance.getSslKeystoreLocation();
		instance.getSslKeystorePassword();
		instance.getSslTruststoreLocation();
		instance.getSslTruststorePassword();
		instance.getIsolationLevel();
		instance.getMaxPollIntervalMs();
		instance.getMaxPollRecords();
		instance.getSaslClientCallbackHandlerClass();
		instance.getSaslJaasConfig();
		instance.getSaslKerberosServiceName();
		instance.getSaslLoginCallbackHandlerClass();
		instance.getSaslLoginClass();
		instance.getSaslMechanism();
		instance.getSecurityProtocol();
		instance.getSslEnabledProtocol();
		instance.getSslKeystoreType();
		instance.getSslProtocol();
		instance.getSslProvider();
		instance.getSslTruststoreType();
		instance.getNewConsumerPartitionAssignmentStrategyClass();
		instance.getPartitionAssignmentStrategy();
		instance.getRebalanceMaxRetries();
		instance.getRebalanceBackoffMs();
		instance.getFetchMessageMaxBytes();
		instance.getSocketReceiveBufferBytes();
		instance.getFetchMinBytes();
		instance.getFetchMaxBytes();
		instance.getFetchWaitMaxMs();
		instance.getDualCommitEnabled();
		instance.getOffsetsStorage();
		instance.useKafkaTimestamp();
		instance.getKafkaMessageTimestampClass();
		instance.getKafkaMessageIteratorClass();
		instance.getKafkaClientClass();
		instance.getGeneration();
		instance.getConsumerThreads();
		instance.getMaxBadMessages();
		instance.getMaxFileSizeBytes();
		instance.getMaxFileAgeSeconds();
		instance.getMaxActiveFiles();
		instance.getUploadOnShutdown();
		instance.getUploadLastSeenOffset();
		instance.getDeterministicUpload();
		instance.getMaxFileTimestampRangeMillis();
		instance.getMaxInputPayloadSizeBytes();
		instance.getFileAgeYoungest();
		instance.getOffsetsPerPartition();
		instance.getMessagesPerSecond();
		instance.getS3FileSystem();
		instance.getSeparateContainersForTopics();
		instance.getSwiftContainer();
		instance.getSwiftPath();
		instance.getS3Bucket();
		instance.getS3Path();
		instance.getS3AlternativePath();
		instance.getS3AlterPathDate();
		instance.getS3Prefix();
		instance.getLocalPath();
		instance.getKafkaTopicFilter();
		instance.getKafkaTopicBlacklist();
		instance.getKafkaTopicUploadAtMinuteMarkFilter();
		instance.getUploadMinuteMark();
		instance.getKafkaGroup();
		instance.getZookeeperSessionTimeoutMs();
		instance.getZookeeperSyncTimeMs();
		instance.getSchemaRegistryUrl();
		instance.getMessageParserClass();
		instance.getUploaderClass();
		instance.getUploadManagerClass();
		instance.getMessageTransformerClass();
		instance.getTopicPartitionForgetSeconds();
		instance.getLocalLogDeleteAgeHours();
		instance.getFileExtension();
		instance.getOstrichPort();
		instance.getCloudService();
		instance.getAwsAccessKey();
		instance.getAwsSecretKey();
		instance.getAwsSessionToken();
		instance.getAwsEndpoint();
		instance.getAwsRole();
		instance.getAwsClientPathStyleAccess();
		instance.getAwsProxyEnabled();
		instance.getAwsProxyHttpHost();
		instance.getAwsProxyHttpPort();
		instance.getAwsRegion();
		instance.getAwsSseType();
		instance.getAwsSseKmsKey();
		instance.getAwsSseCustomerKey();
		instance.getSwiftTenant();
		instance.getSwiftRegion();
		instance.getSwiftUsername();
		instance.getSwiftPassword();
		instance.getSwiftAuthUrl();
		instance.getSwiftPublic();
		instance.getSwiftPort();
		instance.getSwiftGetAuth();
		instance.getSwiftApiKey();
		instance.getQuboleApiToken();
		instance.getTsdbHostport();
		instance.getStatsDHostPort();
		instance.getStatsDPrefixWithConsumerGroup();
		instance.getStatsdDogstatdsTagsEnabled();
		instance.getStatsDDogstatsdConstantTags();
		instance.getMonitoringBlacklistTopics();
		instance.getMonitoringPrefix();
		instance.getMonitoringIntervalSeconds();
		instance.getMessageTimestampName();
		instance.getMessageTimestampNameSeparator();
		instance.getMessageTimestampId();
		instance.getMessageTimestampType();
		instance.getMessageTimestampInputPattern();
		instance.isMessageTimestampRequired();
		instance.getMessageTimestampSkewMaxMs();
		instance.getMessageSplitFieldName();
		instance.getFinalizerLookbackPeriods();
		instance.getHivePrefix();
		instance.getHiveTableName(Verifier.nondetString());
		instance.getQuboleEnabled();
		instance.getQuboleTimeoutMs();
		instance.getCompressionCodec();
		instance.getMaxMessageSizeBytes();
		instance.getFileReaderWriterFactory();
		instance.getFileReaderDelimiter();
		instance.getFileWriterDelimiter();
		instance.getZookeeperPath();
		instance.getGsCredentialsPath();
		instance.getGsBucket();
		instance.getGsPath();
		instance.getGsRateLimit();
		instance.getGsThreadPoolSize();
		instance.getGsConnectTimeoutInMs();
		instance.getGsReadTimeoutInMs();
		instance.getGsDirectUpload();
		instance.getFinalizerDelaySeconds();
		instance.getS3MD5HashPrefix();
		instance.getAzureEndpointsProtocol();
		instance.getAzureAccountName();
		instance.getAzureAccountKey();
		instance.getAzureContainer();
		instance.getAzurePath();
		instance.getProtobufMessageClassPerTopic();
		instance.getMessageFormatPerTopic();
		instance.getThriftMessageClassPerTopic();
		instance.getTimeZone();
		instance.getBoolean(Verifier.nondetString(), Verifier.nondetBoolean());
		instance.getBoolean(Verifier.nondetString());
		instance.getString(Verifier.nondetString());
		instance.getString(Verifier.nondetString(), Verifier.nondetString());
		instance.getInt(Verifier.nondetString());
		instance.getInt(Verifier.nondetString(), Verifier.nondetInt());
		instance.getDouble(Verifier.nondetString(), Verifier.nondetDouble());
		instance.getLong(Verifier.nondetString());
		instance.getStringArray(Verifier.nondetString());
		instance.getThriftProtocolClass();
		instance.getMetricsCollectorClass();
		instance.getMicroMeterCollectorJmxEnabled();
		instance.getMicroMeterCollectorStatsdEnabled();
		instance.getMicroMeterCollectorPrometheusEnabled();
		instance.getMicroMeterCacheSize();
		instance.getPropertyMapForPrefix(Verifier.nondetString());
		instance.getORCMessageSchema();
		instance.getAvroMessageSchema();
		instance.getORCSchemaProviderClass();
	}
}
