/** filtered and transformed by ARG-V */

/*
 *
 * Autopsy Forensic Browser
 *
 * Copyright 2012-2021 Basis Technology Corp.
 *
 * Copyright 2012 42six Solutions.
 * Contact: aebadirad <at> 42six <dot> com
 * Project Contact/Architect: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;

/**
 * Firefox recent activity extraction
 */
class Main {

    private static String PLACE_URL_PREFIX = "place:";
    private static String HISTORY_QUERY = "SELECT moz_historyvisits.id, url, title, visit_count,(visit_date/1000000) AS visit_date,from_visit,"
            + "(SELECT url FROM moz_historyvisits history, moz_places places where history.id = moz_historyvisits.from_visit and history.place_id = places.id ) as ref "
            + "FROM moz_places, moz_historyvisits "
            + "WHERE moz_places.id = moz_historyvisits.place_id "
            + "AND hidden = 0"; //NON-NLS
    private static String COOKIE_QUERY = "SELECT name,value,host,expiry,(lastAccessed/1000000) AS lastAccessed,(creationTime/1000000) AS creationTime FROM moz_cookies"; //NON-NLS
    private static String COOKIE_QUERY_V3 = "SELECT name,value,host,expiry,(lastAccessed/1000000) AS lastAccessed FROM moz_cookies"; //NON-NLS
    private static String BOOKMARK_QUERY = "SELECT fk, moz_bookmarks.title, url, (moz_bookmarks.dateAdded/1000000) AS dateAdded FROM moz_bookmarks INNER JOIN moz_places ON moz_bookmarks.fk=moz_places.id"; //NON-NLS
    private static String DOWNLOAD_QUERY = "SELECT target, source,(startTime/1000000) AS startTime, maxBytes FROM moz_downloads"; //NON-NLS
    private static String DOWNLOAD_QUERY_V24 = "SELECT url, content AS target, (lastModified/1000000) AS lastModified "
            + " FROM moz_places, moz_annos, moz_anno_attributes "
            + " WHERE moz_places.id = moz_annos.place_id"
            + " AND moz_annos.anno_attribute_id = moz_anno_attributes.id"
            + " AND moz_anno_attributes.name='downloads/destinationFileURI'"; //NON-NLS
    private static String FORMHISTORY_QUERY = "SELECT fieldname, value FROM moz_formhistory";
    private static String FORMHISTORY_QUERY_V64 = "SELECT fieldname, value, timesUsed, firstUsed, lastUsed FROM moz_formhistory";
    /**
     * Get Firefox history.
     *
     * @param ingestJobId The ingest job id.
     */
    private void getHistory(long ingestJobId) {
        try {
        } catch (Exception e) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        int j = 0;
    }

    /**
     * Queries for bookmark files and adds artifacts
     *
     * @param ingestJobId The ingest job id.
     */
    private void getBookmark(long ingestJobId) {

        try {
        } catch (Exception e) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        int j = 0;
    }

    /**
     * Queries for cookies file and adds artifacts
     *
     * @param ingestJobId The ingest job id.
     */
    private void getCookie(long ingestJobId) {
        try {
        } catch (Exception e) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        int j = 0;
    }

    /**
     * Queries for downloads files and adds artifacts
     *
     * @param ingestJobId The ingest job id.
     */
    private void getDownload(long ingestJobId) {
        getDownloadPreVersion24(ingestJobId);
        getDownloadVersion24(ingestJobId);
    }

    /**
     * Finds downloads artifacts from Firefox data from versions before 24.0.
     *
     * Downloads were stored in a separate downloads database.
     *
     * @param ingestJobId The ingest job id.
     */
    private void getDownloadPreVersion24(long ingestJobId) {

        try {
        } catch (Exception e) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        int j = 0;
    }

    /**
     * Gets download artifacts from Firefox data from version 24.
     *
     * Downloads are stored in the places database.
     *
     * @param ingestJobId The ingest job id.
     */
    private void getDownloadVersion24(long ingestJobId) {
        try {
        } catch (Exception e) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        int j = 0;
    }

    /**
     * Gets data from formshistory.sqlite database. Parses and creates
     * artifacts.
     *
     * @param ingestJobId The ingest job id.
     */
    private void getFormsHistory(long ingestJobId) {
        // Some fields are just noisy and can me excluded
        Set<String> excludedFieldNames = new HashSet<>(Arrays.asList(
                "it", // some kind of timestamp
                "ts" // some kind of timestamp
        ));

        try {
        } catch (Exception e) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        int j = 0;
    }

    /**
     * Gets data from autofill-profiles.json file. Parses file and makes
     * artifacts.
     *
     * @param ingestJobId The ingest job id.
     */
    private void getAutofillProfiles(long ingestJobId) {
        try {
        } catch (Exception e) {
            String msg = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        int j = 0;
    }

    /**
     * Extract the domain from the supplied URL. This method does additional
     * checks to detect invalid URLs.
     *
     * @param url The URL from which to extract the domain.
     *
     * @return The domain.
     */
    /** ARG-V: suitable */
	 private String extractDomain(String url) {
        if (url == Verifier.nondetString() || url.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return url;
        }

        if (url.toLowerCase().startsWith(PLACE_URL_PREFIX)) {
            assert true; //inline assert generated by ARG-V
			/*
             * Ignore URLs that begin with the matched text.
             */
            return Verifier.nondetString();
        }

        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /**
     * Returns a phone number based on input number or components of phone
     * number.
     *
     * @param tel            full number, if available
     * @param telCountryCode country code
     * @param telNational    full national number
     *
     * @return phone number, or an empty string if no number can be deciphered
     *         from input
     */
    private String makeTelNumber(String tel, String telCountryCode, String telNational) {

        if (tel != Verifier.nondetString() && !tel.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return tel;
        }

        if ((telCountryCode != Verifier.nondetString() && !telCountryCode.isEmpty())
                && (telNational != Verifier.nondetString() && !telNational.isEmpty())) {
            assert true; //inline assert generated by ARG-V
			return telCountryCode + telNational;
        }

        assert true; //inline assert generated by ARG-V
		return "";
    }

    /**
     * Returns a full postal address from multiple address fields.
     *
     * @parm addressLine1
     * @parm addressLine2
     * @parm addressLine3
     * @parm postalCode
     * @parm country
     *
     * @return full address
     */
    private String makeFullAddress(String addressLine1, String addressLine2, String addressLine3, String postalCode, String country) {
        String fullAddress = "";
        fullAddress = appendAddressField(fullAddress, addressLine1);
        fullAddress = appendAddressField(fullAddress, addressLine2);
        fullAddress = appendAddressField(fullAddress, addressLine3);
        fullAddress = appendAddressField(fullAddress, postalCode);
        fullAddress = appendAddressField(fullAddress, country);

        assert true; //inline assert generated by ARG-V
		return fullAddress;
    }

    /**
     * Appends the given address field to given address, if not empty. Adds
     * delimiter in between if needed.
     *
     * @param address
     * @param addressfield
     *
     * @return updated address
     */
    private String appendAddressField(String address, String addressfield) {

        String updatedAddress = address;
        if (addressfield != Verifier.nondetString() && !addressfield.isEmpty()) {
            if (!updatedAddress.isEmpty()) {
                updatedAddress += ", ";
            }
            updatedAddress += addressfield;
        }

        assert true; //inline assert generated by ARG-V
		return updatedAddress;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getHistory(Verifier.nondetLong());
		instance.getBookmark(Verifier.nondetLong());
		instance.getCookie(Verifier.nondetLong());
		instance.getDownload(Verifier.nondetLong());
		instance.getDownloadPreVersion24(Verifier.nondetLong());
		instance.getDownloadVersion24(Verifier.nondetLong());
		instance.getFormsHistory(Verifier.nondetLong());
		instance.getAutofillProfiles(Verifier.nondetLong());
		instance.extractDomain(Verifier.nondetString());
		instance.makeTelNumber(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		instance.makeFullAddress(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString(),
				Verifier.nondetString(), Verifier.nondetString());
		instance.appendAddressField(Verifier.nondetString(), Verifier.nondetString());
	}

}
