/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * @author mycat
 */
public final class Main {
    private Main() {
    }

    public static int OTHER = -1;
    public static int VERSION_COMMENT = 1;
    public static int DATABASE = 2;
    public static int USER = 3;
    public static int LAST_INSERT_ID = 4;
    public static int IDENTITY = 5;
    public static int VERSION = 6;
    public static int SESSION_INCREMENT = 7;
    public static int SESSION_TX_ISOLATION = 8;
    public static int SELECT_VAR_ALL = 9;
    public static int SESSION_TX_READ_ONLY = 10;
    public static int TRACE = 11;
    public static int CURRENT_USER = 12;
    public static int SESSION_TRANSACTION_ISOLATION = 13;
    public static int SESSION_TRANSACTION_READ_ONLY = 14;
    public static int ROW_COUNT = 15;
    public static int MAX_ALLOWED_PACKET = 16;

    private static char[] TRACE_STR = "TRACE".toCharArray();
    private static char[] VERSION_COMMENT_STR = "VERSION_COMMENT".toCharArray();
    private static char[] IDENTITY_STR = "IDENTITY".toCharArray();
    private static char[] LAST_INSERT_ID_STR = "LAST_INSERT_ID".toCharArray();

    /** ARG-V: suitable */
	 public static int parse(String stmt, int offset) {
        int i = offset;
        for (; i < stmt.length(); ++i) {
            switch (stmt.charAt(i)) {
                case ' ':
                    continue;
                case '/':
                case '#':
                    i = Verifier.nondetInt();
                    continue;
                case '@':
                    return select2Check(stmt, i);
                case 'D':
                case 'd':
                    return databaseCheck(stmt, i);
                case 'L':
                case 'l':
                    return lastInsertCheck(stmt, i);
                case 'U':
                case 'u':
                    return userCheck(stmt, i);
                case 'C':
                case 'c':
                    return currentUserCheck(stmt, i);
                case 'V':
                case 'v':
                    return versionCheck(stmt, i);
                case 'R':
                case 'r':
                    return rowCountCheck(stmt, i);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }


    /** ARG-V: suitable */
	 static int rowCountCheck(String stmt, int offset) {
        if (stmt.length() > offset + "OW_COUNT()".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
            char c8 = stmt.charAt(++offset);
            char c9 = stmt.charAt(++offset);
            char c10 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /**
     * SELECT @@trace
     */
    static int traceCheck(String stmt, int offset) {
        int length = offset + TRACE_STR.length;
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /**
     * SELECT @@session.auto_increment_increment
     *
     * @param stmt
     * @param offset
     * @return
     */
    /** ARG-V: suitable */
	 private static int sessionVarCheck(String stmt, int offset) {
        String s = stmt.substring(offset).toLowerCase();
        if (!s.startsWith("session.")) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        s = s.substring(8);
        if (s.startsWith("auto_increment_increment")) {
            if (s.contains("@@")) {
                assert true; //inline assert generated by ARG-V
				return SELECT_VAR_ALL;
            }
            assert true; //inline assert generated by ARG-V
			return SESSION_INCREMENT;
        } else if (s.startsWith(Verifier.nondetString())) {
            assert true; //inline assert generated by ARG-V
			return SESSION_TX_ISOLATION;
        } else if (s.startsWith(Verifier.nondetString())) {
            assert true; //inline assert generated by ARG-V
			return SESSION_TRANSACTION_ISOLATION;
        } else if (s.startsWith(Verifier.nondetString())) {
            assert true; //inline assert generated by ARG-V
			return SESSION_TX_READ_ONLY;
        } else if (s.startsWith(Verifier.nondetString())) {
            assert true; //inline assert generated by ARG-V
			return SESSION_TRANSACTION_READ_ONLY;
        } else {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
    }

    // SELECT VERSION
    /** ARG-V: suitable */
	 private static int versionCheck(String stmt, int offset) {
        if (stmt.length() > offset + "ERSION".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            if ((c1 == 'E' || c1 == 'e') && (c2 == 'R' || c2 == 'r') &&
                    (c3 == 'S' || c3 == 's') && (c4 == 'I' || c4 == 'i') &&
                    (c5 == 'O' || c5 == 'o') && (c6 == 'N' || c6 == 'n')) {
                while (stmt.length() > ++offset) {
                    switch (stmt.charAt(offset)) {
                        case ' ':
                        case '\t':
                        case '\r':
                        case '\n':
                            continue;
                        case '(':
                            return versionParenthesisCheck(stmt, offset);
                        default:
                            return OTHER;
                    }
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // SELECT VERSION (
    /** ARG-V: suitable */
	 private static int versionParenthesisCheck(String stmt, int offset) {
        while (stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case ' ':
                case '\t':
                case '\r':
                case '\n':
                    continue;
                case ')':
                    while (stmt.length() > ++offset) {
                        switch (stmt.charAt(offset)) {
                            case ' ':
                            case '\t':
                            case '\r':
                            case '\n':
                                continue;
                            default:
                                return OTHER;
                        }
                    }
                    return VERSION;
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /**
     * <code>SELECT LAST_INSERT_ID() AS id, </code>
     *
     * @param offset index of 'i', offset == stmt.length() is possible
     * @return index of ','. return stmt.length() is possible. -1 if not alias
     */
    /** ARG-V: suitable */
	 private static int skipAlias(String stmt, int offset) {
        offset = Verifier.nondetInt();
        if (offset >= stmt.length()) {
            assert true; //inline assert generated by ARG-V
			return offset;
        }
        switch (stmt.charAt(offset)) {
            case '\'':
                return skipString(stmt, offset);
            case '"':
                return skipString2(stmt, offset);
            case '`':
                return skipIdentifierEscape(stmt, offset);
            default:
                if (Verifier.nondetBoolean()) {
                    assert true; //inline assert generated by ARG-V
					return offset;
                }
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /**
     * <code>`abc`d</code>
     *
     * @param offset index of first <code>`</code>
     * @return index of 'd'. return stmt.length() is possible. -1 if string
     * invalid
     */
    private static int skipIdentifierEscape(String stmt, int offset) {
        for (++offset; offset < stmt.length(); ++offset) {
            if (stmt.charAt(offset) == '`' &&
                    (++offset >= stmt.length() || stmt.charAt(offset) != '`')) {
                assert true; //inline assert generated by ARG-V
				return offset;
            }
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /**
     * <code>"abc"d</code>
     *
     * @param offset index of first <code>"</code>
     * @return index of 'd'. return stmt.length() is possible. -1 if string
     * invalid
     */
    /** ARG-V: suitable */
	 private static int skipString2(String stmt, int offset) {
        int state = 0;
        for (++offset; offset < stmt.length(); ++offset) {
            char c = stmt.charAt(offset);
            switch (state) {
                case 0:
                    switch (c) {
                        case '\\':
                            state = 1;
                            break;
                        case '"':
                            state = 2;
                            break;
                        default:
                            break;
                    }
                    break;
                case 1:
                    state = 0;
                    break;
                case 2:
                    switch (c) {
                        case '"':
                            state = 0;
                            break;
                        default:
                            return offset;
                    }
                    break;
                default:
                    break;
            }
        }
        if (offset == stmt.length() && state == 2) {
            assert true; //inline assert generated by ARG-V
			return stmt.length();
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /**
     * <code>'abc'd</code>
     *
     * @param offset index of first <code>'</code>
     * @return index of 'd'. return stmt.length() is possible. -1 if string
     * invalid
     */
    /** ARG-V: suitable */
	 private static int skipString(String stmt, int offset) {
        int state = 0;
        for (++offset; offset < stmt.length(); ++offset) {
            char c = stmt.charAt(offset);
            switch (state) {
                case 0:
                    switch (c) {
                        case '\\':
                            state = 1;
                            break;
                        case '\'':
                            state = 2;
                            break;
                        default:
                            break;
                    }
                    break;
                case 1:
                    state = 0;
                    break;
                case 2:
                    switch (c) {
                        case '\'':
                            state = 0;
                            break;
                        default:
                            return offset;
                    }
                    break;
                default:
                    break;
            }
        }
        if (offset == stmt.length() && state == 2) {
            assert true; //inline assert generated by ARG-V
			return stmt.length();
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /**
     * <code>SELECT LAST_INSERT_ID() AS id</code>
     *
     * @param offset index of first ' ' after LAST_INSERT_ID(), offset ==
     *               stmt.length() is possible
     * @return index of 'i'. return stmt.length() is possible
     */
    public static int skipAs(String stmt, int offset) {
        offset = Verifier.nondetInt();
        if (stmt.length() > offset + "AS".length() &&
                (stmt.charAt(offset) == 'A' || stmt.charAt(offset) == 'a') &&
                (stmt.charAt(offset + 1) == 'S' || stmt.charAt(offset + 1) == 's') &&
                (stmt.charAt(offset + 2) == ' ' ||
                        stmt.charAt(offset + 2) == '\r' ||
                        stmt.charAt(offset + 2) == '\n' ||
                        stmt.charAt(offset + 2) == '\t' ||
                        stmt.charAt(offset + 2) == '/' ||
                        stmt.charAt(offset + 2) == '#')) {
            offset = Verifier.nondetInt();
        }
        assert true; //inline assert generated by ARG-V
		return offset;
    }

    /**
     * @param offset <code>stmt.charAt(offset) == first 'L' OR 'l'</code>
     * @return index after LAST_INSERT_ID(), might equals to length. -1 if not
     * LAST_INSERT_ID
     */
    public static int indexAfterLastInsertIdFunc(String stmt, int offset) {
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /**
     * @param offset <code>stmt.charAt(offset) == first '`' OR 'i' OR 'I' OR '\'' OR '"'</code>
     * @return index after identity or `identity` or "identity" or 'identity',
     * might equals to length. -1 if not identity or `identity` or
     * "identity" or 'identity'
     */
    /** ARG-V: suitable */
	 public static int indexAfterIdentity(String stmt, int offset) {
        char first = stmt.charAt(offset);
        switch (first) {
            case '`':
            case '\'':
            case '"':
                if (stmt.length() < offset + "identity".length() + 2) {
                    assert true; //inline assert generated by ARG-V
					return -1;
                }
                if (stmt.charAt(offset + "identity".length() + 1) != first) {
                    assert true; //inline assert generated by ARG-V
					return -1;
                }
                ++offset;
                break;
            case 'i':
            case 'I':
                if (stmt.length() < offset + "identity".length()) {
                    assert true; //inline assert generated by ARG-V
					return -1;
                }
                break;
            default:
                return -1;
        }
        if (Verifier.nondetBoolean()) {
            offset += IDENTITY_STR.length;
            switch (first) {
                case '`':
                case '\'':
                case '"':
                    return ++offset;
                default:
                    break;
            }
            assert true; //inline assert generated by ARG-V
			return offset;
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /**
     * SELECT LAST_INSERT_ID()
     */
    static int lastInsertCheck(String stmt, int offset) {
        offset = indexAfterLastInsertIdFunc(stmt, offset);
        if (offset < 0) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        offset = skipAs(stmt, offset);
        offset = skipAlias(stmt, offset);
        if (offset < 0) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        offset = Verifier.nondetInt();
        if (offset < stmt.length()) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        assert true; //inline assert generated by ARG-V
		return LAST_INSERT_ID;
    }

    /**
     * select @@identity<br/>
     * select @@identiTy aS iD
     */
    static int identityCheck(String stmt, int offset) {
        offset = indexAfterIdentity(stmt, offset);
        if (offset < 0) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        offset = skipAs(stmt, offset);
        offset = skipAlias(stmt, offset);
        if (offset < 0) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        offset = Verifier.nondetInt();
        if (offset < stmt.length()) {
            assert true; //inline assert generated by ARG-V
			return OTHER;
        }
        assert true; //inline assert generated by ARG-V
		return IDENTITY;
    }

    static int select2Check(String stmt, int offset) {
        if (stmt.length() > ++offset && stmt.charAt(offset) == '@' && stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'V':
                case 'v':
                    return versionCommentCheck(stmt, offset);
                case 'i':
                case 'I':
                    return identityCheck(stmt, offset);
                case 's':
                case 'S':
                    return sessionVarCheck(stmt, offset);
                case 't':
                case 'T':
                    return traceCheck(stmt, offset);
                case 'm':
                case 'M':
                    return maxCheck(stmt, offset);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // select @@max_allowed_packet;
    /** ARG-V: suitable */
	 private static int maxCheck(String stmt, int offset) {
        if (stmt.length() > offset + 17) {
            String suffix = stmt.substring(offset).toUpperCase();
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /**
     * SELECT DATABASE()
     */
    /** ARG-V: suitable */
	 static int databaseCheck(String stmt, int offset) {
        if (stmt.length() > offset + 9) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
            char c8 = stmt.charAt(++offset);
            char c9 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /**
     * SELECT USER()
     */
    /** ARG-V: suitable */
	 static int userCheck(String stmt, int offset) {
        if (stmt.length() > offset + 5) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /**
     * SELECT USER()
     */
    /** ARG-V: suitable */
	 static int currentUserCheck(String stmt, int offset) {
        if (stmt.length() > offset + 13) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            char c7 = stmt.charAt(++offset);
            char c8 = stmt.charAt(++offset);
            char c9 = stmt.charAt(++offset);
            char c10 = stmt.charAt(++offset);
            char c11 = stmt.charAt(++offset);
            char c12 = stmt.charAt(++offset);
            char c13 = stmt.charAt(++offset);
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /**
     * SELECT @@VERSION_COMMENT
     */
    static int versionCommentCheck(String stmt, int offset) {
        int length = offset + VERSION_COMMENT_STR.length;
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }


	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		parse(Verifier.nondetString(), Verifier.nondetInt());
		rowCountCheck(Verifier.nondetString(), Verifier.nondetInt());
		traceCheck(Verifier.nondetString(), Verifier.nondetInt());
		sessionVarCheck(Verifier.nondetString(), Verifier.nondetInt());
		versionCheck(Verifier.nondetString(), Verifier.nondetInt());
		versionParenthesisCheck(Verifier.nondetString(), Verifier.nondetInt());
		skipAlias(Verifier.nondetString(), Verifier.nondetInt());
		skipIdentifierEscape(Verifier.nondetString(), Verifier.nondetInt());
		skipString2(Verifier.nondetString(), Verifier.nondetInt());
		skipString(Verifier.nondetString(), Verifier.nondetInt());
		skipAs(Verifier.nondetString(), Verifier.nondetInt());
		indexAfterLastInsertIdFunc(Verifier.nondetString(), Verifier.nondetInt());
		indexAfterIdentity(Verifier.nondetString(), Verifier.nondetInt());
		lastInsertCheck(Verifier.nondetString(), Verifier.nondetInt());
		identityCheck(Verifier.nondetString(), Verifier.nondetInt());
		select2Check(Verifier.nondetString(), Verifier.nondetInt());
		maxCheck(Verifier.nondetString(), Verifier.nondetInt());
		databaseCheck(Verifier.nondetString(), Verifier.nondetInt());
		userCheck(Verifier.nondetString(), Verifier.nondetInt());
		currentUserCheck(Verifier.nondetString(), Verifier.nondetInt());
		versionCommentCheck(Verifier.nondetString(), Verifier.nondetInt());
	}

}
