

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.Arrays;

//输入框表情快捷添加

public class Main {

    private int currentAccount = Verifier.nondetInt();
    private boolean show = Verifier.nondetBoolean(), forceClose = Verifier.nondetBoolean();
    private boolean clear = Verifier.nondetBoolean();

    private void createListView() {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    public boolean isShown() {
        assert true; //inline assert generated by ARG-V
		return show;
    }

    //临时一直关闭
    public void forceClose() {
        show = false;
        forceClose = true;
    }

    private Runnable updateRunnable = null;
    /** ARG-V: suitable */
	 private void update() {
        int selectionStart = Verifier.nondetInt();
        int selectionEnd = Verifier.nondetInt();
        if (selectionStart != selectionEnd) {
            show = false;
            assert true; //inline assert generated by ARG-V
			return;
        }
        CharSequence text = null;
        if (Verifier.nondetBoolean()) {
            if (Verifier.nondetBoolean()) {
                int emojiStart = Verifier.nondetInt();
                int emojiEnd   = Verifier.nondetInt();
                if (selectionStart == emojiEnd) {
                    String emoji = text.toString().substring(emojiStart, emojiEnd);
                    show = true;
                    createListView();
searchAnimated(emoji);
                    assert true; //inline assert generated by ARG-V
					return;
                }
            }
        } else {
            if (Verifier.nondetBoolean() && selectionEnd < 52) {
                show = true;
                createListView();
searchKeywords(text.toString().substring(0, selectionEnd));
                assert true; //inline assert generated by ARG-V
				return;
            }
        }
        show = false;
    }

    private int lastQueryType = Verifier.nondetInt();
    private String lastQuery = Verifier.nondetString();
    private int lastQueryId = Verifier.nondetInt();
    private String[] lastLang = new java.lang.String[] { Verifier.nondetString() };
    private Runnable searchRunnable = null;
    private void searchKeywords(String query) {
        if (query == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        final int id = ++lastQueryId;

        String[] lang = new java.lang.String[] { Verifier.nondetString() };
    }

    private void searchAnimated(String emoji) {
        if (emoji == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        final int id = ++lastQueryId;
    }

    private CharSequence makeEmoji(String emojiSource) {
        CharSequence emoji = null;
        if (emojiSource != Verifier.nondetString() && emojiSource.startsWith("animated_")) {
            try {
                long documentId = Long.parseLong(emojiSource.substring(9));
                emoji = Verifier.nondetString();
            } catch (Exception e) {
                assert true; //inline assert generated by ARG-V
				return null;
            }
        } else {
            emoji = emojiSource;
            emoji = Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return emoji;
    }

    /** ARG-V: suitable */
	 private void onClick(String emojiSource) {
        int start = Verifier.nondetInt(), end = Verifier.nondetInt();
        if (Verifier.nondetBoolean()) {
            start = Verifier.nondetInt();
            end = Verifier.nondetInt();
        } else if (arrowToStart != null && arrowToEnd != null) {
            start = arrowToStart;
            end = arrowToEnd;
        } else {
            assert true; //inline assert generated by ARG-V
			return;
        }
        String fromString = Verifier.nondetString();
        String replacing = fromString.substring(start, end);
        int replacingLength = replacing.length();
        for (int i = end - replacingLength; i >= 0; i -= replacingLength) {
            if (fromString.substring(i, i + replacingLength).equals(replacing)) {
                CharSequence emoji = makeEmoji(emojiSource);
                if (emoji != Verifier.nondetString()) {
                    if (Verifier.nondetBoolean()) {
                        break;
                    }
                } else {
                    break;
                }
            } else {
                break;
            }
        }
        try {
        } catch (Exception e) {}
        show = false;
        forceClose = true;
        lastQueryType = 0;
    }

    private float lastSpanY = Verifier.nondetFloat();
    private Integer arrowToStart = null, arrowToEnd = null;
    private float arrowX = Verifier.nondetFloat();

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.createListView();
		instance.isShown();
		instance.forceClose();
		instance.update();
		instance.searchKeywords(Verifier.nondetString());
		instance.searchAnimated(Verifier.nondetString());
		instance.makeEmoji(Verifier.nondetString());
		instance.onClick(Verifier.nondetString());
	}
}
