/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.regex.Matcher;

/**
 * @author mycat
 */
public final class Main {
    protected Main() {
    }

    /** ARG-V: suitable */
	 public int parse(String stmt) {
        int length = stmt.length();
        //FIX BUG FOR SQL SUCH AS /XXXX/SQL
        int rt = Verifier.nondetInt();
        for (int i = 0; i < length; ++i) {
            switch (stmt.charAt(i)) {
                case ' ':
                case '\t':
                case '\r':
                case '\n':
                    continue;
                case '/':
                    // such as /*!40101 SET character_set_client = @saved_cs_client
                    // */;
                    if (i == 0 && stmt.charAt(1) == '*' && stmt.charAt(2) == '!' && stmt.charAt(length - 2) == '*' &&
                            stmt.charAt(length - 1) == '/') {
                        assert true; //inline assert generated by ARG-V
						return Verifier.nondetInt();
                    }
                    //fall through
                case '#':
                    i = Verifier.nondetInt();
                    if (i + 1 == length) {
                        assert true; //inline assert generated by ARG-V
						return Verifier.nondetInt();
                    }
                    continue;
                case '-':
                    i = Verifier.nondetInt();
                    if (i + 1 == length) {
                        assert true; //inline assert generated by ARG-V
						return Verifier.nondetInt();
                    }
                    continue;
                case 'A':
                case 'a':
                    rt = Verifier.nondetInt();
                    break;
                case 'B':
                case 'b':
                    rt = Verifier.nondetInt();
                    break;
                case 'C':
                case 'c':
                    rt = cCheck(stmt, i);
                    break;
                case 'D':
                case 'd':
                    rt = deleteOrdCheck(stmt, i);
                    break;
                case 'E':
                case 'e':
                    rt = Verifier.nondetInt();
                    break;
                case 'G':
                case 'g':
                    rt = Verifier.nondetInt();
                    break;
                case 'I':
                case 'i':
                    rt = iCheck(stmt, i);
                    break;
                case 'M':
                case 'm':
                    rt = Verifier.nondetInt();
                    break;
                case 'O':
                case 'o':
                    rt = Verifier.nondetInt();
                    break;
                case 'P':
                case 'p':
                    rt = Verifier.nondetInt();
                    break;
                case 'R':
                case 'r':
                    rt = rCheck(stmt, i);
                    break;
                case 'S':
                case 's':
                    rt = sCheck(stmt, i);
                    break;
                case 'T':
                case 't':
                    rt = Verifier.nondetInt();
                    break;
                case 'U':
                case 'u':
                    rt = uCheck(stmt, i);
                    break;
                case 'K':
                case 'k':
                    rt = Verifier.nondetInt();
                    break;
                case 'H':
                case 'h':
                    rt = Verifier.nondetInt();
                    break;
                case 'L':
                case 'l':
                    rt = Verifier.nondetInt();
                    break;
                case 'X':
                case 'x':
                    rt = xCheck(stmt, i);
                    break;
                default:
                    break;
            }
            break;
        }
        assert true; //inline assert generated by ARG-V
		return rt;
    }

    public static int isSetAutocommitSql(String sql) {
        Matcher matcher = null;
        if (matcher.matches()) {
            String value = matcher.group(4);
            if (value != Verifier.nondetString()) {
                value = value.trim();
                if (value.equals("1") || value.toLowerCase().equalsIgnoreCase("on")) {
                    assert true; //inline assert generated by ARG-V
					return 1;
                } else if (value.equals("0") || value.toLowerCase().equalsIgnoreCase("off")) {
                    assert true; //inline assert generated by ARG-V
					return 0;
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /** ARG-V: suitable */
	 private int xCheck(String stmt, int offset) {
        if (stmt.length() > offset + 1) {
            switch (stmt.charAt(++offset)) {
                case 'A':
                case 'a':
                    char charAfterOffset = stmt.charAt(++offset);
                    if (charAfterOffset == ' ' || charAfterOffset == '\t' || charAfterOffset == '\r' || charAfterOffset == '\n')
                        return Verifier.nondetInt();
                    break;
                default:
                    break;
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    // INSERT' ' | INSTALL '  '
    /** ARG-V: suitable */
	 protected int iCheck(String stmt, int offset) {
        int type = Verifier.nondetInt();
        if (stmt.length() > offset + 2) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            if ((c1 == 'N' || c1 == 'n') && (c2 == 'S' || c2 == 's')) {
                switch (c3) {
                    case 'E':
                    case 'e':
                        type = Verifier.nondetInt();
                        break;
                    case 'T':
                    case 't':
                        type = Verifier.nondetInt();
                        break;
                    default:
                        break;
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return type;
    }

    /** ARG-V: suitable */
	 protected int rCheck(String stmt, int offset) {
        if (stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'E':
                case 'e':
                    return reCheck(stmt, offset);
                case 'O':
                case 'o':
                    return rollbackCheck(stmt, offset);
                default:
                    return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    /** ARG-V: suitable */
	 private int reCheck(String stmt, int offset) {
        if (stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'N':
                case 'n':
                    return rename(stmt, offset);
                case 'P':
                case 'p':
                    return Verifier.nondetInt();
                case 'l':
                case 'L':
                    return Verifier.nondetInt();
                case 'v':
                case 'V':
                    return Verifier.nondetInt();
                default:
                    return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    /** ARG-V: suitable */
	 private int rename(String stmt, int offset) {
        if (stmt.length() > offset + 4) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            if ((c1 == 'A' || c1 == 'a') && (c2 == 'M' || c2 == 'm') && (c3 == 'E' || c3 == 'e') &&
                    (c4 == ' ' || c4 == '\t' || c4 == '\r' || c4 == '\n')) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    //UNLOCK | UNINSTALL
    private int unCheck(String stmt, int offset) {
        int type = Verifier.nondetInt();
        switch (stmt.charAt(++offset)) {
            case 'L':
            case 'l':
                type = Verifier.nondetInt();
                break;
            case 'I':
            case 'i':
                type = Verifier.nondetInt();
                break;
            default:
                break;
        }
        assert true; //inline assert generated by ARG-V
		return type;
    }

    // UPDATE' ' | USE' '
    /** ARG-V: suitable */
	 protected int uCheck(String stmt, int offset) {
        if (stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'P':
                case 'p':
                    if (stmt.length() > offset + 5) {
                        char c1 = stmt.charAt(++offset);
                        char c2 = stmt.charAt(++offset);
                        char c3 = stmt.charAt(++offset);
                        char c4 = stmt.charAt(++offset);
                        char c5 = stmt.charAt(++offset);
                        if ((c1 == 'D' || c1 == 'd') &&
                                (c2 == 'A' || c2 == 'a') &&
                                (c3 == 'T' || c3 == 't') &&
                                (c4 == 'E' || c4 == 'e') &&
                                (c5 == ' ' || c5 == '\t' || c5 == '\r' || c5 == '\n')) {
                            assert true; //inline assert generated by ARG-V
							return Verifier.nondetInt();
                        }
                    }
                    break;
                case 'S':
                case 's':
                    if (stmt.length() > offset + 2) {
                        char c1 = stmt.charAt(++offset);
                        char c2 = stmt.charAt(++offset);
                        if ((c1 == 'E' || c1 == 'e') &&
                                (c2 == ' ' || c2 == '\t' || c2 == '\r' || c2 == '\n')) {
                            assert true; //inline assert generated by ARG-V
							return Verifier.nondetInt();
                        }
                    }
                    break;
                case 'N':
                case 'n':
                    return unCheck(stmt, offset);
                default:
                    return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    /** ARG-V: suitable */
	 protected int sCheck(String stmt, int offset) {
        if (stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'A':
                case 'a':
                    return Verifier.nondetInt();
                case 'E':
                case 'e':
                    return Verifier.nondetInt();
                case 'H':
                case 'h':
                    return Verifier.nondetInt();
                case 'T':
                case 't':
                    return startCheck(stmt, offset);
                default:
                    return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    // START' '
    /** ARG-V: suitable */
	 private int startCheck(String stmt, int offset) {
        if (stmt.length() > offset + 4) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            if ((c1 == 'A' || c1 == 'a') && (c2 == 'R' || c2 == 'r') &&
                    (c3 == 'T' || c3 == 't') &&
                    (c4 == ' ' || c4 == '\t' || c4 == '\r' || c4 == '\n')) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    //create table/view/...
    /** ARG-V: suitable */
	 private int createCheck(String stmt, int offset) {
        int len = stmt.length();
        if (len > offset + 6) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            if ((c1 == 'R' || c1 == 'r') && (c2 == 'E' || c2 == 'e') && (c3 == 'A' || c3 == 'a') && (c4 == 'T' || c4 == 't') &&
                    (c5 == 'E' || c5 == 'e')) {
                while (len > ++offset) {
                    if (Verifier.nondetBoolean()) {
                        continue;
                    }
                    char c6 = stmt.charAt(offset);
                    if (c6 == 'd' || c6 == 'D') {
                        assert true; //inline assert generated by ARG-V
						return Verifier.nondetInt();
                    } else if (c6 == 'v' || c6 == 'V') {
                        assert true; //inline assert generated by ARG-V
						return Verifier.nondetInt();
                    } else if (c6 == 'o' || c6 == 'O') {
                        assert true; //inline assert generated by ARG-V
						return Verifier.nondetInt();
                    } else if (c6 == 't' || c6 == 'T') {
                        if (len > ++offset) {
                            char c7 = stmt.charAt(offset);
                            if (c7 == 'e' || c7 == 'E') {
                                assert true; //inline assert generated by ARG-V
								return Verifier.nondetInt();
                            }
                        }
                        assert true; //inline assert generated by ARG-V
						return Verifier.nondetInt();
                    }
                }
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    //drop
    /** ARG-V: suitable */
	 private int dropCheck(String stmt, int offset) {
        if (stmt.length() > offset + 3) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            if ((c1 == 'R' || c1 == 'r') && (c2 == 'O' || c2 == 'o') && (c3 == 'P' || c3 == 'p') &&
                    (c4 == ' ' || c4 == '\t' || c4 == '\r' || c4 == '\n')) {
                while (stmt.length() > ++offset) {
                    switch (stmt.charAt(offset)) {
                        case ' ':
                        case '\t':
                        case '\r':
                        case '\n':
                            continue;
                        case 'V':
                        case 'v':
                            return dropViewCheck(stmt, offset);
                        case 'P':
                        case 'p':
                            return dropPrepareCheck(stmt, offset);
                        case 't':
                        case 'T':
                            return Verifier.nondetInt();
                        default:
                            return Verifier.nondetInt();
                    }
                }
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    private int dropPrepareCheck(String stmt, int offset) {
        if (Verifier.nondetBoolean()) return Verifier.nondetInt();
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    /** ARG-V: suitable */
	 private int dropViewCheck(String stmt, int offset) {
        if (stmt.length() > offset + 3) {
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            if ((c2 == 'i' || c2 == 'I') &&
                    (c3 == 'e' || c3 == 'E') &&
                    (c4 == 'w' || c4 == 'W') &&
                    (c5 == ' ' || c5 == '\t' || c5 == '\r' || c5 == '\n')) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    // delete or drop
    private int deleteOrdCheck(String stmt, int offset) {
        int sqlType = Verifier.nondetInt();
        switch (stmt.charAt((offset + 1))) {
            case 'E':
            case 'e':
                sqlType = Verifier.nondetInt();
                break;
            case 'R':
            case 'r':
                sqlType = dropCheck(stmt, offset);
                break;
            default:
                sqlType = Verifier.nondetInt();
        }
        assert true; //inline assert generated by ARG-V
		return sqlType;
    }

    protected int cCheck(String stmt, int offset) {
        int sqlType = Verifier.nondetInt();
        switch (stmt.charAt((offset + 1))) {
            case 'A':
            case 'a':
                sqlType = Verifier.nondetInt();
                break;
            case 'H':
            case 'h':
                sqlType = Verifier.nondetInt();
                break;
            case 'O':
            case 'o':
                sqlType = Verifier.nondetInt();
                break;
            case 'R':
            case 'r':
                sqlType = createCheck(stmt, offset);
                break;
            default:
                sqlType = Verifier.nondetInt();
        }
        assert true; //inline assert generated by ARG-V
		return sqlType;
    }

    // ROLLBACK
    /** ARG-V: suitable */
	 protected int rollbackCheck(String stmt, int offset) {
        int len = stmt.length();
        if (len > offset + 6) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            if ((c1 == 'L' || c1 == 'l') && (c2 == 'L' || c2 == 'l') &&
                    (c3 == 'B' || c3 == 'b') && (c4 == 'A' || c4 == 'a') &&
                    (c5 == 'C' || c5 == 'c') && (c6 == 'K' || c6 == 'k')) {
                char tmp = Verifier.nondetChar();
                while (len > ++offset) {
                    tmp = stmt.charAt(offset);
                    if (Verifier.nondetBoolean()) {
                        continue;
                    }
                    switch (tmp) {
                        case '/':
                            offset = Verifier.nondetInt();
                            break;
                        case 't':
                        case 'T':
                            return Verifier.nondetInt();
                        case 'w':
                        case 'W':
                            return Verifier.nondetInt();
                        default:
                            break;
                    }
                }
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.parse(Verifier.nondetString());
		isSetAutocommitSql(Verifier.nondetString());
		instance.xCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.iCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.rCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.reCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.rename(Verifier.nondetString(), Verifier.nondetInt());
		instance.unCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.uCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.sCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.startCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.createCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.dropCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.dropPrepareCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.dropViewCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.deleteOrdCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.cCheck(Verifier.nondetString(), Verifier.nondetInt());
		instance.rollbackCheck(Verifier.nondetString(), Verifier.nondetInt());
	}
}
