

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

public class Main {

    public static String PLANTUML_URL_PROPERTY = "plantuml.url";
    public static String PLANTUML_FORMAT_PROPERTY = "plantuml.format";
    public static String PLANTUML_INLINE_PROPERTY = "plantuml.inline";
    private static String TITLE_STRING = "title ";
    private static String NEWLINE = "\n";

    public Main() {
    }

    /** ARG-V: suitable */
	 private String extractTitle(String line) {
        String title = line.substring(TITLE_STRING.length());

        if (title.contains(NEWLINE)) {
            title = title.split(NEWLINE)[0];
        }

        if (title.startsWith("<size:")) {
            title = title.substring(title.indexOf(">") + 1);

            if (title.endsWith("</size>")) {
                title = title.substring(0, title.indexOf("</size>"));
            }
        }

        assert true; //inline assert generated by ARG-V
		return title;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.extractTitle(Verifier.nondetString());
	}

}
