

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public class Main {
    public static String prefsName = "customiuizer_prefs";
    public static boolean moduleActive = false;

    private static String TAG = "LSPosed-Bridge";
    public static boolean silentSync = false;
    public enum SettingsType {
        Preference, Edit
    }

    public enum AppAdapterType {
        Default, Standalone, Mutli, CustomTitles, Activities
    }

    public enum ActionBarType {
        HomeUp, Edit
    }

    public static void log(Throwable t) {
        String logStr = Verifier.nondetString();
    }

    public static void log(String mod, Throwable t) {
        String logStr = Verifier.nondetString();
    }

    public static int getIntOfAppPrefs(String key, int defValue) {
        if (!key.startsWith("pref_key_")) {
            key = "pref_key_" + key;
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    public static String getStringOfAppPrefs(String key, String defValue) {
        if (!key.startsWith("pref_key_")) {
            key = "pref_key_" + key;
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static int getStringAsIntOfAppPrefs(String key, int defValue) {
        if (!key.startsWith("pref_key_")) {
            key = "pref_key_" + key;
        }
        String prefValue = getStringOfAppPrefs(key, null);
        if (prefValue == Verifier.nondetString()) return defValue;
        assert true; //inline assert generated by ARG-V
		return Integer.parseInt(prefValue);
    }

    public static Set<String> getStringSetOfAppPrefs(String key, Set<String> defValue) {
        if (!key.startsWith("pref_key_")) {
            key = "pref_key_" + key;
        }
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public static boolean getBooleanOfAppPrefs(String key) {
        assert true; //inline assert generated by ARG-V
		return getBooleanOfAppPrefs(key, false);
    }
    public static boolean getBooleanOfAppPrefs(String key, boolean defValue) {
        if (!key.startsWith("pref_key_")) {
            key = "pref_key_" + key;
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    /** ARG-V: suitable */
	 public static void addStringPair(Set<String> hayStack, String needle1, String needle2) {
        if (hayStack != null) {
			hayStack.add(needle1 + "|" + needle2);
		}
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{log((java.lang.Throwable)null);log(Verifier.nondetString(),(java.lang.Throwable)null);getIntOfAppPrefs(Verifier.nondetString(),Verifier.nondetInt());getStringOfAppPrefs(Verifier.nondetString(),Verifier.nondetString());getStringAsIntOfAppPrefs(Verifier.nondetString(),Verifier.nondetInt());getStringSetOfAppPrefs(Verifier.nondetString(),(java.util.Set<java.lang.String>)null);getBooleanOfAppPrefs(Verifier.nondetString());getBooleanOfAppPrefs(Verifier.nondetString(),Verifier.nondetBoolean());addStringPair((java.util.Set<java.lang.String>)null,Verifier.nondetString(),Verifier.nondetString());}
}
