

/** filtered and transformed by ARG-V */

/**
 * OpenKM, Open Document Management System (http://www.openkm.com)
 * Copyright (c) Paco Avila & Josep Llort
 * <p>
 * No bytes were intentionally harmed during the development of this application.
 * <p>
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;

/**
 * Folder tree
 *
 * @author jllort
 *
 */
public class Main {

	// Definitions of folder actions
	public static int ACTION_NONE = -1;
	public static int ACTION_CREATE = 0;
	public static int ACTION_RENAME = 1;
	public static int ACTION_SECURITY_REFRESH = 2;

	private boolean panelSelected = true; // Indicates if panel is selected

	ArrayList<String> tmpAllPathFolder = new ArrayList<>(); // Store node path elements
	public int folderAction = ACTION_NONE; // To control rename and create

	private String tmpRenameHtmlFolder = Verifier.nondetString();
	private boolean refreshFileBrowser = false;
	private boolean setTabFolderAfterRefresh = false;
	private boolean treeItemChanged = false;
	private boolean treeItemHasBeenClosed = false;
	private boolean autoOpenFolder = false;
	private boolean openingFldPath = false;
	private boolean flagFileBrowserFinished = true;

	/**
	 * Directory Tree
	 */
	public Main() {
	}

	/**
	 * Deletes a folder, the folder deleted is the actual item and refresh the
	 * parent
	 */
	public void delete() {
		String path = Verifier.nondetString();
	}

	/**
	 * Deletes folder on trash after is moved
	 */
	public void deleteMovedOrRestored() {
		refresh(true);
	}

	/**
	 * Remove folder from tree after deleted from repository ( normaly deleted
	 * on file browser )
	 *
	 * @param path
	 *            The folder
	 */
	public void removeDeleted(String path) {
		boolean found = false;
		int i = 0;
	}

	/**
	 * Opens all path since folder path
	 *
	 * @param fldId
	 *            The folder path
	 * @param docPath
	 *            The document path
	 */
	/** ARG-V: suitable */
	 public void openAllPathFolder(String fldId, String docPath) {
		flagFileBrowserFinished = false;
		openingFldPath = true;
		refreshFileBrowser = true;
		String rootPath = Verifier.nondetString();
		String actualPath = fldId;
		// getChilds method needs it for last folder)

		if (!(refreshFileBrowser && docPath != Verifier.nondetString() && !docPath.equals(""))) {
			if (!rootPath.equals(actualPath)) {
				setTabFolderAfterRefresh = true;
			}
		}

		while (actualPath.length() > 0) {
			tmpAllPathFolder.add(actualPath);
			actualPath = actualPath.substring(0, actualPath.lastIndexOf("/"));
		}
		// The last path value is root path, is added on tmpPath

		if (!tmpAllPathFolder.isEmpty()) {
			int index = tmpAllPathFolder.size() - 1;
			String tmpPath = tmpAllPathFolder.get(index);
			tmpAllPathFolder.remove(index);
			if (index > 0) {
				setActiveNode(tmpPath, true, false);
			} else {
				setActiveNode(tmpPath, true, refreshFileBrowser); // Never should go into
			}
		} else {
			openingFldPath = false;
		}
	}

	/**
	 * canDrag
	 */
	public boolean canDrag() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
	}

	/**
	 * Refresh the tree node
	 */
	public void refresh(final boolean reset) {
		flagFileBrowserFinished = false;
		final String path = Verifier.nondetString();
	}

	/**
	 * Set a new tree node
	 */
	public void setActiveNode(String path, boolean refreshRootNode, boolean refreshFileBrowser) {
		setSelectedPanel(true); // Select this panel
	}

	/**
	 * Add temporary folder on creation
	 */
	public void addTmpFolderCreate() {
		if (folderAction == ACTION_NONE) {
			folderAction = ACTION_CREATE;
		}
	}

	/**
	 * Remove temporary folder on creation Only executed when user closes popup name and
	 */
	public void removeTmpFolderCreate() {
		folderAction = ACTION_NONE;
	}

	/**
	 * Gets the actual path of the selected directory tree
	 *
	 * @return The actual path of selected directory
	 */
	public String getActualPath() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	/**
	 * Shows input text to rename selected folder
	 */
	public void rename() {
		if (folderAction == ACTION_NONE) {
			// while renaming
			folderAction = ACTION_RENAME;
		}
	}

	/**
	 * Cancels the renaming folder
	 */
	public void cancelRename() {
		folderAction = ACTION_NONE;
	}

	/**
	 * Return true if actualItem selected is root node, other case false
	 *
	 * @return value true or false on actualItem to root node comparation
	 */
	public boolean isActualItemRoot() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
	}

	/**
	 * Indicates if panel is selected
	 *
	 * @return The value of panel ( selected )
	 */
	public boolean isPanelSelected() {
		assert true; //inline assert generated by ARG-V
		return panelSelected;
	}

	/**
	 * Sets the selected panel value
	 *
	 * @param selected
	 *            The selected panel value
	 */
	public void setSelectedPanel(boolean selected) {
		panelSelected = selected;
	}

	/**
	 * Used only on changing stack
	 */
	public void forceSetSelectedPanel() {
		panelSelected = false;
		setSelectedPanel(true);
	}

	/**
	 * Indicates if is folder creating
	 *
	 * @return The boolean value if is folder creating
	 */
	public boolean isFolderCreating() {
		assert true; //inline assert generated by ARG-V
		return (folderAction == ACTION_CREATE);
	}

	/**
	 * Indicates if is folder renaming
	 *
	 * @return The boolean value if is folder renaming
	 */
	public boolean isFolderRenaming() {
		assert true; //inline assert generated by ARG-V
		return (folderAction == ACTION_RENAME);
	}

	/**
	 * Gets the actual folder action
	 *
	 * @return The boolean folder action
	 */
	public int getFolderAction() {
		assert true; //inline assert generated by ARG-V
		return folderAction;
	}

	/**
	 * Refresh for security changes on actual tree node selected ( icon color )
	 * only refresh the actual
	 */
	public void securityRefresh() {
		folderAction = ACTION_SECURITY_REFRESH; // To make tab properties
	}

	/**
	 * Purge folder on file browser ( only trash mode )
	 */
	public void purge() {
		String path = Verifier.nondetString();
	}

	public void fileBrowserRefreshDone() {
		flagFileBrowserFinished = true;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.delete();
		instance.deleteMovedOrRestored();
		instance.removeDeleted(Verifier.nondetString());
		instance.openAllPathFolder(Verifier.nondetString(), Verifier.nondetString());
		instance.canDrag();
		instance.refresh(Verifier.nondetBoolean());
		instance.setActiveNode(Verifier.nondetString(), Verifier.nondetBoolean(), Verifier.nondetBoolean());
		instance.addTmpFolderCreate();
		instance.removeTmpFolderCreate();
		instance.getActualPath();
		instance.rename();
		instance.cancelRename();
		instance.isActualItemRoot();
		instance.isPanelSelected();
		instance.setSelectedPanel(Verifier.nondetBoolean());
		instance.forceSetSelectedPanel();
		instance.isFolderCreating();
		instance.isFolderRenaming();
		instance.getFolderAction();
		instance.securityRefresh();
		instance.purge();
		instance.fileBrowserRefreshDone();
	}
}
