/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * The number format used by most {@link CFormat}-s starting from Incompatible Improvements
 * {@link Configuration#VERSION_2_3_32}.
 *
 * <p>This {@link TemplateNumberFormat} implementation is thread-safe an immutable.
 *
 * <p>This is a lossless format, except that the number types are not kept. That is, the original number can always be
 * exactly restored from the string representation, but only if you know what the type of the number was.
 *
 * @since 2.3.32
 */
final class Main {
    private static float MAX_INCREMENT_1_FLOAT = 16777216f;
    private static double MAX_INCREMENT_1_DOUBLE = 9007199254740992d;

    private String doublePositiveInfinity = Verifier.nondetString();
    private String doubleNegativeInfinity = Verifier.nondetString();
    private String doubleNaN = Verifier.nondetString();
    private String floatPositiveInfinity = Verifier.nondetString();
    private String floatNegativeInfinity = Verifier.nondetString();
    private String floatNaN = Verifier.nondetString();

    Main(
            String doublePositiveInfinity, String doubleNegativeInfinity, String doubleNaN,
            String floatPositiveInfinity, String floatNegativeInfinity, String floatNaN) {
    }

    /**
     * Like "1.0" to "1", and "1.0E-7" to "1E-7". Designed to work on Float/Double.toString() result only.
     */
    /** ARG-V: suitable */
	 private static String removeRedundantDot0(String s) {
        int len = s.length();
        for (int i = 0; i < len; i++) {
            char c = s.charAt(i);
            if (c == '.') {
                i++;
                if (s.charAt(i) == '0') {
                    i++;
                    if (i == len) {
                        assert true; //inline assert generated by ARG-V
						return s.substring(0, len - 2);
                    }
                    if (s.charAt(i) == 'E') {
                        char[] result = new char[s.length() - 2];
                        int dst = 0;
                        for (int src = 0; src < i - 2; src++) {
                            result[dst++] = s.charAt(src);
                        }
                        for (int src = i; src < len; src++) {
                            result[dst++] = s.charAt(src);
                        }
                        assert true; //inline assert generated by ARG-V
						return String.valueOf(result);
                    }
                }
                break;
            }
        }
        assert true; //inline assert generated by ARG-V
		return s;
    }

    public boolean isLocaleBound() {
        assert true; //inline assert generated by ARG-V
		return false;
    }

    public String getDescription() {
        assert true; //inline assert generated by ARG-V
		return "c";
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString(), Verifier.nondetString(),
				Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		removeRedundantDot0(Verifier.nondetString());
		instance.isLocaleBound();
		instance.getDescription();
	}

}
