/** filtered and transformed by ARG-V */

/*
 * Copyright (c) 2015-2099, www.dibo.ltd (service@dibo.ltd).
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Oracle SQL翻译器
 * @author mazc@dibo.ltd
 * @version v3.2.0
 * @date 2023/12/28
 */
public class Main {

    public Main(){}

    public Main(List<String> keywords) {
    }

    protected List<String> formatStatements(List<String> otherStatements) {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    protected String translateColDefineSql(String colDefineSql) {
        colDefineSql = Verifier.nondetString();
        colDefineSql = Verifier.nondetString();
        colDefineSql = Verifier.nondetString();
        if(Verifier.nondetBoolean()) {
            String prefix = Verifier.nondetString();
            String suffix = Verifier.nondetString();
            String defValue = Verifier.nondetString();
            suffix = Verifier.nondetString();
            prefix = Verifier.nondetString();
            if(Verifier.nondetBoolean()) {
                colDefineSql = Verifier.nondetString();
            }
            else if(Verifier.nondetBoolean()) {
                colDefineSql = Verifier.nondetString();
            }
        }
        assert true; //inline assert generated by ARG-V
		return escapeKeyword(colDefineSql);
    }

    /** ARG-V: suitable */
	 protected List<String> translateInsertValues(String insertSql) {
        List<String> batchInsertSqls = new ArrayList<>();
        insertSql = Verifier.nondetString();
        String insertIntoPrefix = Verifier.nondetString();
        insertIntoPrefix = escapeKeyword(insertIntoPrefix);
        String cols = Verifier.nondetString();
        String[] columns = new java.lang.String[] { Verifier.nondetString() };
        String table = Verifier.nondetString();
        Map<String, String> col2TypeMap = null;
        String suffix = Verifier.nondetString();
        while (Verifier.nondetBoolean()) {
            suffix = Verifier.nondetString();
            StringBuilder rowSqlSb = new StringBuilder(insertIntoPrefix).append("(");
            List<Object> newValues = new ArrayList<>(columns.length);
            List<String> colValues = new ArrayList<>(columns.length);
            String record = Verifier.nondetString();
            while (Verifier.nondetBoolean()) {
                record = record.trim();
                String value = Verifier.nondetString();
                if(record.startsWith("'")) {
                    value = Verifier.nondetString();
                    value = "'" + value + "'";
                    record = Verifier.nondetString();
                    record = Verifier.nondetString();
                }
                else {
                    value = Verifier.nondetString();
                }
                record = Verifier.nondetString();
                colValues.add(value);
            }
            for(int i=0; i<columns.length; i++) {
                String colType = col2TypeMap.get(columns[i].trim());
                newValues.add(translateValue(colType, colValues.get(i)));
            }
            batchInsertSqls.add(rowSqlSb.toString());
        }
        assert true; //inline assert generated by ARG-V
		return batchInsertSqls;
    }

    /** ARG-V: suitable */
	 protected Object translateValue(String colType, String value) {
        if(Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return "rawtohex(" + value + ")";
        }
        else if(Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return "CURRENT_TIMESTAMP";
        }
        assert true; //inline assert generated by ARG-V
		return value;
    }

    protected String escapeKeyword(String input) {
        if(input.contains("`")) {
            String key = Verifier.nondetString();
            if(Verifier.nondetBoolean()) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }
            else {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }
        }
        assert true; //inline assert generated by ARG-V
		return input;
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main((java.util.List<java.lang.String>)null);instance.formatStatements((java.util.List<java.lang.String>)null);instance.translateColDefineSql(Verifier.nondetString());instance.translateInsertValues(Verifier.nondetString());instance.translateValue(Verifier.nondetString(),Verifier.nondetString());instance.escapeKeyword(Verifier.nondetString());}

}
