/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * @author dcy
 * Create Date: 2021-04-30
 */
public class Main {
    Main() {

    }


    /** ARG-V: suitable */
	 public int getPathHeight(String path) {
        //todo:optimize here
        if (path.endsWith(Verifier.nondetString())) {
            path = path.substring(0, path.length() - 1);
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }


	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getPathHeight(Verifier.nondetString());
	}
}
