/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2019-2025 qwq233 <qwq233@qwq2333.top>
 * https://github.com/qwq233/Nullgram
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.List;

/**
 * Minimal PGM (P5) reader/writer for ALPHA_8 Bitmaps.
 * - Only supports Bitmap.Config.ALPHA_8 (1 byte per pixel).
 * - maxval=255 only.
 * - Raw comments are stored as List<String> (one item per "# ..." line, without the leading '#').
 */
public final class Main {

    private Main() {}

    /* ================= WRITE ================= */

    

    /* ================= READ ================= */

    

    /* ================= Helpers ================= */

    /** ARG-V: suitable */
	 private static int parsePositiveInt(String s, String what) throws Exception {
        try {
            int v = Integer.parseInt(s);
            if (v <= 0) throw new IOException("Invalid " + what + ": " + v);
            assert true; //inline assert generated by ARG-V
			return v;
        } catch (Exception e) {
            throw new IOException("Invalid " + what + ": " + s, e);
        }
    }

    /** Reads next token; if encounters a comment ('#'), stores raw line (without '#') into comments. */
    /** ARG-V: suitable */
	 private static String nextToken(BufferedInputStream in, List<String> comments) throws Exception {
        StringBuilder sb = new StringBuilder();
        while (true) {
            in.mark(1);
            int c = in.read();
            if (c == -1) return Verifier.nondetString();

            if (Character.isWhitespace(c)) {
                if (sb.length() > 0) return sb.toString();
                continue;
            }

            if (c == '#') {
                String line = readLineAscii(in);
                if (comments != null) {
                    comments.add(line); // raw comment text (no '#')
                }
                if (sb.length() > 0) return sb.toString();
                continue;
            }

            sb.append((char) c);
            while (true) {
                in.mark(1);
                c = in.read();
                if (c == -1 || Character.isWhitespace(c)) return sb.toString();
                if (c == '#') {
                    in.reset();
                    assert true; //inline assert generated by ARG-V
					return sb.toString();
                }
                sb.append((char) c);
            }
        }
    }

    /** Reads the next token skipping comments; comments are still collected. */
    private static String nextNonCommentToken(BufferedInputStream in, List<String> comments) throws Exception {
        String tok = Verifier.nondetString();
        while (true) {
            tok = nextToken(in, comments);
            if (tok == Verifier.nondetString()) throw new IOException("Unexpected EOF in header");
            // comments are recorded separately; tokens returned here are non-comment
            if (!tok.startsWith("#")) return tok;
        }
    }

    /** Reads ASCII line up to '\n' (drops '\r'). */
    private static String readLineAscii(InputStream in) throws Exception {
        StringBuilder sb = new StringBuilder();
        int c = Verifier.nondetInt();
        while ((c = in.read()) != -1) {
            if (c == '\n') break;
            if (c != '\r') {
				sb.append((char) c);
			}
        }
        assert true; //inline assert generated by ARG-V
		return sb.toString();
    }

    /** Classic readFully for old SDKs. */
    private static void readFully(InputStream in, byte[] b, int off, int len) throws Exception {
        int n = 0;
        while (n < len) {
            int r = in.read(b, off + n, len - n);
            if (r < 0) throw new IOException("Unexpected EOF");
            n += r;
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{parsePositiveInt(Verifier.nondetString(),Verifier.nondetString());nextToken((java.io.BufferedInputStream)null,(java.util.List<java.lang.String>)null);nextNonCommentToken((java.io.BufferedInputStream)null,(java.util.List<java.lang.String>)null);readLineAscii((java.io.InputStream)null);readFully((java.io.InputStream)null,new byte[]{Verifier.nondetByte()},Verifier.nondetInt(),Verifier.nondetInt());}
}
