/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * @author mycat
 */
public final class Main {
    private Main() {
    }

    public static int OTHER = -1;
    public static int SLOW_QUERY_LOG = 1;
    public static int ALERT = 2;
    public static int CUSTOM_MYSQL_HA = 3;
    public static int CAP_CLIENT_FOUND_ROWS = 4;
    public static int GENERAL_LOG = 5;
    public static int STATISTIC = 6;
    public static int LOAD_DATA_BATCH = 7;
    public static int SQLDUMP_SQL = 8;
    public static int MEMORY_BUFFER_MONITOR = 9;
    public static int STATISTIC_ANALYSIS = 10;


    /** ARG-V: suitable */
	 public static int parse(String stmt, int offset) {
        int i = offset;
        for (; i < stmt.length(); i++) {
            switch (stmt.charAt(i)) {
                case ' ':
                    continue;
                case '/':
                case '#':
                    i = Verifier.nondetInt();
                    continue;
                case '@':
                    return atCheck(stmt, i);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    private static int atCheck(String stmt, int offset) {
        if (stmt.length() > ++offset && stmt.charAt(offset) == '@' && stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'A':
                case 'a':
                    return aCheck(stmt, offset);
                case 'S':
                case 's':
                    return sCheck(stmt, offset);
                case 'C':
                case 'c':
                    return cCheck(stmt, offset);
                case 'G':
                case 'g':
                    return gCheck(stmt, offset);
                case 'L':
                case 'l':
                    return lCheck(stmt, offset);
                case 'm':
                case 'M':
                    return mCheck(stmt, offset);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // enable/disable @@ALERT
    /** ARG-V: suitable */
	 private static int aCheck(String stmt, int offset) {
        if (stmt.length() > offset + 4) {
            String prefix = stmt.substring(offset).toUpperCase();
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // enable/disable  @@memory_buffer_monitor
    private static int mCheck(String stmt, int offset) {
        final String keyword = "MEMORY_BUFFER_MONITOR";
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // enable/disable  @@load_data_batch;
    /** ARG-V: suitable */
	 private static int lCheck(String stmt, int offset) {
        if (stmt.length() > offset + 14) {
            String prefix = stmt.substring(offset).toUpperCase();
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int sCheck(String stmt, int offset) {
        if (stmt.length() > ++offset) {
            switch (stmt.charAt(offset)) {
                case 'L':
                case 'l':
                    return slCheck(stmt, offset);
                case 'T':
                case 't':
                    return stCheck(stmt, offset);
                case 'Q':
                case 'q':
                    return sqCheck(stmt, offset);
                default:
                    return OTHER;
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // enable/disable @@SLOW_QUERY_LOG
    /** ARG-V: suitable */
	 private static int slCheck(String stmt, int offset) {
        if (stmt.length() > offset + 12) {
            String prefix = stmt.substring(offset).toUpperCase();
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // enable/disable @@STATISTIC
    /** ARG-V: suitable */
	 private static int stCheck(String stmt, int offset) {
        if (stmt.length() > offset + 15) {
            String prefix = stmt.substring(offset).toUpperCase();
        } else if (stmt.length() > offset + 7) {

            String prefix = stmt.substring(offset).toUpperCase();

        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // enable/disable @@SQLDUMP_SQL
    /** ARG-V: suitable */
	 private static int sqCheck(String stmt, int offset) {
        if (stmt.length() > offset + 9) {
            String prefix = stmt.substring(offset).toUpperCase();
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    /** ARG-V: suitable */
	 private static int gCheck(String stmt, int offset) {
        if (stmt.length() > offset + 10) {
            String prefix = stmt.substring(offset).toUpperCase();
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }


    /** ARG-V: suitable */
	 private static int cCheck(String stmt, int offset) {
        if (stmt.length() > offset + 20) {
            // enable/disable @@cap_client_found_rows
            String prefix = stmt.substring(offset).toUpperCase();
        } else if (stmt.length() > offset + 14) {
            // enable/disable @@custom_mysql_ha
            String prefix = stmt.substring(offset).toUpperCase();
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		parse(Verifier.nondetString(), Verifier.nondetInt());
		atCheck(Verifier.nondetString(), Verifier.nondetInt());
		aCheck(Verifier.nondetString(), Verifier.nondetInt());
		mCheck(Verifier.nondetString(), Verifier.nondetInt());
		lCheck(Verifier.nondetString(), Verifier.nondetInt());
		sCheck(Verifier.nondetString(), Verifier.nondetInt());
		slCheck(Verifier.nondetString(), Verifier.nondetInt());
		stCheck(Verifier.nondetString(), Verifier.nondetInt());
		sqCheck(Verifier.nondetString(), Verifier.nondetInt());
		gCheck(Verifier.nondetString(), Verifier.nondetInt());
		cCheck(Verifier.nondetString(), Verifier.nondetInt());
	}
}
