

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
	public int width = Verifier.nondetInt();
	public int height = Verifier.nondetInt();
	public int[] pixels = new int[] { Verifier.nondetInt() };
	
	public Main(int width, int height) {
	}
	
	/** ARG-V: suitable */
	 public void drawText(String text, int xOffset, int yOffset, int color)
	{
		if(text == Verifier.nondetString()) return;
		for(int i = 0; i < text.length(); i++)
		{
			if(text.charAt(i) == '\n') {
				yOffset += 8;
			} else drawChar(text.charAt(i), xOffset + i * 8, yOffset, color);
		}
	}
	
	public void drawChar(char toDraw, int xOffset, int yOffset, int color)
	{
		int charPos = Verifier.nondetInt();
		if(charPos == -1) return;
		
		int drawY = (charPos / 16) * 8;
		int drawX = (charPos % 16) * 8;
		
		for(int x = 0; x < 8; x++)
		{
			for(int y = 0; y < 8; y++)
			{
				int fontpix = Verifier.nondetInt();
			}
		}
	}
	
	public void mult(int color)
	{
		for(int i = 0; i < width * height; i++)
		{
			int r = (pixels[i] >> 16) & 0xff;
			int g = (pixels[i] >> 8) & 0xff;
			int b = pixels[i] & 0xff;
			
			int mr = (color >> 16) & 0xff;
			int mg = (color >> 8) & 0xff;
			int mb = color & 0xff;
			
			r += mr;
			g += mg;
			b += mb;
			
			if(r > 255) {
				r = 255;
			}
			if(g > 255) {
				g = 255;
			}
			if(b > 255) {
				b = 255;
			}
		}
	}
	
	public void rotateClockwise() {
		int[] copyPixels = pixels.clone();
	}
	
	public void rotateCounterClockwise() {
		int[] copyPixels = pixels.clone();
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetInt(), Verifier.nondetInt());
		instance.drawText(Verifier.nondetString(), Verifier.nondetInt(), Verifier.nondetInt(), Verifier.nondetInt());
		instance.drawChar(Verifier.nondetChar(), Verifier.nondetInt(), Verifier.nondetInt(), Verifier.nondetInt());
		instance.mult(Verifier.nondetInt());
		instance.rotateClockwise();
		instance.rotateCounterClockwise();
	}
}
