/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * based on code by MyCATCopyrightHolder Copyright (c) 2013, OpenCloudDB/MyCAT.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * @author songwie
 */
public final class Main {
    private Main() {
    }

    public static int OTHER = -1;

    // SHOW @@HEARTBEAT
    /** ARG-V: suitable */
	 static int show2HeaCheck(String stmt, int offset) {
        if (stmt.length() > offset + "RTBEAT".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            if ((c1 == 'R' || c1 == 'r') && (c2 == 'T' || c2 == 't') && (c3 == 'B' || c3 == 'b') &&
                    (c4 == 'E' || c4 == 'e') && (c5 == 'A' || c5 == 'a') && (c6 == 'T' || c6 == 't')) {
                if (stmt.length() > offset + ".DETAIL".length()) {
                    char c7 = stmt.charAt(++offset);
                    if (c7 == '.') {
                        assert true; //inline assert generated by ARG-V
						return show2HeaDetailCheck(stmt, offset);
                    }
                }
                if (Verifier.nondetBoolean()) {
                    assert true; //inline assert generated by ARG-V
					return OTHER;
                }
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

    // SHOW @@HEARTBEAT.DETAIL
    /** ARG-V: suitable */
	 static int show2HeaDetailCheck(String stmt, int offset) {
        if (stmt.length() > offset + "DETAIL".length()) {
            char c1 = stmt.charAt(++offset);
            char c2 = stmt.charAt(++offset);
            char c3 = stmt.charAt(++offset);
            char c4 = stmt.charAt(++offset);
            char c5 = stmt.charAt(++offset);
            char c6 = stmt.charAt(++offset);
            if ((c1 == 'D' || c1 == 'd') && (c2 == 'E' || c2 == 'e') && (c3 == 'T' || c3 == 't') &&
                    (c4 == 'A' || c4 == 'a') && (c5 == 'I' || c5 == 'i') && (c6 == 'L' || c6 == 'l')) {
                if (stmt.length() > ++offset && stmt.charAt(offset) != ' ') {
                    assert true; //inline assert generated by ARG-V
					return OTHER;
                }
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetInt();
            }
        }
        assert true; //inline assert generated by ARG-V
		return OTHER;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		show2HeaCheck(Verifier.nondetString(), Verifier.nondetInt());
		show2HeaDetailCheck(Verifier.nondetString(), Verifier.nondetInt());
	}
}
