/** filtered and transformed by ARG-V */

/*
 * $Id: PdfChunk.java 4092 2009-11-11 17:58:16Z psoares33 $
 *
 * Copyright 1999, 2000, 2001, 2002 Bruno Lowagie
 *
 * The contents of this file are subject to the Mozilla Public License Version 1.1
 * (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the License.
 *
 * The Original Code is 'iText, a free JAVA-PDF library'.
 *
 * The Initial Developer of the Original Code is Bruno Lowagie. Portions created by
 * the Initial Developer are Copyright (C) 1999, 2000, 2001, 2002 by Bruno Lowagie.
 * All Rights Reserved.
 * Co-Developer of the code is Paulo Soares. Portions created by the Co-Developer
 * are Copyright (C) 2000, 2001, 2002 by Paulo Soares. All Rights Reserved.
 *
 * Contributor(s): all the names of the contributors are added in the source code
 * where applicable.
 *
 * Alternatively, the contents of this file may be used under the terms of the
 * LGPL license (the "GNU LIBRARY GENERAL PUBLIC LICENSE"), in which case the
 * provisions of LGPL are applicable instead of those above.  If you wish to
 * allow use of your version of this file only under the terms of the LGPL
 * License and not to allow others to use your version of this file under
 * the MPL, indicate your decision by deleting the provisions above and
 * replace them with the notice and other provisions required by the LGPL.
 * If you do not delete the provisions above, a recipient may use your version
 * of this file under either the MPL or the GNU LIBRARY GENERAL PUBLIC LICENSE.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the MPL as stated above or under the terms of the GNU
 * Library General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Library general Public License for more
 * details.
 *
 * If you didn't download this code from the following link, you should check if
 * you aren't using an obsolete version:
 * https://github.com/LibrePDF/OpenPDF
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.awt.Color;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * A <CODE>PdfChunk</CODE> is the PDF translation of a <CODE>Chunk</CODE>.
 * <p>
 * A <CODE>PdfChunk</CODE> is a <CODE>PdfString</CODE> in a certain
 * <CODE>PdfFont</CODE> and <CODE>Color</CODE>.
 *
 * @see PdfString
 * @see org.openpdf.text.Chunk
 * @see org.openpdf.text.Font
 */

public class Main {

    private static char[] singleSpace = {' '};
    private static float ITALIC_ANGLE = 0.21256f;
    /**
     * The allowed attributes in variable <CODE>attributes</CODE>.
     */
    private static Map<String, Object> keysAttributes = new HashMap<>();

    /**
     * The allowed attributes in variable <CODE>noStroke</CODE>.
     */
    private static Map<String, Object> keysNoStroke = new HashMap<>();

    

    // membervariables

    /**
     * The value of this object.
     */
    protected String value = Verifier.nondetString();

    /**
     * The encoding.
     */
    protected String encoding = Verifier.nondetString();


    /**
     * Metric attributes.
     * <p>
     * This attributes require the measurement of characters widths when rendering such as underline.
     */
    protected Map<String, Object> attributes = new HashMap<>();

    /**
     * Non metric attributes.
     * <p>
     * This attributes do not require the measurement of characters widths when rendering such as Color.
     */
    protected Map<String, Object> noStroke = new HashMap<>();

    /**
     * <CODE>true</CODE> if the chunk split was cause by a newline.
     */
    protected boolean newlineSplit = Verifier.nondetBoolean();

    /**
     * The offset in the x direction for the image
     */
    protected float offsetX = Verifier.nondetFloat();

    /**
     * The offset in the y direction for the image
     */
    protected float offsetY = Verifier.nondetFloat();

    /**
     * Indicates if the height and offset of the Image has to be taken into account
     */
    protected boolean changeLeading = false;

    // constructors

    

    // methods

    public static boolean noPrint(int c) {
        assert true; //inline assert generated by ARG-V
		return ((c >= 0x200b && c <= 0x200f) || (c >= 0x202a && c <= 0x202e));
    }

    /**
     * Gets the Unicode equivalent to a CID. The (nonexistent) CID <code>FF00</code> is translated as '\n'. It has only
     * meaning with CJK fonts with Identity encoding.
     *
     * @param c the CID code
     * @return the Unicode equivalent
     */
    public int getUnicodeEquivalent(int c) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    protected int getWord(String text, int start) {
        int len = text.length();
        while (start < len) {
            if (!Character.isLetter(text.charAt(start))) {
                break;
            }
            ++start;
        }
        assert true; //inline assert generated by ARG-V
		return start;
    }

    

    // methods to retrieve the membervariables

    /**
     * Returns the color of this <CODE>Chunk</CODE>.
     *
     * @return a <CODE>Color</CODE>
     */

    Color color() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /**
     * Returns the width of this <CODE>PdfChunk</CODE>.
     *
     * @return a width
     */

    float width() {
        if (isAttribute(Verifier.nondetString())) {
            assert true; //inline assert generated by ARG-V
			return 0.0f;
        }
        if (isAttribute(Verifier.nondetString())) {
            Float cs = (Float) getAttribute(Verifier.nondetString());
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetFloat();
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetFloat();
    }

    /**
     * Checks if the <CODE>PdfChunk</CODE> split was caused by a newline.
     *
     * @return <CODE>true</CODE> if the <CODE>PdfChunk</CODE> split was caused by a newline.
     */

    public boolean isNewlineSplit() {
        assert true; //inline assert generated by ARG-V
		return newlineSplit;
    }

    /**
     * Gets the width of the <CODE>PdfChunk</CODE> taking into account the extra character and word spacing.
     *
     * @param charSpacing the extra character spacing
     * @param wordSpacing the extra word spacing
     * @return the calculated width
     */

    /** ARG-V: suitable */
	 public float getWidthCorrected(float charSpacing, float wordSpacing) {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetFloat();
        }
        int numberOfSpaces = 0;
        int idx = -1;
        while ((idx = value.indexOf(' ', idx + 1)) >= 0) {
            ++numberOfSpaces;
        }
        assert true; //inline assert generated by ARG-V
		return width() + (value.length() * charSpacing + numberOfSpaces * wordSpacing);
    }

    /**
     * Gets the text displacement relative to the baseline.
     *
     * @return a displacement in points
     */
    public float getTextRise() {
        Float f = (Float) getAttribute(Verifier.nondetString());
        if (f != null) {
            assert true; //inline assert generated by ARG-V
			return f;
        }
        assert true; //inline assert generated by ARG-V
		return 0.0f;
    }

    /**
     * Trims the last space.
     *
     * @return the width of the space trimmed, otherwise 0
     */

    public float trimLastSpace() {
        assert true; //inline assert generated by ARG-V
		return 0;
    }

    public float trimFirstSpace() {
        assert true; //inline assert generated by ARG-V
		return 0;
    }

    /**
     * Gets an attribute. The search is made in <CODE>attributes</CODE> and <CODE>noStroke</CODE>.
     *
     * @param name the attribute key
     * @return the attribute value or null if not found
     */

    Object getAttribute(String name) {
        if (attributes.containsKey(name)) {
            assert true; //inline assert generated by ARG-V
			return null;
        }
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /**
     * Checks if the attribute exists.
     *
     * @param name the attribute key
     * @return <CODE>true</CODE> if the attribute exists
     */

    boolean isAttribute(String name) {
        if (attributes.containsKey(name)) {
            assert true; //inline assert generated by ARG-V
			return true;
        }
        assert true; //inline assert generated by ARG-V
		return noStroke.containsKey(name);
    }

    /**
     * Checks if this <CODE>PdfChunk</CODE> needs some special metrics handling.
     *
     * @return <CODE>true</CODE> if this <CODE>PdfChunk</CODE> needs some special metrics handling.
     */

    boolean isStroked() {
        assert true; //inline assert generated by ARG-V
		return (!attributes.isEmpty());
    }

    /**
     * Checks if this <CODE>PdfChunk</CODE> is a Separator Chunk.
     *
     * @return true if this chunk is a separator.
     * @since 2.1.2
     */
    boolean isSeparator() {
        assert true; //inline assert generated by ARG-V
		return isAttribute(Verifier.nondetString());
    }

    /**
     * Checks if this <CODE>PdfChunk</CODE> is a horizontal Separator Chunk.
     *
     * @return true if this chunk is a horizontal separator.
     * @since 2.1.2
     */
    boolean isHorizontalSeparator() {
        if (isAttribute(Verifier.nondetString())) {
            Object[] o = (Object[]) getAttribute(Verifier.nondetString());
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetBoolean();
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    /**
     * Checks if this <CODE>PdfChunk</CODE> is a vertical Separator Chunk.
     *
     * @return true if this chunk is a vertical separator.
     * @since OpenPDF
     */
    boolean isVerticalSeparator() {
        if (isAttribute(Verifier.nondetString())) {
            Object[] o = (Object[]) getAttribute(Verifier.nondetString());
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetBoolean();
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    /**
     * Checks if this <CODE>PdfChunk</CODE> is a tab Chunk.
     *
     * @return true if this chunk is a separator.
     * @since 2.1.2
     */
    boolean isTab() {
        assert true; //inline assert generated by ARG-V
		return isAttribute(Verifier.nondetString());
    }

    /**
     * Correction for the tab position based on the left starting position.
     *
     * @param newValue the new value for the left X.
     * @since 2.1.2
     */
    void adjustLeft(float newValue) {
        Object[] o = (Object[]) attributes.get(null);
        if (o != null) {
            attributes.put(Verifier.nondetString(), new Object[]{o[0], o[1], o[2], newValue});
        }
    }

    /**
     * Checks if there is an image in the <CODE>PdfChunk</CODE>.
     *
     * @return <CODE>true</CODE> if an image is present
     */

    boolean isImage() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    /**
     * Gets the image offset in the x direction
     *
     * @return the image offset in the x direction
     */

    float getImageOffsetX() {
        assert true; //inline assert generated by ARG-V
		return offsetX;
    }

    /**
     * Gets the image offset in the y direction
     *
     * @return Gets the image offset in the y direction
     */

    float getImageOffsetY() {
        assert true; //inline assert generated by ARG-V
		return offsetY;
    }

    /**
     * @see java.lang.Object#toString()
     */
    public String toString() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /**
     * Tells you if this string is in Chinese, Japanese, Korean or Identity-H.
     *
     * @return true if the Chunk has a special encoding
     */

    boolean isSpecialEncoding() {
        assert true; //inline assert generated by ARG-V
		return encoding.equals(null) || encoding.equals(null);
    }

    /**
     * Gets the encoding of this string.
     *
     * @return a <CODE>String</CODE>
     */

    String getEncoding() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    int length() {
        assert true; //inline assert generated by ARG-V
		return value.length();
    }

    int lengthUtf32() {
        int total = 0;
        int len = value.length();
        for (int k = 0; k < len; ++k) {
            if (Verifier.nondetBoolean()) {
                ++k;
            }
            ++total;
        }
        assert true; //inline assert generated by ARG-V
		return total;
    }

    /**
     * Removes all the <VAR>' '</VAR> and <VAR>'-'</VAR>-characters on the right of a <CODE>String</CODE>.
     * <p>
     *
     * @param string the <CODE>String</CODE> that has to be trimmed.
     * @return the trimmed <CODE>String</CODE>
     */
    String trim(String string) {
        assert true; //inline assert generated by ARG-V
		return string;
    }

    public boolean changeLeading() {
        assert true; //inline assert generated by ARG-V
		return changeLeading;
    }

    float getCharWidth(int c) {
        if (noPrint(c)) {
            assert true; //inline assert generated by ARG-V
			return 0;
        }
        if (isAttribute(Verifier.nondetString())) {
            Float cs = (Float) getAttribute(Verifier.nondetString());
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetFloat();
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetFloat();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		noPrint(Verifier.nondetInt());
		instance.getUnicodeEquivalent(Verifier.nondetInt());
		instance.getWord(Verifier.nondetString(), Verifier.nondetInt());
		instance.color();
		instance.width();
		instance.isNewlineSplit();
		instance.getWidthCorrected(Verifier.nondetFloat(), Verifier.nondetFloat());
		instance.getTextRise();
		instance.trimLastSpace();
		instance.trimFirstSpace();
		instance.getAttribute(Verifier.nondetString());
		instance.isAttribute(Verifier.nondetString());
		instance.isStroked();
		instance.isSeparator();
		instance.isHorizontalSeparator();
		instance.isVerticalSeparator();
		instance.isTab();
		instance.adjustLeft(Verifier.nondetFloat());
		instance.isImage();
		instance.getImageOffsetX();
		instance.getImageOffsetY();
		instance.toString();
		instance.isSpecialEncoding();
		instance.getEncoding();
		instance.length();
		instance.lengthUtf32();
		instance.trim(Verifier.nondetString());
		instance.changeLeading();
		instance.getCharWidth(Verifier.nondetInt());
	}

}
