

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

/**
 * 楽曲詳細情報
 * 
 * @author exch
 */
public class Main {
	
	/**
	 * 譜面のハッシュ値
	 */
	private String sha256 = Verifier.nondetString();
	/**
	 * 通常ノート総数
	 */
	private int n = Verifier.nondetInt();
	/**
	 * ロングノート総数
	 */
	private int ln = Verifier.nondetInt();
	/**
	 * スクラッチノート総数
	 */
	private int s = Verifier.nondetInt();
	/**
	 * ロングスクラッチノート総数
	 */
	private int ls = Verifier.nondetInt();
	/**
	 * 平均密度
	 */
	private double density = Verifier.nondetDouble();
	/**
	 * 最大密度
	 */
	private double peakdensity = Verifier.nondetDouble();
	/**
	 * 終盤最大密度
	 */
	private double enddensity = Verifier.nondetDouble();

	/**
	 * TOTAL
	 */
	private double total = Verifier.nondetDouble();
	
	private double mainbpm = Verifier.nondetDouble();

	/**
	 * 分布
	 */
	private String distribution = "";
	
	private int[][] distributionValues = new int[0][7];

	/**
	 * BPM遷移
	 */
	private String speedchange = "";
	
	private double[][] speedchangeValues = new double[0][2];

	/**
	 * 各レーンのノーツ数
	 */
	private String lanenotes = "";
	
	private int[][] lanenotesValues = new int[0][3];

	public Main() {
		
	}
	
	public String getDistribution() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	/** ARG-V: suitable */
	 public void setDistribution(String distribution) {
		int[] index = {0,2,3,5,6};
		if(distribution.startsWith("#")) {
			index = new int[]{0,1,2,3,4,5,6};
			distribution = distribution.substring(1);
		}
		final int count = distribution.length() % (index.length * 2) == 0 ? distribution.length() / (index.length * 2) : 0;
		if(count == 0) {
			Logger.getGlobal().warning("distributionのString超が不正です");
		}
		for(int i = 0;i < count;i++) {
			for(int j = 0;j < index.length;j++) {
				try {
				} catch(Exception e) {
					Logger.getGlobal().warning("distribution解析中の例外:" + e.getMessage());
				}
			}
		}
		
	}
	
	public int[][] getDistributionValues() {
		assert true; //inline assert generated by ARG-V
		return new int[][] { { Verifier.nondetInt() } };
	}

	/** ARG-V: suitable */
	 public void setDistributionValues(int[][] values) {
		StringBuilder sb = new StringBuilder(values.length * 14 + 1);
		sb.append("#");
		for(int i = 0;i < values.length;i++) {
			for(int j = 0;j < 7;j++) {
				int value = Math.min(distributionValues[i][j], 36 * 36 - 1);
				int val1 = value / 36;
				sb.append((char) (val1 >= 10 ? val1 - 10 + 'a' : val1 + '0'));
				val1 = value % 36;
				sb.append((char) (val1 >= 10 ? val1 - 10 + 'a' : val1 + '0'));
			}
		}
	}

	/** ARG-V: suitable */
	 private static int parseInt36(String s, int index) throws RuntimeException {
		int result = 0;
		final char c1 = s.charAt(index);
		if (c1 >= '0' && c1 <= '9') {
			result = (c1 - '0') * 36;
		} else if (c1 >= 'a' && c1 <= 'z') {
			result = ((c1 - 'a') + 10) * 36;
		} else if (c1 >= 'A' && c1 <= 'Z') {
			result = ((c1 - 'A') + 10) * 36;
		} else {
			throw new NumberFormatException();
		}

		final char c2 = s.charAt(index + 1);
		if (c2 >= '0' && c2 <= '9') {
			result += (c2 - '0');
		} else if (c2 >= 'a' && c2 <= 'z') {
			result += (c2 - 'a') + 10;
		} else if (c2 >= 'A' && c2 <= 'Z') {
			result += (c2 - 'A') + 10;
		} else {
			throw new NumberFormatException();
		}

		assert true; //inline assert generated by ARG-V
		return result;
	}

	public String getSpeedchange() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public void setSpeedchange(String speedchange) {
		ArrayList<double[]> result = new ArrayList<double[]>();
		int index = 0;
		double[] values = new double[2];
		try {
		} catch(Exception e) {
			result.clear();
		}
	}

	public double[][] getSpeedchangeValues() {
		assert true; //inline assert generated by ARG-V
		return new double[][] { { Verifier.nondetDouble() } };
	}

	/** ARG-V: suitable */
	 public void setSpeedchangeValues(double[][] values) {
		StringBuilder sb = new StringBuilder(values.length * 14 + 1);
		for(int i = 0;i < values.length;i++) {
			sb.append(values[i][0]).append(',').append(values[i][1]);
			if(i < values.length - 1) {
				sb.append(',');
			}
		}
	}

	public String getLanenotes() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public void setLanenotes(String lanenotes) {
		ArrayList<int[]> result = new ArrayList<int[]>();
		int index = 0;
		int[] values = new int[3];
		try {
		} catch(Exception e) {
			result.clear();
		}
	}

	public int[][] getLanenotesValues() {
		assert true; //inline assert generated by ARG-V
		return new int[][] { { Verifier.nondetInt() } };
	}

	/** ARG-V: suitable */
	 public void setLanenotesValues(int[][] values) {
		StringBuilder sb = new StringBuilder(values.length * 14 + 1);
		for(int i = 0;i < values.length;i++) {
			sb.append(values[i][0]).append(',').append(values[i][1]).append(',').append(values[i][2]);
			if(i < values.length - 1) {
				sb.append(',');
			}
		}
	}

	public int getN() {
		assert true; //inline assert generated by ARG-V
		return n;
	}

	public int getLn() {
		assert true; //inline assert generated by ARG-V
		return ln;
	}

	public int getS() {
		assert true; //inline assert generated by ARG-V
		return s;
	}

	public int getLs() {
		assert true; //inline assert generated by ARG-V
		return ls;
	}

	public double getDensity() {
		assert true; //inline assert generated by ARG-V
		return density;
	}

	public String getSha256() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public double getTotal() {
		assert true; //inline assert generated by ARG-V
		return total;
	}

	public double getPeakdensity() {
		assert true; //inline assert generated by ARG-V
		return peakdensity;
	}

	public double getEnddensity() {
		assert true; //inline assert generated by ARG-V
		return enddensity;
	}

	public double getMainbpm() {
		assert true; //inline assert generated by ARG-V
		return mainbpm;
	}

	public boolean validate() {
		if(sha256 == Verifier.nondetString() || sha256.length() != 64) {
			assert true; //inline assert generated by ARG-V
			return false;
		}
		if(n < 0 || ln < 0 || s < 0 || ls < 0) {
			assert true; //inline assert generated by ARG-V
			return false;
		}
		if(density < 0 || peakdensity < 0 || enddensity < 0 || density > peakdensity || enddensity > peakdensity) {
			assert true; //inline assert generated by ARG-V
			return false;
		}
		assert true; //inline assert generated by ARG-V
		return true;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getDistribution();
		instance.setDistribution(Verifier.nondetString());
		instance.getDistributionValues();
		instance.setDistributionValues(new int[][] { { Verifier.nondetInt() } });
		parseInt36(Verifier.nondetString(), Verifier.nondetInt());
		instance.getSpeedchange();
		instance.setSpeedchange(Verifier.nondetString());
		instance.getSpeedchangeValues();
		instance.setSpeedchangeValues(new double[][] { { Verifier.nondetDouble() } });
		instance.getLanenotes();
		instance.setLanenotes(Verifier.nondetString());
		instance.getLanenotesValues();
		instance.setLanenotesValues(new int[][] { { Verifier.nondetInt() } });
		instance.getN();
		instance.getLn();
		instance.getS();
		instance.getLs();
		instance.getDensity();
		instance.getSha256();
		instance.getTotal();
		instance.getPeakdensity();
		instance.getEnddensity();
		instance.getMainbpm();
		instance.validate();
	}

}
