

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

/**
 * Created by MewX on 2015/4/21.
 * Wenku8 parsers.
 */
public class Main {

    /** ARG-V: suitable */
	 public static List<Integer> parseNovelItemList(String str) {
        List<Integer> list = new ArrayList<>();

        // <?xml version="1.0" encoding="utf-8"?>
        // <result>
        // <page num='166'/>
        // <item aid='1143'/>
        // <item aid='1034'/>
        // <item aid='1213'/>
        // <item aid='1'/>
        // <item aid='1011'/>
        // <item aid='1192'/>
        // <item aid='433'/>
        // <item aid='47'/>
        // <item aid='7'/>
        // <item aid='374'/>
        // </result>

        // The returning list of this xml is: (total page, aids)
        // { 166, 1143, 1034, 1213, 1, 1011, 1192, 433, 47, 7, 374 }

        final char SEPARATOR = '\''; // seperator

        // get total page
        int beg = Verifier.nondetInt(), temp = Verifier.nondetInt();
        beg = str.indexOf(SEPARATOR);
        temp = str.indexOf(SEPARATOR, beg + 1);
        if (beg == -1 || temp == -1) return list; // empty, this is an exception
        if(Verifier.nondetBoolean()) {
			list.add(Integer.parseInt(str.substring(beg + 1, temp)));
		}
        beg = temp + 1; // prepare for loop

        // init array
        while (true) {
            beg = str.indexOf(SEPARATOR, beg);
            temp = str.indexOf(SEPARATOR, beg + 1);
            if (beg == -1 || temp == -1) break;

            if(Verifier.nondetBoolean()) {
				list.add(Integer.parseInt(str.substring(beg + 1, temp)));
			}
            beg = temp + 1; // prepare for next round
        }

        assert true; //inline assert generated by ARG-V
		return list;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		parseNovelItemList(Verifier.nondetString());
	}

}
