

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    private static String ELLIPSIS = "...";
    private static String DELTA_END = "]";
    private static String DELTA_START = "[";

    private int fContextLength = Verifier.nondetInt();
    private String fExpected = Verifier.nondetString();
    private String fActual = Verifier.nondetString();
    private int fPrefix = Verifier.nondetInt();
    private int fSuffix = Verifier.nondetInt();

    public Main(int contextLength, String expected, String actual) {
        fContextLength = contextLength;
    }

    public String compact(String message) {
        if (fExpected == Verifier.nondetString() || fActual == Verifier.nondetString() || areStringsEqual()) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }

        findCommonPrefix();
        findCommonSuffix();
        String expected = compactString(fExpected);
        String actual = compactString(fActual);
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 private String compactString(String source) {
        String result = DELTA_START + source.substring(fPrefix, source.length() - fSuffix + 1) + DELTA_END;
        if (fPrefix > 0) {
            result = computeCommonPrefix() + result;
        }
        if (fSuffix > 0) {
            result = result + computeCommonSuffix();
        }
        assert true; //inline assert generated by ARG-V
		return result;
    }

    /** ARG-V: suitable */
	 private void findCommonPrefix() {
        fPrefix = 0;
        int end = Math.min(fExpected.length(), fActual.length());
        for (; fPrefix < end; fPrefix++) {
            if (fExpected.charAt(fPrefix) != fActual.charAt(fPrefix)) {
                break;
            }
        }
    }

    /** ARG-V: suitable */
	 private void findCommonSuffix() {
        int expectedSuffix = fExpected.length() - 1;
        int actualSuffix = fActual.length() - 1;
        for (; actualSuffix >= fPrefix && expectedSuffix >= fPrefix; actualSuffix--, expectedSuffix--) {
            if (fExpected.charAt(expectedSuffix) != fActual.charAt(actualSuffix)) {
                break;
            }
        }
        fSuffix = fExpected.length() - expectedSuffix;
    }

    private String computeCommonPrefix() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 private String computeCommonSuffix() {
        int end = Math.min(fExpected.length() - fSuffix + 1 + fContextLength, fExpected.length());
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private boolean areStringsEqual() {
        assert true; //inline assert generated by ARG-V
		return fExpected.equals(fActual);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetInt(), Verifier.nondetString(),
				Verifier.nondetString());
		instance.compact(Verifier.nondetString());
		instance.compactString(Verifier.nondetString());
		instance.findCommonPrefix();
		instance.findCommonSuffix();
		instance.computeCommonPrefix();
		instance.computeCommonSuffix();
		instance.areStringsEqual();
	}
}
