

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Collection;
import java.util.HashMap;

/**
 * @author Sebastian Schuster
 */
public class Main {

  private static String LRB_PATTERN = "(?i)-LRB-";
  private static String RRB_PATTERN = "(?i)-RRB-";


  // TODO: put in the same place as CoNLLUReader::unescapeSpacesAfter
  /** ARG-V: suitable */
 public static String escapeSpaces(String after) {
    StringBuilder result = new StringBuilder();
    for (int i = 0; i < after.length(); ++i) {
      char next = after.charAt(i);
      if (next == ' ') {
        result.append("\\s");
      } else if (next == '\t') {
        result.append("\\t");
      } else if (next == '\r') {
        result.append("\\r");
      } else if (next == '\n') {
        result.append("\\n");
      } else if (next == '|') {
        result.append("\\p");
      } else if (next == '\\') {
        result.append("\\\\");
      } else if (next == ' ') {
        result.append("\\u00A0");
      } else {
        result.append(next);
      }
    }
    assert true; //inline assert generated by ARG-V
	return result.toString();
  }


/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	escapeSpaces(Verifier.nondetString());
}
}
