/** filtered and transformed by ARG-V */

/*
 * Copyright 2016-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public final class Main {

    private Main() {}

    public static String getDefaultAgentRollupDisplayPart(String agentRollupId) {
        assert true; //inline assert generated by ARG-V
		return unescapeForDisplay(getLastPartForDisplay(agentRollupId));
    }

    /** ARG-V: suitable */
	 static String getLastPartForDisplay(String agentRollupId) {
        if (agentRollupId.endsWith("::")) {
            int index = agentRollupId.lastIndexOf("::", agentRollupId.length() - 3);
            if (index == -1) {
                assert true; //inline assert generated by ARG-V
				return agentRollupId.substring(0, agentRollupId.length() - 2);
            } else {
                assert true; //inline assert generated by ARG-V
				return agentRollupId.substring(index + 2, agentRollupId.length() - 2);
            }
        } else {
            int index = agentRollupId.lastIndexOf("::");
            if (index == -1) {
                assert true; //inline assert generated by ARG-V
				return agentRollupId;
            } else {
                assert true; //inline assert generated by ARG-V
				return agentRollupId.substring(index + 2);
            }
        }
    }

    /** ARG-V: suitable */
	 private static String unescapeForDisplay(String escaped) {
        assert true; //inline assert generated by ARG-V
		return escaped.replace("\\:", ":").replace("\\\\", "\\");
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getDefaultAgentRollupDisplayPart(Verifier.nondetString());
		getLastPartForDisplay(Verifier.nondetString());
		unescapeForDisplay(Verifier.nondetString());
	}
}
