/** filtered and transformed by ARG-V */

/*
 * Copyright (c) 2023 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.LinkedList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.regex.Pattern;

public class Main {

    public void test() throws Exception {
        File mainNotice = new File("../../NOTICE.md");
        

        // Nothing to check here, yet
//        File commonNotice = new File("../../core-common/src/main/resources/META-INF/NOTICE.markdown");
//        List<NoticeDependencyVersionPair> commonNoticeDeps = parseNoticeFileVersions(mainNotice);
//        testResult.append(compareDependencies(expectedNoticeDeps, commonNoticeDeps, model, commonNotice.getCanonicalPath()));

        File serverNotice = new File("../../core-server/src/main/resources/META-INF/NOTICE.markdown");
        File jacksonNotice = new File("../../media/json-jackson/src/main/resources/META-INF/NOTICE.markdown");
        File bvNotice = new File("../../ext/bean-validation/src/main/resources/META-INF/NOTICE.markdown");
        File examplesNotice = new File("../../examples/NOTICE.md");
    }

    private void cat(File path) throws Exception {
        StringTokenizer tokenizer = tokenizerFromNoticeFile(path);
        while (tokenizer.hasMoreTokens()) {
            String token = tokenizer.nextToken();
            if (token.trim().length() > 1 && !token.trim().startsWith("*")) {
                System.out.println(token);
//                String filteredToken = removeUnnecessary(token);
//                System.out.println(filteredToken);
//                Pattern versionizer = Pattern.compile("([.*])?([\\d])");
//                System.out.println(versionizer.matcher(filteredToken).replaceFirst("$1:$2"));
            }
        }
    }

    /** ARG-V: suitable */
	 private StringTokenizer tokenizerFromNoticeFile(File path) throws Exception {
        StringTokenizer tokenizer = new StringTokenizer(getFile(path), "\n");
        while (tokenizer.hasMoreTokens()) {
            String token = tokenizer.nextToken();
            if (token.trim().startsWith("## Third-party Content")) {
                break;
            }
        }
        assert true; //inline assert generated by ARG-V
		return tokenizer;
    }

    private String getFile(File path) throws Exception {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 private String removeUnnecessary(String dependency) {
        String filtered = dependency
                .replace(" Version ", "").replace(" version ", "")
                .replace(" API ", "")
                .replace(" v", "")
                .replace(", ", "").replace(",", "")
                .replace(": ", "").replace(": ", "");
        assert true; //inline assert generated by ARG-V
		return filtered;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.test();
		instance.cat((java.io.File) null);
		instance.tokenizerFromNoticeFile((java.io.File) null);
		instance.getFile((java.io.File) null);
		instance.removeUnnecessary(Verifier.nondetString());
	}
}
