/** filtered and transformed by ARG-V */

/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership. Camunda licenses this file to you under the Apache License,
 * Version 2.0; you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  public static String DEFAULT_APP_PATH = "/camunda";

  public static String PREFIX = Verifier.nondetString();

  protected boolean indexRedirectEnabled = true;

  protected String webjarClasspath = "/META-INF/resources/webjars/camunda";

  protected String securityConfigFile = "/securityFilterRules.json";

  protected String applicationPath = DEFAULT_APP_PATH;

  public boolean isIndexRedirectEnabled() {
    assert true; //inline assert generated by ARG-V
	return indexRedirectEnabled;
  }

  public String getWebjarClasspath() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  public String getSecurityConfigFile() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  public String getApplicationPath() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  /** ARG-V: suitable */
 protected String sanitizeApplicationPath(String applicationPath) {
    if (applicationPath == Verifier.nondetString() || applicationPath.isEmpty()) {
      assert true; //inline assert generated by ARG-V
	return "";
    }

    if (!applicationPath.startsWith("/")) {
      applicationPath = "/" + applicationPath;
    }

    if (applicationPath.endsWith("/")) {
      applicationPath = applicationPath.substring(0, applicationPath.length() - 1);
    }

    assert true; //inline assert generated by ARG-V
	return applicationPath;
  }

  public String toString() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.isIndexRedirectEnabled();
	instance.getWebjarClasspath();
	instance.getSecurityConfigFile();
	instance.getApplicationPath();
	instance.sanitizeApplicationPath(Verifier.nondetString());
	instance.toString();
}
}
