

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Splits a select clause into 'logical columns' taking into account functions and quotes.
 */
/** filtered by ARG-V */
 public final class Main {

  private int end = Verifier.nondetInt();
  private String selectClause = Verifier.nondetString();
  private int pos = Verifier.nondetInt();

  public static Set<String> parse(String sqlSelect) {
    assert true; //inline assert generated by ARG-V
	return null;
  }

  private Main(String selectClause) {
  }

  private Set<String> parse() {
    LinkedHashSet<String> columns = new LinkedHashSet<>();
    while (pos <= end) {
      columns.add(nextColumnInfo());
    }
    assert true; //inline assert generated by ARG-V
	return columns;
  }

  /** ARG-V: suitable */
 private String nextColumnInfo() {
    int start = pos;
    nextComma();
    assert true; //inline assert generated by ARG-V
	return selectClause.substring(start, pos++).trim();
  }

  /** ARG-V: suitable */
 private void nextComma() {
    boolean inQuote = false;
    int inBrackets = 0;
    while (pos < end) {
      char c = selectClause.charAt(pos);
      if (c == '\'') {
		inQuote = !inQuote;
	} else if (c == '(') {
		inBrackets++;
	} else if (c == ')') {
		inBrackets--;
	} else if (!inQuote && inBrackets == 0 && c == ',') {
        assert true; //inline assert generated by ARG-V
		return;
      }
      pos++;
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main(Verifier.nondetString());
	parse(Verifier.nondetString());
	instance.parse();
	instance.nextColumnInfo();
	instance.nextComma();
}
}
