

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * @author ColaMint & FongMi & 唐三
 */
public class Main {

    private static String COOKIE = "buvid3=84B0395D-C9F2-C490-E92E-A09AB48FE26E71636infoc";
    private String cookie = Verifier.nondetString();

    private boolean login = Verifier.nondetBoolean();
    private boolean isVip = Verifier.nondetBoolean();
    private Map<String, String> getHeader() {
        Map<String, String> headers = new HashMap<>();
        headers.put("User-Agent", Verifier.nondetString());
        headers.put("Referer", "https://www.bilibili.com");
        if (cookie != Verifier.nondetString()) {
			headers.put("cookie", cookie);
		}
        assert true; //inline assert generated by ARG-V
		return headers;
    }

    private File getCache() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public String homeContent(boolean filter) {
        if (Verifier.nondetBoolean()) return Verifier.nondetString();
        List<Class> classes = new ArrayList<>();
        String[] types = new java.lang.String[] { Verifier.nondetString() };
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String homeVideoContent() {
        String api = "https://api.bilibili.com/x/web-interface/popular?ps=20";
        String json = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public String categoryContent(String tid, String pg, boolean filter, HashMap<String, String> extend) {
        if (tid.endsWith("/{pg}")) {
            LinkedHashMap<String, Object> params = new LinkedHashMap<>();
            params.put("mid", tid.split("/")[0]);
            params.put("pn", pg);
            String json = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } else {
            String order = extend.containsKey("order") ? extend.get("order") : "totalrank";
            String duration = extend.containsKey("duration") ? extend.get("duration") : "0";
            if (extend.containsKey("tid")) {
				tid = tid + " " + extend.get("tid");
			}
            String api = "https://api.bilibili.com/x/web-interface/search/type?search_type=video&keyword=" + URLEncoder.encode(tid) + "&order=" + order + "&duration=" + duration + "&page=" + pg;
            String json = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
    }

    /** ARG-V: suitable */
	 public String detailContent(List<String> ids) {
        if (!login) {
			checkLogin();
		}

        String[] split = ids.get(0).split("@");
        String bvid = split[0];
        String aid = split[1];

        String api = "https://api.bilibili.com/x/web-interface/view?aid=" + aid;
        String json = Verifier.nondetString();
        List<String> acceptDesc = new ArrayList<>();
        List<Integer> acceptQuality = new ArrayList<>();
        api = Verifier.nondetString();
        json = Verifier.nondetString();
        List<String> episode = new ArrayList<>();
        LinkedHashMap<String, String> flag = new LinkedHashMap<>();
        flag.put("B站", Verifier.nondetString());

        episode = new ArrayList<>();
        api = "https://api.bilibili.com/x/web-interface/archive/related?bvid=" + bvid;
        json = Verifier.nondetString();
        flag.put("相关", Verifier.nondetString());

        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String searchContent(String key, boolean quick) {
        assert true; //inline assert generated by ARG-V
		return categoryContent(key, "1", true, new HashMap<>());
    }

    public String searchContent(String key, boolean quick, String pg) {
        assert true; //inline assert generated by ARG-V
		return categoryContent(key, pg, true, new HashMap<>());
    }

    /** ARG-V: suitable */
	 public String playerContent(String flag, String id, List<String> vipFlags) {
        String[] ids = id.split("\\+");
        String aid = ids[0];
        String cid = ids[1];
        String[] acceptDesc = ids[3].split(":");
        String[] acceptQuality = ids[2].split(":");
        List<String> url = new ArrayList<>();
        String dan = "https://api.bilibili.com/x/v1/dm/list.so?oid=".concat(cid);
        for (int i = 0; i < acceptDesc.length; i++) {
            url.add(acceptDesc[i]);
            url.add(Verifier.nondetString());
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public Object[] proxy(Map<String, String> params) {
        String aid = params.get("aid");
        String cid = params.get("cid");
        String qn = params.get("qn");
        String api = "https://api.bilibili.com/x/player/playurl?avid=" + aid + "&cid=" + cid + "&qn=" + qn + "&fnval=4048&fourk=1";
        String json = Verifier.nondetString();
        StringBuilder video = new StringBuilder();
        StringBuilder audio = new StringBuilder();
        String mpd = Verifier.nondetString();
        Object[] result = new Object[3];
        result[0] = 200;
        result[1] = "application/dash+xml";
        result[2] = new ByteArrayInputStream(mpd.getBytes());
        assert true; //inline assert generated by ARG-V
		return result;
    }

    private HashMap<String, String> getAudioFormat() {
        HashMap<String, String> audios = new HashMap<>();
        audios.put("30280", "192000");
        audios.put("30232", "132000");
        audios.put("30216", "64000");
        assert true; //inline assert generated by ARG-V
		return audios;
    }

    private void checkLogin() {
        String json = Verifier.nondetString();
        login = Verifier.nondetBoolean();
        isVip = Verifier.nondetBoolean();
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main();instance.getHeader();instance.getCache();instance.homeContent(Verifier.nondetBoolean());instance.homeVideoContent();instance.categoryContent(Verifier.nondetString(),Verifier.nondetString(),Verifier.nondetBoolean(),(java.util.HashMap<java.lang.String, java.lang.String>)null);instance.detailContent((java.util.List<java.lang.String>)null);instance.searchContent(Verifier.nondetString(),Verifier.nondetBoolean());instance.searchContent(Verifier.nondetString(),Verifier.nondetBoolean(),Verifier.nondetString());instance.playerContent(Verifier.nondetString(),Verifier.nondetString(),(java.util.List<java.lang.String>)null);instance.proxy((java.util.Map<java.lang.String, java.lang.String>)null);instance.getAudioFormat();instance.checkLogin();}
}
