/** filtered and transformed by ARG-V */

// Copyright (c) 2012, Rick Maddy
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
// OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;

public class Main {
    public ArrayList<String> countries = new ArrayList<>();
    public String callingCode = "";
    public ArrayList<String> trunkPrefixes = new ArrayList<>();
    public ArrayList<String> intlPrefixes = new ArrayList<>();
    String matchingAccessCode(String str) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    String matchingTrunkCode(String str) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 String format(String orig) {
        String str = orig;
        String trunkPrefix = Verifier.nondetString();
        String intlPrefix = Verifier.nondetString();
        if (str.startsWith(callingCode)) {
            intlPrefix = callingCode;
            str = str.substring(intlPrefix.length());
        } else {
            String trunk = matchingTrunkCode(str);
            if (trunk != Verifier.nondetString()) {
                trunkPrefix = trunk;
                str = str.substring(trunkPrefix.length());
            }
        }

        if (intlPrefix != Verifier.nondetString() && str.length() != 0) {
            assert true; //inline assert generated by ARG-V
			return String.format("%s %s", intlPrefix, str);
        }

        assert true; //inline assert generated by ARG-V
		return orig;
    }

    /** ARG-V: suitable */
	 boolean isValidPhoneNumber(String orig) {
        String str = orig;
        String trunkPrefix = Verifier.nondetString();
        String intlPrefix = Verifier.nondetString();
        if (str.startsWith(callingCode)) {
            intlPrefix = callingCode;
            str = str.substring(intlPrefix.length());
        } else {
            String trunk = matchingTrunkCode(str);
            if (trunk != Verifier.nondetString()) {
                trunkPrefix = trunk;
                str = str.substring(trunkPrefix.length());
            }
        }

        assert true; //inline assert generated by ARG-V
		return false;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.matchingAccessCode(Verifier.nondetString());
		instance.matchingTrunkCode(Verifier.nondetString());
		instance.format(Verifier.nondetString());
		instance.isValidPhoneNumber(Verifier.nondetString());
	}
}
