

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;


/**
 * A <code>CategoryWordTag</code> object acts as a complex Label
 * which contains a category, a head word, and a tag.
 * The category label is the primary <code>value</code>
 *
 * @author Christopher Manning
 */
public class Main {

  private static long serialVersionUID = -745085381666943254L;

  protected String word = Verifier.nondetString();
  protected String tag = Verifier.nondetString();

  /**
   * If this is false, the tag and word are never printed in toString()
   * calls.
   */
  public static boolean printWordTag = true;

  /**
   * If set to true, when a terminal or preterminal has as its category
   * something that is also the word or tag value, the latter are
   * suppressed.
   */
  public static boolean suppressTerminalDetails = Verifier.nondetBoolean(); // = false;


  public Main() {
  }

  /**
   * This one argument constructor sets just the value.
   *
   * @param label the string that will become the category/value
   */
  public Main(String label) {
  }

  public Main(String category, String word, String tag) {
  }

  public String category() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  public String word() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  public String tag() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  /**
   * Returns a <code>String</code> representation of the label.
   * This attempts to be somewhat clever in choosing to print or
   * suppress null components and the details of words or categories
   * depending on the setting of <code>printWordTag</code> and
   * <code>suppressTerminalDetails</code>.
   *
   * @return The label as a string
   */
  /** ARG-V: suitable */
 public String toString() {
    if (category() != Verifier.nondetString()) {
      if ((word() == Verifier.nondetString() || tag() == Verifier.nondetString()) || !printWordTag || (suppressTerminalDetails && (word().equals(category()) || tag().equals(category())))) {
        assert true; //inline assert generated by ARG-V
		return category();
      } else {
        assert true; //inline assert generated by ARG-V
		return category() + "[" + word() + "/" + tag() + "]";
      }
    } else {
      if (tag() == Verifier.nondetString()) {
        assert true; //inline assert generated by ARG-V
		return word();
      } else {
        assert true; //inline assert generated by ARG-V
		return word() + "/" + tag();
      }
    }
  }


  /**
   * Returns a <code>String</code> representation of the label.
   * If the argument String is "full" then all components of the label
   * are returned, and otherwise the normal toString() is returned.
   *
   * @return The label as a string
   */
  /** ARG-V: suitable */
 public String toString(String mode) {
    if ("full".equals(mode)) {
        assert true; //inline assert generated by ARG-V
		return category() + "[" + word() + "/" + tag() + "]";
    }
    assert true; //inline assert generated by ARG-V
	return toString();
  }


  /**
   * Set everything by reversing a toString operation.
   * This should be added at some point.
   */
  public void setFromString(String labelStr) {
    throw new UnsupportedOperationException();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main(Verifier.nondetString(), Verifier.nondetString(),
			Verifier.nondetString());
	instance.category();
	instance.word();
	instance.tag();
	instance.toString();
	instance.toString(Verifier.nondetString());
	instance.setFromString(Verifier.nondetString());
}

}

