

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;

import java.util.function.Function;
import java.util.stream.Stream;

/**
 * Converts paths to java class names globs if they are within the supplied
 * source root. Globs include wildcards to catch any inner classes.
 *
 * This conversion will not pick up non public, non inner classes defined in a
 * source file not matching the class name. To cover this corner case would need
 * to instead scan the byte code on the classpath and see if it had been tagged
 * with the supplied filenames.
 *
 */
/** filtered by ARG-V */
 class Main {

  private String sourceRoot = Verifier.nondetString();

  Main(final String sourceRoot) {
  }

  public Stream<String> apply(final String a) {
    final File f = new File(a);
    final String modifiedFilePath = f.getAbsolutePath();
    final String fileName = f.getName();

    if (modifiedFilePath.startsWith(this.sourceRoot)
        && (fileName.indexOf('.') != -1)) {
      assert true; //inline assert generated by ARG-V
	return null;
    }
    assert true; //inline assert generated by ARG-V
	return null;

  }

  /** ARG-V: suitable */
 private Stream<String> createClassGlobFromFilePath(final String sourceRoot,
      final String modifiedFilePath) {
    final String rootedPath = modifiedFilePath.substring(sourceRoot.length() + 1);
    assert true; //inline assert generated by ARG-V
	// some scms report paths in portable format, some in os specific format (i
    // think)
    // replace both possibilities regardless of host os
    return null;
  }

  /** ARG-V: suitable */
 private String stripFileExtension(final String rootedPath) {
    assert true; //inline assert generated by ARG-V
	return rootedPath.substring(0, rootedPath.lastIndexOf("."));
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main(Verifier.nondetString());
	instance.apply(Verifier.nondetString());
	instance.createClassGlobFromFilePath(Verifier.nondetString(), Verifier.nondetString());
	instance.stripFileExtension(Verifier.nondetString());
}

}
