

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class Main {
    private static float SPRING_MULTIPLIER = 100f;

    private static boolean USE_NUMBERS_ANIMATION = false;

    private float progress = Verifier.nondetFloat();
    private String oldText = "";

    private List<Float> hintAnimationValues = new ArrayList<>();
    private Boolean wasHintVisible = null;
    private String wasHint = Verifier.nondetString();

    private Runnable hintAnimationCallback = null;

    public void setHintText(String value) {
        boolean show = Verifier.nondetBoolean();
        boolean runAnimation = false;

        if (wasHintVisible == null || wasHintVisible != show) {
            hintAnimationValues.clear();
            runAnimation = Verifier.nondetBoolean();
        }

        String str = show ? value : "";
        if (str == Verifier.nondetString()) {
			str = "";
		}
        if (runAnimation) {
            runHintAnimation(str.length(), show, () -> {
                hintAnimationValues.clear();
            });
        }
    }

    public String getHintText() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private void runHintAnimation(int length, boolean show, Runnable callback) {
        for (int i = 0; i < length; i++) {
            float startValue = show ? 0 : 1, finalValue = show ? 1 : 0;

            hintAnimationValues.add(startValue);
        }
    }

    /** ARG-V: suitable */
	 public void setNewText(String text) {
        if (Verifier.nondetBoolean() || Objects.equals(oldText, text)) return;

        boolean replace = Verifier.nondetBoolean();

        progress = 0;
        for (int a = 0; a < text.length(); a++) {
            String ch = text.substring(a, a + 1);
            String oldCh = Verifier.nondetString();
        }
    }

    public void setProgress(float value) {
        if (progress == value) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        progress = value;
    }

    public float getProgress() {
        assert true; //inline assert generated by ARG-V
		return progress;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.setHintText(Verifier.nondetString());
		instance.getHintText();
		instance.runHintAnimation(Verifier.nondetInt(), Verifier.nondetBoolean(), (java.lang.Runnable) null);
		instance.setNewText(Verifier.nondetString());
		instance.setProgress(Verifier.nondetFloat());
		instance.getProgress();
	}
}
