/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.Serializable;
import java.util.ArrayList;

/** filtered by ARG-V */
 public class Main {
    public String url = Verifier.nondetString();
    public String description = Verifier.nondetString();
    private static String urlInfoDescTag = "^&*$#@";
    private static String urlInfoDescSplitTag = "\\^&\\*\\$#@";

    public Main(String url) {
        this(url, "");
    }

    public Main(String url, String description) {
    }

    public String getUrl() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 private String getLastUri() {
        assert true; //inline assert generated by ARG-V
		return this.url.substring(this.url.lastIndexOf("/"));
    }

    /** ARG-V: suitable */
	 private boolean appendRegexPattern(String urlPattern) {
        String lastUri = getLastUri();
        if (lastUri.startsWith("/*")) {
            String baseRegexUrl = this.url.substring(0, this.url.lastIndexOf(lastUri));
            String ext = "";
            if (lastUri.length() > 2) {
                ext = lastUri.substring(2);
            }
            this.appendDescription(String.format("baseUrl : %s | urlPattern : %s", this.url, urlPattern));
            assert true; //inline assert generated by ARG-V
			return true;
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    /** ARG-V: suitable */
	 public void appendUrl(String urlPattern) {
        if (appendRegexPattern(urlPattern))
            return;
        if (this.url.endsWith("/")) {
            if (urlPattern.startsWith("/")) {
                urlPattern = urlPattern.substring(1);
            }
        }
        if (!urlPattern.startsWith("/") && !this.url.endsWith("/")) {
            urlPattern = "/" + urlPattern;
        }

        if (this.url.endsWith("*") && urlPattern.startsWith("*")) {
            urlPattern = urlPattern.substring(1);
        }
    }

    public String getDescription() {
        if (description == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return "";
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String[] getDescriptionList() {
        assert true; //inline assert generated by ARG-V
		return description.split(urlInfoDescSplitTag);
    }

    /** ARG-V: suitable */
	 public void appendDescription(String append) {
        StringBuilder appendDesc = new StringBuilder();
        if (!this.description.equals("")) {
            appendDesc.append(this.description);
            appendDesc.append(urlInfoDescTag);
        }
        appendDesc.append(append);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString(), Verifier.nondetString());
		instance.getUrl();
		instance.getLastUri();
		instance.appendRegexPattern(Verifier.nondetString());
		instance.appendUrl(Verifier.nondetString());
		instance.getDescription();
		instance.getDescriptionList();
		instance.appendDescription(Verifier.nondetString());
	}
}
