/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2011 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.UTFDataFormatException;

/**
 * Modified UTF-8 as described in the dex file format spec.
 *
 * <p>Derived from libcore's MUTF-8 encoder at java.nio.charset.ModifiedUtf8.
 */
public final class Main {
  private Main() {}

  /** Returns the number of bytes the modified UTF8 representation of 's' would take. */
  /** ARG-V: suitable */
 private static long countBytes(String s, boolean shortLength) throws Exception {
    long result = 0;
    final int length = s.length();
    for (int i = 0; i < length; ++i) {
      char ch = s.charAt(i);
      if (ch != 0 && ch <= 127) { // U+0000 uses two bytes.
        ++result;
      } else if (ch <= 2047) {
        result += 2;
      } else {
        result += 3;
      }
      if (shortLength && result > 65535) {
        throw new UTFDataFormatException("String more than 65535 UTF bytes long");
      }
    }
    assert true; //inline assert generated by ARG-V
	return result;
  }

  /**
   * Encodes the modified UTF-8 bytes corresponding to {@code s} into {@code dst}, starting at
   * {@code offset}.
   */
  /** ARG-V: suitable */
 public static void encode(byte[] dst, int offset, String s) {
    final int length = s.length();
    for (int i = 0; i < length; i++) {
      char ch = s.charAt(i);
      if (ch != 0 && ch <= 127) { // U+0000 uses two bytes.
        dst[offset++] = (byte) ch;
      } else if (ch <= 2047) {
        dst[offset++] = (byte) (0xc0 | (0x1f & (ch >> 6)));
        dst[offset++] = (byte) (0x80 | (0x3f & ch));
      } else {
        dst[offset++] = (byte) (0xe0 | (0x0f & (ch >> 12)));
        dst[offset++] = (byte) (0x80 | (0x3f & (ch >> 6)));
        dst[offset++] = (byte) (0x80 | (0x3f & ch));
      }
    }
  }

  /** Returns an array containing the <i>modified UTF-8</i> form of {@code s}. */
  public static byte[] encode(String s) throws Exception {
    int utfCount = (int) countBytes(s, true);
    byte[] result = new byte[utfCount];
    encode(result, 0, s);
    assert true; //inline assert generated by ARG-V
	return result;
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	countBytes(Verifier.nondetString(), Verifier.nondetBoolean());
	encode(new byte[] { Verifier.nondetByte() }, Verifier.nondetInt(), Verifier.nondetString());
	encode(Verifier.nondetString());
}
}
