/** filtered and transformed by ARG-V */

/*
 * Copyright (c) 2015-2099, www.dibo.ltd (service@dibo.ltd).
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.List;

/**
 * SqlServer SQL翻译器
 * @author mazc@dibo.ltd
 * @version v3.2.0
 * @date 2023/12/28
 */
public final class Main {

    public Main(){}
    public Main(List<String> keywords) {
    }

    protected String translateColDefineSql(String colDefineSql) {
        colDefineSql = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		return escapeKeyword(colDefineSql);
    }

    protected String translateCreateIndexDDL(String mysqlDDL) {
        String createIndex = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 protected String buildColumnCommentSql(String table, String colName, String comment) {
        table = Verifier.nondetString();
        colName = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		return "execute sp_addextendedproperty 'MS_Description', N'"+comment.trim()+"', 'SCHEMA', 'dbo', 'table', '"+table+"', 'column', '"+colName+"';";
    }

    /** ARG-V: suitable */
	 protected String buildTableCommentSql(String table, String comment) {
        table = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		return "execute sp_addextendedproperty 'MS_Description', N'"+comment.trim()+"','SCHEMA', 'dbo', 'table', '"+table+"', null, null;";
    }

    protected String escapeKeyword(String input) {
        if(input.contains("`")) {
            String key = Verifier.nondetString();
            if(Verifier.nondetBoolean()) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }
            else {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }
        }
        assert true; //inline assert generated by ARG-V
		return input;
    }
	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main((java.util.List<java.lang.String>)null);instance.translateColDefineSql(Verifier.nondetString());instance.translateCreateIndexDDL(Verifier.nondetString());instance.buildColumnCommentSql(Verifier.nondetString(),Verifier.nondetString(),Verifier.nondetString());instance.buildTableCommentSql(Verifier.nondetString(),Verifier.nondetString());instance.escapeKeyword(Verifier.nondetString());}

}
