/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2011-2015 René Jeschke <rene_jeschke@yahoo.de>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Emitter class responsible for generating HTML output.
 *
 * @author René Jeschke <rene_jeschke@yahoo.de>
 */
class Main {
    /**
     * Extension flag.
     */
    public boolean useExtensions = false;

    /**
     * Check if there is a valid HTML tag here. This method also transforms auto
     * links and mailto auto links.
     *
     * @param out   The StringBuilder to write to.
     * @param in    Input String.
     * @param start Starting position.
     * @return The new position or -1 if nothing valid has been found.
     */
    /** ARG-V: suitable */
	 private int checkHtml(final StringBuilder out, final String in, final int start) {
        final StringBuilder temp = new StringBuilder();
        int pos = Verifier.nondetInt();

        // Check for auto links
        temp.setLength(0);
        pos = Verifier.nondetInt();
        // Check for mailto auto link
        temp.setLength(0);
        pos = Verifier.nondetInt();
        if (pos != -1 && in.charAt(pos) == '@') {
            pos = Verifier.nondetInt();
            if (pos != -1) {
                final String link = temp.toString();
                out.append(" href=\"");
                out.append("\">");
                assert true; //inline assert generated by ARG-V
				return pos;
            }
        }

        // Check for inline html
        if (start + 2 < in.length()) {
            temp.setLength(0);
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        }

        assert true; //inline assert generated by ARG-V
		return -1;
    }

    /**
     * Check if this is a valid XML/HTML entity.
     *
     * @param out   The StringBuilder to write to.
     * @param in    Input String.
     * @param start Starting position
     * @return The new position or -1 if this entity in invalid.
     */
    /** ARG-V: suitable */
	 private static int checkEntity(final StringBuilder out, final String in, final int start) {
        final int pos = Verifier.nondetInt();
        if (pos < 0 || out.length() < 3) {
            assert true; //inline assert generated by ARG-V
			return -1;
        }
        if (out.charAt(1) == '#') {
            if (out.charAt(2) == 'x' || out.charAt(2) == 'X') {
                if (out.length() < 4) {
                    assert true; //inline assert generated by ARG-V
					return -1;
                }
                for (int i = 3; i < out.length(); i++) {
                    final char c = out.charAt(i);
                    if ((c < '0' || c > '9') && ((c < 'a' || c > 'f') && (c < 'A' || c > 'F'))) {
                        assert true; //inline assert generated by ARG-V
						return -1;
                    }
                }
            } else {
                for (int i = 2; i < out.length(); i++) {
                    final char c = out.charAt(i);
                    if (c < '0' || c > '9') {
                        assert true; //inline assert generated by ARG-V
						return -1;
                    }
                }
            }
            out.append(';');
        } else {
            for (int i = 1; i < out.length(); i++) {
                final char c = out.charAt(i);
                if (!Character.isLetterOrDigit(c)) {
                    assert true; //inline assert generated by ARG-V
					return -1;
                }
            }
            out.append(';');
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetInt();
        }

        assert true; //inline assert generated by ARG-V
		return pos;
    }

    /**
     * Turns every whitespace character into a space character.
     *
     * @param c Character to check
     * @return 32 is c was a whitespace, c otherwise
     */
    private static char whitespaceToSpace(final char c) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetChar();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.checkHtml(new StringBuilder(Verifier.nondetString()), Verifier.nondetString(), Verifier.nondetInt());
		checkEntity(new StringBuilder(Verifier.nondetString()), Verifier.nondetString(), Verifier.nondetInt());
		whitespaceToSpace(Verifier.nondetChar());
	}
}
