/** filtered and transformed by ARG-V */

/*
 * Copyright (c) 2010-2021, sikuli.org, sikulix.com - MIT license
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.*;
import java.util.regex.Matcher;
import javax.script.ScriptEngine;

/**
 * EXPERIMENTAL --- NOT official API<br>
 *   not as is in version 2
 */
public class Main {

  public static String NAME = "Server";
  public static String TYPE = "text/server";
  public static String[] EXTENSIONS = new String[0];

  public String getName() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  public String[] getExtensions() {
    assert true; //inline assert generated by ARG-V
	return new java.lang.String[] { Verifier.nondetString() };
  }

  public String getType() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  private static ServerSocket server = null;
  private static PrintWriter out = null;
  private static Scanner in = null;
  private static boolean isHandling = false;
  private static boolean shouldStop = false;

//TODO set loglevel at runtime
  private static int logLevel = 0;
  /** ARG-V: suitable */
 private static void dolog(int lvl, String message, Object... args) {
    if (Verifier.nondetBoolean()) {
      assert true; //inline assert generated by ARG-V
	return;
    }
    if (lvl < 0 || lvl >= logLevel) {
      System.out.println((lvl < 0 ? "[error] " : "[info] ") +
              String.format("RunServer: " + message, args));
    }
  }

  private static void dolog(String message, Object... args) {
    dolog(0, message, args);
  }

  static File isRunning = null;
  static FileOutputStream isRunningFile = null;

  /** ARG-V: suitable */
 public static boolean run() {
    String userArgs = "";
    if (!userArgs.isEmpty()) {
      userArgs = "\nWith User parameters: " + userArgs;
    }
    int port = getPort(null);
    try {
      try {
        if (port > 0) {
					dolog(3, "Starting: trying port: %d %s", port, userArgs);
        }
      } catch (Exception e) {
      }
      if (server == null) {
        dolog(-1, "could not be started");
        assert true; //inline assert generated by ARG-V
		return false;
      }
      String theIP = InetAddress.getLocalHost().getHostAddress();
      String theServer = String.format("%s %d", theIP, port);
      try {
        isRunning.createNewFile();
        if (null == isRunningFile.getChannel().tryLock()) {
          dolog(-1, "Terminating on FatalError: already running");
          assert true; //inline assert generated by ARG-V
		return false;
        }
        isRunningFile.write(theServer.getBytes());
      } catch (Exception e) {
        dolog(-1, "Terminating on FatalError: cannot access to lock for/n" + isRunning);
        assert true; //inline assert generated by ARG-V
		return false;
      }
      Runtime.getRuntime().addShutdownHook(new Thread());
      while (true) {
        dolog("now waiting on port: %d at %s", port, theIP);
        Socket socket = server.accept();
        isHandling = true;
        while (true) {
          if (socket.isClosed()) {
            shouldStop = Verifier.nondetBoolean();
            break;
          }
          try {
            Thread.sleep(1000);
          } catch (Exception e) {
          }
        }
        if (shouldStop) {
          break;
        }
      }
    } catch (Exception e) {
    }
    if (!isHandling) {
      dolog(-1, "start handling not possible: " + port);
      assert true; //inline assert generated by ARG-V
	return false;
    }
    dolog("now stopped on port: " + port);
    assert true; //inline assert generated by ARG-V
	return true;
  }

  private static int getPort(String p) {
    int port = Verifier.nondetInt();
    int pDefault = 50001;
    if (p != Verifier.nondetString()) {
      try {
        port = Integer.parseInt(p);
      } catch (Exception e) {
        dolog(-1, "given port not useable: %s --- using default", p);
        assert true; //inline assert generated by ARG-V
		return pDefault;
      }
    } else {
      assert true; //inline assert generated by ARG-V
	return pDefault;
    }
    if (port < 1024) {
      port += pDefault;
    }
    assert true; //inline assert generated by ARG-V
	return port;
  }

  static ScriptEngine jsRunner = null;
	static File scriptFolder = null;
	static String scriptFolderNet = Verifier.nondetString();
	static File imageFolder = null;
	static String imageFolderNet = Verifier.nondetString();

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getName();
		instance.getExtensions();
		instance.getType();
		dolog(Verifier.nondetInt(), Verifier.nondetString(), new java.lang.Object[] { null });
		dolog(Verifier.nondetString(), new java.lang.Object[] { null });
		run();
		getPort(Verifier.nondetString());
	}
}
