/** filtered and transformed by ARG-V */

/*
 * Copyright 2013-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.IOException;
import java.util.List;
import java.util.Map;

class Main {

    /** ARG-V: suitable */
	 static String stripContextPath(String path, String contextPath) {
        if (contextPath.equals("/")) {
            assert true; //inline assert generated by ARG-V
			return path;
        }
        if (path.equals(contextPath)) {
            assert true; //inline assert generated by ARG-V
			return "/";
        }
        assert true; //inline assert generated by ARG-V
		return path.substring(contextPath.length());
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		stripContextPath(Verifier.nondetString(), Verifier.nondetString());
	}
}
