/** filtered and transformed by ARG-V */

// Copyright 2011-2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import org.sosy_lab.sv_benchmarks.Verifier;
import java.awt.event.KeyEvent;

public class Main {
  private int getXdelta() {
    int delta = 0;

    assert true; //inline assert generated by ARG-V
	return delta;
  }

  private int getYdelta() {
    int delta = 0;

    assert true; //inline assert generated by ARG-V
	return delta;
  }

  /** ARG-V: suitable */
 protected void handleNotShiftAndCtrl(final int xdelta, final int ydelta) {
    int caretStartPos_X = Verifier.nondetInt();
    int mousePressed_X = Verifier.nondetInt();
    final int mousePressed_Y = Verifier.nondetInt();

    int caretEndPos_X = Verifier.nondetInt();
    int mouseReleased_X = Verifier.nondetInt();
    final int mouseReleased_Y = Verifier.nondetInt();

    if (xdelta != 0) {
      final String s = Verifier.nondetString();

      if (xdelta > 0) {
        final boolean firstIsSpace = s.charAt(caretEndPos_X) == ' ';

        int endindex = 0;

        for (int i = caretEndPos_X; i < s.length(); ++i) {
          endindex = i;
          if (firstIsSpace) {
            if (s.charAt(i) != ' ') {
              break;
            }
          } else {
            if (s.charAt(i) == ' ') {
              break;
            }
          }
        }

        caretStartPos_X = endindex;
        mousePressed_X = endindex;
        mouseReleased_X = endindex;
        caretEndPos_X = endindex;
      } else if (xdelta < 0) {
        if (caretEndPos_X == 0) {
          assert true; //inline assert generated by ARG-V
		return;
        }
        final boolean firstIsSpace = s.charAt(caretEndPos_X - 1) == ' ';

        int startindex = caretEndPos_X - 1;

        for (int i = caretEndPos_X - 1; i >= 0; --i) {
          if (firstIsSpace) {
            if (s.charAt(i) != ' ') {
              break;
            }
          } else {
            if (s.charAt(i) == ' ') {
              break;
            }
          }
          startindex = i;
        }

        caretStartPos_X = startindex;
        mousePressed_X = startindex;
        mouseReleased_X = startindex;
        caretEndPos_X = startindex;
      }

      mouseReleased_X = Verifier.nondetInt();
    } else if (ydelta != 0) {
      handleNotShiftAndNotCtrl(0, ydelta);
    }
  }

  protected void handleNotShiftAndNotCtrl(final int xdelta, final int ydelta) {
    int caretStartPos_X = Verifier.nondetInt();
    int mousePressed_X = Verifier.nondetInt();
    int mousePressed_Y = Verifier.nondetInt();

    int caretEndPos_X = Verifier.nondetInt();
    int mouseReleased_X = Verifier.nondetInt();
    int mouseReleased_Y = Verifier.nondetInt();

    mouseReleased_X = Verifier.nondetInt();
  }

  /** ARG-V: suitable */
 protected void handleShiftAndCtrl(final int xdelta, final int ydelta) {
    if (ydelta != 0) {
      handleShiftAndNotCtrl(0, ydelta);
    } else if (xdelta != 0) {
      int caretStartPos_X = Verifier.nondetInt();
      final int mousePressed_X = Verifier.nondetInt();
      final int mousePressed_Y = Verifier.nondetInt();

      int caretEndPos_X = Verifier.nondetInt();
      int mouseReleased_X = Verifier.nondetInt();
      final int mouseReleased_Y = Verifier.nondetInt();

      final String s = Verifier.nondetString();

      if (xdelta > 0) {
        final boolean firstIsSpace = s.charAt(caretEndPos_X) == ' ';
        int endindex = 0;
        for (int i = caretEndPos_X; i < s.length(); ++i) {
          endindex = i;
          if (firstIsSpace) {
            if (s.charAt(i) != ' ') {
              break;
            }
          } else {
            if (s.charAt(i) == ' ') {

              break;
            }
          }
        }

        caretStartPos_X = mousePressed_X;

        mouseReleased_X = endindex;
        caretEndPos_X = endindex;

        final boolean noReturn = Verifier.nondetBoolean();
        final boolean withReturn =
            Verifier.nondetBoolean();
        final boolean withCReturn =
            Verifier.nondetBoolean();

        if (noReturn || withReturn || withCReturn) {
          mouseReleased_X = Verifier.nondetInt();
        }
      } else if (xdelta < 0) {
        if (caretEndPos_X == 0) {
          assert true; //inline assert generated by ARG-V
		return;
        }
        final boolean firstIsSpace = s.charAt(caretEndPos_X - 1) == ' ';
        int startindex = caretEndPos_X - 1;
        for (int i = caretEndPos_X - 1; i >= 0; --i) {
          if (firstIsSpace) {
            if (s.charAt(i) != ' ') {
              break;
            }
          } else {
            if (s.charAt(i) == ' ') {
              break;
            }
          }
          startindex = i;
        }
        caretStartPos_X = mousePressed_X;

        mouseReleased_X = startindex;
        caretEndPos_X = startindex;
      }

      mouseReleased_X = Verifier.nondetInt();
    }
  }

  protected void handleShiftAndNotCtrl(final int xDelta, final int yDelta) {
    int caretStartPos_X = Verifier.nondetInt();
    final int mousePressed_X = Verifier.nondetInt();
    final int mousePressed_Y = Verifier.nondetInt();

    int caretEndPos_X = Verifier.nondetInt();
    int mouseReleased_X = Verifier.nondetInt();
    int mouseReleased_Y = Verifier.nondetInt();

    final int linecount = Verifier.nondetInt();

    if ((xDelta != 0) || (yDelta != 0)) {
      mouseReleased_Y += yDelta;
      if (mouseReleased_Y < 0) {
        mouseReleased_Y = 0;
      }
      if (mouseReleased_Y > (linecount - 1)) {
        mouseReleased_Y = linecount - 1;
      }

      mouseReleased_X += xDelta;
      if (mouseReleased_X < 0) {
        mouseReleased_X = 0;
      }

      int lp = mousePressed_Y;
      int lr = mouseReleased_Y;

      if (lp > lr) {
        lp = mouseReleased_Y;
        lr = mousePressed_Y;
      }

      int maxlength = 0;
      for (int y = lp; y <= lr; ++y) {
        maxlength = Verifier.nondetInt();
      }

      if (mouseReleased_X > maxlength) {
        mouseReleased_X = maxlength;
      }

      caretStartPos_X = mousePressed_X;
    }

    mouseReleased_X = Verifier.nondetInt();
  }

  protected void updateCaret() {
    final int xDelta = getXdelta();
    final int yDelta = getYdelta();
  }

  protected void updateLabelContent() {
    assert true; //inline assert generated by ARG-V
	return;
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.getXdelta();
	instance.getYdelta();
	instance.handleNotShiftAndCtrl(Verifier.nondetInt(), Verifier.nondetInt());
	instance.handleNotShiftAndNotCtrl(Verifier.nondetInt(), Verifier.nondetInt());
	instance.handleShiftAndCtrl(Verifier.nondetInt(), Verifier.nondetInt());
	instance.handleShiftAndNotCtrl(Verifier.nondetInt(), Verifier.nondetInt());
	instance.updateCaret();
	instance.updateLabelContent();
}
}
