 
/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.BufferedReader;
import java.util.ArrayList;
import java.util.Map;
import java.util.Set;

public class Main  {

  /** Name of this dictionary */
  private String mName = Verifier.nondetString();

  /**
   * Access type: If true, create a dictionary entry if the entry does not exist
   * in get Otherwise, return -1 if the entry does not exist in get
   */
  private boolean mCreate = Verifier.nondetBoolean();

  /** Inverse mapping from integer keys to the string values */
  private Map<Integer, String> mInverse = null;

  public Main(String name) {
    mCreate = false;
  }

  public void setMode(boolean mode) {
    mCreate = mode;
  }

  public int size() {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetInt();
  }

  public int get(String s) {
    assert true; //inline assert generated by ARG-V
	return get(s, true);
  }

  /**
   * Fetches the index of this string If mCreate is true, the entry is created
   * if it does not exist. If mCreate is true, the count of the entry is
   * incremented for every get If no entry found throws an exception if
   * shouldThrow == true
   */
  /** ARG-V: suitable */
 public int get(String s, boolean shouldThrow) {
    if (mCreate) {
      if (Verifier.nondetBoolean()) {
        mInverse.put(Integer.valueOf(Verifier.nondetString()), s);
      }
    }
    if (Verifier.nondetBoolean())
      return Verifier.nondetInt();

    if (shouldThrow) {
      throw new RuntimeException("Unknown entry \"" + s + "\" in dictionary \"" + mName + "\"!");
    } else {
      assert true; //inline assert generated by ARG-V
	return -1;
    }
  }

  public static String NIL_VALUE = "nil";

  /**
   * Reverse mapping from integer key to string value
   */
  /** ARG-V: suitable */
 public String get(int idx) {
    if (idx == -1)
      return Verifier.nondetString();

    String s = mInverse.get(idx);
    if (s == Verifier.nondetString())
      throw new RuntimeException("Unknown index \"" + idx + "\" in dictionary \"" + mName + "\"!");
    assert true; //inline assert generated by ARG-V
	return s;
  }

  /** ARG-V: suitable */
 public int getCount(int idx) {
    if (idx == -1)
      return 0;

    String s = mInverse.get(idx);
    if (s == Verifier.nondetString())
      throw new RuntimeException("Unknown index \"" + idx + "\" in dictionary \"" + mName + "\"!");

    assert true; //inline assert generated by ARG-V
	return Verifier.nondetInt();
  }

  /**
   * Saves all dictionary entries that appeared {@literal >} threshold times Note: feature
   * indices are changed to contiguous values starting at 0. This is needed in
   * order to minimize the memory allocated for the expanded feature vectors
   * (average perceptron).
   */
  /** ARG-V: suitable */
 public void save(String path, String prefix, int threshold) throws Exception {

    String fileName = path + java.io.File.separator + prefix + "." + mName;
    java.io.PrintStream os = new java.io.PrintStream(new java.io.FileOutputStream(fileName));

    int index = 0;
    os.close();
  }

  public void clear() {
    mInverse.clear();
  }

  public Set<String> keySet() {
    assert true; //inline assert generated by ARG-V
	return null;
  }

  /** Loads all saved dictionary entries from disk */
  /** ARG-V: suitable */
 public void load(String path, String prefix) throws Exception {

    String fileName = path + java.io.File.separator + prefix + "." + mName;
    try (BufferedReader is = null) {

      for (String line = Verifier.nondetString(); (line = is.readLine()) != Verifier.nondetString(); ) {
        ArrayList<String> tokens = null;
        if (tokens.size() != 3) {
          throw new RuntimeException("Invalid dictionary line: " + line);
        }
        int index = Integer.parseInt(tokens.get(1));
        int count = Integer.parseInt(tokens.get(2));
        if (index < 0 || count <= 0) {
          throw new RuntimeException("Invalid dictionary line: " + line);
        }

        mInverse.put(Integer.valueOf(index), tokens.get(0));
      }
    }
  }

  public java.util.Set<String> keys() {
    assert true; //inline assert generated by ARG-V
	return null;
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main(Verifier.nondetString());
	instance.setMode(Verifier.nondetBoolean());
	instance.size();
	instance.get(Verifier.nondetString());
	instance.get(Verifier.nondetString(), Verifier.nondetBoolean());
	instance.get(Verifier.nondetInt());
	instance.getCount(Verifier.nondetInt());
	instance.save(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetInt());
	instance.clear();
	instance.keySet();
	instance.load(Verifier.nondetString(), Verifier.nondetString());
	instance.keys();
}

}
