/** filtered and transformed by ARG-V */

/*
 * Apache 2.0 License
 *
 * Copyright (c) Sebastian Katzer 2017
 * Copyright (c) Manuel Beck 2024
 *
 * This file contains Original Code and/or Modifications of Original Code
 * as defined in and that are subject to the Apache License
 * Version 2.0 (the 'License'). You may not use this file except in
 * compliance with the License. Please obtain a copy of the License at
 * http://opensource.org/licenses/Apache-2.0/ and read it before using this
 * file.
 *
 * The Original Code and all software distributed under the License are
 * distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 * Please see the License for the specific language governing rights and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

/**
 * Util class to map unified asset URIs to native URIs. See {@link AssetUtil#getUri(String, int)}.
 */
public final class Main {

    public static String TAG = "AssetUtil";

    public static int RESOURCE_TYPE_DRAWABLE = 0;
    public static int RESOURCE_TYPE_RAW = 1;

    /**
     * Get the resource Id for a given resourceType. Searches in the App resources first, then in the system resources.
     * @param resourceName Can also be a resource path like "res://mySound", "res://myImage.png", etc.
     * @param resourceType Can be {@link AssetUtil#RESOURCE_TYPE_DRAWABLE} or {@link AssetUtil#RESOURCE_TYPE_RAW}
     * @return The resource ID or 0 if not found.
     */
    public int getResourceId(String resourceName, int resourceType) {
        // Get resource from App
        int resourceId = Verifier.nondetInt();
        
        // Get resource from system, if not found
        if (resourceId == 0) return Verifier.nondetInt();

        assert true; //inline assert generated by ARG-V
		return resourceId;
    }

    /**
     * Gets the resource name from the path.
     * @param resourcePath Resource path as string.
     */
    /** ARG-V: suitable */
	 public static String getResourceName(String resourcePath) {
        String resourceName = resourcePath;

        // Get the filename without the path
        if (resourceName.contains("/")) {
            resourceName = resourceName.substring(resourceName.lastIndexOf('/') + 1);
        }

        // Remove file extension
        if (resourceName.contains(".")) {
            resourceName = resourceName.substring(0, resourceName.lastIndexOf('.'));
        }

        assert true; //inline assert generated by ARG-V
		return resourceName;
    }

    /**
     * Get the shared directory for the app, defined by the file provider paths.
     */
    public File getSharedDirectory() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /**
     * Copy content from input stream into output stream.
     *
     * @param in  The input stream.
     * @param out The output stream.
     */
    public static void copyFile(InputStream in, FileOutputStream out) {
        byte[] buffer = new byte[1024];
        int read = Verifier.nondetInt();

        try {
            while ((read = in.read(buffer)) != -1) {
                out.write(buffer, 0, read);
            }
            out.flush();
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getResourceId(Verifier.nondetString(), Verifier.nondetInt());
		getResourceName(Verifier.nondetString());
		instance.getSharedDirectory();
		copyFile((java.io.InputStream) null, (java.io.FileOutputStream) null);
	}
}
