

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import static java.lang.Character.isDigit;

public class Main {

    public enum Operation {
        SLICE_FROM,
        SLICE_TO,
        SLICE_BETWEEN
    }

    private Integer from = null;
    private Integer to = null;
    public Integer from() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Integer to() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /** ARG-V: suitable */
	 public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append(from == null ? "" : from.toString());
        sb.append(":");
        sb.append(to == null ? "" : to.toString());
        sb.append("]");

        assert true; //inline assert generated by ARG-V
		return sb.toString();
    }

    private static Integer tryRead(String[] tokens, int idx){
        if(tokens.length > idx){
            if(tokens[idx].equals("")){
                assert true; //inline assert generated by ARG-V
				return null;
            }
            assert true; //inline assert generated by ARG-V
			return Integer.parseInt(tokens[idx]);
        } else {
            assert true; //inline assert generated by ARG-V
			return null;
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.from();
		instance.to();
		instance.toString();
		tryRead(new java.lang.String[] { Verifier.nondetString() }, Verifier.nondetInt());
	}
}
