/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2024-2024 Sermant Authors. All rights reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.concurrent.TimeUnit;

/**
 * test method class
 *
 * @author chengyouling
 * @since 2024-10-30
 */
public class Main {
    private static String CONFIG_KEY = "grayscale.mq.config";

    private static String CONSUMER_TYPE_PULL = "PULL";

    private static String CONSUMER_TYPE_LITE_PULL = "LITE-PULL";

    private static String CONSUMER_TYPE_PUSH = "PUSH";

    public void testPluginEnabledFalseConsumeMessage() throws Exception {
        testPluginEnabledFalsePull();
        Thread.sleep(10000);
        testPluginEnabledFalseLitePull();
        Thread.sleep(10000);
        testPluginEnabledFalsePush();
    }

    private void testPluginEnabledFalsePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testPluginEnabledFalseLitePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testPluginEnabledFalsePush() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private int parseBaseMessageCount(String messageCount) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    private int parseGrayMessageCount(String messageCount) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    public void testAutoOnlyBaseConsumeMessage() throws Exception {
        createGrayscaleConfig("AUTO", "");
        testAutoOnlyBasePull();
        Thread.sleep(15000);
        testAutoOnlyBaseLitePull();
        Thread.sleep(15000);
        testAutoOnlyBasePush();
    }

    private void testAutoOnlyBasePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testAutoOnlyBaseLitePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testAutoOnlyBasePush() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    public void testAutoExcOnlyBaseConsumeMessage() throws Exception {
        createGrayscaleConfig("AUTO", "gray");
        testAutoExcOnlyBasePull();
        Thread.sleep(15000);
        testAutoExcOnlyBaseLitePull();
        Thread.sleep(15000);
        testAutoExcOnlyBasePush();
    }

    private void testAutoExcOnlyBasePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testAutoExcOnlyBaseLitePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testAutoExcOnlyBasePush() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    public void testAutoBaseGrayConsumeMessage() throws Exception {
        createGrayscaleConfig("AUTO", "");
        testAutoBaseGrayPull();
        Thread.sleep(15000);
        testAutoBaseGrayLitePull();
        Thread.sleep(15000);
        testAutoBaseGrayPush();
    }

    public void testAutoBaseGrayPull() throws Exception {
        createGrayscaleConfig("AUTO", "");
        initAndProduceMessage(true, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String grayResult = getPullGrayResult();
        int grayGrayCount = parseGrayMessageCount(grayResult);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
    }

    public void testAutoBaseGrayLitePull() throws Exception {
        createGrayscaleConfig("AUTO", "");
        initAndProduceMessage(true, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String grayResult = getLitePullGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    public void testAutoBaseGrayPush() throws Exception {
        createGrayscaleConfig("AUTO", "");
        initAndProduceMessage(true, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getPushGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
    }

    public void testAutoExcBaseGrayConsumeMessage() throws Exception {
        createGrayscaleConfig("AUTO", "gray");
        testAutoExcBaseGrayPull();
        Thread.sleep(15000);
        testAutoExcBaseGrayLitePull();
        Thread.sleep(15000);
        testAutoExcBaseGrayPush();
    }

    private void testAutoExcBaseGrayPull() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String grayResult = getPullGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testAutoExcBaseGrayLitePull() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getLitePullGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
    }

    private void testAutoExcBaseGrayPush() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getPushGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
    }

    public void testBaseOnlyBaseConsumeMessage() throws Exception {
        createGrayscaleConfig("BASE", "");
        testBaseOnlyBasePull();
        Thread.sleep(15000);
        testBaseOnlyBaseLitePull();
        Thread.sleep(15000);
        testBaseOnlyBasePush();
    }

    private void testBaseOnlyBasePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testBaseOnlyBaseLitePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testBaseOnlyBasePush() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    public void testBaseExcOnlyBaseConsumeMessage() throws Exception {
        createGrayscaleConfig("BASE", "gray");
        testBaseExcOnlyBasePull();
        Thread.sleep(15000);
        testBaseExcOnlyBaseLitePull();
        Thread.sleep(15000);
        testBaseExcOnlyBasePush();
    }

    private void testBaseExcOnlyBasePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testBaseExcOnlyBaseLitePull() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    private void testBaseExcOnlyBasePush() throws Exception {
        initAndProduceMessage(false, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
    }

    public void testBaseBaseGrayConsumeMessage() throws Exception {
        createGrayscaleConfig("BASE", "");
        testBaseBaseGrayPull();
        Thread.sleep(15000);
        testBaseBaseGrayLitePull();
        Thread.sleep(15000);
        testBaseBaseGrayPush();
    }

    private void testBaseBaseGrayPull() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getPullGrayResult();
        int grayGrayCount = parseGrayMessageCount(grayResult);
        int grayBaseCount = parseBaseMessageCount(grayResult);
    }

    private void testBaseBaseGrayLitePull() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getLitePullGrayResult();
        int grayGrayCount = parseGrayMessageCount(grayResult);
        int grayBaseCount = parseBaseMessageCount(grayResult);
    }

    private void testBaseBaseGrayPush() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getPushGrayResult();
        int grayGrayCount = parseGrayMessageCount(grayResult);
        int grayBaseCount = parseBaseMessageCount(grayResult);
    }

    public void testBaseExcBaseGrayConsumeMessage() throws Exception {
        createGrayscaleConfig("BASE", "gray");
        testBaseExcBaseGrayPull();
        Thread.sleep(15000);
        testBaseExcBaseGrayLitePull();
        Thread.sleep(15000);
        testBaseExcBaseGrayPush();
    }

    private void testBaseExcBaseGrayPull() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_PULL);
        Thread.sleep(240000);
        String baseResult = getPullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getPullGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
    }

    private void testBaseExcBaseGrayLitePull() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_LITE_PULL);
        Thread.sleep(240000);
        String baseResult = getLitePullBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getLitePullGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
    }

    private void testBaseExcBaseGrayPush() throws Exception {
        initAndProduceMessage(true, CONSUMER_TYPE_PUSH);
        Thread.sleep(240000);
        String baseResult = getPushBaseResult();
        int baseBaseCount = parseBaseMessageCount(baseResult);
        int baseGrayCount = parseGrayMessageCount(baseResult);
        String grayResult = getPushGrayResult();
        int grayBaseCount = parseBaseMessageCount(grayResult);
        int grayGrayCount = parseGrayMessageCount(grayResult);
    }

    private void initAndProduceMessage(boolean isGrayInstanceInit, String consumerType)
            throws Exception {
        produceMessage(consumerType);
        if (isGrayInstanceInit) {
            Thread.sleep(150000);
        }
    }

    private String getPullBaseResult() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private String getPushBaseResult() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private String getLitePullBaseResult() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private String getPullGrayResult() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private String getPushGrayResult() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    private String getLitePullGrayResult() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 private void produceMessage(String consumerType) {
        String path = consumerType.equals(CONSUMER_TYPE_PULL) ? "producePullMessage" :
                consumerType.equals(CONSUMER_TYPE_LITE_PULL) ? "produceLitePullMessage" : "producePushMessage";
    }

    /** ARG-V: suitable */
	 private void createGrayscaleConfig(String consumeMode, String excludeTag) {
        String testModel = System.getProperty("grayscale.rocketmq.integration.test.type");
        String CONTENT = "enabled: true\n"
                + "grayscale:\n"
                + "  - consumerGroupTag: gray\n"
                + "    serviceMeta:\n"
                + "      version: 1.0.1\n"
                + "    trafficTag:\n"
                + "      x_lane_canary: gray\n"
                + "base:\n"
                + "  autoCheckDelayTime: 5\n"
                + "  consumeMode: " + consumeMode + "\n"
                + "  excludeGroupTags: [\""+ excludeTag + "\"]\n";
    }

    public void deleteGrayscaleConfig() {
        try {
            TimeUnit.SECONDS.sleep(2);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.testPluginEnabledFalseConsumeMessage();
		instance.testPluginEnabledFalsePull();
		instance.testPluginEnabledFalseLitePull();
		instance.testPluginEnabledFalsePush();
		instance.parseBaseMessageCount(Verifier.nondetString());
		instance.parseGrayMessageCount(Verifier.nondetString());
		instance.testAutoOnlyBaseConsumeMessage();
		instance.testAutoOnlyBasePull();
		instance.testAutoOnlyBaseLitePull();
		instance.testAutoOnlyBasePush();
		instance.testAutoExcOnlyBaseConsumeMessage();
		instance.testAutoExcOnlyBasePull();
		instance.testAutoExcOnlyBaseLitePull();
		instance.testAutoExcOnlyBasePush();
		instance.testAutoBaseGrayConsumeMessage();
		instance.testAutoBaseGrayPull();
		instance.testAutoBaseGrayLitePull();
		instance.testAutoBaseGrayPush();
		instance.testAutoExcBaseGrayConsumeMessage();
		instance.testAutoExcBaseGrayPull();
		instance.testAutoExcBaseGrayLitePull();
		instance.testAutoExcBaseGrayPush();
		instance.testBaseOnlyBaseConsumeMessage();
		instance.testBaseOnlyBasePull();
		instance.testBaseOnlyBaseLitePull();
		instance.testBaseOnlyBasePush();
		instance.testBaseExcOnlyBaseConsumeMessage();
		instance.testBaseExcOnlyBasePull();
		instance.testBaseExcOnlyBaseLitePull();
		instance.testBaseExcOnlyBasePush();
		instance.testBaseBaseGrayConsumeMessage();
		instance.testBaseBaseGrayPull();
		instance.testBaseBaseGrayLitePull();
		instance.testBaseBaseGrayPush();
		instance.testBaseExcBaseGrayConsumeMessage();
		instance.testBaseExcBaseGrayPull();
		instance.testBaseExcBaseGrayLitePull();
		instance.testBaseExcBaseGrayPush();
		instance.initAndProduceMessage(Verifier.nondetBoolean(), Verifier.nondetString());
		instance.getPullBaseResult();
		instance.getPushBaseResult();
		instance.getLitePullBaseResult();
		instance.getPullGrayResult();
		instance.getPushGrayResult();
		instance.getLitePullGrayResult();
		instance.produceMessage(Verifier.nondetString());
		instance.createGrayscaleConfig(Verifier.nondetString(), Verifier.nondetString());
		instance.deleteGrayscaleConfig();
	}
}
