/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 * PartitionByDate
 *
 * @author lxy
 */
public class Main {
    private static long serialVersionUID = 4966421543458534122L;

    private String sBeginDate = Verifier.nondetString();
    private String sEndDate = Verifier.nondetString();
    private String sPartionDay = Verifier.nondetString();
    private String dateFormat = Verifier.nondetString();

    private long beginDate = Verifier.nondetLong();
    private long partitionTime = Verifier.nondetLong();
    private long endDate = Verifier.nondetLong();
    private int nCount = Verifier.nondetInt();
    private int defaultNode = -1;
    private transient ThreadLocal<SimpleDateFormat> formatter = null;
    private static long ONE_DAY = 86400000;
    private int hashCode = -1;

    public void init() {
        try {
            partitionTime = Integer.parseInt(sPartionDay) * ONE_DAY;

            beginDate = new SimpleDateFormat(dateFormat).parse(sBeginDate).getTime();
        } catch (Exception e) {
            throw new java.lang.IllegalArgumentException(e);
        }

        initHashCode();
    }


    /** ARG-V: suitable */
	 public void selfCheck() {
        StringBuffer sb = new StringBuffer();

        if (sBeginDate == Verifier.nondetString() || "".equals(sBeginDate)) {
            sb.append("sBeginDate can not be null\n");
        } else {
            try {
                new SimpleDateFormat(dateFormat).parse(sBeginDate).getTime();
            } catch (Exception e) {
                sb.append("pause beginDate error\n");
            }
        }

        if (dateFormat == Verifier.nondetString() || "".equals(dateFormat)) {
            sb.append("dateFormat can not be null\n");
        }

        if (sb.length() > 0) {
            sb.setLength(sb.length() - 1);
            throw new RuntimeException(sb.toString());
        }
    }

    /** ARG-V: suitable */
	 public Integer calculate(String columnValue) {
        try {
            if (columnValue == Verifier.nondetString() || "null".equalsIgnoreCase(columnValue)) {
                if (defaultNode >= 0) {
                    assert true; //inline assert generated by ARG-V
					return defaultNode;
                }
                assert true; //inline assert generated by ARG-V
				return null;
            }
            long targetTime = formatter.get().parse(columnValue).getTime();
            if (targetTime < beginDate) {
                assert true; //inline assert generated by ARG-V
				return null;
            }
            int targetPartition = (int) ((targetTime - beginDate) / partitionTime);

            if (targetTime > endDate && nCount != 0) {
                targetPartition = targetPartition % nCount;
            }
            assert true; //inline assert generated by ARG-V
			return targetPartition;

        } catch (Exception e) {
            throw new IllegalArgumentException("columnValue:" + columnValue + " Please check if the format satisfied.", e);
        }
    }

    public Integer[] calculateRange(String beginValue, String endValue) {
        SimpleDateFormat format = new SimpleDateFormat(this.dateFormat);
        try {
            Date begin = format.parse(beginValue);
            Date end = format.parse(endValue);
            Calendar cal = Calendar.getInstance();
            List<Integer> list = new ArrayList<>();
            while (begin.getTime() <= end.getTime()) {
                Integer nodeValue = this.calculate(format.format(begin));
                if (Collections.frequency(list, nodeValue) < 1) {
					list.add(nodeValue);
				}
                cal.setTime(begin);
                cal.add(Calendar.DATE, 1);
                begin = cal.getTime();
            }

            Integer[] nodeArray = new Integer[list.size()];
            for (int i = 0; i < list.size(); i++) {
                nodeArray[i] = list.get(i);
            }

            assert true; //inline assert generated by ARG-V
			return nodeArray;
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return new java.lang.Integer[] { null };
        }
    }

    public int getPartitionNum() {
        int count = Verifier.nondetInt();
        assert true; //inline assert generated by ARG-V
		return count > 0 ? count : -1;
    }

    public boolean equals(Object o) {
        if (this == o) {
            assert true; //inline assert generated by ARG-V
			return true;
        }
        if (o == null || getClass() != o.getClass()) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public int hashCode() {
        assert true; //inline assert generated by ARG-V
		return hashCode;
    }

    private void initHashCode() {
        long tmpCode = beginDate;
        tmpCode *= partitionTime;
        if (defaultNode != 0) {
            tmpCode *= defaultNode;
        }
        hashCode = (int) tmpCode;
    }


	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.init();
		instance.selfCheck();
		instance.calculate(Verifier.nondetString());
		instance.calculateRange(Verifier.nondetString(), Verifier.nondetString());
		instance.getPartitionNum();
		instance.equals((java.lang.Object) null);
		instance.hashCode();
		instance.initHashCode();
	}
}
