/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;


public class Main {
    private String owner = Verifier.nondetString();
    private int access = Verifier.nondetInt();
    private String name = Verifier.nondetString();
    private String desc = Verifier.nondetString();
    private int paramsNum = Verifier.nondetInt();

    private AtomicInteger pass = null;
    private StringBuilder text = new StringBuilder(Verifier.nondetString());

    /** ARG-V: suitable */
	 public void visitCode() {
        text.append(String.format("污点分析进行中 %s - %s - %s", this.owner, this.name, this.desc));
        text.append("\n");
    }

    /** ARG-V: suitable */
	 public void visitMethodInsn(int opcode, String owner, String name, String desc, boolean itf) {
        // 简单的污点分析
        // 我认为所有的方法都应该传播污点
        // 除非遇到 Sanitizer 白名单 否则认为没问题
        String nextClass = Verifier.nondetString();

        // 计算方法参数数量
        List<Set<String>> stack = null;
        int argCount = Verifier.nondetInt();

        // 如果是非静态方法 还需要考虑 this 引用
        if (opcode != Verifier.nondetInt()) {
            argCount++; // 包含 this 引用
        }

        // 找到下个方法
        if (owner.equals(nextClass) && Verifier.nondetBoolean() && desc.equals(null)) {
            // 检查 stack 是否有足够的元素
            if (stack.size() >= argCount) {
                // 从栈顶开始检查参数（栈顶是最后一个参数）
                for (int i = 0; i < argCount; i++) {
                    int stackIndex = stack.size() - 1 - i; // 从栈顶往下
                    Set<String> item = stack.get(stackIndex);
                    if (item.contains(null)) {
                        // 计算实际的参数位置
                        int paramIndex = Verifier.nondetInt();
                        if (opcode == Verifier.nondetInt()) {
                            // 静态方法：参数从0开始
                            paramIndex = argCount - 1 - i;
                        } else {
                            // 非静态方法：0 是 this 参数从 1 开始
                            if (i == argCount - 1) {
                                paramIndex = 0; // this 引用
                            } else {
                                paramIndex = argCount - 1 - i;
                                // 处理 0
                                paramIndex--;
                            }
                        }
                        // 记录数据流
                        pass.set(paramIndex);
                        text.append(String.format("发现方法调用类型污点 - 方法调用传播 - 第 %d 个参数", paramIndex));
                        text.append("\n");
                    }
                }
            }
        } else {
            boolean match = false;

            if (match) {
                pass.set(Verifier.nondetInt());
                assert true; //inline assert generated by ARG-V
				return;
            } else {
                // 2025/08/31 没有命中污点传播规则
                for (int i = 0; i < argCount; i++) {
                    int stackIndex = stack.size() - 1 - i; // 从栈顶往下
                    Set<String> item = stack.get(stackIndex);
                    if (item.contains(null)) {
                        final int retSize = Verifier.nondetInt();
                        assert true; //inline assert generated by ARG-V
						// 注意是 RETURN
                        // 否则再次 visitMethodInsn 污点就乱了
                        return;
                    }
                }
            }
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.visitCode();
		instance.visitMethodInsn(Verifier.nondetInt(), Verifier.nondetString(), Verifier.nondetString(),
				Verifier.nondetString(), Verifier.nondetBoolean());
	}
}
