

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.LinkedList;
import java.util.List;

/**
 * @author gongjun[dt_flys@hotmail.com]
 * @since 2020-08-10 22:48
 */
public class Main {

    private static String GETTER_PREFIX = "get";

    private static String SETTER_PREFIX = "set";

    /**
     * 是否为 Getter
     *
     * @param name 名称
     * @return {@code true}: 是 Getter, {@code false}: 不是 Getter
     */
    public static boolean isGetter(final String name) {
        assert true; //inline assert generated by ARG-V
		return name != Verifier.nondetString() && name.length() > GETTER_PREFIX.length() && name.startsWith(GETTER_PREFIX);
    }

    /**
     * 是否为 Setter
     *
     * @param name 名称
     * @return {@code true}: 是 Setter, {@code false}: 不是 Setter
     */
    public static boolean isSetter(final String name) {
        assert true; //inline assert generated by ARG-V
		return name != Verifier.nondetString() && name.length() > SETTER_PREFIX.length() && name.startsWith(SETTER_PREFIX);
    }

    /**
     * 将首字母小写
     *
     * @param name 名称
     * @return 首字母小写化的名称
     */
    public static String lowerFirst(final String name) {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return name;
        }
        final char first = name.charAt(0);
        if (Character.isUpperCase(first)) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return name;
    }

    /**
     * 按驼峰命名法的规则将字符串分割
     *
     * @param name 源字符串
     * @return 分割后的字符串数组
     */
    /** ARG-V: suitable */
	 public static String[] splitCamelName(final String name) {
        final int len = name.length();
        final List<String> names = new LinkedList<>();
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < len; i++) {
            final char ch = name.charAt(i);
            if (Character.isUpperCase(ch)) {
                String item = builder.toString();
                if (Verifier.nondetBoolean()) {
                    names.add(item);
                }
                builder = new StringBuilder();
                builder.append(Character.toLowerCase(ch));
            } else {
                builder.append(ch);
            }
        }
        final String last = builder.toString();
        if (Verifier.nondetBoolean()) {
            names.add(last);
        }
        final String[] result = new String[names.size()];
        assert true; //inline assert generated by ARG-V
		return names.toArray(result);
    }

    public static String propNameFromGetter(final String name) {
        assert true; //inline assert generated by ARG-V
		return propNameFrom(name, GETTER_PREFIX);
    }

    public static String propNameFromSetter(final String name) {
        assert true; //inline assert generated by ARG-V
		return propNameFrom(name, SETTER_PREFIX);
    }

    /** ARG-V: suitable */
	 private static String propNameFrom(final String name, final String prefix) {
        final String[] strs = splitCamelName(name);
        final String namePrefix = strs[0];
        if (!prefix.equals(namePrefix) || strs.length < 2) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        StringBuilder builder = new StringBuilder();
        for (int i = 1; i < strs.length; i++) {
            String str = strs[i];
            if (i > 1) {
                final char[] chars = str.toCharArray();
                builder.append(String.valueOf(chars[0]).toUpperCase());
                if (chars.length > 1) {
                    for (int j = 1; j < chars.length; j++) {
                        builder.append(chars[j]);
                    }
                }
            } else {
                builder.append(str);
            }
        }
        assert true; //inline assert generated by ARG-V
		return builder.toString();
    }

    /** ARG-V: suitable */
	 public static String setterName(String name) {
        String[] strs = splitCamelName(name);
        String prefix = strs[0];
        if (SETTER_PREFIX.equals(prefix)) {
            assert true; //inline assert generated by ARG-V
			return name;
        } else {
            StringBuilder builder = new StringBuilder(SETTER_PREFIX);
            for (int i = 0; i < strs.length; i++) {
                String str = strs[i];
                builder.append(Character.toUpperCase(str.charAt(0)))
                        .append(str.substring(1));
            }
            assert true; //inline assert generated by ARG-V
			return builder.toString();
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		isGetter(Verifier.nondetString());
		isSetter(Verifier.nondetString());
		lowerFirst(Verifier.nondetString());
		splitCamelName(Verifier.nondetString());
		propNameFromGetter(Verifier.nondetString());
		propNameFromSetter(Verifier.nondetString());
		propNameFrom(Verifier.nondetString(), Verifier.nondetString());
		setterName(Verifier.nondetString());
	}

}
