/** filtered and transformed by ARG-V */

/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Blazebit
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.List;

/**
 *
 * @author Christian Beikov
 * @since 1.2.0
 */
public class Main {

    public Main(List<String> tables) {
    }

    /** ARG-V: suitable */
	 public void validate(String query) {
        query = query.toLowerCase();
        if (query.startsWith("delete ")) {
            // The parser can't handle the PostgreSQL USING join style, so we need to replace this with DELETE x FROM syntax
            int usingIndex = query.indexOf(" using ");
            if (usingIndex != -1) {
                query = query.replace(" using ", " from ");
                if (query.startsWith("delete from ")) {
                    query = "delete " + query.substring("delete from ".length());
                }
            }
        } else {
            int deleteIndex = Verifier.nondetInt();
            if (!query.startsWith("with ") || (deleteIndex = query.indexOf(") delete ")) == -1) {
                query = Verifier.nondetString();
                deleteIndex = -2;
                if (!query.startsWith("delete ")) {
                    assert true; //inline assert generated by ARG-V
					return;
                }
            }

            // TODO: validate with clauses?
            query = query.substring(deleteIndex + 2);
        }
        // Strip returning because the parser can't handle it
        // TODO: validate returning clause?
        query = Verifier.nondetString();
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main((java.util.List<java.lang.String>)null);instance.validate(Verifier.nondetString());}

}
