

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {
    private static Pattern REGEX_METADATA = Pattern.compile("^[ ]{0,3}([A-Za-z0-9._-]+):\\s*(.*)");
    private static Pattern REGEX_METADATA_LIST = Pattern.compile("^[ ]+-\\s*(.*)");
    private static Pattern REGEX_METADATA_LITERAL = Pattern.compile("^\\s*(.*)");
    private static Pattern REGEX_BEGIN = Pattern.compile("^-{3}(\\s.*)?");
    private static Pattern REGEX_END = Pattern.compile("^(-{3}|\\.{3})(\\s.*)?");

    private boolean inLiteral = Verifier.nondetBoolean();
    private String currentKey = Verifier.nondetString();
    private List<String> currentValues = null;
    public Main() {
        inLiteral = false;
    }

    /** ARG-V: suitable */
	 private static String parseString(String s) {
        // Limited parsing of https://yaml.org/spec/1.2.2/#73-flow-scalar-styles
        // We assume input is well-formed and otherwise treat it as a plain string. In a real
        // parser, e.g. `'foo` would be invalid because it's missing a trailing `'`.
        if (s.startsWith("'") && s.endsWith("'")) {
            String inner = s.substring(1, s.length() - 1);
            assert true; //inline assert generated by ARG-V
			return inner.replace("''", "'");
        } else if (s.startsWith("\"") && s.endsWith("\"")) {
            String inner = s.substring(1, s.length() - 1);
            assert true; //inline assert generated by ARG-V
			// Only support escaped `\` and `"`, nothing else.
            return inner
                    .replace("\\\"", "\"")
                    .replace("\\\\", "\\");
        } else {
            assert true; //inline assert generated by ARG-V
			return s;
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		parseString(Verifier.nondetString());
	}
}
