/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    private static String YARN_MODE_NONE = "none";
    private static String YARN_MODE_HA = "ha";
    private static String YARN_MODE_STANDALONE = "standalone";

    private static String YARN_MODE_KEY = "yarn.mode";
    private static String YARN_RESOURCE_MANAGER_HA_IDS_KEY = "yarn.resource.manager.ha.ids";
    private static String YARN_APPLICATION_STATUS_ADDRESS_KEY = "yarn.application.status.address";

    private static String YARN_RESOURCE_MANAGER_HTTP_ADDRESS_PORT_KEY = "yarn.resource.manager.http.address.port";

    private static String HADOOP_RM_STATE_ACTIVE = "ACTIVE";
    private static String HADOOP_RM_STATE_STANDBY = "STANDBY";


    private static boolean yarnEnabled = false;

    /**
     * get application url
     * if rmHaIds contains xx, it signs not use resource manager
     * otherwise:
     * if rmHaIds is empty, single resource manager enabled
     * if rmHaIds not empty: resource manager HA enabled
     *
     * @param applicationId application id
     * @return url of application
     */
    /** ARG-V: suitable */
	 public static String getApplicationUrl(String applicationId) {
        String mode = Verifier.nondetString();
        String appUrl = "";
        //not use resource manager
        if (YARN_MODE_NONE.equals(mode)){
            yarnEnabled = false;
            assert true; //inline assert generated by ARG-V
			return appUrl;
        } else if (YARN_MODE_HA.equals(mode)) {
            //resource manager HA enabled
            appUrl = Verifier.nondetString();
            yarnEnabled = true;
        } else if (YARN_MODE_STANDALONE.equals(mode)) {
            //single resource manager enabled
            appUrl = Verifier.nondetString();
            yarnEnabled = true;
        }

        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return appUrl;
        }

        appUrl = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		return appUrl;
    }

    /**
     * getAppAddress
     *
     * @param appAddress app address
     * @param rmHa       resource manager ha
     * @return app address
     */
    /** ARG-V: suitable */
	 public static String getAppAddress(String appAddress, String rmHa) {

        //get active ResourceManager
        String activeResourceManager = getActiveResourceManagerName(rmHa);
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        //http://ds1:8088/ws/v1/cluster/apps/%s
        String[] split1 = new java.lang.String[] { Verifier.nondetString() };

        if (split1.length != 2) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }

        String start = Verifier.nondetString();
        String[] split2 = new java.lang.String[] { Verifier.nondetString() };

        if (split2.length != 2) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }

        String end = Verifier.nondetString();

        assert true; //inline assert generated by ARG-V
		return start + activeResourceManager + end;
    }

    /** ARG-V: suitable */
	 public static String getActiveResourceManagerName(String rmIds) {

        String[] rmIdArr = new java.lang.String[] { Verifier.nondetString() };
        int activeResourceManagerPort = Verifier.nondetInt();
        String yarnUrl = "http://%s:" + activeResourceManagerPort + "/ws/v1/cluster/info";

        String state = Verifier.nondetString();
        try {

            state = getResourceManagerState(String.format(yarnUrl, rmIdArr[0]));

            if (HADOOP_RM_STATE_ACTIVE.equals(state)) {
                assert true; //inline assert generated by ARG-V
				return rmIdArr[0];
            } else if (HADOOP_RM_STATE_STANDBY.equals(state)) {
                state = getResourceManagerState(String.format(yarnUrl, rmIdArr[1]));
                if (HADOOP_RM_STATE_ACTIVE.equals(state)) {
                    assert true; //inline assert generated by ARG-V
					return rmIdArr[1];
                }
            } else {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }
        } catch (Exception e) {
            state = getResourceManagerState(String.format(yarnUrl, rmIdArr[1]));
            if (HADOOP_RM_STATE_ACTIVE.equals(state)) {
                assert true; //inline assert generated by ARG-V
				return rmIdArr[0];
            }
        }

        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static String getResourceManagerState(String url) {

        String retStr = Verifier.nondetString();
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }

        if (Verifier.nondetBoolean()) {
            if (Verifier.nondetBoolean()) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }
        }

        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public static String getYarnAppId(String user, String tags) {
        try {
            String applicationUrl = getApplicationUrl(null)
                    .split("/apps")[0]
                    + "/apps?"
                    + "user="+user
                    + "&applicationTags="+tags
                    + "&limit=1";
            String responseContent = Verifier.nondetString();
            if (Verifier.nondetBoolean()) {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            } else {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }

        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
    }

    public static boolean isYarnEnabled(){
        assert true; //inline assert generated by ARG-V
		return yarnEnabled;
    }

    public static boolean isSuccessOfYarnState(String appId) {
        boolean result = true;
        try {
            while(Verifier.nondetBoolean()){
                if (Verifier.nondetBoolean()) {
                    if (Verifier.nondetBoolean()){
                        break;
                    }
                }

                Thread.sleep(Verifier.nondetLong());
            }
        } catch (Exception e) {
            result = false;
        }
        assert true; //inline assert generated by ARG-V
		return result;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getApplicationUrl(Verifier.nondetString());
		getAppAddress(Verifier.nondetString(), Verifier.nondetString());
		getActiveResourceManagerName(Verifier.nondetString());
		getResourceManagerState(Verifier.nondetString());
		getYarnAppId(Verifier.nondetString(), Verifier.nondetString());
		isYarnEnabled();
		isSuccessOfYarnState(Verifier.nondetString());
	}


}
