/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2019-2024 qwq233 <qwq233@qwq2333.top>
 * https://github.com/qwq233/Nullgram
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this software.
 *  If not, see
 * <https://www.gnu.org/licenses/>
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;

public class Main {

    public static int DIRECTION_TO_BOTTOM = 0;
    public static int DIRECTION_TO_TOP = 1;

    private int currentAccount = Verifier.nondetInt();
    private int direction = DIRECTION_TO_BOTTOM;
    private int horizontalPadding = Verifier.nondetInt();

    private boolean show = Verifier.nondetBoolean(), forceClose = Verifier.nondetBoolean();
    private boolean clear = Verifier.nondetBoolean();
    private boolean isCopyForbidden = Verifier.nondetBoolean();
    private boolean isSetAsStatusForbidden = Verifier.nondetBoolean();

    public void forbidCopy() {
        isCopyForbidden = true;
    }

    public void forbidSetAsStatus() {
        isSetAsStatusForbidden = true;
    }

    private void createListView() {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    public boolean isShown() {
        assert true; //inline assert generated by ARG-V
		return show;
    }

    public int getDirection() {
        assert true; //inline assert generated by ARG-V
		return direction;
    }

    public void forceClose() {
        show = false;
        forceClose = true;
    }

    private Runnable updateRunnable = null;
    private void update() {
        int selectionStart = Verifier.nondetInt();
        int selectionEnd = Verifier.nondetInt();
        if (selectionStart != selectionEnd) {
            show = false;
            assert true; //inline assert generated by ARG-V
			return;
        }
        CharSequence text = null;
        show = false;
    }

    private int lastQueryType = Verifier.nondetInt();
    private String lastQuery = Verifier.nondetString();
    private int lastQueryId = Verifier.nondetInt();
    private String[] lastLang = new java.lang.String[] { Verifier.nondetString() };
    private Runnable searchRunnable = null;
    private long lastLangChangedTime = 0;

    /**
     * The user needs time to change the locale. We estimate this time to be at least 360 ms.
     */
    private String[] detectKeyboardLangThrottleFirstWithDelay() {
        long currentTime = System.currentTimeMillis();
        int delay = 360;
        if (lastLang == null || Math.abs(currentTime - lastLangChangedTime) > delay) {
            lastLangChangedTime = currentTime;
            assert true; //inline assert generated by ARG-V
			return new java.lang.String[] { Verifier.nondetString() };
        } else {
            lastLangChangedTime = currentTime;
        }
        assert true; //inline assert generated by ARG-V
		return new java.lang.String[] { Verifier.nondetString() };
    }

    private void searchKeywords(String query) {
        if (query == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        final int id = ++lastQueryId;
        String[] lang = detectKeyboardLangThrottleFirstWithDelay();
    }

    private void searchAnimated(String emoji) {
        if (emoji == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        final int id = ++lastQueryId;
    }

    private CharSequence makeEmoji(String emojiSource) {
        CharSequence emoji = null;
        if (emojiSource != Verifier.nondetString() && emojiSource.startsWith("animated_")) {
            try {
                long documentId = Long.parseLong(emojiSource.substring(9));
                emoji = Verifier.nondetString();
            } catch (Exception e) {
                assert true; //inline assert generated by ARG-V
				return null;
            }
        } else {
            emoji = emojiSource;
            emoji = Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return emoji;
    }

    /** ARG-V: suitable */
	 private void onClick(String emojiSource) {
        int start = Verifier.nondetInt(), end = Verifier.nondetInt();
        if (Verifier.nondetBoolean()) {
            start = Verifier.nondetInt();
            end = Verifier.nondetInt();
        } else if (arrowToStart != null && arrowToEnd != null) {
            start = arrowToStart;
            end = arrowToEnd;
        } else {
            assert true; //inline assert generated by ARG-V
			return;
        }
        String fromString = Verifier.nondetString();
        String replacing = fromString.substring(start, end);
        int replacingLength = replacing.length();
        for (int i = end - replacingLength; i >= 0; i -= replacingLength) {
            if (fromString.substring(i, i + replacingLength).equals(replacing)) {
                CharSequence emoji = makeEmoji(emojiSource);
                if (emoji != Verifier.nondetString()) {
                    if (Verifier.nondetBoolean()) {
                        break;
                    }
                } else {
                    break;
                }
            } else {
                break;
            }
        }
        try {
        } catch (Exception e) {}
        show = false;
        forceClose = true;
        lastQueryType = 0;
    }

    private float lastSpanY = Verifier.nondetFloat();
    private Integer arrowToStart = null, arrowToEnd = null;
    private float arrowX = Verifier.nondetFloat();
    protected int emojiCacheType() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.forbidCopy();
		instance.forbidSetAsStatus();
		instance.createListView();
		instance.isShown();
		instance.getDirection();
		instance.forceClose();
		instance.update();
		instance.detectKeyboardLangThrottleFirstWithDelay();
		instance.searchKeywords(Verifier.nondetString());
		instance.searchAnimated(Verifier.nondetString());
		instance.makeEmoji(Verifier.nondetString());
		instance.onClick(Verifier.nondetString());
		instance.emojiCacheType();
	}
}
