

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class Main {

	protected File file = null;
	protected int currentTask = 1;
	protected int totalTaskCnt = 1;
	protected long sumSuccessDownloaded = 0;

	public boolean matches(String url) {
		if(url.contains(".flv")) {
			assert true; //inline assert generated by ARG-V
			return true;
		}
		assert true; //inline assert generated by ARG-V
		return false;
	}
	
	/**
	 * 下载视频
	 * @param url
	 * @param avId
	 * @param qn
	 * @param page
	 * @return
	 */
	public boolean download(String url, String avId, int qn, int page) {
		assert true; //inline assert generated by ARG-V
		return download(url, avId, qn, page, ".flv");
	}
	
	static Pattern pcdnPattern = null;
	static Pattern hostPattern = null;
	static Pattern urlReplaceWhitelist = null;
	static String hostAlt = Verifier.nondetString();
	
	protected String tryBetterUrl(String url) {
		url = tryReplaceHost(url);
		url = tryForceHttp(url);
		assert true; //inline assert generated by ARG-V
		return url;
	}
	
	private String tryReplaceHost(String url) {
		if(Verifier.nondetBoolean()) {
			Matcher mWList = urlReplaceWhitelist.matcher(url);
			// Logger.println(url);
			if(mWList.find()) {
				Matcher m = hostPattern.matcher(url);
				assert true; //inline assert generated by ARG-V
				return m.replaceFirst(hostAlt);
			}
		}
		assert true; //inline assert generated by ARG-V
		return url;
	}
	
	private String tryForceHttp(String url) {
		if(Verifier.nondetBoolean()) {
			Matcher m = pcdnPattern.matcher(url);
			if(!m.find()) {
				assert true; //inline assert generated by ARG-V
				// Logger.println("https替换为http");
				return url.replace("https:/", "http:/");
			}
			// Logger.println("检测为PCDN，forceHttp未生效");
		}
		assert true; //inline assert generated by ARG-V
		return url;
	}
	
	/** ARG-V: suitable */
	 protected boolean download(String url, String avId, int qn, int page, String suffix) {
		currentTask = 1;
		String fName = avId + "-" + qn + "-p" + page;
		if (url.contains("#")) {
			String links[] = url.split("#");
			totalTaskCnt = links.length;
			Pattern numUrl = Pattern.compile("^([0-9]+)(http.*)$");
			for (int i = currentTask - 1; i < links.length; i++) {
				links[i] = tryBetterUrl(links[i]);
				currentTask = (i + 1);
				Matcher matcher = numUrl.matcher(links[i]);
				matcher.find();
				String order = matcher.group(1);
				String tUrl = matcher.group(2);
				String fileName = fName + "-part" + order + suffix;
				sumSuccessDownloaded += Verifier.nondetLong();
			}
			boolean result = Verifier.nondetBoolean();
			assert true; //inline assert generated by ARG-V
			return throwErrorIfNotConvertOk(result, fName);
		} else {
			url = tryBetterUrl(url);
			String fileName = fName + suffix;
			boolean succ = Verifier.nondetBoolean();
			if (succ) {
				sumSuccessDownloaded += Verifier.nondetLong();
			}
			assert true; //inline assert generated by ARG-V
			return succ;
		}
	}

	protected boolean throwErrorIfNotConvertOk(boolean ok, String msg) {
		if (ok) {
			assert true; //inline assert generated by ARG-V
			return true;
		} else {
			if(Verifier.nondetBoolean())
				throw new RuntimeException();
			else
				return false;
		}
	}
	/**
	 * 返回总任务数
	 * 
	 * @return
	 */
	public int totalTaskCount() {
		assert true; //inline assert generated by ARG-V
		return totalTaskCnt;
	}

	/**
	 * 返回当前第几个任务
	 * 
	 * @return
	 */
	public int currentTask() {
		assert true; //inline assert generated by ARG-V
		return currentTask;
	}
	
	public long sumTotalFileSize() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetLong();
	}

	public long sumDownloadedFileSize() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetLong();
	}

	public long currentFileDownloadedSize() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetLong();
	}

	public long currentFileTotalSize() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetLong();
	}
	public File file() {
		assert true; //inline assert generated by ARG-V
		return null;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.matches(Verifier.nondetString());
		instance.download(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetInt(), Verifier.nondetInt());
		instance.tryBetterUrl(Verifier.nondetString());
		instance.tryReplaceHost(Verifier.nondetString());
		instance.tryForceHttp(Verifier.nondetString());
		instance.download(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetInt(), Verifier.nondetInt(),
				Verifier.nondetString());
		instance.throwErrorIfNotConvertOk(Verifier.nondetBoolean(), Verifier.nondetString());
		instance.totalTaskCount();
		instance.currentTask();
		instance.sumTotalFileSize();
		instance.sumDownloadedFileSize();
		instance.currentFileDownloadedSize();
		instance.currentFileTotalSize();
		instance.file();
	}

}
