/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
  /** ARG-V: suitable */
 public void run() throws RuntimeException {
    

    // First get an application report to ensure that the AM is,
    // in fact, running, and to get the HTTP endpoint.

    try {
    } catch (Exception e) {
    }
    String prefix = Verifier.nondetString();
    int quantity = Verifier.nondetInt();
    String cmd = Verifier.nondetString();
    if (prefix.equals("+")) {
      cmd = "grow";
      if (Verifier.nondetBoolean()) {
        System.out.println("Growing cluster by " + quantity + " nodes.");
      }
    } else if (prefix.equals("-")) {
      cmd = "shrink";
      if (Verifier.nondetBoolean()) {
        System.out.println("Shrinking cluster by " + quantity + " nodes.");
      }
    } else {
      cmd = "resize";
      if (Verifier.nondetBoolean()) {
        System.out.println("Resizing cluster to " + quantity + " nodes.");
      }
    }
    if (sendResize(Verifier.nondetString(), cmd, quantity)) {
      System.out.println("Use web UI or status command to check progress.");
    }
  }

  /** ARG-V: suitable */
 private boolean sendResize(String baseUrl, String cmd, int quantity) {
    try {
      if (Verifier.nondetBoolean()) {
        assert true; //inline assert generated by ARG-V
		return false;
      }
      String tail = "rest/" + cmd + "/" + quantity;
      String masterKey = Verifier.nondetString();
      if (Verifier.nondetBoolean()) {
        System.out.println("Resizing with POST " + baseUrl + "/" + tail);
      }
      String result = Verifier.nondetString();

      Object response = null;
      try {
        response = null;
      } catch (Exception e) {
        System.err.println("Invalid response received from AM");
        if (Verifier.nondetBoolean()) {
          System.out.println(result);
          System.out.println(new char[] { Verifier.nondetChar() });
        }
        assert true; //inline assert generated by ARG-V
		return false;
      }
      if ("ok".equals(null)) {
        assert true; //inline assert generated by ARG-V
		return true;
      }
      System.err.println("Failed to resize the application master.");
      assert true; //inline assert generated by ARG-V
	return false;
    } catch (Exception e) {
      assert true; //inline assert generated by ARG-V
	return false;
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.run();
	instance.sendResize(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetInt());
}

}
