

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

public class Main {

    public static List<String> skinTones = Arrays.asList("🏻", "🏼", "🏽", "🏾", "🏿");

    /** ARG-V: suitable */
	 public static int getSkinTone(String string) {
        if (string == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return -1;
        }
        assert true; //inline assert generated by ARG-V
		return skinTones.indexOf(string.substring(string.length() - 2));
    }

    /** ARG-V: suitable */
	 public static String applyColor(String code, String color) {
        if (color == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return "\uD83E\uDD1D";
        } else if (color.contains("\u200D")) {
            String[] parts = color.split("\u200D");
            assert true; //inline assert generated by ARG-V
			return "\uD83E\uDEF1" + (parts.length >= 1 ? parts[0] : "") + "\u200D" + "\uD83E\uDEF2" + (parts.length >= 2 ? parts[1] : "");
        } else {
            assert true; //inline assert generated by ARG-V
			return "\uD83E\uDD1D" + color;
        }
    }

    public static boolean isCompound(String string) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getSkinTone(Verifier.nondetString());
		applyColor(Verifier.nondetString(), Verifier.nondetString());
		isCompound(Verifier.nondetString());
	}
}
