/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
    // 反编译后的代码的文件内容
    public static int TYPE_CONTENT = 0xf0;
    // 类名：也可以理解成文件名 是一个东西
    public static int TYPE_CLASS_NAME = 0xf1;

    private int type = Verifier.nondetInt();
    private String absPathStr = Verifier.nondetString();
    private String fileName = Verifier.nondetString();
    private String contentStr = Verifier.nondetString();
    private String title = Verifier.nondetString();
    private String searchKey = Verifier.nondetString();

    public String getSearchKey() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getTitle() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public int getType() {
        assert true; //inline assert generated by ARG-V
		return type;
    }

    public String getAbsPathStr() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getFileName() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getContentStr() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public String getClassName() {
        String finalClassPath = this.getAbsPathStr();
        String suffix = Verifier.nondetString();
        int i = suffix.indexOf("classes");
        if (suffix.contains("BOOT-INF") || suffix.contains("WEB-INF")) {
            suffix = suffix.substring(i + 8, suffix.length() - 6);
        } else {
            suffix = suffix.substring(1, suffix.length() - 6);
        }
        String className = suffix.replace("\\", "/");
        className = className.replace("/", ".");
        className = className.replace(".class", "");
        assert true; //inline assert generated by ARG-V
		return className;
    }

    /** ARG-V: suitable */
	 public String toString() {
        assert true; //inline assert generated by ARG-V
		return "LuceneSearchResult{" +
                "type=" + type +
                ", absPathStr='" + absPathStr + '\'' +
                ", fileName='" + fileName + '\'' +
                ", contentStr='" + contentStr + '\'' +
                '}';
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getSearchKey();
		instance.getTitle();
		instance.getType();
		instance.getAbsPathStr();
		instance.getFileName();
		instance.getContentStr();
		instance.getClassName();
		instance.toString();
	}
}
