

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Map;

public class Main {

    void recordDirectAttributionInternal(String campaignType, String campaignData) {
        if (campaignType == Verifier.nondetString() || campaignType.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (campaignData == Verifier.nondetString() || campaignData.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (!campaignType.equals("countly") && !campaignType.equals("_special_test")) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        if (campaignType.equals("countly")) {
            reportLegacyInstallAttribution(campaignData);
        }
    }

    /** ARG-V: suitable */
	 void reportLegacyInstallAttribution(String campaignData) {
        try {
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        String campaignId = Verifier.nondetString();
        try {
            campaignId = Verifier.nondetString();

            if (campaignId.isEmpty()) {
                assert true; //inline assert generated by ARG-V
				return;
            }
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        String campaignUserId = Verifier.nondetString();

        try {
            if (Verifier.nondetBoolean()) {
                campaignUserId = Verifier.nondetString();

                if (campaignUserId.isEmpty()) {
                    campaignUserId = Verifier.nondetString();
                }
            }
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    void recordIndirectAttributionInternal(Map<String, String> attributionId) {
        if (attributionId == null || attributionId.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        String attributionObj = Verifier.nondetString();
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main();instance.recordDirectAttributionInternal(Verifier.nondetString(),Verifier.nondetString());instance.reportLegacyInstallAttribution(Verifier.nondetString());instance.recordIndirectAttributionInternal((java.util.Map<java.lang.String, java.lang.String>)null);}
}
