/** filtered and transformed by ARG-V */

/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Blazebit
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

/**
 *
 * @author Christian Beikov
 * @since 1.2.0
 */
public class Main {

    private List<String> fetchedTables = null;

    public Main(List<String> tables, List<String> fetchedTables) {
    }

    /** ARG-V: suitable */
	 public void validate(String query) {
        query = query.toLowerCase();
        if (!query.startsWith("select ")) {
            int selectIndex = Verifier.nondetInt();
            if (!query.startsWith("with ") || (selectIndex = query.indexOf(") select ")) == -1) {
                assert true; //inline assert generated by ARG-V
				return;
            }

            // TODO: validate with clauses?
            query = query.substring(selectIndex + 2);
        }
        if (!fetchedTables.isEmpty()) {
            List<String> fromElements = null;

            List<String> missingFromElements = new ArrayList<>(fetchedTables);
            ListIterator<String> iter = fromElements.listIterator();
            while (iter.hasNext()) {
                String element = iter.next();
                if (missingFromElements.remove(element)) {
                    iter.remove();
                }
            }
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main((java.util.List<java.lang.String>)null,(java.util.List<java.lang.String>)null);instance.validate(Verifier.nondetString());}

}
