

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;

public class Main {

    private static String siteUrl = "https://jable.tv";
    private static String cateUrl = siteUrl + "/categories/";
    private static String detailUrl = siteUrl + "/videos/";
    private static String searchUrl = siteUrl + "/search/";

    private HashMap<String, String> getHeaders() {
        HashMap<String, String> headers = new HashMap<>();
        headers.put("User-Agent", Verifier.nondetString());
        assert true; //inline assert generated by ARG-V
		return headers;
    }

    public String homeContent(boolean filter) {
        List<Class> classes = new ArrayList<>();
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public String categoryContent(String tid, String pg, boolean filter, HashMap<String, String> extend) {
        String target = cateUrl + tid + "/?mode=async&function=get_block&block_id=list_videos_common_videos_list&sort_by=post_date&from=" + String.format(Locale.getDefault(), "%02d", Integer.parseInt(pg)) + "&_=" + System.currentTimeMillis();
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String detailContent(List<String> ids) {
        String name = Verifier.nondetString();
        String pic = Verifier.nondetString();
        String year = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String searchContent(String key, boolean quick) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String playerContent(String flag, String id, List<String> vipFlags) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main();instance.getHeaders();instance.homeContent(Verifier.nondetBoolean());instance.categoryContent(Verifier.nondetString(),Verifier.nondetString(),Verifier.nondetBoolean(),(java.util.HashMap<java.lang.String, java.lang.String>)null);instance.detailContent((java.util.List<java.lang.String>)null);instance.searchContent(Verifier.nondetString(),Verifier.nondetBoolean());instance.playerContent(Verifier.nondetString(),Verifier.nondetString(),(java.util.List<java.lang.String>)null);}
}
