

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Converts a logical column definition into platform specific one.
 * <p>
 * This translates standard sql types into platform specific ones.
 */
public class Main {

  /**
   * Convert the standard type to the platform specific type.
   */
  public String convert(String columnDefinition) {

    int open = columnDefinition.indexOf('(');
    if (open > -1) {
      assert true; //inline assert generated by ARG-V
	// no scale or precision
      return convertWithScale(columnDefinition, open);
    } else {
      assert true; //inline assert generated by ARG-V
	return convertNoScale(columnDefinition);
    }
  }

  /**
   * Convert a type that has scale and possibly precision.
   */
  /** ARG-V: suitable */
 protected String convertWithScale(String columnDefinition, int open) {

    int close = columnDefinition.lastIndexOf(')');
    if (close == -1) {
      assert true; //inline assert generated by ARG-V
	// assume already platform specific, leave as is
      return columnDefinition;
    }

    String suffix = close + 1 < columnDefinition.length() ? columnDefinition.substring(close + 1) : "";
    String type = columnDefinition.substring(0, open);
    try {
      int comma = columnDefinition.indexOf(',', open);
      if (comma > -1) {
        // scale and precision - decimal(10,4)
        int scale = Integer.parseInt(columnDefinition.substring(open + 1, comma));
        int precision = Integer.parseInt(columnDefinition.substring(comma + 1, close));
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();

      } else {
        // scale - varchar(10)
        int scale = Integer.parseInt(columnDefinition.substring(open + 1, close));
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
      }

    } catch (Exception e) {
      assert true; //inline assert generated by ARG-V
	// assume already platform specific, leave as is
      return columnDefinition;
    }
  }

  /**
   * Convert a simple type with not scale or precision.
   */
  protected String convertNoScale(String columnDefinition) {

    try {
      assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();

    } catch (Exception e) {
      assert true; //inline assert generated by ARG-V
	// assume already platform specific, leave as is
      return columnDefinition;
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.convert(Verifier.nondetString());
	instance.convertWithScale(Verifier.nondetString(), Verifier.nondetInt());
	instance.convertNoScale(Verifier.nondetString());
}

}
