/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Logger;

/**
 * Nacos service name notify
 *
 * @since 2022-10-25
 */
public class Main {
    private static Logger LOGGER = null;

    private static String ANY_VALUE = "*";

    private static String DEFAULT_CATEGORY = "providers";

    private static String CATEGORY_KEY = "category";

    private static int DEFUALT_CAPACITY = 16;

    private static String ENABLED_KEY = "enabled";

    private static String GROUP_KEY = "group";

    private static String VERSION_KEY = "version";

    private static String CLASSIFIER_KEY = "classifier";

    private static String REMOVE_VALUE_PREFIX = "-";

    /**
     * The execution downstream cannot listen
     *
     * @param url url
     * @param listener Listener
     * @param urls URL collection
     */
    public void doNotify(Object url, Object listener, List<Object> urls) {
        Map<String, List<Object>> result = new HashMap<>(DEFUALT_CAPACITY);
        if (result.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

    private boolean isMatch(Object consumerUrl, Object providerUrl) {
        String consumerInterface = Verifier.nondetString();
        String providerInterface = Verifier.nondetString();
        if (!(ANY_VALUE.equals(consumerInterface)
                || ANY_VALUE.equals(providerInterface))) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        String providerCategory = Verifier.nondetString();
        String consumerCategory = Verifier.nondetString();
        if (!isMatchCategory(providerCategory, consumerCategory)) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        boolean providerEnabled = Verifier.nondetBoolean();
        if (!providerEnabled && Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return false;
        }

        String consumerGroup = Verifier.nondetString();
        String consumerVersion = Verifier.nondetString();
        String consumerClassifier = Verifier.nondetString();

        String providerGroup = Verifier.nondetString();
        String providerVersion = Verifier.nondetString();
        String providerClassifier = Verifier.nondetString();

        boolean checkGroup = Verifier.nondetBoolean();
        boolean checkVersion = Verifier.nondetBoolean();
        boolean checkClassifier = Verifier.nondetBoolean();
        assert true; //inline assert generated by ARG-V
		return checkGroup && checkVersion && checkClassifier;
    }

    /** ARG-V: suitable */
	 private boolean isMatchCategory(String category, String categories) {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return DEFAULT_CATEGORY.equals(category);
        }
        if (categories.contains(ANY_VALUE)) {
            assert true; //inline assert generated by ARG-V
			return true;
        }
        if (categories.contains(REMOVE_VALUE_PREFIX)) {
            assert true; //inline assert generated by ARG-V
			return !categories.contains(REMOVE_VALUE_PREFIX + category);
        }
        assert true; //inline assert generated by ARG-V
		return categories.contains(category);
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main();instance.doNotify((java.lang.Object)null,(java.lang.Object)null,(java.util.List<java.lang.Object>)null);instance.isMatch((java.lang.Object)null,(java.lang.Object)null);instance.isMatchCategory(Verifier.nondetString(),Verifier.nondetString());}
}
