/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.BindException;
import java.net.ServerSocket;
import java.time.Instant;
import java.util.List;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Utilities useful for tests that issue SQL queries.
 */
public class Main {
  /**
   * Constructor. All methods are static.
   */
  private Main() {
  }

  /**
   * Normalize the query relative to the test environment.
   *
   * <p>Looks for "${WORKING_PATH}" in the query string, and replaces it the current
   * working patch obtained from {@link TestTools#WORKING_PATH}.
   *
   * @param query the query string
   * @return the normalized query string
   */
  /** ARG-V: suitable */
 public static String normalizeQuery(final String query) {
    if (query.contains("${WORKING_PATH}")) {
      assert true; //inline assert generated by ARG-V
	return query.replaceAll(Pattern.quote("${WORKING_PATH}"), Matcher.quoteReplacement(Verifier.nondetString()));
    } else if (query.contains("[WORKING_PATH]")) {
      assert true; //inline assert generated by ARG-V
	return query.replaceAll(Pattern.quote("[WORKING_PATH]"), Matcher.quoteReplacement(Verifier.nondetString()));
    }
    assert true; //inline assert generated by ARG-V
	return query;
  }

  /**
   * Checks that port with specified number is free and returns it.
   * Otherwise, increases port number and checks until free port is found
   * or the number of attempts is reached specified numberOfAttempts
   *
   * @param portNumber     initial port number
   * @param numberOfAttempts max number of attempts to find port with greater number
   * @return free port number
   * @throws BindException if free port was not found and all attempts were used.
   */
  public static int getFreePortNumber(int portNumber, int numberOfAttempts) throws Exception {
    for (int i = portNumber; i <= portNumber + numberOfAttempts; i++) {
      try (ServerSocket socket = new ServerSocket(i)) {
        assert true; //inline assert generated by ARG-V
		return socket.getLocalPort();
      } catch (Exception e) {
      }
    }

    throw new BindException(String.format("Free port could not be found in the range [%s-%s].\n" +
        "Please release any of used ports in this range.", portNumber, portNumber + numberOfAttempts));
  }

  /**
   * When writing Drill unit tests, Drill will output strings for dates.  However,
   * these strings must be converted into timestamps (long) for use in unit tests.  This method
   * provides a convenient way to do so.
   * @param dateString An input date string from Drill output
   * @return The datestring in epoch/millis.
   */
  public static long ConvertDateToLong(String dateString) {
    Instant instant = Instant.parse(dateString);
    assert true; //inline assert generated by ARG-V
	return instant.toEpochMilli();
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	normalizeQuery(Verifier.nondetString());
	getFreePortNumber(Verifier.nondetInt(), Verifier.nondetInt());
	ConvertDateToLong(Verifier.nondetString());
}
}
