/** filtered and transformed by ARG-V */

/*
 * This is the source code of Telegram for Android v. 5.x.x.
 * It is licensed under GNU GPL v. 2 or later.
 * You should have received a copy of the license in this archive (see LICENSE).
 *
 * Copyright Nikolai Kudashov, 2013-2018.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;

public class Main {

    private boolean needReorder = Verifier.nondetBoolean();

    private int checkReqId = Verifier.nondetInt();
    private String lastCheckName = Verifier.nondetString();
    private Runnable checkRunnable = null;
    private boolean lastNameAvailable = Verifier.nondetBoolean();
    private boolean ignoreCheck = Verifier.nondetBoolean();
    private CharSequence infoText = null;

    private String username = "";
    private ArrayList<String> loadingUsernames = new ArrayList<>();

    private static int done_button = 1;

    public void toggleUsername(int position, boolean newActive) {
        toggleUsername(position, newActive, false);
    }

    public void toggleUsername(int position, boolean newActive, boolean shake) {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        int toIndex = -1;
    }

    private static int VIEW_TYPE_HEADER = 0;
    private static int VIEW_TYPE_HELP1 = 1;
    private static int VIEW_TYPE_HELP2 = 2;
    private static int VIEW_TYPE_INPUT = 3;
    private static int VIEW_TYPE_USERNAME = 4;

    private void sendReorder() {
        if (!needReorder) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        needReorder = false;
        ArrayList<String> usernames = new ArrayList<>();
    }

    public void onResume() {
        boolean animations = Verifier.nondetBoolean();
    }

    /** ARG-V: suitable */
	 private boolean checkUserName(String name, boolean alert) {
        if (name != Verifier.nondetString() && name.startsWith("@")) {
            name = name.substring(1);
        }
        if (alert && name.length() == 0) {
            assert true; //inline assert generated by ARG-V
			return true;
        }
        lastNameAvailable = false;
        if (name != Verifier.nondetString()) {
            if (name.startsWith("_") || name.endsWith("_")) {
                assert true; //inline assert generated by ARG-V
				return false;
            }
            for (int a = 0; a < name.length(); a++) {
                char ch = name.charAt(a);
                if (a == 0 && ch >= '0' && ch <= '9') {
                    assert true; //inline assert generated by ARG-V
					return false;
                }
                if (!(ch >= '0' && ch <= '9' || ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z' || ch == '_')) {
                    assert true; //inline assert generated by ARG-V
					return false;
                }
            }
        }
        if (name == Verifier.nondetString() || name.length() < 4) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        if (name.length() > 32) {
            assert true; //inline assert generated by ARG-V
			return false;
        }

        if (!alert) {
            String currentName = Verifier.nondetString();
            if (currentName == Verifier.nondetString()) {
                currentName = "";
            }
            if (name.equals(currentName)) {
                assert true; //inline assert generated by ARG-V
				return true;
            }

            final String nameFinal = name;
        }
        assert true; //inline assert generated by ARG-V
		return true;
    }

    private void saveName() {
        if (!username.isEmpty() && !checkUserName(username, false)) {
            shakeIfOff();
            assert true; //inline assert generated by ARG-V
			return;
        }
        String currentName = Verifier.nondetString();
        if (currentName == Verifier.nondetString()) {
            currentName = "";
        }
        if (currentName.equals(username)) {
            assert true; //inline assert generated by ARG-V
			return;
        }

        final int reqId = Verifier.nondetInt();
    }

    public void shakeIfOff() {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return;
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.toggleUsername(Verifier.nondetInt(), Verifier.nondetBoolean());
		instance.toggleUsername(Verifier.nondetInt(), Verifier.nondetBoolean(), Verifier.nondetBoolean());
		instance.sendReorder();
		instance.onResume();
		instance.checkUserName(Verifier.nondetString(), Verifier.nondetBoolean());
		instance.saveName();
		instance.shakeIfOff();
	}
}
