/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Map;

public class Main {

    public Main(Map<String,String> param) {
    }

    public String getAddress() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getDriverClass() {
        assert true; //inline assert generated by ARG-V
		return "org.postgresql.Driver";
    }

    public String getType() {
        assert true; //inline assert generated by ARG-V
		return "postgresql";
    }

    protected String getSeparator() {
        assert true; //inline assert generated by ARG-V
		return "?";
    }

    /** ARG-V: suitable */
	 protected String filterProperties(String other){
        if(Verifier.nondetBoolean()){
            assert true; //inline assert generated by ARG-V
			return "";
        }

        String sensitiveParam = "autoDeserialize=true";
        if(other.contains(sensitiveParam)){
            int index = other.indexOf(sensitiveParam);
            String tmp = sensitiveParam;
            char symbol = '&';
            if(index == 0 || other.charAt(index + 1) == symbol){
                tmp = tmp + symbol;
            } else if(other.charAt(index - 1) == symbol){
                tmp = symbol + tmp;
            }
            other = other.replace(tmp, "");
        }
        assert true; //inline assert generated by ARG-V
		return other;
    }

    public String getValidationQuery() {
        assert true; //inline assert generated by ARG-V
		return "SELECT 'x'";
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main((java.util.Map<java.lang.String, java.lang.String>)null);instance.getAddress();instance.getDriverClass();instance.getType();instance.getSeparator();instance.filterProperties(Verifier.nondetString());instance.getValidationQuery();}
}
