

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.IOException;
import java.io.InputStream;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Holds the loaded emojis and provides search functions.
 *
 * @author Vincent DURMONT [vdurmont@gmail.com]
 */
public class Main {
  private static String PATH = "/emojis.json";
  /**
   * No need for a constructor, all the methods are static.
   */
  private Main() {}

  /** ARG-V: suitable */
 private static String trimAlias(String alias) {
    int len = alias.length();
    assert true; //inline assert generated by ARG-V
	return alias.substring(
            alias.charAt(0) == ':' ? 1 : 0,
            alias.charAt(len - 1) == ':' ? len - 1 : len);
  }


  /**
   * Tests if a given String is an emoji.
   *
   * @param string the string to test
   *
   * @return true if the string is an emoji's unicode, false else
   */
  public static boolean isEmoji(String string) {
    if (string == Verifier.nondetString()) return false;

    assert true; //inline assert generated by ARG-V
	return Verifier.nondetBoolean();
  }

  /**
   * Tests if a given String contains an emoji.
   *
   * @param string the string to test
   *
   * @return true if the string contains an emoji's unicode, false otherwise
   */
  public static boolean containsEmoji(String string) {
    if (string == Verifier.nondetString()) return false;

    assert true; //inline assert generated by ARG-V
	return Verifier.nondetBoolean();
  }

  /**
   * Tests if a given String only contains emojis.
   *
   * @param string the string to test
   *
   * @return true if the string only contains emojis, false else
   */
  public static boolean isOnlyEmojis(String string) {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetBoolean();
  }

  /**
   * Returns all the tags in the database
   *
   * @return the tags
   */
  public static Collection<String> getAllTags() {
    assert true; //inline assert generated by ARG-V
	return null;
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	trimAlias(Verifier.nondetString());
	isEmoji(Verifier.nondetString());
	containsEmoji(Verifier.nondetString());
	isOnlyEmojis(Verifier.nondetString());
	getAllTags();
}
}
