/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

public class Main {
    private static String META_INF = "META-INF";
    private static int MAX_PARENT_SEARCH = 20;

    // 配置文件扩展名列表
    public static Set<String> CONFIG_EXTENSIONS = new HashSet<>(Arrays.asList(
            ".yml", ".yaml", ".properties", ".xml", ".json", ".conf", ".config", ".ini", ".toml", "web.xml"
    ));

    public static boolean isConfigFile(String fileName) {
        fileName = fileName.toLowerCase();
        assert true; //inline assert generated by ARG-V
		return false;
    }

    /** ARG-V: suitable */
	 private static boolean shouldRun(String whiteText, String blackText, String saveClass) {
        boolean whiteDoIt = false;

        // 处理 BOOT-INF WEB-INF 的问题
        int i = saveClass.indexOf("classes");
        if (i > 0) {
            if (saveClass.contains("BOOT-INF") || saveClass.contains("WEB-INF")) {
                saveClass = saveClass.substring(i + 8, saveClass.length() - 6);
            } else {
                saveClass = saveClass.substring(0, saveClass.length() - 6);
            }
        }

        if (!whiteDoIt) {
            assert true; //inline assert generated by ARG-V
			return false;
        }

        boolean doIt = true;
        if (!doIt) {
            assert true; //inline assert generated by ARG-V
			return false;
        }

        assert true; //inline assert generated by ARG-V
		return true;
    }

    /** ARG-V: suitable */
	 private static void resolve(Integer jarId, String jarPathStr, Path tmpDir) {
        String text = Verifier.nondetString();
        String whiteText = Verifier.nondetString();
        Path jarPath = Paths.get(jarPathStr);
        if (!Files.exists(jarPath)) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        try {
            if (jarPathStr.toLowerCase(null).endsWith(".class")) {
                String fileText = Verifier.nondetString();
                if (jarPathStr.contains(fileText)) {
                    String backPath = jarPathStr;

                    // #################################################
                    // 2025/06/26 处理重大 BUG
                    // 加载单个 CLASS 时 CLASSNAME 按照 META-INF 决定
                    Path parentPath = jarPath;
                    Path resultPath = null;
                    // 循环找 META-INF 目录
                    int index = 0;
                    while ((parentPath = parentPath.getParent()) != null) {
                        Path metaPath = parentPath.resolve("META-INF");
                        if (Files.exists(metaPath)) {
                            resultPath = metaPath;
                            break;
                        }
                        index++;
                        // 防止一直循环
                        if (index > MAX_PARENT_SEARCH) {
                            break;
                        }
                    }
                    if (resultPath == null) {
                        assert true; //inline assert generated by ARG-V
						return;
                    }
                    String finalPath = resultPath.toAbsolutePath().toString();
                    if (!finalPath.contains(fileText)) {
                        assert true; //inline assert generated by ARG-V
						// 跨越目录除外
                        return;
                    }
                    // 防止预期外错误
                    if (finalPath.length() < META_INF.length()) {
                        assert true; //inline assert generated by ARG-V
						return;
                    }
                    try {
                        jarPathStr = jarPathStr.substring(finalPath.length() - META_INF.length());
                    } catch (Exception e) {
                        assert true; //inline assert generated by ARG-V
						return;
                    }
                    String saveClass = jarPathStr.replace("\\", "/");
                    if (!shouldRun(whiteText, text, saveClass)) {
                        assert true; //inline assert generated by ARG-V
						return;
                    }

                    Path fullPath = tmpDir.resolve(jarPathStr);
                    Path parPath = fullPath.getParent();
                    if (!Files.exists(parPath)) {
                        Files.createDirectories(parPath);
                    }
                    try {
                        Files.createFile(fullPath);
                    } catch (Exception e) {
                    }
                    InputStream fis = Files.newInputStream(Paths.get(backPath));
                    OutputStream outputStream = Files.newOutputStream(fullPath);
                    outputStream.close();
                    fis.close();
                } else {
                    assert true; //inline assert generated by ARG-V
					return;
                }
            } else if (jarPathStr.toLowerCase(null).endsWith(".jar") ||
                    jarPathStr.toLowerCase(null).endsWith(".war")) {
                while (Verifier.nondetBoolean()) {
                    // =============== 2024/04/26 修复 ZIP SLIP 漏洞 ===============
                    String jarEntryName = Verifier.nondetString();
                    // 第一次检查是否包含 ../ ..\\ 绕过
                    if (jarEntryName.contains("../") || jarEntryName.contains("..\\")) {
                        // 不抛出异常只跳过这个文件继续处理其他文件
                        continue;
                    }
                    // 可能还有其他的绕过情况？
                    // 先 normalize 处理 ../ 情况
                    // 再保证 entryPath 绝对路径必须以解压临时目录 tmpDir 开头
                    Path entryPath = tmpDir.resolve(jarEntryName).toAbsolutePath().normalize();
                    Path tmpDirAbs = tmpDir.toAbsolutePath();
                    if (!entryPath.toString().startsWith(tmpDirAbs.toString())) {
                        continue;
                    }
                    // ============================================================
                    Path fullPath = tmpDir.resolve(jarEntryName);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void doInternal(Integer jarId, Path jarPath, Path tmpDir, String text, String whiteText) {
        try {
            while (Verifier.nondetBoolean()) {
                // =============== 2024/04/26 修复 ZIP SLIP 漏洞 ===============
                String jarEntryName = Verifier.nondetString();
                // 第一次检查是否包含 ../ ..\\ 绕过
                if (jarEntryName.contains("../") || jarEntryName.contains("..\\")) {
                    // 不抛出异常只跳过这个文件继续处理其他文件
                    continue;
                }
                // 可能还有其他的绕过情况？
                // 先 normalize 处理 ../ 情况
                // 再保证 entryPath 绝对路径必须以解压临时目录 tmpDir 开头
                Path entryPath = tmpDir.resolve(jarEntryName).toAbsolutePath().normalize();
                Path tmpDirAbs = tmpDir.toAbsolutePath();
                if (!entryPath.toString().startsWith(tmpDirAbs.toString())) {
                    continue;
                }
                // ============================================================
                Path fullPath = tmpDir.resolve(jarEntryName);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		isConfigFile(Verifier.nondetString());
		shouldRun(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		resolve((java.lang.Integer) null, Verifier.nondetString(), (java.nio.file.Path) null);
		doInternal((java.lang.Integer) null, (java.nio.file.Path) null, (java.nio.file.Path) null,
				Verifier.nondetString(), Verifier.nondetString());
	}
}
