 
/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

// Looks like the intended behavior of TestTagProjection is:

// 1) Include the basic category (everything before a '-' or '^' annotation)

// 2) Include any annotation introduced with '-'

// 3) Exclude any annotation introduced with '^'

// 4) Annotations introduced with other characters will be included or excluded

//    as determined by the previous annotation or basic category.

//

// This seems awfully haphazard :(

//

//  Roger

/** @author Dan Klein */
public class Main  {

  private static long serialVersionUID = 9161675508802284114L;

  /** ARG-V: suitable */
 public String project(String tagStr) {
    StringBuilder sb = new StringBuilder();
    boolean good = true;
    for (int pos = 0, len = tagStr.length(); pos < len; pos++) {
      char c = tagStr.charAt(pos);
      if (c == '-') {
        good = true;
      } else if (c == '^') {
        good = false;
      }
      if (good) {
        sb.append(c);
      }
    }
    String ret = sb.toString();
    assert true; //inline assert generated by ARG-V
	// log.info("TTP mapped " + tagStr + " to " + ret);
    return ret;
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.project(Verifier.nondetString());
}

}
