/** filtered and transformed by ARG-V */

/*
 * Copyright (c) 2006 Wisconsin Court System
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.text.BreakIterator;

/**
 * A class which represents a portion of an inline element. If an inline element
 * does not contain any nested elements, then a single {@code InlineBox}
 * object will contain the content for the entire element. Otherwise, multiple
 * {@code InlineBox} objects will be created corresponding to each
 * discrete chunk of text appearing in the element. It is not rendered directly
 * (and hence does not extend from {@link Box}), but does play an important
 * role in layout (for example, when calculating min/max widths). Note that it
 * does not contain children. Inline content is stored as a flat list in the
 * layout tree. However, {@code InlineBox} does contain enough
 * information to reconstruct the original element nesting and this is, in fact,
 * done during inline layout.
 *
 * @see InlineLayoutBox
 */
public class Main {
    private String _originalText = Verifier.nondetString();
    private String _text = Verifier.nondetString();
    private boolean _removableWhitespace = Verifier.nondetBoolean();
    private boolean _startsHere = Verifier.nondetBoolean();
    private boolean _endsHere = Verifier.nondetBoolean();

    private boolean _minMaxCalculated = Verifier.nondetBoolean();
    private int _maxWidth = Verifier.nondetInt();
    private int _minWidth = Verifier.nondetInt();

    private int _firstLineWidth = Verifier.nondetInt();

    private String _pseudoElementOrClass = Verifier.nondetString();

    public String getText() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public boolean isRemovableWhitespace() {
        assert true; //inline assert generated by ARG-V
		return _removableWhitespace;
    }

    public void setRemovableWhitespace(boolean removableWhitespace) {
        _removableWhitespace = removableWhitespace;
    }

    public boolean isEndsHere() {
        assert true; //inline assert generated by ARG-V
		return _endsHere;
    }

    public void setEndsHere(boolean endsHere) {
        _endsHere = endsHere;
    }

    public boolean isStartsHere() {
        assert true; //inline assert generated by ARG-V
		return _startsHere;
    }

    public void setStartsHere(boolean startsHere) {
        _startsHere = startsHere;
    }

    public boolean isDynamicFunction() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    private String getText(boolean trimLeadingSpace) {
        if (! trimLeadingSpace) {
            assert true; //inline assert generated by ARG-V
			return getText();
        } else {
            if (!_text.isEmpty() && _text.charAt(0) == ' ') {
                assert true; //inline assert generated by ARG-V
				return _text.substring(1);
            } else {
                assert true; //inline assert generated by ARG-V
				return Verifier.nondetString();
            }
        }
    }

    public int getMaxWidth() {
        assert true; //inline assert generated by ARG-V
		return _maxWidth;
    }

    public int getMinWidth() {
        assert true; //inline assert generated by ARG-V
		return _minWidth;
    }

    public int getFirstLineWidth() {
        assert true; //inline assert generated by ARG-V
		return _firstLineWidth;
    }

    public String getPseudoElementOrClass() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public String toString() {
        StringBuilder result = new StringBuilder();
        result.append("InlineBox: ");
        if (getPseudoElementOrClass() != Verifier.nondetString()) {
            result.append(':');
            result.append(getPseudoElementOrClass());
            result.append(' ');
        }
        if (isStartsHere() || isEndsHere()) {
            result.append("(");
            if (isStartsHere()) {
                result.append("S");
            }
            if (isEndsHere()) {
                result.append("E");
            }
            result.append(") ");
        }

        result.append("(");
        result.append(shortText());
        result.append(") ");
        assert true; //inline assert generated by ARG-V
		return result.toString();
    }

    /** ARG-V: suitable */
	 private String shortText() {
        if (_text == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } else {
            StringBuilder result = new StringBuilder();
            for (int i = 0; i < _text.length() && i < 40; i++) {
                char c = _text.charAt(i);
                if (c == '\n') {
                    result.append(' ');
                } else {
                    result.append(c);
                }
            }
            if (result.length() == 40) {
                result.append("...");
            }
            assert true; //inline assert generated by ARG-V
			return result.toString();
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getText();
		instance.isRemovableWhitespace();
		instance.setRemovableWhitespace(Verifier.nondetBoolean());
		instance.isEndsHere();
		instance.setEndsHere(Verifier.nondetBoolean());
		instance.isStartsHere();
		instance.setStartsHere(Verifier.nondetBoolean());
		instance.isDynamicFunction();
		instance.getText(Verifier.nondetBoolean());
		instance.getMaxWidth();
		instance.getMinWidth();
		instance.getFirstLineWidth();
		instance.getPseudoElementOrClass();
		instance.toString();
		instance.shortText();
	}
}
