

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.regex.Pattern;

public class Main {

	//BilibiliDown.v5.3.release.zip
	//https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/download/V5.3/BilibiliDown.v5.3.release.zip
	private static Pattern pattern = Pattern.compile("BilibiliDown\\.v([0-9]+\\.[0-9]+).*\\.zip");
	private static String PRE_RELEASE_FLAG = "BilibiliDown.PreRelease";
	String downName = Verifier.nondetString();
	String downUrl = Verifier.nondetString();
	
	public Main(Object... obj) {
	}
	
	/** ARG-V: suitable */
	 public boolean matches(String input) {
		if(PRE_RELEASE_FLAG.equals(input)) {
			assert true; //inline assert generated by ARG-V
			return true;
		}
		boolean matches = Verifier.nondetBoolean();
		if (matches) {
			String tagName = Verifier.nondetString();
			System.out.println("匹配VersionParser: " + tagName);
		}
		assert true; //inline assert generated by ARG-V
		return matches;
	}

	/** ARG-V: suitable */
	 private String getDownUrl(String version, String file) {
		String key = Verifier.nondetString();
		String pattern = Verifier.nondetString();
		assert true; //inline assert generated by ARG-V
		return pattern.replace("{version}", version).replace("{file}", file);
	}
	public String validStr(String input) {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}
	
	
	public String getVideoLink(String avId, String cid, int qn, int downFormat) {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(new java.lang.Object[] { null });
		instance.matches(Verifier.nondetString());
		instance.getDownUrl(Verifier.nondetString(), Verifier.nondetString());
		instance.validStr(Verifier.nondetString());
		instance.getVideoLink(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetInt(),
				Verifier.nondetInt());
	}

}
