/** filtered and transformed by ARG-V */

// Copyright 2011-2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import org.sosy_lab.sv_benchmarks.Verifier;
import java.awt.Point;

public class Main {
  private boolean m_wasSelection = false;

  private boolean m_isAboveComment = Verifier.nondetBoolean();
  private boolean m_isBehindComment = Verifier.nondetBoolean();
  private boolean m_isLabelComment = Verifier.nondetBoolean();

  private Point getMultiCommentEndPoint(final int lineXPos, final int lineYPos) {
    if (Verifier.nondetBoolean()) {
      int x =
          Verifier.nondetInt();

      int y = lineYPos;

      assert true; //inline assert generated by ARG-V
	return new Point(x, y);
    }

    assert true; //inline assert generated by ARG-V
	return null;
  }

  protected void initUndoHistory() {
    final int x = Verifier.nondetInt();
    final int y = Verifier.nondetInt();

    if (Verifier.nondetBoolean()) {
      String text =
          Verifier.nondetString();

      m_isAboveComment = Verifier.nondetBoolean();
      m_isBehindComment = Verifier.nondetBoolean();
      m_isLabelComment = Verifier.nondetBoolean();

      if (Verifier.nondetBoolean()) {
        text = Verifier.nondetString();
      }
    }
  }

  protected void updateCaret() {
    m_wasSelection = false;
  }

  /** ARG-V: suitable */
 protected void updateLabelContent() {
    if (m_wasSelection) {
      assert true; //inline assert generated by ARG-V
	return;
    }

    final int x = Verifier.nondetInt();
    final int y = Verifier.nondetInt();

    if (Verifier.nondetBoolean()) {
      assert true; //inline assert generated by ARG-V
	return;
    }

    if (Verifier.nondetBoolean()) {
      // Caret end was within a comment, when key was pressed.

      if (Verifier.nondetBoolean()) {
        assert true; //inline assert generated by ARG-V
		return;
      }

      final Point commentEndPoint = getMultiCommentEndPoint(x, y);

      final int textCursor = Verifier.nondetInt();
      final String text =
          Verifier.nondetString();

      String changedText = text;

      if (textCursor < text.length()) {
        changedText =
            String.format("%s%s", text.substring(0, textCursor), text.substring(textCursor + 1));
      }

      if (Verifier.nondetBoolean()) {
        changedText = Verifier.nondetString();
        if (!changedText.endsWith("\r")) {
          changedText += "\r";
        }
      }
    } else {
      // Caret end was within an editable object, but NOT a comment.

      throw new RuntimeException("Not implemented yet.");
    }
  }

  protected void updateSelection() {
    m_wasSelection = Verifier.nondetBoolean();
  }

  protected void updateUndoHistory() {
    final int x = Verifier.nondetInt();
    final int y = Verifier.nondetInt();

    String text = "";

    if (Verifier.nondetBoolean()) {
      text =
          Verifier.nondetString();

      if (Verifier.nondetBoolean()) {
        text = Verifier.nondetString();
      }
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.getMultiCommentEndPoint(Verifier.nondetInt(), Verifier.nondetInt());
	instance.initUndoHistory();
	instance.updateCaret();
	instance.updateLabelContent();
	instance.updateSelection();
	instance.updateUndoHistory();
}
}
