/** filtered and transformed by ARG-V */

/*
 * Copyright 2019, the original author or authors.
 * Licensed under the Apache License, Version 2.0
 * See LICENSE file in project root for terms.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.Callable;

/**
 * Spring rest controller for Elide JSON-API.
 * Based on 'https://github.com/illyasviel/elide-spring-boot/'
 */
public class Main {
    /** ARG-V: suitable */
	 protected String getBaseUrl(String prefix) {
        String baseUrl = Verifier.nondetString();

        if (Verifier.nondetBoolean()) {
            baseUrl = Verifier.nondetString();
        }

        if (prefix.length() > 1) {
            if (baseUrl.endsWith("/")) {
                baseUrl = baseUrl.substring(0, baseUrl.length() - 1) + prefix;
            } else {
                baseUrl = baseUrl + prefix;
            }
        }

        assert true; //inline assert generated by ARG-V
		return baseUrl;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getBaseUrl(Verifier.nondetString());
	}
}
