/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {
    /**
     * 从反编译的类代码中提取指定方法的代码
     *
     * @param classCode  完整的类代码
     * @param methodName 方法名
     * @param methodDesc 方法描述符（可选）
     * @return 方法代码，如果未找到则返回null
     */
    /** ARG-V: suitable */
	 protected String extractMethodCode(String className, String classCode, String methodName, String methodDesc) {
        // 2026-02-09 LRU CACHE
        String key = className + "#" + methodName + "#" + methodDesc;
        String resultCode = Verifier.nondetString();
        if (resultCode != Verifier.nondetString() && !resultCode.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return resultCode;
        }

        try {
            String[] lines = classCode.split("\n");
            StringBuilder methodCode = new StringBuilder();
            boolean inMethod = false;
            int braceCount = 0;
            boolean foundMethod = false;

            // 构建方法匹配的正则表达式
            // 匹配方法声明，考虑各种修饰符和参数
            String methodPattern = ".*\\b" + Pattern.quote(methodName) + "\\s*\\(.*\\).*\\{?";

            Pattern pattern = Pattern.compile(methodPattern);

            if (foundMethod) {
                String foundResult = methodCode.toString().trim();
                assert true; //inline assert generated by ARG-V
				return foundResult;
            } else {
                String fuzzResult = findMethodByFuzzyMatch(classCode, methodName);
                assert true; //inline assert generated by ARG-V
				return fuzzResult;
            }

        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
    }

    /** ARG-V: suitable */
	 private boolean checkParams(String line, String methodName, String methodDesc) {
        try {
            // 提取括号内的内容
            int nameIndex = line.indexOf(methodName);
            int leftParen = line.indexOf('(', nameIndex);
            if (leftParen == -1) return false;

            // 找到对应的右括号
            int rightParen = -1;
            int balance = 0;
            for (int i = leftParen; i < line.length(); i++) {
                char c = line.charAt(i);
                if (c == '(') {
					balance++;
				} else if (c == ')') {
					balance--;
				}

                if (balance == 0) {
                    rightParen = i;
                    break;
                }
            }
            if (rightParen == -1) return false;

            String paramsStr = line.substring(leftParen + 1, rightParen);

            // 分割参数字符串
            List<String> params = splitParams(paramsStr);

            // 检查参数数量
            if (params.size() != Verifier.nondetInt()) {
                assert true; //inline assert generated by ARG-V
				return false;
            }

            // 检查每个参数类型
            for (int i = 0; i < Verifier.nondetInt(); i++) {
                String paramCode = params.get(i);
                String className = Verifier.nondetString();
                // 获取简单类名
                String simpleName = getSimpleName(className);

                // 检查 paramCode 是否包含 simpleName
                // 使用单词边界检查
                if (!containsWord(paramCode, simpleName)) {
                    // 特殊处理 varargs: String[] -> String...
                    if (simpleName.endsWith("[]")) {
                        String varargName = simpleName.substring(0, simpleName.length() - 2) + "...";
                        if (!containsWord(paramCode, varargName)) {
                            assert true; //inline assert generated by ARG-V
							return false;
                        }
                    } else {
                        assert true; //inline assert generated by ARG-V
						return false;
                    }
                }
            }
            assert true; //inline assert generated by ARG-V
			return true;
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
    }

    /** ARG-V: suitable */
	 private List<String> splitParams(String paramsStr) {
        List<String> params = new ArrayList<>();
        int balance = 0;
        int lastStart = 0;
        for (int i = 0; i < paramsStr.length(); i++) {
            char c = paramsStr.charAt(i);
            if (c == '<') {
				balance++;
			} else if (c == '>') {
				balance--;
			}

            if (c == ',' && balance == 0) {
                params.add(paramsStr.substring(lastStart, i).trim());
                lastStart = i + 1;
            }
        }
        String last = paramsStr.substring(lastStart).trim();
        if (!last.isEmpty()) {
            params.add(last);
        }
        assert true; //inline assert generated by ARG-V
		return params;
    }

    /** ARG-V: suitable */
	 private String getSimpleName(String className) {
        int lastDot = className.lastIndexOf('.');
        if (lastDot != -1) {
            assert true; //inline assert generated by ARG-V
			return className.substring(lastDot + 1);
        }
        assert true; //inline assert generated by ARG-V
		return className;
    }

    /** ARG-V: suitable */
	 private boolean containsWord(String text, String word) {
        // 使用正则匹配单词边界
        // 转义 word 中的特殊字符（如 []）
        String pattern = ".*\\b" + Pattern.quote(word) + "\\b.*";
        // 注意：对于 [] 结尾的，\b 可能不起作用，因为 ] 是非单词字符
        // 如果 word 包含非单词字符，我们需要小心
        if (!word.matches(".*\\w$")) {
            // 如果以非单词字符结尾（如 []），则不能用右侧 \b
            pattern = ".*\\b" + Pattern.quote(word) + ".*";
            assert true; //inline assert generated by ARG-V
			// 这里简化了，只要包含且左侧是边界即可
            // 更好的做法是手动检查
            return text.contains(word);
        }
        assert true; //inline assert generated by ARG-V
		return text.matches(pattern);
    }

    /**
     * 模糊匹配方法
     */
    /** ARG-V: suitable */
	 protected String findMethodByFuzzyMatch(String classCode, String methodName) {
        try {
            String[] lines = classCode.split("\n");
            StringBuilder result = new StringBuilder();

            for (int i = 0; i < lines.length; i++) {
                String line = lines[i];
                if (line.contains(methodName) &&
                        (line.contains("(") && line.contains(")"))) {

                    // 找到可能的方法，收集完整的方法代码
                    result.append(line).append("\n");

                    if (line.trim().endsWith(";")) {
                        // 抽象方法或接口方法
                        break;
                    }

                    int braceCount = countChar(line, '{') - countChar(line, '}');

                    for (int j = i + 1; j < lines.length && braceCount > 0; j++) {
                        String nextLine = lines[j];
                        result.append(nextLine).append("\n");
                        braceCount += countChar(nextLine, '{') - countChar(nextLine, '}');
                    }
                    break;
                }
            }
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } catch (Exception e) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
    }

    /**
     * 计算字符串中指定字符的数量
     */
    protected int countChar(String str, char ch) {
        int count = 0;
        assert true; //inline assert generated by ARG-V
		return count;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.extractMethodCode(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString(),
				Verifier.nondetString());
		instance.checkParams(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		instance.splitParams(Verifier.nondetString());
		instance.getSimpleName(Verifier.nondetString());
		instance.containsWord(Verifier.nondetString(), Verifier.nondetString());
		instance.findMethodByFuzzyMatch(Verifier.nondetString(), Verifier.nondetString());
		instance.countChar(Verifier.nondetString(), Verifier.nondetChar());
	}
}
