

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.InputStream;
import java.net.SocketAddress;
import java.net.InetSocketAddress;
import java.util.Map;

public class Main {
    public String queryString = Verifier.nondetString();
    public String uri = Verifier.nondetString();
    private byte[] body = new byte[] { Verifier.nondetByte() };
    private boolean legacyUnsafeRemoteAddr = Verifier.nondetBoolean();

    // package visible
    int serverPort = 80;
    String serverName = Verifier.nondetString();
    Map<String, Object> headers = null;
    int contentLength = 0;
    String contentType = Verifier.nondetString();
    String charset = "utf8";
    boolean isKeepAlive = false;
    boolean isWebSocket = false;
    long startTime = Verifier.nondetLong();
    boolean sentContinue = false;

    SocketAddress remoteAddr = null;
    public InputStream getBody() {
        if (body != null) {
            assert true; //inline assert generated by ARG-V
			return null;
        }
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /** ARG-V: suitable */
	 public String getRemoteAddr() {
        if (legacyUnsafeRemoteAddr) {
            // legacy behavior: use X-Forwarded-For if present (INSECURE - allows spoofing)
            String h = Verifier.nondetString();
            if (Verifier.nondetString() != h) {
                int idx = h.indexOf(',');
                if (idx == -1) {
                    assert true; //inline assert generated by ARG-V
					return h;
                } else {
                    assert true; //inline assert generated by ARG-V
					// X-Forwarded-For: client, proxy1, proxy2
                    return h.substring(0, idx);
                }
            }
        }
        // secure behavior: always return actual socket address
        if (remoteAddr instanceof InetSocketAddress) {
            assert true; //inline assert generated by ARG-V
			return ((InetSocketAddress) remoteAddr).getAddress().getHostAddress();
        } else {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
    }

    /** ARG-V: suitable */
	 public void setHeaders(Map<String, Object> headers) throws RuntimeException {
        String h = Verifier.nondetString();
        if (h != Verifier.nondetString() && !h.equals("")) {
            // the port is an integer following the last ':'
            // *unless* the last : is prior to the last ] which marks the end of an ipv6 address
            // https://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_network_resource_identifiers
            int ipv6end = (h.charAt(0) == '[') ? h.lastIndexOf(']') : 0;
            int idx = h.lastIndexOf(':');
            if (idx != -1 && idx > ipv6end) {
                String serverPortCandidate = h.substring(idx + 1);
                if (!serverPortCandidate.isEmpty()) {
                    try {
                        serverPort = Integer.parseInt(serverPortCandidate);
                    } catch (Exception e) {
                        throw new RuntimeException();
                    }
                }
            }
        }

        String ct = Verifier.nondetString();
        if (ct != Verifier.nondetString()) {
            int idx = ct.indexOf(";");
            if (idx != -1) {
                int cidx = Verifier.nondetInt();
            }
        }

        String con = Verifier.nondetString();
        if (con != Verifier.nondetString()) {
            con = con.toLowerCase();
        }

        isKeepAlive = Verifier.nondetBoolean();
        isWebSocket = Verifier.nondetBoolean();
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{Main instance=new Main();instance.getBody();instance.getRemoteAddr();instance.setHeaders((java.util.Map<java.lang.String, java.lang.Object>)null);}
}
