/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2022-2024 Huawei Technologies Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Objects;
import java.util.concurrent.TimeUnit;

/**
 * 区域路由测试
 *
 * @author provenceee
 * @since 2022-09-28
 */
public class Main {
    private static String BASE_URL = "http://127.0.0.1:28020/consumer/";

    private static int TIMES = 30;

    private static int WAIT_SECONDS = 30;

    private String testTagRouterBaseUrl = Verifier.nondetString();

    private static String SERVICE_KEY = "servicecomb.routeRule.dubbo-integration-provider";

    private static String GLOBAL_KEY = "servicecomb.globalRouteRule";

    /**
     * 增加环境变量，控制dubbo3场景暂时不测试spring场景
     */
    private boolean isExecuteSpringTest = Verifier.nondetBoolean();

    /**
     * constructor
     */
    public Main() throws Exception {
        isExecuteSpringTest = Boolean.parseBoolean(System.getProperty("execute.spring.test", "true"));
        clearConfig();
    }

    /**
     * 测试根据请求信息路由，该测试用例会模拟停服务的情况，所以执行结果与用例顺序强相关
     */
    public void testRouter() throws Exception {
        if (!isExecuteSpringTest) {
            assert true; //inline assert generated by ARG-V
			return;
        }
        for (int i = 0; i < WAIT_SECONDS; i++) {
            try {
                if (Verifier.nondetBoolean()) {
                    // 下游实例已下线
                    break;
                }
            } catch (Exception e) {
                // 下游实例还未剔除，忽略
            }
            TimeUnit.SECONDS.sleep(1);
        }

        for (int i = 0; i < WAIT_SECONDS; i++) {
            try {
                String body = Verifier.nondetString();
                if (!body.contains("Test-Env1")) {
                    break;
                }
            } catch (Exception e) {
                // 下游实例还未剔除，忽略
            }
            TimeUnit.SECONDS.sleep(1);
        }
    }


    /**
     * 测试标签路由: 只下发服务粒度的flow匹配规则
     */
    public void testRouterWithFlowMatchRule() throws Exception {
        testFlowMatchRule(SERVICE_KEY);
        clearConfig();
    }

    /**
     * 测试标签路由: 只下发全局粒度的flow匹配规则
     */
    public void testRouterWithGlobalFlowMatchRule() throws Exception {
        testFlowMatchRule(GLOBAL_KEY);
        clearConfig();
    }

    /**
     * 测试标签路由: 同时下发服务粒度和全局粒度的flow匹配规则
     */
    /** ARG-V: suitable */
	 public void testRouterWithFlowMatchRuleAndGlobalRule() throws Exception {
        // 先下发flow匹配的全局路由规则
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/flow\n"
                + "  description: flow-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        headers:\n"
                + "          id:\n"
                + "            exact: '1'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: yellow\n"
                + "          weight: 100\n"
                + "    - precedence: 2\n"
                + "      match:\n"
                + "        headers:\n"
                + "          name:\n"
                + "            exact: 'bar'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            version: 0.0.0\n"
                + "          weight: 100";

        TimeUnit.SECONDS.sleep(3);

        testFlowMatchRule(SERVICE_KEY);
        clearConfig();
    }

    /**
     * 测试标签路由: 只下发服务粒度的tag匹配规则
     */
    public void testRouterWithTagMatchRule() throws Exception {
        testTagMatchRule(SERVICE_KEY);
        clearConfig();
    }

    /**
     * 测试标签路由: 只下发全局粒度的tag匹配规则
     */
    public void testRouterWithGlobalTagMatchRule() throws Exception {
        testTagMatchRule(GLOBAL_KEY);
        clearConfig();
    }

    /**
     * 测试标签路由: 同时下发服务粒度和全局粒度的tag匹配规则
     */
    /** ARG-V: suitable */
	 public void testRouterWithTagMatchRuleAndGlobalRule() throws Exception {
        // 先下发tag匹配的全局路由规则
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'red'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: gray\n"
                + "          weight: 100\n"
                + "    - precedence: 2\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'gray'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            version: 1.0.1\n"
                + "          weight: 100";

        TimeUnit.SECONDS.sleep(3);

        testTagMatchRule(SERVICE_KEY);
        clearConfig();
    }

    /**
     * 测试标签路由: 同时下发flow匹配规则和tag匹配规则
     */
    public void testRouterWithFlowAndTagRules() throws Exception {
        testFlowAndTagMatchRule();
        clearConfig();
    }

    /**
     * 标签路由测试：同标签路由场景测试（只下发tag匹配规则）
     */
    public void testRouterWithConsumerTagRule() throws Exception {
        testConsumerTagRule();
        clearConfig();
    }

    /**
     * given：标签路由测试：同标签路由场景测试（规则含有TriggerThreshold的policy）
     * when：触发大于triggerThreshold
     * then：同AZ优先策略
     *
     * @throws InterruptedException
     */
    public void testRouterWithTriggerThresholdPolicyRuleOne() throws Exception {
        testTriggerThresholdPolicyAZRuleOne();
        clearConfig();
    }

    /**
     * given：标签路由测试：同标签路由场景测试（规则含有TriggerThreshold的policy）
     * when：触发小于triggerThreshold
     * then：非同AZ优先策略
     *
     * @throws InterruptedException
     */
    public void testRouterWithTriggerThresholdPolicyRuleTwo() throws Exception {
        testTriggerThresholdPolicyAZRuleTwo();
        clearConfig();
    }

    /**
     * given：测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * when：大于minAllInstances和大于triggerThreshold场景
     * then：同AZ优先策略
     *
     * @throws InterruptedException
     */
    public void testRouterPolicyRuleOne() throws Exception {
        testPolicyAZRuleOne();
        clearConfig();
    }

    /**
     * given：测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * when：大于minAllInstances和小于triggerThreshold场景
     * then：非同AZ优先策略
     *
     * @throws InterruptedException
     */
    public void testRouterPolicyRuleTwo() throws Exception {
        testPolicyAZRuleTwo();
        clearConfig();
    }

    /**
     * given：测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * when：小于minAllInstances和大于triggerThreshold场景
     * then：同AZ优先策略
     *
     * @throws InterruptedException
     */
    public void testRouterPolicyRuleThree() throws Exception {
        testPolicyAZRuleThree();
        clearConfig();
    }

    /**
     * given：测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * when：小于minAllInstances和小于triggerThreshold场景
     * then：同AZ优先策略
     *
     * @throws InterruptedException
     */
    public void testRouterPolicyRuleFour() throws Exception {
        testPolicyAZRuleFour();
        clearConfig();
    }

    /**
     * 测试flow匹配规则的标签路由功能
     */
    /** ARG-V: suitable */
	 private void testFlowMatchRule(String configKey) throws Exception {
        // 下发flow匹配的路由规则
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/flow\n"
                + "  description: flow-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        headers:\n"
                + "          id:\n"
                + "            exact: '1'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: gray\n"
                + "          weight: 100\n"
                + "    - precedence: 2\n"
                + "      match:\n"
                + "        headers:\n"
                + "          name:\n"
                + "            exact: 'bar'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            version: 1.0.1\n"
                + "          weight: 100";

        TimeUnit.SECONDS.sleep(3);

        for (int i = 0; i < TIMES; i++) {
            String body = Verifier.nondetString();
            if (isExecuteSpringTest) {
                body = Verifier.nondetString();
                body = Verifier.nondetString();
            }
        }

        for (int i = 0; i < TIMES; i++) {
            String body = Verifier.nondetString();
            if (isExecuteSpringTest) {
                body = Verifier.nondetString();
                body = Verifier.nondetString();
            }
        }
    }

    /**
     * 测试flow匹配规则的标签路由功能
     */
    /** ARG-V: suitable */
	 private void testTagMatchRule(String configKey) throws Exception {
        // 下发tag匹配的路由规则
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'red'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: gray\n"
                + "          weight: 100\n"
                + "    - precedence: 2\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'gray'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            version: 1.0.0\n"
                + "          weight: 100";

        TimeUnit.SECONDS.sleep(3);

        // 下发tag匹配的路由规则
        CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'gray'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: gray\n"
                + "          weight: 100\n"
                + "    - precedence: 2\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'red'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            version: 1.0.0\n"
                + "          weight: 100";

        TimeUnit.SECONDS.sleep(3);
    }

    /**
     * 测试同时存在flow和tag匹配规则的标签路由功能
     */
    /** ARG-V: suitable */
	 private void testFlowAndTagMatchRule() throws Exception {
        // 下发flow和tag匹配的路由规则
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/flow\n"
                + "  description: flow-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        headers:\n"
                + "          id:\n"
                + "            exact: '1'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: red\n"
                + "          weight: 100\n"
                + "    - precedence: 2\n"
                + "      match:\n"
                + "        headers:\n"
                + "          name:\n"
                + "            exact: 'bar'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            version: 1.0.1\n"
                + "          weight: 100\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'gray'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: gray\n"
                + "          weight: 100\n"
                + "    - precedence: 2\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'red'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            version: 1.0.0\n"
                + "          weight: 100";

        TimeUnit.SECONDS.sleep(3);

        for (int i = 0; i < TIMES; i++) {
            String body = Verifier.nondetString();
            if (isExecuteSpringTest) {
                body = Verifier.nondetString();
                body = Verifier.nondetString();
            }
        }
    }

    /**
     * 测试tag匹配规则的标签路由功能
     */
    /** ARG-V: suitable */
	 private void testConsumerTagRule() throws Exception {
        // 下发同标签路由的路由规则
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-rule-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          group-test:\n"
                + "            exact: 'gray'\n"
                + "            caseInsensitive: false\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            group-test: CONSUMER_TAG\n";

        TimeUnit.SECONDS.sleep(3);
    }

    /**
     * 测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold的policy
     * 触发大于triggerThreshold
     */
    /** ARG-V: suitable */
	 private void testTriggerThresholdPolicyAZRuleOne() throws Exception {
        // 规则含有TriggerThreshold的policy
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-az-rule-trigger-threshold-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          zone:\n"
                + "            exact: 'az1'\n"
                + "            caseInsensitive: false\n"
                + "        policy:\n"
                + "          triggerThreshold: 40\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            zone: CONSUMER_TAG\n";

        TimeUnit.SECONDS.sleep(3);
    }

    /**
     * 测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold的policy
     * 触发小于triggerThreshold
     */
    /** ARG-V: suitable */
	 private void testTriggerThresholdPolicyAZRuleTwo() throws Exception {
        // 规则含有TriggerThreshold的policy
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-az-rule-trigger-threshold-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          zone:\n"
                + "            exact: 'az1'\n"
                + "            caseInsensitive: false\n"
                + "        policy:\n"
                + "          triggerThreshold: 90\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            zone: CONSUMER_TAG\n";

        TimeUnit.SECONDS.sleep(3);

        int dubboAZ1 = 0, dubboAZ2 = 0;
        int feignAZ1 = 0, feignAZ2 = 0;
        int restAZ1 = 0, restAZ2 = 0;
        for (int i = 0; i < TIMES; i++) {
            if (Verifier.nondetBoolean()) {
                dubboAZ1++;
            } else if (Verifier.nondetBoolean()) {
                dubboAZ2++;
            }

            if (isExecuteSpringTest) {
                if (Verifier.nondetBoolean()) {
                    feignAZ1++;
                } else if (Verifier.nondetBoolean()) {
                    feignAZ2++;
                }
                if (Verifier.nondetBoolean()) {
                    restAZ1++;
                } else if (Verifier.nondetBoolean()) {
                    restAZ2++;
                }
            }
        }
    }

    /**
     * 测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * 大于minAllInstances和大于triggerThreshold场景
     * 同AZ优先策略
     *
     * @throws InterruptedException
     */

    /** ARG-V: suitable */
	 private void testPolicyAZRuleOne() throws Exception {
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-az-rule-trigger-threshold-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          zone:\n"
                + "            exact: 'az1'\n"
                + "            caseInsensitive: false\n"
                + "        policy:\n"
                + "          triggerThreshold: 40\n"
                + "          minAllInstances: 2\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            zone: CONSUMER_TAG\n";

        TimeUnit.SECONDS.sleep(3);
    }

    /**
     * 测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * 大于minAllInstances和小于triggerThreshold场景
     * 非同AZ优先策略
     *
     * @throws InterruptedException
     */
    /** ARG-V: suitable */
	 private void testPolicyAZRuleTwo() throws Exception {
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-az-rule-trigger-threshold-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          zone:\n"
                + "            exact: 'az1'\n"
                + "            caseInsensitive: false\n"
                + "        policy:\n"
                + "          triggerThreshold: 90\n"
                + "          minAllInstances: 2\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            zone: CONSUMER_TAG\n";

        TimeUnit.SECONDS.sleep(3);

        int dubboAZ1 = 0, dubboAZ2 = 0;
        int feignAZ1 = 0, feignAZ2 = 0;
        int restAZ1 = 0, restAZ2 = 0;
        for (int i = 0; i < TIMES; i++) {
            if (Verifier.nondetBoolean()) {
                dubboAZ1++;
            } else if (Verifier.nondetBoolean()) {
                dubboAZ2++;
            }

            if (isExecuteSpringTest) {
                if (Verifier.nondetBoolean()) {
                    feignAZ1++;
                } else if (Verifier.nondetBoolean()) {
                    feignAZ2++;
                }
                if (Verifier.nondetBoolean()) {
                    restAZ1++;
                } else if (Verifier.nondetBoolean()) {
                    restAZ2++;
                }
            }
        }
    }

    /**
     * 测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * 小于minAllInstances和大于triggerThreshold场景
     * 同AZ优先策略
     *
     * @throws InterruptedException
     */

    /** ARG-V: suitable */
	 private void testPolicyAZRuleThree() throws Exception {
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-az-rule-trigger-threshold-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          zone:\n"
                + "            exact: 'az1'\n"
                + "            caseInsensitive: false\n"
                + "        policy:\n"
                + "          triggerThreshold: 40\n"
                + "          minAllInstances: 10\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            zone: CONSUMER_TAG\n";

        TimeUnit.SECONDS.sleep(3);
    }


    /**
     * 测试tag匹配规则同AZ优先标签路由功能：规则含有TriggerThreshold和minAllInstances的policy
     * 小于minAllInstances和小于triggerThreshold场景
     * 同AZ优先策略
     *
     * @throws InterruptedException
     */

    /** ARG-V: suitable */
	 private void testPolicyAZRuleFour() throws Exception {
        String CONTENT = "---\n"
                + "- kind: routematcher.sermant.io/tag\n"
                + "  description: tag-az-rule-trigger-threshold-test\n"
                + "  rules:\n"
                + "    - precedence: 1\n"
                + "      match:\n"
                + "        tags:\n"
                + "          zone:\n"
                + "            exact: 'az1'\n"
                + "            caseInsensitive: false\n"
                + "        policy:\n"
                + "          triggerThreshold: 90\n"
                + "          minAllInstances: 10\n"
                + "      route:\n"
                + "        - tags:\n"
                + "            zone: CONSUMER_TAG\n";

        TimeUnit.SECONDS.sleep(3);
    }

    private void clearConfig() throws Exception {
        TimeUnit.SECONDS.sleep(3);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.testRouter();
		instance.testRouterWithFlowMatchRule();
		instance.testRouterWithGlobalFlowMatchRule();
		instance.testRouterWithFlowMatchRuleAndGlobalRule();
		instance.testRouterWithTagMatchRule();
		instance.testRouterWithGlobalTagMatchRule();
		instance.testRouterWithTagMatchRuleAndGlobalRule();
		instance.testRouterWithFlowAndTagRules();
		instance.testRouterWithConsumerTagRule();
		instance.testRouterWithTriggerThresholdPolicyRuleOne();
		instance.testRouterWithTriggerThresholdPolicyRuleTwo();
		instance.testRouterPolicyRuleOne();
		instance.testRouterPolicyRuleTwo();
		instance.testRouterPolicyRuleThree();
		instance.testRouterPolicyRuleFour();
		instance.testFlowMatchRule(Verifier.nondetString());
		instance.testTagMatchRule(Verifier.nondetString());
		instance.testFlowAndTagMatchRule();
		instance.testConsumerTagRule();
		instance.testTriggerThresholdPolicyAZRuleOne();
		instance.testTriggerThresholdPolicyAZRuleTwo();
		instance.testPolicyAZRuleOne();
		instance.testPolicyAZRuleTwo();
		instance.testPolicyAZRuleThree();
		instance.testPolicyAZRuleFour();
		instance.clearConfig();
	}
}
