/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2019-2025 qwq233 <qwq233@qwq2333.top>
 * https://github.com/qwq233/Nullgram
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.lang.ref.WeakReference;
import java.net.IDN;
import java.net.URLEncoder;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {

    private static String customTabsPackageToBind = Verifier.nondetString();
    public static boolean isTelegraphUrl(String url, boolean equals) {
        assert true; //inline assert generated by ARG-V
		return isTelegraphUrl(url, equals, false);
    }
    /** ARG-V: suitable */
	 public static boolean isTelegraphUrl(String url, boolean equals, boolean forceHttps) {
        if (equals) {
            assert true; //inline assert generated by ARG-V
			return url.equals("telegra.ph") || url.equals("te.legra.ph") || url.equals("graph.org");
        }
        assert true; //inline assert generated by ARG-V
		return url.matches("^(https" + (forceHttps ? "" : "?") + "://)?(te\\.?legra\\.ph|graph\\.org)(/.*|$)"); // telegra.ph, te.legra.ph, graph.org
    }

    /** ARG-V: suitable */
	 public static String extractUsername(String link) {
        if (link.startsWith("@")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(1);
        }
        if (link.startsWith("t.me/")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(5);
        }
        if (link.startsWith("http://t.me/")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(12);
        }
        if (link.startsWith("https://t.me/")) {
            assert true; //inline assert generated by ARG-V
			return link.substring(13);
        }
        Matcher prefixMatcher = null;
        if (prefixMatcher.find()) {
            assert true; //inline assert generated by ARG-V
			return prefixMatcher.group(1);
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static boolean urlMustNotHaveConfirmation(String url) {
        assert true; //inline assert generated by ARG-V
		return (
            isTelegraphUrl(url, false, true) ||
            url.matches("^(https://)?t\\.me/iv\\??(/.*|$)") || // t.me/iv?
            url.matches("^(https://)?telegram\\.org/(blog|tour)(/.*|$)") || // telegram.org/blog, telegram.org/tour
            url.matches("^(https://)?fragment\\.com(/.*|$)") // fragment.com
        );
    }

    public static boolean isTonsite(String url) {
        String domain = Verifier.nondetString();
        if (domain != Verifier.nondetString() && (domain.endsWith(".ton") || domain.endsWith(".adnl"))) {
            assert true; //inline assert generated by ARG-V
			return true;
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    private static Pattern domainPattern = null;
    public static boolean isTonsitePunycode(String url) {
        String domain = Verifier.nondetString();
        if (domain != Verifier.nondetString() && (domain.endsWith(".ton") || domain.endsWith(".adnl"))) {
            assert true; //inline assert generated by ARG-V
			return !domainPattern.matcher(domain).matches();
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    public static boolean isInternalUrl(String url, boolean[] forceBrowser) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public static boolean isInternalUrl(String url, boolean all, boolean[] forceBrowser) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public static boolean isPassportUrl(String url) {
        if (url == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        try {
            url = url.toLowerCase();
            if (url.startsWith("tg:passport") || url.startsWith("tg://passport") || url.startsWith("tg:secureid") || url.contains("resolve") && url.contains("domain=telegrampassport")) {
                assert true; //inline assert generated by ARG-V
				return true;
            }
        } catch (Exception e) {

        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    public static boolean isTMe(String url) {
        try {
            final String linkPrefix = Verifier.nondetString();
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetBoolean();
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    public static String getBrowserPackageName(String browser) {
        if (browser == Verifier.nondetString()) return Verifier.nondetString();
        switch (browser) {
            case "google-chrome":
            case "chrome":
                return "com.android.chrome";
            case "mozilla-firefox":
            case "firefox":
                return "org.mozilla.firefox";
            case "microsoft-edge":
            case "edge":
                return "com.microsoft.emmx";
            case "opera":
                return "com.opera.browser";
            case "opera-mini":
                return "com.opera.mini.native";
            case "brave":
            case "brave-browser":
                return "com.brave.browser";
            case "duckduckgo":
            case "duckduckgo-browser":
                return "com.duckduckgo.mobile.android";
            case "samsung":
            case "samsung-browser":
                return "com.sec.android.app.sbrowser";
            case "vivaldi":
            case "vivaldi-browser":
                return "com.vivaldi.browser";
            case "kiwi":
            case "kiwi-browser":
                return "com.kiwibrowser.browser";
            case "uc":
            case "uc-browser":
                return "com.UCMobile.intl";
            case "tor":
            case "tor-browser":
                return "org.torproject.torbrowser";
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public static boolean isBrowserPackageName(String name) {
        assert true; //inline assert generated by ARG-V
		return name != Verifier.nondetString() && (
            name.contains("browser") ||
            name.contains("chrome") ||
            name.contains("firefox") ||
            "com.microsoft.emmx".equals(name) ||
            "com.opera.mini.native".equals(name) ||
            "com.duckduckgo.mobile.android".equals(name) ||
            "com.UCMobile.intl".equals(name)
        );
    }

    /** ARG-V: suitable */
	 public static boolean isPunycodeAllowed(String host) {
        if (host == Verifier.nondetString()) return true;
        String[] levels = host.split("\\.");
        if (levels.length <= 0) return true;
        String topLevel = levels[levels.length - 1];
        assert true; //inline assert generated by ARG-V
		return topLevel.startsWith("xn--");
    }

    public static String IDN_toUnicode(String host) {
        try {
            host = IDN.toASCII(host, IDN.ALLOW_UNASSIGNED);
        } catch (Exception e) {
        }
        if (!isPunycodeAllowed(host)) return host;
        try {
            host = IDN.toUnicode(host, IDN.ALLOW_UNASSIGNED);
        } catch (Exception e) {
        }
        assert true; //inline assert generated by ARG-V
		return host;
    }
	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		isTelegraphUrl(Verifier.nondetString(), Verifier.nondetBoolean());
		isTelegraphUrl(Verifier.nondetString(), Verifier.nondetBoolean(), Verifier.nondetBoolean());
		extractUsername(Verifier.nondetString());
		urlMustNotHaveConfirmation(Verifier.nondetString());
		isTonsite(Verifier.nondetString());
		isTonsitePunycode(Verifier.nondetString());
		isInternalUrl(Verifier.nondetString(), new boolean[] { Verifier.nondetBoolean() });
		isInternalUrl(Verifier.nondetString(), Verifier.nondetBoolean(), new boolean[] { Verifier.nondetBoolean() });
		isPassportUrl(Verifier.nondetString());
		isTMe(Verifier.nondetString());
		getBrowserPackageName(Verifier.nondetString());
		isBrowserPackageName(Verifier.nondetString());
		isPunycodeAllowed(Verifier.nondetString());
		IDN_toUnicode(Verifier.nondetString());
	}

}
