

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Created by HaKr on 31/12/16.
 */

public class Main{

	public static char separatorChar = '/';
	public static String separator = "/";
	private String path = Verifier.nondetString();
	private boolean isRoot = false;
	public String host = Verifier.nondetString();

	public Main(String path, String host) {
		if(path.equals(separator)){
			setRoot(true);
		}
	}

	public String getName() {
		int separatorIndex = path.lastIndexOf(separator);
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	/** ARG-V: suitable */
	 public String getParent() {
		int length = path.length(), firstInPath = 0;
		int index = path.lastIndexOf(separatorChar);
		if (index == -1 || path.charAt(length - 1) == separatorChar) {
			assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
		}
		if (path.indexOf(separatorChar) == index
				&& path.charAt(firstInPath) == separatorChar) {
			assert true; //inline assert generated by ARG-V
			return path.substring(0, index + 1);
		}
		assert true; //inline assert generated by ARG-V
		return path.substring(0, index);
	}

	/**
	 * Returns the file of this file.
	 */
	public String getPath() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public String getAbsolutePath() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public boolean isDirectory() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
	}

	public boolean isFile() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
	}

	public long getSize() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetLong();
	}

	public boolean canWrite(){
		assert true; //inline assert generated by ARG-V
		return true;
	}

	public long lastModified(){
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetLong();
	}

	public void setRoot(boolean root){
		isRoot = root;
	}

	public  boolean isRoot(){
		assert true; //inline assert generated by ARG-V
		return isRoot;
	}

	public String getHost(){
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	public static String fixSlashes(String origPath) {
		// Remove duplicate adjacent slashes.
		boolean lastWasSlash = false;
		char[] newPath = origPath.toCharArray();
		int length = newPath.length;
		int newLength = 0;
		for (int i = 0; i < length; ++i) {
			char ch = newPath[i];
			if (ch == '/') {
				if (!lastWasSlash) {
					newPath[newLength++] = separatorChar;
					lastWasSlash = true;
				}
			} else {
				newPath[newLength++] = ch;
				lastWasSlash = false;
			}
		}
		// Remove any trailing slash (unless this is the root of the file system).
		if (lastWasSlash && newLength > 1) {
			newLength--;
		}
		assert true; //inline assert generated by ARG-V
		// Reuse the original string if possible.
		return (newLength != length) ? new String(newPath, 0, newLength) : origPath;
	}

	// Joins two file components, adding a separator only if necessary.
	/** ARG-V: suitable */
	 public static String join(String prefix, String suffix) {
		int prefixLength = prefix.length();
		boolean haveSlash = (prefixLength > 0 && prefix.charAt(prefixLength - 1) == separatorChar);
		if (!haveSlash) {
			haveSlash = (suffix.length() > 0 && suffix.charAt(0) == separatorChar);
		}
		assert true; //inline assert generated by ARG-V
		return haveSlash ? (prefix + suffix) : (prefix + separatorChar + suffix);
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString(), Verifier.nondetString());
		instance.getName();
		instance.getParent();
		instance.getPath();
		instance.getAbsolutePath();
		instance.isDirectory();
		instance.isFile();
		instance.getSize();
		instance.canWrite();
		instance.lastModified();
		instance.setRoot(Verifier.nondetBoolean());
		instance.isRoot();
		instance.getHost();
		fixSlashes(Verifier.nondetString());
		join(Verifier.nondetString(), Verifier.nondetString());
	}
}
