

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.UUID;

public class Main {
    public Main() { }

	public boolean isExit = false;

	public boolean unloadParentLevel = true;

	public boolean unloadThisLevelOnExit = true;

	public boolean fadetoBlack = true;

	public boolean showLoadingScreen = true;

	public String toWarpMarkerId = Verifier.nondetString();

	public boolean generated = false;

	public String levelToLoad = Verifier.nondetString();

	public String levelTheme = "DUNGEON";

	public String levelName = "UNKNOWN";

	public boolean spawnMonsters = false;

	public String travelPath = Verifier.nondetString();

	public float fogStart = 5;

	public float fogEnd = 15;

	public String loadingScreenBackground = Verifier.nondetString();

	public String levelChangeSound = "door_beginning.mp3";

	public String music = Verifier.nondetString();

	public String ambientSound = Verifier.nondetString();

	public String objectivePrefabToSpawn = Verifier.nondetString();

	public void doTriggerEvent(String value) {
		if(!(Verifier.nondetBoolean())){if (isExit){if (Verifier.nondetBoolean()){assert true;return;}}}
	}

	/** ARG-V: suitable */
	 public String getUseVerb() {
		String useVerbLocalized = Verifier.nondetString();
		if (useVerbLocalized.startsWith("triggers.")) {
			useVerbLocalized = Verifier.nondetString();
		}

		assert true; //inline assert generated by ARG-V
		return useVerbLocalized + " " + levelName;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.doTriggerEvent(Verifier.nondetString());
		instance.getUseVerb();
	}
}
