/** filtered and transformed by ARG-V */

/*
 * $Id: HtmlEncoder.java 3373 2008-05-12 16:21:24Z xlv $
 *
 * Copyright 1999, 2000, 2001, 2002 by Bruno Lowagie.
 *
 * The contents of this file are subject to the Mozilla Public License Version 1.1
 * (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the License.
 *
 * The Original Code is 'iText, a free JAVA-PDF library'.
 *
 * The Initial Developer of the Original Code is Bruno Lowagie. Portions created by
 * the Initial Developer are Copyright (C) 1999, 2000, 2001, 2002 by Bruno Lowagie.
 * All Rights Reserved.
 * Co-Developer of the code is Paulo Soares. Portions created by the Co-Developer
 * are Copyright (C) 2000, 2001, 2002 by Paulo Soares. All Rights Reserved.
 *
 * Contributor(s): all the names of the contributors are added in the source code
 * where applicable.
 *
 * Alternatively, the contents of this file may be used under the terms of the
 * LGPL license (the "GNU LIBRARY GENERAL PUBLIC LICENSE"), in which case the
 * provisions of LGPL are applicable instead of those above.  If you wish to
 * allow use of your version of this file only under the terms of the LGPL
 * License and not to allow others to use your version of this file under
 * the MPL, indicate your decision by deleting the provisions above and
 * replace them with the notice and other provisions required by the LGPL.
 * If you do not delete the provisions above, a recipient may use your version
 * of this file under either the MPL or the GNU LIBRARY GENERAL PUBLIC LICENSE.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the MPL as stated above or under the terms of the GNU
 * Library General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Library general Public License for more
 * details.
 *
 * If you didn't download this code from the following link, you should check if
 * you aren't using an obsolete version:
 * https://github.com/LibrePDF/OpenPDF
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.awt.Color;

/**
 * This class converts a <CODE>String</CODE> to the HTML-format of a String.
 * <p>
 * To convert the <CODE>String</CODE>, each character is examined:
 * <UL>
 * <LI>ASCII-characters from 000 till 031 are represented as &amp;#xxx;<BR>
 * (with xxx = the value of the character)
 * <LI>ASCII-characters from 032 t/m 127 are represented by the character itself, except for:
 * <UL>
 * <LI>'\n'    becomes &lt;BR&gt;\n
 * <LI>&quot; becomes &amp;quot;
 * <LI>&amp; becomes &amp;amp;
 * <LI>&lt; becomes &amp;lt;
 * <LI>&gt; becomes &amp;gt;
 * </UL>
 * <LI>ASCII-characters from 128 till 255 are represented as &amp;#xxx;<BR>
 * (with xxx = the value of the character)
 * </UL>
 * <p>
 * Example:
 * </p>
 * <BLOCKQUOTE><PRE>
 * String htmlPresentation = HtmlEncoder.encode("Marie-Th&#233;r&#232;se S&#248;rensen");
 * </PRE></BLOCKQUOTE>
 * <p>
 * for more info: see O'Reilly; "HTML: The Definitive Guide" (page 164)
 * </p>
 *
 * @author mario.maccarini@ugent.be
 *
 * @deprecated
 *
 */

public final class Main {

    // membervariables

    /**
     * List with the HTML translation of all the characters.
     */
    private static String[] htmlCode = new String[256];

    

    // constructors

    /**
     * This class will never be constructed.
     * <p>
     * HtmlEncoder only contains static methods.
     */

    private Main() {
    }

    // methods

    /**
     * Converts a <CODE>String</CODE> to the HTML-format of this <CODE>String</CODE>.
     *
     * @param string The <CODE>String</CODE> to convert
     * @return a <CODE>String</CODE>
     */

    /** ARG-V: suitable */
	 public static String encode(String string) {
        int n = string.length();
        char character = Verifier.nondetChar();
        StringBuilder buffer = new StringBuilder();
        // loop over all the characters of the String.
        for (int i = 0; i < n; i++) {
            character = string.charAt(i);
            // the Htmlcode of these characters are added to a StringBuffer one by one
            if (character < 256) {
                buffer.append(htmlCode[character]);
            } else {
                // Improvement posted by Joachim Eyrich
                buffer.append("&#").append((int) character).append(';');
            }
        }
        assert true; //inline assert generated by ARG-V
		return buffer.toString();
    }

    /**
     * Converts a <CODE>Color</CODE> into a HTML representation of this <CODE>Color</CODE>.
     *
     * @param color the <CODE>Color</CODE> that has to be converted.
     * @return the HTML representation of this <CODE>Color</CODE>
     */

    /** ARG-V: suitable */
	 public static String encode(Color color) {
        StringBuilder buffer = new StringBuilder("#");
        if (color.getRed() < 16) {
            buffer.append('0');
        }
        buffer.append(Integer.toString(color.getRed(), 16));
        if (color.getGreen() < 16) {
            buffer.append('0');
        }
        buffer.append(Integer.toString(color.getGreen(), 16));
        if (color.getBlue() < 16) {
            buffer.append('0');
        }
        buffer.append(Integer.toString(color.getBlue(), 16));
        assert true; //inline assert generated by ARG-V
		return buffer.toString();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		encode(Verifier.nondetString());
		encode((java.awt.Color) null);
	}
}
