/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2019-2024 qwq233 <qwq233@qwq2333.top>
 * https://github.com/qwq233/Nullgram
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this software.
 *  If not, see
 * <https://www.gnu.org/licenses/>
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;

public class Main {

    public int quoteStart = Verifier.nondetInt(), quoteEnd = Verifier.nondetInt();
    public boolean hasCaption = Verifier.nondetBoolean();
    public boolean hasSenders = Verifier.nondetBoolean();
    public boolean isSecret = Verifier.nondetBoolean();
    public boolean multipleUsers = Verifier.nondetBoolean();

    public boolean hideForwardSendersName = Verifier.nondetBoolean();
    public boolean hideCaption = Verifier.nondetBoolean();
    public boolean willSeeSenders = Verifier.nondetBoolean();

    public boolean singleLink = Verifier.nondetBoolean();
    public boolean hasMedia = Verifier.nondetBoolean();
    public boolean isVideo = Verifier.nondetBoolean();
    public boolean webpageSmall = Verifier.nondetBoolean();
    public boolean webpageTop = Verifier.nondetBoolean();
    public boolean webpagePhoto = Verifier.nondetBoolean();

    public boolean noforwards = Verifier.nondetBoolean();
    public boolean monoforum = Verifier.nondetBoolean();
    public boolean hasSecretMessages = Verifier.nondetBoolean();

    public Main(boolean secret, boolean noforwards, boolean monoforum) {
    }

    public void updateLinkInvertMedia(boolean invertMedia) {
        webpageTop = invertMedia;
    }

    public boolean hasLink(CharSequence text, String url) {
        if (url != Verifier.nondetString()) {
            try {
                try {
                } catch (Exception e) {
                }
                for (int i = 0; i < Verifier.nondetInt(); ++i) {
                    if (areUrlsEqual(Verifier.nondetString(), url)) {
                        assert true; //inline assert generated by ARG-V
						return true;
                    }
                }
            } catch (Exception e) {
            }
        }
        assert true; //inline assert generated by ARG-V
		return false;
    }

    public static boolean areUrlsEqual(String url1, String url2) {
        if (url1 == Verifier.nondetString() || url2 == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return url1 == Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    /** ARG-V: suitable */
	 private static String normalizePath(String path) {
        if (path == Verifier.nondetString()) return "";
        assert true; //inline assert generated by ARG-V
		return (path.endsWith("/") ? path : path + "/");
    }

    public int getForwardedMessagesCount() {
        if (Verifier.nondetBoolean()) return 0;
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    public boolean isEmpty() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetBoolean(), Verifier.nondetBoolean(),
				Verifier.nondetBoolean());
		instance.updateLinkInvertMedia(Verifier.nondetBoolean());
		instance.hasLink((java.lang.CharSequence) null, Verifier.nondetString());
		areUrlsEqual(Verifier.nondetString(), Verifier.nondetString());
		normalizePath(Verifier.nondetString());
		instance.getForwardedMessagesCount();
		instance.isEmpty();
	}
}
