


/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

    private static String PROXY_USER_TICKET_ID_STRING = "dss_user_session_proxy_ticket_id_v1";
    private static String PROXY_USER_PREFIX = "proxy_";

    /**
     * 通过 {@code SSOMsgParseOperation} 的 getUser 方法中获得的 user，是否是由 userName + proxyUser 组成的
     * @param user {@code SSOMsgParseOperation} 的 getUser 方法中获得的 user
     * @return true 如果是 user 是由userName + proxyUser 组成，否则返回 false
     */
    public static boolean existsProxyUser(String user) {
        assert true; //inline assert generated by ARG-V
		return user.startsWith(PROXY_USER_PREFIX);
    }

    /**
     * 返回一个经过特殊处理的、包含了 userName 和 proxyUser 的特殊字符串，可通过 {@code getUserAndProxyUser} 解密获取 userName 和 proxyUser
     * @param userName 登录用户名
     * @param proxyUser 代理用户
     * @return 返回包含了 userName 和 proxyUser 的特殊字符串
     */
    /** ARG-V: suitable */
	 public static String setUserAndProxyUser(String userName, String proxyUser) {
        int length = userName.length();
        if(length > 99) {
            throw new RuntimeException();
        }
        String lengthStr = String.valueOf(length);
        if(length < 10) {
            lengthStr = "0" + lengthStr;
        }
        assert true; //inline assert generated by ARG-V
		return String.format("%s%s%s%s", PROXY_USER_PREFIX, lengthStr, userName, proxyUser);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		existsProxyUser(Verifier.nondetString());
		setUserAndProxyUser(Verifier.nondetString(), Verifier.nondetString());
	}

}
