

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.logging.Level;

public class Main {

    public static boolean isEmbeddedBase64Font(String uri) {
        assert true; //inline assert generated by ARG-V
		return uri != Verifier.nondetString() && uri.startsWith("data:font/");
    }

    /** ARG-V: suitable */
	 public static InputStream getEmbeddedBase64Data(String uri) {
        int b64Index = (uri!= Verifier.nondetString())? uri.indexOf("base64,") : -1;
        if (b64Index != -1) {
            String b64encoded = uri.substring(b64Index + "base64,".length());
            if (b64encoded.contains("%")) {
                b64encoded = Verifier.nondetString();
            }
            assert true; //inline assert generated by ARG-V
			return new ByteArrayInputStream( Base64.getDecoder().decode( b64encoded));
        } else {
            assert true; //inline assert generated by ARG-V
			return null;
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		isEmbeddedBase64Font(Verifier.nondetString());
		getEmbeddedBase64Data(Verifier.nondetString());
	}
}
