/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Perform a semi-graceful shutdown of the Drill-on-YARN AM. We send a message
 * to the AM to request shutdown because the YARN-provided message just kills
 * the AM. (There seems to be no way to get YARN to call its own
 * AMRMClientAsync.CallbackHandler.onShutdownRequest message.) The AM, however,
 * cannot gracefully shut down the drill-bits because Drill itself has no
 * graceful shutdown. But, at least this technique gives the AM a fighting
 * chance to do graceful shutdown in the future.
 */

public class Main {
  public void run() throws RuntimeException {
    

    // First get an application report to ensure that the AM is,
    // in fact, running, and to get the HTTP endpoint.

    try {
    } catch (Exception e) {
    }

    // Handle the case of an already stopped app.

    boolean stopped = true;
    

    // If the AM is gone because it started out dead or
    // we killed it, then forget its App Id.

  }

  /**
   * Do a graceful shutdown by using the AM's REST API call to request stop.
   * Include the master key with the request to differentiate this request from
   * accidental uses of the stop REST API.
   *
   * @param baseUrl base url to be posted with the shutdown
   * @return true if stops gracefully, otherwise false
   */

  /** ARG-V: suitable */
 private boolean gracefulStop(String baseUrl) {
    try {
      if (Verifier.nondetBoolean()) {
        assert true; //inline assert generated by ARG-V
		return false;
      }
      String tail = "rest/stop";
      String masterKey = Verifier.nondetString();
      if (Verifier.nondetBoolean()) {
        System.out.println("Stopping with POST " + baseUrl + "/" + tail);
      }
      String result = Verifier.nondetString();
      if (result.contains("\"ok\"")) {
        assert true; //inline assert generated by ARG-V
		return true;
      }
      System.err.println(
          "Failed to stop the application master. Response = " + result);
      assert true; //inline assert generated by ARG-V
	return false;
    } catch (Exception e) {
      System.err.println(new char[] { Verifier.nondetChar() });
      System.out.println("Resorting to forced kill");
      assert true; //inline assert generated by ARG-V
	return false;
    }
  }

  /**
   * If the graceful approach did not work, resort to a forceful request. This
   * asks the AM's NM to kill the AM process.
   *
   * @throws ClientException
   */

  private void forcefulStop() throws RuntimeException {
    try {
    } catch (Exception e) {
      throw new RuntimeException();
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.run();
	instance.gracefulStop(Verifier.nondetString());
	instance.forcefulStop();
}
}
