/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;

public class Main {
    private String url = Verifier.nondetString();
    private String hash = Verifier.nondetString();
    private String urlDesc = Verifier.nondetString();
    private ArrayList<String> globalDesc = null;

    public String getUrl() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getHash() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getUrlDesc() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public ArrayList<String> getGlobalDesc() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /** ARG-V: suitable */
	 public String toString() {
        String hexHash = Integer.toHexString(Integer.parseInt(hash));
        assert true; //inline assert generated by ARG-V
		return String.format("<html>" +
                "HASH: " +
                "<font style=\"color: blue; font-weight: bold;\">%s</font>" +
                "   URL: " +
                "<font style=\"color: red; font-weight: bold;\">%s</font>" +
                "</html>", hexHash, this.url);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getUrl();
		instance.getHash();
		instance.getUrlDesc();
		instance.getGlobalDesc();
		instance.toString();
	}
}
