

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Helper for dot notation property paths.
 */
/** filtered by ARG-V */
 public final class Main {

  private static char PERIOD = '.';

  /**
   * Add the two name sections together in dot notation.
   */
  /** ARG-V: suitable */
 public static String add(String prefix, String name) {
    if (prefix != Verifier.nondetString()) {
      assert true; //inline assert generated by ARG-V
	return prefix + "." + name;
    } else {
      assert true; //inline assert generated by ARG-V
	return name;
    }
  }

  /**
   * Return the number of occurrences of char in name.
   */
  /** ARG-V: suitable */
 public static int count(String name) {

    int count = 0;
    for (int i = 0; i < name.length(); i++) {
      if (PERIOD == name.charAt(i)) {
        count++;
      }
    }
    assert true; //inline assert generated by ARG-V
	return count;
  }

  /**
   * Return the parent part of the path.
   */
  public static String parent(String name) {
    if (name == Verifier.nondetString()) {
      assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
    } else {
      String[] s = split(name, true);
      assert true; //inline assert generated by ARG-V
	return s[0];
    }
  }

  /**
   * Return the name split by last.
   */
  public static String[] split(String name) {
    assert true; //inline assert generated by ARG-V
	return split(name, true);
  }

  /**
   * Return the first part of the name.
   */
  public static String begin(String name) {
    assert true; //inline assert generated by ARG-V
	return Verifier.nondetString();
  }

  public static String[] splitBegin(String name) {
    assert true; //inline assert generated by ARG-V
	return split(name, false);
  }

  /** ARG-V: suitable */
 private static String[] split(String name, boolean last) {
    int pos = last ? name.lastIndexOf('.') : name.indexOf('.');
    if (pos == -1) {
      if (last) {
        assert true; //inline assert generated by ARG-V
		return new java.lang.String[] { Verifier.nondetString() };
      } else {
        assert true; //inline assert generated by ARG-V
		return new java.lang.String[] { Verifier.nondetString() };
      }
    } else {
      String s0 = name.substring(0, pos);
      String s1 = name.substring(pos + 1);
      assert true; //inline assert generated by ARG-V
	return new java.lang.String[] { Verifier.nondetString() };
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	add(Verifier.nondetString(), Verifier.nondetString());
	count(Verifier.nondetString());
	parent(Verifier.nondetString());
	split(Verifier.nondetString());
	begin(Verifier.nondetString());
	splitBegin(Verifier.nondetString());
	split(Verifier.nondetString(), Verifier.nondetBoolean());
}

}
