

/** filtered and transformed by ARG-V */

/**
 * Copyright (c) 2011-2023, James Zhan 詹波 (jfinal@126.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Include
 *
 * 1：父模板被缓存时，被 include 的模板会被间接缓存，无需关心缓存问题
 * 2：同一个模板文件被多个父模板 include，所处的背景环境不同，例如各父模板中定义的模板函数不同
 * 各父模板所处的相对路径不同，所以多个父模板不能共用一次 parse 出来的结果，而是在每个被include
 * 的地方重新 parse
 *
 * <pre>
 * 两种用法：
 * 1：只传入一个参数，参数必须是 String 常量，如果希望第一个参数是变量可以使用 #render 指令去实现
 *   #include("_hot.html")
 *
 * 2：传入任意多个参数，除第一个参数以外的所有参数必须是赋值表达式，用于实现参数传递功能
 *   #include("_hot.html", title = "热门新闻", list = newsList)
 *
 *   上例中传递了 title、list 两个参数，可以代替父模板中的 #set 指令传参方式
 *   并且此方式传入的参数只在子模板作用域有效，不会污染父模板作用域
 *
 *   这种传参方式有利于将子模板模块化，例如上例的调用改成如下的参数：
 *   #include("_hot.html", title = "热门项目", list = projectList)
 *   通过这种传参方式在子模板 _hot.html 之中，完全不需要修改对于 title 与 list
 *   这两个变量的处理代码，就实现了对 “热门项目” 数据的渲染
 * </pre>
 */
public class Main {

    /**
     * 获取在父模板之下子模板的最终文件名，子模板目录相对于父模板文件目录来确定
     * 以 "/" 打头则以 baseTemplatePath 为根，否则以父文件所在路径为根
     */
    /** ARG-V: suitable */
	 public static String getSubFileName(String fileName, String parentFileName) {
        if (parentFileName == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return fileName;
        }
        if (fileName.startsWith("/")) {
            assert true; //inline assert generated by ARG-V
			return fileName;
        }
        int index = parentFileName.lastIndexOf('/');
        if (index == -1) {
            assert true; //inline assert generated by ARG-V
			return fileName;
        }
        assert true; //inline assert generated by ARG-V
		return parentFileName.substring(0, index + 1) + fileName;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getSubFileName(Verifier.nondetString(), Verifier.nondetString());
	}
}







