

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** filtered by ARG-V */
 public class Main {

    public int index = Verifier.nondetInt();
    public String rule = Verifier.nondetString();
    public List<String> excludes = null;

    public Main(String rule) {
    }

    /** ARG-V: suitable */
	 public void setInfo(String pos) {
        if (rule.contains("--")) {
            String[] rules = rule.split("--");
            setExcludes(rules);
        } else if (pos.contains("--")) {
            String[] rules = pos.split("--");
            setExcludes(rules);
            pos = rules[0];
        }
        try {
            index = Integer.parseInt(pos.replace("eq(", "").replace(")", ""));
        } catch (Exception e) {
            index = 0;
        }
    }

    public void setExcludes(String[] rules) {
        excludes.remove(0);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString());
		instance.setInfo(Verifier.nondetString());
		instance.setExcludes(new java.lang.String[] { Verifier.nondetString() });
	}
}
