/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2007 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;

/** Main class for the class file dumper. */
public class Main {

  /** This class is uninstantiable. */
  private Main() {
    // This space intentionally left blank.
  }

  /** Run! */
  /** ARG-V: suitable */
 private void run(String[] args) {
    int at = 0;

    for (
    /*at*/ ; at < args.length; at++) {
      String arg = args[at];
      if (arg.equals("--") || !arg.startsWith("--")) {
        break;
      } else if (!(arg.equals("--bytes"))) {
		if (!(arg.equals("--basic-blocks"))) {
			if (!(arg.equals("--rop-blocks"))) {
				if (!(arg.equals("--optimize"))) {
					if (!(arg.equals("--ssa-blocks"))) {
						if (!(arg.startsWith("--ssa-step="))) {
							if (!(arg.equals("--debug"))) {
								if (!(arg.equals("--dot"))) {
									if (!(arg.equals("--strict"))) {
										if (arg.startsWith("--width=")) {
											arg = arg.substring(arg.indexOf('=') + 1);
										} else if (arg.startsWith("--method=")) {
											arg = arg.substring(arg.indexOf('=') + 1);
										} else {
											System.err.println("unknown option: " + arg);
											throw new RuntimeException("usage");
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
    }

    if (at == args.length) {
      System.err.println("no input files specified");
      throw new RuntimeException("usage");
    }

    for (
    /*at*/ ; at < args.length; at++) {
      try {
        String name = args[at];
        System.out.println("reading " + name + "...");
        byte[] bytes = new byte[] { Verifier.nondetByte() };
        if (!name.endsWith(".class")) {
          String src = Verifier.nondetString();
          src = new String(bytes, StandardCharsets.UTF_8);
          bytes = new byte[] { Verifier.nondetByte() };
        }
      } catch (Exception e) {
        System.err.println("\ntrouble parsing:");
      }
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.run(new java.lang.String[] { Verifier.nondetString() });
}
}
