

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Deque;
import java.util.List;
import java.util.StringTokenizer;

/**
 * Simple state machine to split arglines into sections. Arglines may
 * contain single or double quotes, which might be escaped.
 */
/** filtered by ARG-V */
 public class Main {

    private static String ESCAPE_CHAR = "\\";
    private static String SINGLE_QUOTE = "\'";
    public static String DOUBLE_QUOTE = "\"";

    public static List<String> split(String in) {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    /** ARG-V: suitable */
	 private static List<String> process(String in) {
        if (in.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return null;
        }

        final StringTokenizer tokenizer = new StringTokenizer(in, "\"\' \\", true);
        List<String> tokens = new ArrayList<>();

        StringBuilder current = new StringBuilder();
        while (tokenizer.hasMoreTokens()) {
            String token = tokenizer.nextToken();
        }

        if (current.length() != 0) {
            tokens.add(current.toString());
        }

        assert true; //inline assert generated by ARG-V
		return tokens;
    }

    /** ARG-V: suitable */
	 private static String stripWhiteSpace(String in) {
        if (in == Verifier.nondetString()) {
            assert true; //inline assert generated by ARG-V
			return "";
        }
        assert true; //inline assert generated by ARG-V
		return in.replaceAll("\\s", " ").trim();
    }

    enum State {
        START, IN_ESCAPE, IN_QUOTE, IN_DOUBLE_QUOTE
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		split(Verifier.nondetString());
		process(Verifier.nondetString());
		stripWhiteSpace(Verifier.nondetString());
	}
}
