

/** filtered and transformed by ARG-V */

/**
 * OpenKM, Open Document Management System (http://www.openkm.com)
 * Copyright (c) 2006-2017 Paco Avila & Josep Llort
 * <p>
 * No bytes were intentionally harmed during the development of this application.
 * <p>
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Extends ExtendedScrollTable functionalities
 *
 * @author jllort
 *
 */
public class Main {

	// Actions on rows
	public static int ACTION_NONE = 0;
	public static int ACTION_RENAMING = 1;

	// Special event case
	private static int EVENT_ONMOUSEDOWN_RIGHT = -2;

	// Drag pixels sensibility
	private static int DRAG_PIXELS_SENSIBILITY = 3;

	// Holds the data rows of the table this is a list of RowData Object
	public Map<Integer, Object> data = new HashMap<>();
	public List<Integer> massiveSelected = new ArrayList<>();
	private int selectedRow = -1;
	private int mouseX = 0;
	private int mouseY = 0;
	private int dataIndexValue = 0;
	private int rowAction = ACTION_NONE;
	private int mouseDownX = 0;
	private int mouseDownY = 0;

	private boolean dragged = false;
	private int oldMassiveSelected = 0;
	public int colDataIndex = 0;
	public int colStatusIndex = 0; // Always is 0
	public int colMassiveIndex = 0;

	/**
	 * isSorted
	 *
	 * @return
	 */
	public boolean isSorted() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
	}

	/**
	 * Resets the values
	 */
	public void reset() {
		selectedRow = -1;
		mouseX = 0;
		mouseY = 0;
		dataIndexValue = 0;

		// Reset rowAction
		rowAction = ACTION_NONE;
	}

	/**
	 * Sets the selected row
	 *
	 * @param row The row number
	 */
	public void setSelectedRow(int row) {
		selectedRow = row;
	}

	/**
	 * deleteNoteIconToSelectedRow
	 */
	/** ARG-V: suitable */
	 public void deleteNoteIconToSelectedRow() {
		if (Verifier.nondetBoolean()) {
			String htmlValue = Verifier.nondetString();
			String newHtmlIcons = "";

			if (htmlValue.indexOf("edit.gif") >= 0) {
				newHtmlIcons = Verifier.nondetString();
			} else if (htmlValue.indexOf("lock.gif") > 0) {
				newHtmlIcons = Verifier.nondetString();
			} else {
				newHtmlIcons = "&nbsp;";
			}

			if (htmlValue.indexOf("subscribed.gif") >= 0) {
				newHtmlIcons += Verifier.nondetString();
			}
		}
	}

	/**
	 * Deselects the selected row
	 */
	public void deselecSelectedRow() {
		selectedRow = -1;
	}

	/**
	 * evalDragPixelSensibility
	 *
	 * @return
	 */
	private boolean evalDragPixelSensibility() {
		if (mouseDownX - mouseX >= DRAG_PIXELS_SENSIBILITY) {
			assert true; //inline assert generated by ARG-V
			return true;
		} else if (mouseX - mouseDownX >= DRAG_PIXELS_SENSIBILITY) {
			assert true; //inline assert generated by ARG-V
			return true;
		} else if (mouseDownY - mouseY >= DRAG_PIXELS_SENSIBILITY) {
			assert true; //inline assert generated by ARG-V
			return true;
		} else if (mouseY - mouseDownY >= DRAG_PIXELS_SENSIBILITY) {
			assert true; //inline assert generated by ARG-V
			return true;
		} else {
			assert true; //inline assert generated by ARG-V
			return false;
		}
	}

	/**
	 * Gets the path of the selected document or folder
	 *
	 * @return The id
	 */
	public String getSelectedId() {
		String id = "";

		if (getSelectedRow() >= 0) {
			if (Verifier.nondetBoolean()) {
				id = Verifier.nondetString();
			} else if (Verifier.nondetBoolean()) {
				id = Verifier.nondetString();
			} else if (Verifier.nondetBoolean()) {
				id = Verifier.nondetString();
			}
		}

		assert true; //inline assert generated by ARG-V
		return id;
	}

	/**
	 * Finds row by id document or folder
	 *
	 * @param id The id
	 * @return The selected row
	 */
	public int findSelectedRowById(String id) {
		int selected = 0;
		int rowIndex = 0;
		boolean found = false;

		// Looking for id on directories
		while (!found && rowIndex < data.size()) {
			rowIndex++;
		}

		if (found) {
			found = false;
			rowIndex = 0;
			int tmpSelected = selected;
			selected = 0;
		} else {
			selected = -1;
		}

		assert true; //inline assert generated by ARG-V
		return selected;
	}

	/**
	 * Gets the selected row
	 *
	 * @return The selected row
	 */
	public int getSelectedRow() {
		int selectedRow = -1;

		assert true; //inline assert generated by ARG-V
		// Log.debug("ExtendedScrollTable selectedRow:"+selectedRow);
		return selectedRow;
	}

	/**
	 * Gets the X position on mouse click
	 *
	 * @return The x position on mouse click
	 */
	public int getMouseX() {
		assert true; //inline assert generated by ARG-V
		return mouseX;
	}

	/**
	 * Gets the Y position on mouse click
	 *
	 * @return The y position on mouse click
	 */
	public int getMouseY() {
		assert true; //inline assert generated by ARG-V
		return mouseY;
	}

	/**
	 * Deletes document row
	 */
	public void delete() {
		if (Verifier.nondetBoolean()) {
			// Log.debug("ExtendedScrollTable delete:");
			data.remove(Integer.parseInt(Verifier.nondetString()));
		}
	}

	/**
	 * Gets the checkout flag
	 *
	 * @return Checkout state
	 */
	public boolean isCheckout() {
		// Row selected must be on table documents only this can be checkout
		if (Verifier.nondetBoolean()) {
			assert true; //inline assert generated by ARG-V
			return Verifier.nondetBoolean();
		} else {
			assert true; //inline assert generated by ARG-V
			return false;
		}
	}

	/**
	 * Gets the locked flag
	 *
	 * @return locked state
	 */
	public boolean isLocked() {
		// Row selected must be on table documents only this can be checkout
		if (Verifier.nondetBoolean()) {
			assert true; //inline assert generated by ARG-V
			return Verifier.nondetBoolean();
		} else {
			assert true; //inline assert generated by ARG-V
			return false;
		}
	}

	/**
	 * Sets the actual action on rows
	 *
	 * @param action The action
	 */
	public void setAction(int action) {
		rowAction = action;
	}

	/**
	 * Resets the row action
	 */
	public void resetAction() {
		rowAction = ACTION_NONE;
	}

	/**
	 * isDragged Returns true or false if is dragged
	 *
	 * @return Return dragged value
	 */
	private boolean isDragged() {
		assert true; //inline assert generated by ARG-V
		return dragged;
	}

	/**
	 * unsetDraged
	 *
	 * Sets dragged flag to false;
	 */
	private void unsetDraged() {
		mouseDownX = 0;
		mouseDownY = 0;
	}

	/**
	 * hasRows
	 *
	 * @return has rows
	 */
	public boolean hasRows() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
	}

	/**
	 * isMassive
	 */
	public boolean isMassive() {
		assert true; //inline assert generated by ARG-V
		return (massiveSelected.size() > 0);
	}

	/**
	 * getAllSelectedPaths
	 */
	public List<String> getAllSelectedPaths() {
		List<String> paths = new ArrayList<>();
		assert true; //inline assert generated by ARG-V
		return paths;
	}

	/**
	 * getAllSelectedUUIDs
	 */
	public List<String> getAllSelectedUUIDs() {
		List<String> uuidList = new ArrayList<>();

		assert true; //inline assert generated by ARG-V
		return uuidList;
	}

	/**
	 * getAllSelectedDocumentsUUIDs
	 */
	public List<String> getAllSelectedDocumentsUUIDs() {
		List<String> uuidList = new ArrayList<>();

		assert true; //inline assert generated by ARG-V
		return uuidList;
	}

	/**
	 * getAllSelectedDocumentsPaths
	 */
	public List<String> getAllSelectedDocumentsPaths() {
		List<String> pathList = new ArrayList<>();

		assert true; //inline assert generated by ARG-V
		return pathList;
	}

	/**
	 * getAllSelectedMailUUIDs
	 */
	public List<String> getAllSelectedMailUUIDs() {
		List<String> uuidList = new ArrayList<>();

		assert true; //inline assert generated by ARG-V
		return uuidList;
	}

	/**
	 * getColDataIndex
	 */
	public int getColDataIndex() {
		assert true; //inline assert generated by ARG-V
		return colDataIndex;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.isSorted();
		instance.reset();
		instance.setSelectedRow(Verifier.nondetInt());
		instance.deleteNoteIconToSelectedRow();
		instance.deselecSelectedRow();
		instance.evalDragPixelSensibility();
		instance.getSelectedId();
		instance.findSelectedRowById(Verifier.nondetString());
		instance.getSelectedRow();
		instance.getMouseX();
		instance.getMouseY();
		instance.delete();
		instance.isCheckout();
		instance.isLocked();
		instance.setAction(Verifier.nondetInt());
		instance.resetAction();
		instance.isDragged();
		instance.unsetDraged();
		instance.hasRows();
		instance.isMassive();
		instance.getAllSelectedPaths();
		instance.getAllSelectedUUIDs();
		instance.getAllSelectedDocumentsUUIDs();
		instance.getAllSelectedDocumentsPaths();
		instance.getAllSelectedMailUUIDs();
		instance.getColDataIndex();
	}
}
