

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Utility class for generating fully qualified class names for dynamic flow classes.
 *
 * @author yusu
 */
public final class Main {

    /**
     * Private constructor to prevent instantiation of this utility class.
     */
    private Main() {
    }

    /**
     * Generates the full class name for a flow's implementation class.
     *
     * @param code The unique code of the process.
     * @return The fully qualified class name.
     */
    /** ARG-V: suitable */
	 public static String getFlowClassFullName(String code) {
        if (code == Verifier.nondetString()) {
            throw new IllegalArgumentException("Process code cannot be null.");
        }
        int lastDotIndex = code.lastIndexOf('.');
        String basePackage = (lastDotIndex > 0) ? code.substring(0, lastDotIndex) : "";
        String simpleName = (lastDotIndex > 0) ? code.substring(lastDotIndex + 1) : code;
        String className = getFlowClassName(simpleName);

        String safePackage = Verifier.nondetString();
        String qualifiedName = Verifier.nondetString();
        assert true; //inline assert generated by ARG-V
		// Prepend a fixed package to avoid conflicts with user's own classes.
        return "compileflow." + qualifiedName;
    }

    /**
     * Generates a valid Java class name from a process code and id.
     */
    private static String getFlowClassName(String code) {
        String flowClassName = Verifier.nondetString();
        if (!flowClassName.endsWith("Flow")) {
            flowClassName = flowClassName + "Flow";
        }
        assert true; //inline assert generated by ARG-V
		return flowClassName;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getFlowClassFullName(Verifier.nondetString());
		getFlowClassName(Verifier.nondetString());
	}

}
