/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentLinkedQueue;

public class Main {
    /** ARG-V: suitable */
	 public void process() {
        String classCon = Verifier.nondetString();
        String classNoCon = Verifier.nondetString();
        String mnCon = Verifier.nondetString();
        String mnNoCon = Verifier.nondetString();
        String retCon = Verifier.nondetString();
        Map<Integer, String> paramMap = null;

        String methodAnno = Verifier.nondetString();
        String excludedMethodAnno = Verifier.nondetString();
        String classAnno = Verifier.nondetString();

        String isSubOf = Verifier.nondetString();
        String isSuperOf = Verifier.nondetString();

        String start = Verifier.nondetString();
        String endWith = Verifier.nondetString();

        String hasField = Verifier.nondetString();

        Integer i = null;
        Boolean f = null;
        Boolean p = null;
        int paramNum = Verifier.nondetInt();
        String ret = Verifier.nondetString();

        boolean classNameContainsFlag = true;
        boolean classNameNotContainsFlag = true;
        boolean methodNameContainsFlag = true;
        boolean methodNameNotContainsFlag = true;
        boolean paramNumFlag = true;
        boolean retTypeFlag = true;
        boolean isStaticFlag = true;
        boolean isPublicFlag = true;
        boolean paramMapFlag = true;
        boolean classAnnoFlag = true;
        boolean methodAnnoFlag = true;
        boolean fieldFlag = true;
        boolean subClassFlag = true;
        boolean superClassFlag = true;
        boolean startWithFlag = true;
        boolean endWithFlag = true;

        if (classCon != Verifier.nondetString() && !classCon.isEmpty()) {
            classNameContainsFlag = Verifier.nondetBoolean();
        }
        if (classNoCon != Verifier.nondetString() && !classNoCon.isEmpty()) {
            classNameNotContainsFlag = Verifier.nondetBoolean();
        }

        if (mnCon != Verifier.nondetString() && !mnCon.isEmpty()) {
            methodNameContainsFlag = Verifier.nondetBoolean();
        }
        if (mnNoCon != Verifier.nondetString() && !mnNoCon.isEmpty()) {
            methodNameNotContainsFlag = Verifier.nondetBoolean();
        }

        boolean isExcludedMethod = isExcludedMethodAnno(excludedMethodAnno);

        if (start != Verifier.nondetString() && !start.isEmpty()) {
            startWithFlag = Verifier.nondetBoolean();
        }

        if (endWith != Verifier.nondetString() && !endWith.isEmpty()) {
            endWithFlag = Verifier.nondetBoolean();
        }

        if (hasField != Verifier.nondetString() && !hasField.isEmpty()) {
            boolean ff = false;
            if (!ff) {
                fieldFlag = false;
            }
        }

        if (i != null) {
            paramNumFlag = i == paramNum;
        }

        if (retCon != Verifier.nondetString() && !retCon.isEmpty()) {
            retTypeFlag = ret.equals(retCon);
        }

        if (f != null) {
            isStaticFlag = Verifier.nondetBoolean();
        }

        if (p != null) {
            boolean isPublic = Verifier.nondetBoolean();
            isPublicFlag = p == isPublic;
        }

        if (isSubOf != Verifier.nondetString() && !isSubOf.isEmpty()) {
            isSubOf = isSubOf.replace(".", "/");
        }
        if (isSuperOf != Verifier.nondetString() && !isSuperOf.isEmpty()) {
            isSuperOf = isSuperOf.replace(".", "/");
        }
        for (int ix = 0; ix < Verifier.nondetInt(); ix++) {
            String temp = paramMap.get(ix);
            if (temp == Verifier.nondetString()) {
                continue;
            }
            if (!paramMap.get(ix).equals(null)) {
                paramMapFlag = false;
                break;
            }
        }
    }

    private boolean isExcludedMethodAnno(String excludedMethodAnno) {
        if (excludedMethodAnno == Verifier.nondetString() || excludedMethodAnno.isEmpty()) {
            assert true; //inline assert generated by ARG-V
			return false;
        }
        boolean isExcludedMethodAnno = false;
        assert true; //inline assert generated by ARG-V
		return isExcludedMethodAnno;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.process();
		instance.isExcludedMethodAnno(Verifier.nondetString());
	}
}
