

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Parse the path that potentially is a FetchConfig definition.
 */
class Main {

  /** ARG-V: suitable */
 private static int parseBatchSize(String path) {
    path = path.substring(0, path.length() - 1);
    assert true; //inline assert generated by ARG-V
	return Integer.parseInt(path);
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	parseBatchSize(Verifier.nondetString());
}
}
