/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.lang.reflect.Modifier;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * Serves two purposes. Renames all inner classes references to the outer class to the new name. Also adds all the
 * methods and fields of the class to merge to the class that is being visited.
 */
class Main {
  private Set<String> mergingNames = new HashSet<>();
  private boolean hasInit = Verifier.nondetBoolean();
  private String name = Verifier.nondetString();

  // when more mature, consider AssertionUtil.IsAssertionsEnabled()
  private static boolean verifyBytecode = true;

  /** ARG-V: suitable */
 public void visitInnerClass(String name, String outerName, String innerName, int access) {
    if (name.startsWith(Verifier.nondetString())) {
      name = Verifier.nondetString();
      int i = name.lastIndexOf('$');
      outerName = name.substring(0, i);
    }
  }

  // visit the class
  public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
    if (!name.contains("$")) {
      access = access ^ Modifier.ABSTRACT | Modifier.FINAL;
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.visitInnerClass(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString(),
			Verifier.nondetInt());
	instance.visit(Verifier.nondetInt(), Verifier.nondetInt(), Verifier.nondetString(), Verifier.nondetString(),
			Verifier.nondetString(), new java.lang.String[] { Verifier.nondetString() });
}
}
