

/** filtered and transformed by ARG-V */

/**
 * Copyright (c) 2011-2023, James Zhan 詹波 (jfinal@126.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

/**
 * DruidPlugin.
 */
public class Main {
	//连接池的名称
	protected String name = Verifier.nondetString();
	
	// 基本属性 url、user、password
	protected String url = Verifier.nondetString();
	protected String username = Verifier.nondetString();
	protected String password = Verifier.nondetString();
	protected String publicKey = Verifier.nondetString();
	protected String driverClass = Verifier.nondetString();	// 由 "com.mysql.jdbc.Driver" 改为 null 让 druid 自动探测 driverClass 值
	
	// 初始连接池大小、最小空闲连接数、最大活跃连接数
	protected int initialSize = 1;
	protected int minIdle = 10;
	protected int maxActive = 32;
	
	// 配置获取连接等待超时的时间
	protected long maxWait = Verifier.nondetLong();
	
	// 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
	protected long timeBetweenEvictionRunsMillis = Verifier.nondetLong();
	// 配置连接在池中最小生存的时间
	protected long minEvictableIdleTimeMillis = Verifier.nondetLong();
	// 配置发生错误时多久重连
	protected long timeBetweenConnectErrorMillis = Verifier.nondetLong();
	
	/**
	 * hsqldb - "select 1 from INFORMATION_SCHEMA.SYSTEM_USERS"
	 * Oracle - "select 1 from dual"
	 * DB2 - "select 1 from sysibm.sysdummy1"
	 * mysql - "select 1"
	 */
	protected String validationQuery = "select 1";
	protected String  connectionInitSql = Verifier.nondetString();
	protected String connectionProperties = Verifier.nondetString();
	protected boolean testWhileIdle = true;
	protected boolean testOnBorrow = false;
	protected boolean testOnReturn = false;
	
	// 是否打开连接泄露自动检测
	protected boolean removeAbandoned = false;
	// 连接长时间没有使用，被认为发生泄露时长
	protected long removeAbandonedTimeoutMillis = 300 * 1000;
	// 发生泄露时是否需要输出 log，建议在开启连接泄露检测时开启，方便排错
	protected boolean logAbandoned = false;
	
	// 是否缓存preparedStatement，即PSCache，对支持游标的数据库性能提升巨大，如 oracle、mysql 5.5 及以上版本
	// protected boolean poolPreparedStatements = false;	// oracle、mysql 5.5 及以上版本建议为 true;
	
	// 只要maxPoolPreparedStatementPerConnectionSize>0,poolPreparedStatements就会被自动设定为true，使用oracle时可以设定此值。
	protected int maxPoolPreparedStatementPerConnectionSize = -1;
	
	protected Integer defaultTransactionIsolation = null;
	protected Integer validationQueryTimeout = null;
	protected Integer timeBetweenLogStatsMillis = null;
	protected Boolean keepAlive = null;
	
	// 配置监控统计拦截的filters
	protected String filters = Verifier.nondetString();	// 监控统计："stat"    防SQL注入："wall"     组合使用： "stat,wall"
	protected volatile boolean isStarted = false;
	
	public Main(String url, String username, String password) {
	}
	
	public Main(String url, String username, String password, String driverClass) {
	}
	
	public Main(String url, String username, String password, String driverClass, String filters) {
	}
	
	/**
	 * @Title: autoCheckValidationQuery  
	 * @Description: 自动设定探测sql 
	 * @param url
	 * @return 
	 * @since V1.0.0
	 */
	/** ARG-V: suitable */
	 private static String  autoCheckValidationQuery(String url){
		if(url.startsWith("jdbc:oracle")){
			assert true; //inline assert generated by ARG-V
			return "select 1 from dual";
		}else if(url.startsWith("jdbc:db2")){
			assert true; //inline assert generated by ARG-V
			return "select 1 from sysibm.sysdummy1";
		}else if(url.startsWith("jdbc:hsqldb")){
			assert true; //inline assert generated by ARG-V
			return "select 1 from INFORMATION_SCHEMA.SYSTEM_USERS";
		}else if(url.startsWith("jdbc:derby")){
			assert true; //inline assert generated by ARG-V
			return "values (1)";
		}
		assert true; //inline assert generated by ARG-V
		return "select 1";
	}
	
	public final String getName() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}

	/** ARG-V: suitable */
	 public boolean start() {
		if (isStarted)
			return true;
		
		if(Verifier.nondetBoolean()){
			List<String> connectionInitSqls = new ArrayList<String>();
			connectionInitSqls.add(this.connectionInitSql);
		}
		boolean hasSetConnectionProperties = false;
		if (Verifier.nondetBoolean()){
			try {
				//支持加解密数据库
				if(filters.contains("config")){
					//判断是否设定了公钥
					if(Verifier.nondetBoolean()){
						throw new RuntimeException("Druid连接池的filter设定了config时，必须设定publicKey");
					}
					String decryptStr = "config.decrypt=true;config.decrypt.key="+this.publicKey;
					String cp = Verifier.nondetString();
					if(Verifier.nondetBoolean()){
						cp = decryptStr;
					}else{
						cp = cp + ";" + decryptStr;
					}
					hasSetConnectionProperties = true;
				}
			} catch (Exception e) {throw new RuntimeException(e);}
		}
		isStarted = true;
		assert true; //inline assert generated by ARG-V
		return true;
	}
	
	public boolean stop() {
		isStarted = false;
		assert true; //inline assert generated by ARG-V
		return true;
	}

	public String getJdbcUrl() {
		assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
	}
	
	public DataSource getDataSource() {
		assert true; //inline assert generated by ARG-V
		return null;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(Verifier.nondetString(), Verifier.nondetString(),
				Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
		autoCheckValidationQuery(Verifier.nondetString());
		instance.getName();
		instance.start();
		instance.stop();
		instance.getJdbcUrl();
		instance.getDataSource();
	}
}
