

/** filtered and transformed by ARG-V */

/**
 * OpenKM, Open Document Management System (http://www.openkm.com)
 * Copyright (c) Paco Avila & Josep Llort
 * <p>
 * No bytes were intentionally harmed during the development of this application.
 * <p>
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.StringTokenizer;
import java.util.zip.ZipFile;

public class Main {
	/**
	 * Text spell checker
	 */
	/** ARG-V: suitable */
	 public static String spellChecker(String text) throws Exception {
		StringBuilder sb = new StringBuilder();

		if (Verifier.nondetBoolean()) {
			sb.append(text);
		} else {
			StringTokenizer st = new StringTokenizer(text);

			while (st.hasMoreTokens()) {
				String w = st.nextToken();
				List<String> s = null;

				if (s.isEmpty()) {
					sb.append(w).append(" ");
				} else {
					sb.append(s.get(0)).append(" ");
				}
			}
		}

		assert true; //inline assert generated by ARG-V
		return sb.toString();
	}

	/**
	 * Obtain lock token from node id
	 */
	/** ARG-V: suitable */
	 public static String getLockToken(String id) {
		StringBuffer buf = new StringBuffer();
		buf.append(id.toString());
		buf.append('-');
		buf.append(getCheckDigit(id.toString()));
		assert true; //inline assert generated by ARG-V
		return buf.toString();
	}

	/**
	 * Calculate check digit for lock token
	 *
	 * @see org.apache.jackrabbit.core.lock.LockToken.getCheckDigit(String uuid)
	 */
	/** ARG-V: suitable */
	 private static char getCheckDigit(String uuid) {
		int result = 0;
		int multiplier = 36;

		for (int i = 0; i < uuid.length(); i++) {
			char c = uuid.charAt(i);
			if (c >= '0' && c <= '9') {
				int num = c - '0';
				result += multiplier * num;
				multiplier--;
			} else if (c >= 'A' && c <= 'F') {
				int num = c - 'A' + 10;
				result += multiplier * num;
				multiplier--;
			} else if (c >= 'a' && c <= 'f') {
				int num = c - 'a' + 10;
				result += multiplier * num;
				multiplier--;
			}
		}

		int rem = result % 37;
		if (rem != 0) {
			rem = 37 - rem;
		}

		if (rem >= 0 && rem <= 9) {
			assert true; //inline assert generated by ARG-V
			return (char) ('0' + rem);
		} else if (rem >= 10 && rem <= 35) {
			assert true; //inline assert generated by ARG-V
			return (char) ('A' + rem - 10);
		} else {
			assert true; //inline assert generated by ARG-V
			return Verifier.nondetChar();
		}
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		spellChecker(Verifier.nondetString());
		getLockToken(Verifier.nondetString());
		getCheckDigit(Verifier.nondetString());
	}
}
