

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.Serializable;
import java.util.Map;
import java.util.regex.Pattern;

/** filtered by ARG-V */
 public class Main {
  String annotation = Verifier.nondetString();
  Pattern key = null;

  // TODO: separate these into two different classes?
  Pattern casedPattern = null;
  Pattern caselessPattern = null;
  String exactMatch = Verifier.nondetString();

  boolean negated = Verifier.nondetBoolean();

  /** ARG-V: suitable */
 Main(String annotation, String key, String value, boolean negated) {
    //System.out.println(annotation + " " + key + " " + value + " " + negated);
    String keyContent = key.substring(1, key.length() - 1);
    if (!(value.equals("__"))) {
		if (value.matches("/.*/")) {
			String patternContent = value.substring(1, value.length() - 1);
		}
	}
  }

  /** ARG-V: suitable */
 boolean valueMatches(boolean ignoreCase, String value) {
    if (ignoreCase) {
      assert true; //inline assert generated by ARG-V
	return caselessPattern == null ? value.equalsIgnoreCase(exactMatch.toString()) : caselessPattern.matcher(value).matches();
    } else {
      assert true; //inline assert generated by ARG-V
	return casedPattern == null ? value.equals(exactMatch.toString()) : casedPattern.matcher(value).matches();
    }
  }

  boolean checkMatches(Map<?, ?> map, boolean ignoreCase) {
    //System.out.println("CHECKING MATCHES");
    //System.out.println(map);
    if (Verifier.nondetBoolean()) {
      assert true; //inline assert generated by ARG-V
	// we treat an empty map as failing to match
      // so if the attribute is negated, that means this attribute passes
      return negated;
    }

    assert true; //inline assert generated by ARG-V
	return negated;
  }

  private static long serialVersionUID = 378257698196124612L;

/** This main was generated by ARG-V */
 public static void main(String[] args) throws Exception{Main instance=new Main(Verifier.nondetString(),Verifier.nondetString(),Verifier.nondetString(),Verifier.nondetBoolean());instance.valueMatches(Verifier.nondetBoolean(),Verifier.nondetString());instance.checkMatches((java.util.Map<?, ?>)null,Verifier.nondetBoolean());}
}
