

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

/**
 * @author shuzijun
 */
public class Main {

    private Integer version = null;

    private String pluginVersion = Verifier.nondetString();

    private String id = Verifier.nondetString();

    /**
     * 配置名称
     */
    private String name = Verifier.nondetString();

    /**
     * 用户名
     */
    private String loginName = Verifier.nondetString();

    /**
     * 密码
     */
    private String password = Verifier.nondetString();

    /**
     * 临时文件路径
     */
    private String filePath = Verifier.nondetString();

    /**
     * 语言
     */
    private String codeType = Verifier.nondetString();

    /**
     * url
     */
    private String url = Verifier.nondetString();

    /**
     * 检查更新
     */
    private Boolean update = true;

    /**
     * 使用代理
     */
    private Boolean proxy = false;

    /**
     * 自定义代码生成
     */
    private Boolean customCode = false;
    /**
     * 适应英文描述
     */
    private Boolean englishContent = false;

    /**
     * 自定义文件名
     */
    private String customFileName = Verifier.nondetString();
    /**
     * 自定义代码
     */
    private String customTemplate = Verifier.nondetString();
    /**
     * 用户cookie
     */
    private Map<String, String> userCookie = new HashMap<>();

    /**
     * 题目颜色
     */
    private String levelColour = Verifier.nondetString();

    /**
     * 使用cookie登录
     */
    private boolean cookie = false;

    /**
     * question Split Editor
     */
    private String questionEditor = "Left";

    /**
     * Content  Multiline Comment
     */
    private Boolean multilineComment = false;

    /**
     * html Content
     */
    private Boolean htmlContent = false;

    /**
     * showTopics
     */
    private Boolean showTopics = true;

    /**
     * showToolIcon
     */
    private Boolean showToolIcon = true;

    /**
     * convergeEditor
     */
    private Boolean convergeEditor = true;

    /**
     * 使用的导航
     */
    private String navigatorName = Verifier.nondetString();

    /**
     * 显示编辑器标志
     */
    private boolean showQuestionEditorSign = true;

    public String getId() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getName() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getLoginName() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getFilePath() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getCodeType() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public String getUrl() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public boolean getUpdate() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetBoolean();
    }

    public Integer getVersion() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Boolean getProxy() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Boolean getCustomCode() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public String getCustomFileName() {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } else {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
    }

    public String getCustomTemplate() {
        if (Verifier.nondetBoolean()) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        } else {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
    }

    public Map<String, String> getUserCookie() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public String getAlias() {
        if ("leetcode.com".equals(getUrl())) {
            assert true; //inline assert generated by ARG-V
			return "en";
        } else {
            assert true; //inline assert generated by ARG-V
			return "cn";
        }
    }

    public void addCookie(String user, String cookie) {
        userCookie.put(user, cookie);
    }

    public String getCookie(String user) {
        if (userCookie == null) {
            assert true; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        assert true; //inline assert generated by ARG-V
		return userCookie.get(user);
    }

    public String getLevelColour() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    /** ARG-V: suitable */
	 public Color[] getFormatLevelColour() {
        Color[] formatColors = new Color[3];
        formatColors[0] = new Color(92, 184, 92);
        formatColors[1] = new Color(240, 173, 78);
        formatColors[2] = new Color(217, 83, 79);
        String[] colors = getLevelColour().split(";");
        if (colors.length > 0) {
            try {
                formatColors[0] = new Color(Integer.parseInt(colors[0].replace("#", ""), 16));
            } catch (Exception e) {
            }
        }
        if (colors.length > 1) {
            try {
                formatColors[1] = new Color(Integer.parseInt(colors[1].replace("#", ""), 16));
            } catch (Exception e) {
            }
        }
        if (colors.length > 2) {
            try {
                formatColors[2] = new Color(Integer.parseInt(colors[2].replace("#", ""), 16));
            } catch (Exception e) {
            }
        }
        assert true; //inline assert generated by ARG-V
		return formatColors;
    }

    public void setFormatLevelColour(Color... colors) {
        StringBuilder levelColour = new StringBuilder();
    }

    public Boolean getEnglishContent() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public boolean isCookie() {
        assert true; //inline assert generated by ARG-V
		return cookie;
    }

    public Boolean isShowQuestionEditor() {
        assert true; //inline assert generated by ARG-V
		return !"Disable".equals(questionEditor) && !"false".equals(questionEditor);
    }

    public Boolean isLeftQuestionEditor() {
        assert true; //inline assert generated by ARG-V
		return "Left".equals(questionEditor) || "true".equals(questionEditor) || !isShowQuestionEditor();
    }

    public String getQuestionEditor() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public Boolean getMultilineComment() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Boolean getHtmlContent() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Boolean getShowTopics() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Boolean getShowToolIcon() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public Boolean getConvergeEditor() {
        assert true; //inline assert generated by ARG-V
		return null;
    }

    public String getNavigatorName() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    public boolean isShowQuestionEditorSign() {
        assert true; //inline assert generated by ARG-V
		return showQuestionEditorSign;
    }

    public String getPluginVersion() {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getId();
		instance.getName();
		instance.getLoginName();
		instance.getFilePath();
		instance.getCodeType();
		instance.getUrl();
		instance.getUpdate();
		instance.getVersion();
		instance.getProxy();
		instance.getCustomCode();
		instance.getCustomFileName();
		instance.getCustomTemplate();
		instance.getUserCookie();
		instance.getAlias();
		instance.addCookie(Verifier.nondetString(), Verifier.nondetString());
		instance.getCookie(Verifier.nondetString());
		instance.getLevelColour();
		instance.getFormatLevelColour();
		instance.setFormatLevelColour(new java.awt.Color[] { null });
		instance.getEnglishContent();
		instance.isCookie();
		instance.isShowQuestionEditor();
		instance.isLeftQuestionEditor();
		instance.getQuestionEditor();
		instance.getMultilineComment();
		instance.getHtmlContent();
		instance.getShowTopics();
		instance.getShowToolIcon();
		instance.getConvergeEditor();
		instance.getNavigatorName();
		instance.isShowQuestionEditorSign();
		instance.getPluginVersion();
	}
}
