/** filtered and transformed by ARG-V */

// Copyright 2011-2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
  private int m_caretY = -1;

  private boolean m_wasUneditableSelection = Verifier.nondetBoolean();

  protected void initUndoHistory() {
    int x = Verifier.nondetInt();
    int y = Verifier.nondetInt();

    if (Verifier.nondetBoolean()) {
      // Caret end was within a comment, when return was pressed

      String text = "";

      if (Verifier.nondetBoolean()) {
        x = Verifier.nondetInt();
      }

      text = Verifier.nondetString();
    } else {
      // Caret was not within a comment. Note: Line fragments are always single lined

      y = Verifier.nondetInt();

      String text = "";

      boolean isAboveLineComment = false;
      boolean isBehindLineComment = false;
      boolean isLabelComment = false;

      if (Verifier.nondetBoolean()) {
        assert true; //inline assert generated by ARG-V
		return;
      }
    }
  }

  /** ARG-V: suitable */
 protected void updateLabelContent() {
    if (m_wasUneditableSelection) {
      assert true; //inline assert generated by ARG-V
	return;
    }

    int x = Verifier.nondetInt();
    final int y = Verifier.nondetInt();

    m_caretY = y + 1;

    if (Verifier.nondetBoolean()) {
      // Caret end was within a comment. Insert a new line into the comment.

      if (Verifier.nondetBoolean()) {
        x = Verifier.nondetInt();
      }

      int textCursor = Verifier.nondetInt();
      final String text =
          Verifier.nondetString();

      if (text.endsWith("\r") && (textCursor == text.length())) {
        --textCursor;
      }

      String changedLine =
          String.format("%s%s%s", text.substring(0, textCursor), "\n", text.substring(textCursor));
      changedLine = Verifier.nondetString();

      if (Verifier.nondetBoolean()) {
        assert true; //inline assert generated by ARG-V
		return;
      }
    } else {
      // Caret was not within a comment. Create a new comment.

      m_caretY = Verifier.nondetInt();
    }
  }

  protected void updateSelection() {
    m_wasUneditableSelection = Verifier.nondetBoolean();
  }

  protected void updateUndoHistory() {
    final int x = Verifier.nondetInt();
    final int y = Verifier.nondetInt();

    if (Verifier.nondetBoolean()) {
      String text =
          Verifier.nondetString();

      if (Verifier.nondetBoolean()) {
        text = Verifier.nondetString();
      }
    }
  }

/** This main was generated by ARG-V */

public static void main(String[] args) throws Exception {
	Main instance = new Main();
	instance.initUndoHistory();
	instance.updateLabelContent();
	instance.updateSelection();
	instance.updateUndoHistory();
}
}
