

/** filtered and transformed by ARG-V */

/*******************************************************************************
 * Copyright (c) 2019 Wajd Tohme, Ahmad Hussaein, Petr Kocián, Matias Carlander-Reuterfelt, 
 *                    Ismail Hilal, Tuna Gersil, and Zainab Alsaadi and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 *
 * The Eclipse Public License is available at
 *    http://www.eclipse.org/legal/epl-v20.html
 * and the Eclipse Distribution License is available at
 *    http://www.eclipse.org/org/documents/edl-v10.html.
 *
 * Contributors:
 *    Wajd Tohme
 *    Ahmad Hussaein
 *    Petr Kocián
 *    Matias Carlander-Reuterfelt
 *    Ismail Hilal
 *    Tuna Gersil
 *    Zainab Alsaadi
 *
 ******************************************************************************/
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Set;
import java.util.concurrent.ConcurrentSkipListSet;

/**
 * The Converter class is a collection of helper functions that make using Californium {@link WebLink}
 * and {@link CoapResponse} easier to use. It also holds various uri linting functions
 * The {@link PubSub} methods return CoapResponse and this helps with using them
 */
public class Main {

    /*helper functions for  CoapResponse */

    

    /*helper functions for Set<WebLink>*/

    

    /*helper functions for WebLink*/

    /**
     * renders the text description of the given content type integer
     * uses {@link MediaTypeRegistry}
     *
     * @param ct int
     * @return String Content Type
     */
    public static String getContentTypeString (int ct) {
        assert true; //inline assert generated by ARG-V
		return Verifier.nondetString();
    }

    

    /*helper functions for uri*/

    /**
     * parses given uri string for the substring after the last slash
     *
     * @param uri String
     * @return a String name
     */
    /** ARG-V: suitable */
	 public static String getName (String uri) {
        assert true; //inline assert generated by ARG-V
		return cleanUri(uri).substring(uri.lastIndexOf('/'));
    }

    /**
     * parses given uri string for the substring before the last slash
     * this is the uri of the direct parent
     *
     * @param uri String
     * @return a String parent uri
     */
    /** ARG-V: suitable */
	 public static String getParentUri (String uri) {
        assert true; //inline assert generated by ARG-V
		return cleanUri(uri).substring(0, uri.lastIndexOf('/'));
    }


    /**
     * trims unnecessary slashes at the start and end of given uri string
     * prevents unexpected behaviour
     *
     * @param uri String
     * @return a String uri
     */
    /** ARG-V: suitable */
	 public static String cleanUri (String uri) {
        if(uri.startsWith("/")) {
			uri = uri.substring(1);
		}
        if (uri.endsWith("/")) {
			uri = uri.substring(0, uri.length()-1);
		}
        assert true; //inline assert generated by ARG-V
		return uri;
    }



	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		getContentTypeString(Verifier.nondetInt());
		getName(Verifier.nondetString());
		getParentUri(Verifier.nondetString());
		cleanUri(Verifier.nondetString());
	}

}
